import Foundation

extension SeibuLineData {

    // MARK: - Seibu Shinjuku Line (SS)

    // First/last: ekitan + Yahoo, July 2026 (medium confidence).
    // Coordinates: ja.wikipedia per-station infoboxes, 2026-07-08.
    static let shinjuku = StaticTrainLine(
        id: "Railway:Seibu.Shinjuku",
        nameJa: "西武新宿線",
        nameEn: "Seibu Shinjuku Line",
        operatorId: "Operator:Seibu",
        colorHex: "#00A6BF",
        stations: [
            st("Seibu.Shinjuku", "SeibuShinjuku", "西武新宿", "Seibu-Shinjuku", "SS01", 35.6963, 139.7000),
            st("Seibu.Shinjuku", "Takadanobaba", "高田馬場", "Takadanobaba", "SS02", 35.7131, 139.7041),
            st("Seibu.Shinjuku", "ShimoOchiai", "下落合", "Shimo-ochiai", "SS03", 35.7158, 139.6951),
            st("Seibu.Shinjuku", "Nakai", "中井", "Nakai", "SS04", 35.7151, 139.6872),
            st("Seibu.Shinjuku", "Araiyakushimae", "新井薬師前", "Araiyakushi-mae", "SS05", 35.7158, 139.6719),
            st("Seibu.Shinjuku", "Numabukuro", "沼袋", "Numabukuro", "SS06", 35.7194, 139.6638),
            st("Seibu.Shinjuku", "Nogata", "野方", "Nogata", "SS07", 35.7197, 139.6528),
            st("Seibu.Shinjuku", "ToritsuKasei", "都立家政", "Toritsu-kasei", "SS08", 35.7223, 139.6446),
            st("Seibu.Shinjuku", "Saginomiya", "鷺ノ宮", "Saginomiya", "SS09", 35.7226, 139.6389),
            st("Seibu.Shinjuku", "ShimoIgusa", "下井草", "Shimo-igusa", "SS10", 35.7239, 139.6243),
            st("Seibu.Shinjuku", "Iogi", "井荻", "Iogi", "SS11", 35.7245, 139.6147),
            st("Seibu.Shinjuku", "KamiIgusa", "上井草", "Kami-igusa", "SS12", 35.7251, 139.6036),
            st("Seibu.Shinjuku", "KamiShakujii", "上石神井", "Kami-shakujii", "SS13", 35.7263, 139.5921),
            st("Seibu.Shinjuku", "MusashiSeki", "武蔵関", "Musashi-seki", "SS14", 35.7276, 139.5769),
            st("Seibu.Shinjuku", "HigashiFushimi", "東伏見", "Higashi-fushimi", "SS15", 35.7287, 139.5643),
            st("Seibu.Shinjuku", "SeibuYagisawa", "西武柳沢", "Seibu-yagisawa", "SS16", 35.7286, 139.5526),
            st("Seibu.Shinjuku", "Tanashi", "田無", "Tanashi", "SS17", 35.7274, 139.5393),
            st("Seibu.Shinjuku", "HanaKoganei", "花小金井", "Hana-koganei", "SS18", 35.7261, 139.5132),
            st("Seibu.Shinjuku", "Kodaira", "小平", "Kodaira", "SS19", 35.7370, 139.4883),
            st("Seibu.Shinjuku", "Kumegawa", "久米川", "Kumegawa", "SS20", 35.7500, 139.4720),
            st("Seibu.Shinjuku", "HigashiMurayama", "東村山", "Higashi-murayama", "SS21", 35.7606, 139.4658),
            st("Seibu.Shinjuku", "Tokorozawa", "所沢", "Tokorozawa", "SS22", 35.7867, 139.4733),
            st("Seibu.Shinjuku", "KokuKoen", "航空公園", "Koku-koen", "SS23", 35.7984, 139.4657),
            st("Seibu.Shinjuku", "ShinTokorozawa", "新所沢", "Shin-tokorozawa", "SS24", 35.8067, 139.4561),
            st("Seibu.Shinjuku", "Iriso", "入曽", "Iriso", "SS25", 35.8325, 139.4272),
            st("Seibu.Shinjuku", "Sayamashi", "狭山市", "Sayamashi", "SS26", 35.8569, 139.4131),
            st("Seibu.Shinjuku", "ShinSayama", "新狭山", "Shin-sayama", "SS27", 35.8741, 139.4333),
            st("Seibu.Shinjuku", "MinamiOtsuka", "南大塚", "Minami-otsuka", "SS28", 35.8898, 139.4543),
            st("Seibu.Shinjuku", "HonKawagoe", "本川越", "Hon-kawagoe", "SS29", 35.9142, 139.4814),
        ],
        hopTimesMinutes: [
            3, 2, 1, 2, 1, 2, 1, 1, 2, 1, 2, 2, 2, 2,
            1, 2, 3, 3, 2, 2, 4, 2, 2, 4, 3, 3, 3, 4,
        ],
        directions: [
            direction("Seibu.Shinjuku", "HonKawagoe", "所沢・本川越方面", "For Tokorozawa & Hon-Kawagoe",
                      ascending: true,
                      weekday: pattern("05:01", "24:17", [
                          ("05:01", 8), ("06:30", 4), ("09:30", 5), ("16:30", 5), ("20:00", 6), ("22:00", 8),
                      ]),
                      holiday: pattern("05:01", "24:17", [
                          ("05:01", 8), ("07:00", 5), ("10:00", 5), ("20:00", 8),
                      ]),
                      // 拝島行き 急行/準急 diverge onto the 拝島線 at 小平.
                      expressWeekday: shinjukuAscExpressWd,
                      expressHoliday: shinjukuAscExpressHol),
            direction("Seibu.Shinjuku", "SeibuShinjuku", "高田馬場・西武新宿方面", "For Takadanobaba & Seibu-Shinjuku",
                      ascending: false,
                      weekday: pattern("04:54", "23:31", [
                          ("04:54", 10), ("06:30", 5), ("09:30", 8), ("16:30", 6), ("20:00", 8), ("22:00", 10),
                      ]),
                      holiday: pattern("04:54", "23:31", [
                          ("04:54", 10), ("07:00", 8), ("10:00", 8), ("20:00", 10),
                      ]),
                      origins: [
                          originRuns("Station:Seibu.Shinjuku.Tanashi",
                                     shinjukuDescExpressWd_org_Tanashi, shinjukuDescExpressHol_org_Tanashi),
                          originRuns("Station:Seibu.Shinjuku.ShinTokorozawa",
                                     shinjukuDescExpressWd_org_ShinTokorozawa, shinjukuDescExpressHol_org_ShinTokorozawa),
                      ],
                      expressWeekday: shinjukuDescExpressWd,
                      expressHoliday: shinjukuDescExpressHol),
        ],
        delayInfo: delayInfo,
        throughServices: [
            through("Seibu.Shinjuku.Kodaira", .ascending,
                    "西武拝島線", "Seibu Haijima Line",
                    "拝島方面", "for Haijima"),
        ],
        // 停車駅 hand-coded from Seibu's official 停車駅案内 and cross-checked
        // against ODPT StationTimetable presence. Times/types/termini are
        // ODPT-exact; stop patterns are not ODPT-per-train verifiable.
        // Sources: https://ja.wikipedia.org/wiki/西武新宿線 (停車駅一覧),
        //          https://www.seiburailway.jp/railways/timetable/ (停車駅案内).
        // Indices are into `stations` (0=西武新宿 … 28=本川越).
        stopPatterns: [
            .express:         [0, 1, 8, 12, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28],  // 急行
            .semiExpress:     [0, 1, 8, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28], // 準急
            .commuterExpress: [0, 1, 8, 12, 16, 20, 21, 23, 25, 28],                              // 通勤急行 (千鳥停車)
            .rapidExpress:    [0, 1, 16, 20, 21, 23, 24, 25, 26, 27, 28],                         // 快速急行
        ]
    )

    // MARK: - Seibu Shinjuku Express Runs (ODPT StationTimetable, July-2026)

    private static let shinjukuAscExpressWd: [ExactRun] = [
        ExactRun("05:46", trainType: .semiExpress),
        ExactRun("06:02", trainType: .express),
        ExactRun("06:13", trainType: .express),
        ExactRun("06:24", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("06:32", trainType: .express),
        ExactRun("06:42", trainType: .express),
        ExactRun("06:51", trainType: .express),
        ExactRun("07:00", trainType: .semiExpress),
        ExactRun("07:08", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("07:15", trainType: .semiExpress),
        ExactRun("07:22", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("07:29", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .semiExpress),
        ExactRun("07:37", trainType: .semiExpress),
        ExactRun("07:45", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("07:48", trainType: .express),
        ExactRun("07:53", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("07:57", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .semiExpress),
        ExactRun("08:02", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("08:05", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("08:10", trainType: .express),
        ExactRun("08:12", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("08:17", trainType: .express),
        ExactRun("08:20", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("08:25", trainType: .express),
        ExactRun("08:27", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .semiExpress),
        ExactRun("08:32", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("08:37", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .semiExpress),
        ExactRun("08:42", terminusStationId: "Station:Seibu.Shinjuku.Tanashi", trainType: .semiExpress),
        ExactRun("08:47", trainType: .express),
        ExactRun("08:54", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("09:01", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .express),
        ExactRun("09:03", trainType: .semiExpress),
        ExactRun("09:10", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("09:16", trainType: .express),
        ExactRun("09:24", trainType: .semiExpress),
        ExactRun("09:31", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .express),
        ExactRun("09:41", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("09:46", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .express),
        ExactRun("09:51", trainType: .express),
        ExactRun("10:01", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("10:11", trainType: .express),
        ExactRun("10:21", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("10:31", trainType: .express),
        ExactRun("10:41", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("10:51", trainType: .express),
        ExactRun("11:01", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("11:11", trainType: .express),
        ExactRun("11:21", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("11:31", trainType: .express),
        ExactRun("11:41", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("11:51", trainType: .express),
        ExactRun("12:01", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("12:11", trainType: .express),
        ExactRun("12:21", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("12:31", trainType: .express),
        ExactRun("12:41", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("12:51", trainType: .express),
        ExactRun("13:01", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("13:11", trainType: .express),
        ExactRun("13:21", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("13:31", trainType: .express),
        ExactRun("13:41", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("13:51", trainType: .express),
        ExactRun("14:01", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("14:11", trainType: .express),
        ExactRun("14:21", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("14:31", trainType: .express),
        ExactRun("14:41", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("14:51", trainType: .express),
        ExactRun("15:01", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("15:11", trainType: .express),
        ExactRun("15:21", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("15:31", trainType: .express),
        ExactRun("15:41", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("15:51", trainType: .express),
        ExactRun("16:01", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("16:11", trainType: .express),
        ExactRun("16:21", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("16:31", trainType: .express),
        ExactRun("16:37", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("16:44", trainType: .express),
        ExactRun("16:51", trainType: .express),
        ExactRun("16:58", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("17:05", trainType: .express),
        ExactRun("17:12", trainType: .express),
        ExactRun("17:20", trainType: .express),
        ExactRun("17:28", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .semiExpress),
        ExactRun("17:35", trainType: .express),
        ExactRun("17:42", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("17:50", trainType: .express),
        ExactRun("17:56", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("18:03", trainType: .express),
        ExactRun("18:08", trainType: .semiExpress),
        ExactRun("18:13", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .semiExpress),
        ExactRun("18:22", trainType: .express),
        ExactRun("18:27", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("18:32", trainType: .express),
        ExactRun("18:38", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("18:44", trainType: .express),
        ExactRun("18:51", trainType: .express),
        ExactRun("18:56", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("19:04", trainType: .express),
        ExactRun("19:11", trainType: .express),
        ExactRun("19:20", trainType: .express),
        ExactRun("19:26", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("19:35", trainType: .express),
        ExactRun("19:41", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("19:49", trainType: .express),
        ExactRun("19:57", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("20:05", trainType: .express),
        ExactRun("20:11", trainType: .express),
        ExactRun("20:19", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .express),
        ExactRun("20:27", trainType: .semiExpress),
        ExactRun("20:35", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("20:41", trainType: .express),
        ExactRun("20:49", trainType: .express),
        ExactRun("20:57", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("21:04", trainType: .express),
        ExactRun("21:11", trainType: .express),
        ExactRun("21:20", trainType: .express),
        ExactRun("21:27", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("21:36", trainType: .express),
        ExactRun("21:44", trainType: .express),
        ExactRun("21:52", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("22:03", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("22:12", trainType: .express),
        ExactRun("22:24", trainType: .express),
        ExactRun("22:35", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("22:44", trainType: .express),
        ExactRun("22:54", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("23:07", trainType: .express),
        ExactRun("23:19", trainType: .semiExpress),
        ExactRun("23:32", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .semiExpress),
        ExactRun("23:42", trainType: .semiExpress),
        ExactRun("23:59", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .semiExpress),
        ExactRun("24:14", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .semiExpress),
    ]

    private static let shinjukuAscExpressHol: [ExactRun] = [
        ExactRun("05:45", trainType: .semiExpress),
        ExactRun("06:00", trainType: .express),
        ExactRun("06:16", trainType: .express),
        ExactRun("06:30", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("06:40", trainType: .express),
        ExactRun("06:50", trainType: .express),
        ExactRun("07:00", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("07:10", trainType: .express),
        ExactRun("07:20", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("07:31", trainType: .express),
        ExactRun("07:40", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("07:50", trainType: .express),
        ExactRun("07:54", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("08:01", trainType: .express),
        ExactRun("08:09", trainType: .express),
        ExactRun("08:19", trainType: .semiExpress),
        ExactRun("08:26", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("08:33", trainType: .express),
        ExactRun("08:40", trainType: .express),
        ExactRun("08:49", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .express),
        ExactRun("08:58", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("09:00", trainType: .rapidExpress),
        ExactRun("09:09", trainType: .express),
        ExactRun("09:20", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("09:27", trainType: .express),
        ExactRun("09:38", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("09:43", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .semiExpress),
        ExactRun("09:49", trainType: .express),
        ExactRun("09:56", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("10:04", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("10:10", trainType: .express),
        ExactRun("10:16", trainType: .semiExpress),
        ExactRun("10:21", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("10:31", trainType: .express),
        ExactRun("10:41", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("10:51", trainType: .express),
        ExactRun("11:01", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("11:11", trainType: .express),
        ExactRun("11:21", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("11:31", trainType: .express),
        ExactRun("11:41", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("11:51", trainType: .express),
        ExactRun("12:01", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("12:11", trainType: .express),
        ExactRun("12:21", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("12:31", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .express),
        ExactRun("12:41", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("12:51", trainType: .express),
        ExactRun("13:01", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("13:11", trainType: .express),
        ExactRun("13:21", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("13:31", trainType: .express),
        ExactRun("13:41", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("13:51", trainType: .express),
        ExactRun("14:01", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("14:11", trainType: .express),
        ExactRun("14:21", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("14:31", trainType: .express),
        ExactRun("14:41", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("14:51", trainType: .express),
        ExactRun("15:01", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("15:11", trainType: .express),
        ExactRun("15:21", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("15:31", trainType: .express),
        ExactRun("15:41", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("15:51", trainType: .express),
        ExactRun("16:01", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("16:11", trainType: .express),
        ExactRun("16:21", trainType: .express),
        ExactRun("16:31", trainType: .express),
        ExactRun("16:41", trainType: .express),
        ExactRun("16:51", trainType: .express),
        ExactRun("17:02", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("17:10", trainType: .express),
        ExactRun("17:19", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("17:25", trainType: .semiExpress),
        ExactRun("17:32", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("17:41", trainType: .express),
        ExactRun("17:49", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("17:54", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("18:02", trainType: .express),
        ExactRun("18:10", trainType: .express),
        ExactRun("18:19", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("18:24", trainType: .semiExpress),
        ExactRun("18:32", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("18:41", trainType: .express),
        ExactRun("18:49", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("18:54", trainType: .semiExpress),
        ExactRun("19:02", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("19:10", trainType: .express),
        ExactRun("19:19", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .express),
        ExactRun("19:24", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .semiExpress),
        ExactRun("19:32", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("19:40", trainType: .express),
        ExactRun("19:48", trainType: .express),
        ExactRun("19:57", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("20:02", trainType: .semiExpress),
        ExactRun("20:12", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .express),
        ExactRun("20:21", trainType: .express),
        ExactRun("20:31", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .express),
        ExactRun("20:41", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("20:51", trainType: .express),
        ExactRun("21:01", terminusStationId: "Station:Seibu.Shinjuku.Tanashi", trainType: .express),
        ExactRun("21:11", trainType: .express),
        ExactRun("21:21", trainType: .express),
        ExactRun("21:31", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .express),
        ExactRun("21:41", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("21:51", trainType: .express),
        ExactRun("22:01", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("22:11", trainType: .express),
        ExactRun("22:21", trainType: .express),
        ExactRun("22:31", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .express),
        ExactRun("22:41", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("22:51", trainType: .express),
        ExactRun("23:01", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("23:11", trainType: .semiExpress),
        ExactRun("23:21", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("23:31", trainType: .semiExpress),
        ExactRun("23:43", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .semiExpress),
        ExactRun("23:58", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .semiExpress),
        ExactRun("24:14", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .semiExpress),
    ]

    private static let shinjukuDescExpressWd: [ExactRun] = [
        ExactRun("04:54", trainType: .semiExpress),
        ExactRun("05:12", trainType: .express),
        ExactRun("05:31", trainType: .express),
        ExactRun("05:46", trainType: .express),
        ExactRun("06:01", trainType: .express),
        ExactRun("06:16", trainType: .express),
        ExactRun("06:24", trainType: .semiExpress),
        ExactRun("06:34", trainType: .semiExpress),
        ExactRun("06:42", trainType: .express),
        ExactRun("06:49", trainType: .express),
        ExactRun("07:04", trainType: .commuterExpress),
        ExactRun("07:06", trainType: .express),
        ExactRun("07:15", trainType: .semiExpress),
        ExactRun("07:27", trainType: .express),
        ExactRun("07:37", trainType: .semiExpress),
        ExactRun("07:48", trainType: .express),
        ExactRun("08:07", trainType: .express),
        ExactRun("08:27", trainType: .semiExpress),
        ExactRun("08:47", trainType: .express),
        ExactRun("08:57", trainType: .express),
        ExactRun("09:17", trainType: .express),
        ExactRun("09:27", trainType: .express),
        ExactRun("09:37", trainType: .express),
        ExactRun("09:57", trainType: .express),
        ExactRun("10:17", trainType: .express),
        ExactRun("10:37", trainType: .express),
        ExactRun("10:57", trainType: .express),
        ExactRun("11:17", trainType: .express),
        ExactRun("11:37", trainType: .express),
        ExactRun("11:57", trainType: .express),
        ExactRun("12:17", trainType: .express),
        ExactRun("12:37", trainType: .express),
        ExactRun("12:57", trainType: .express),
        ExactRun("13:17", trainType: .express),
        ExactRun("13:37", trainType: .express),
        ExactRun("13:57", trainType: .express),
        ExactRun("14:17", trainType: .express),
        ExactRun("14:37", trainType: .express),
        ExactRun("14:57", trainType: .express),
        ExactRun("15:17", trainType: .express),
        ExactRun("15:37", trainType: .express),
        ExactRun("15:57", trainType: .express),
        ExactRun("16:17", trainType: .express),
        ExactRun("16:38", trainType: .express),
        ExactRun("16:58", trainType: .express),
        ExactRun("17:20", trainType: .express),
        ExactRun("17:42", trainType: .express),
        ExactRun("17:53", trainType: .semiExpress),
        ExactRun("18:02", trainType: .semiExpress),
        ExactRun("18:12", trainType: .express),
        ExactRun("18:22", trainType: .express),
        ExactRun("18:32", trainType: .express),
        ExactRun("18:42", trainType: .express),
        ExactRun("19:02", trainType: .express),
        ExactRun("19:12", trainType: .express),
        ExactRun("19:22", trainType: .express),
        ExactRun("19:32", trainType: .express),
        ExactRun("19:42", trainType: .express),
        ExactRun("19:52", trainType: .semiExpress),
        ExactRun("20:02", trainType: .semiExpress),
        ExactRun("20:12", trainType: .express),
        ExactRun("20:22", trainType: .express),
        ExactRun("20:32", trainType: .semiExpress),
        ExactRun("20:42", trainType: .semiExpress),
        ExactRun("21:02", trainType: .express),
        ExactRun("21:12", trainType: .express),
        ExactRun("21:22", trainType: .express),
        ExactRun("21:42", trainType: .express),
        ExactRun("21:52", trainType: .express),
        ExactRun("22:07", trainType: .express),
        ExactRun("22:19", trainType: .semiExpress),
        ExactRun("22:32", trainType: .semiExpress),
        ExactRun("22:47", trainType: .semiExpress),
        ExactRun("23:04", trainType: .semiExpress),
    ]

    private static let shinjukuDescExpressHol: [ExactRun] = [
        ExactRun("04:54", trainType: .semiExpress),
        ExactRun("05:12", trainType: .express),
        ExactRun("05:34", trainType: .express),
        ExactRun("05:54", trainType: .express),
        ExactRun("06:07", trainType: .express),
        ExactRun("06:23", trainType: .express),
        ExactRun("06:35", trainType: .express),
        ExactRun("06:51", trainType: .express),
        ExactRun("06:59", trainType: .express),
        ExactRun("07:10", trainType: .express),
        ExactRun("07:19", trainType: .express),
        ExactRun("07:40", trainType: .express),
        ExactRun("07:49", trainType: .express),
        ExactRun("07:59", trainType: .express),
        ExactRun("08:10", trainType: .express),
        ExactRun("08:23", trainType: .express),
        ExactRun("08:39", trainType: .express),
        ExactRun("08:49", trainType: .express),
        ExactRun("09:02", trainType: .express),
        ExactRun("09:12", trainType: .express),
        ExactRun("09:20", trainType: .express),
        ExactRun("09:32", trainType: .express),
        ExactRun("09:39", trainType: .express),
        ExactRun("09:50", trainType: .express),
        ExactRun("10:09", trainType: .express),
        ExactRun("10:17", trainType: .express),
        ExactRun("10:37", trainType: .express),
        ExactRun("10:57", trainType: .express),
        ExactRun("11:17", trainType: .express),
        ExactRun("11:37", trainType: .express),
        ExactRun("11:57", trainType: .express),
        ExactRun("12:17", trainType: .express),
        ExactRun("12:37", trainType: .express),
        ExactRun("12:57", trainType: .express),
        ExactRun("13:17", trainType: .express),
        ExactRun("13:37", trainType: .express),
        ExactRun("13:57", trainType: .express),
        ExactRun("14:17", trainType: .express),
        ExactRun("14:37", trainType: .express),
        ExactRun("14:57", trainType: .express),
        ExactRun("15:17", trainType: .express),
        ExactRun("15:37", trainType: .express),
        ExactRun("15:57", trainType: .express),
        ExactRun("16:07", trainType: .express),
        ExactRun("16:17", trainType: .semiExpress),
        ExactRun("16:37", trainType: .express),
        ExactRun("16:57", trainType: .express),
        ExactRun("17:07", trainType: .express),
        ExactRun("17:17", trainType: .semiExpress),
        ExactRun("17:27", trainType: .express),
        ExactRun("17:37", trainType: .express),
        ExactRun("17:46", trainType: .semiExpress),
        ExactRun("17:56", trainType: .express),
        ExactRun("18:18", trainType: .express),
        ExactRun("18:40", trainType: .express),
        ExactRun("18:48", trainType: .semiExpress),
        ExactRun("19:02", trainType: .express),
        ExactRun("19:19", trainType: .express),
        ExactRun("19:32", trainType: .express),
        ExactRun("19:49", trainType: .express),
        ExactRun("20:02", trainType: .express),
        ExactRun("20:18", trainType: .express),
        ExactRun("20:48", trainType: .express),
        ExactRun("21:04", trainType: .semiExpress),
        ExactRun("21:18", trainType: .express),
        ExactRun("21:33", trainType: .semiExpress),
        ExactRun("22:03", trainType: .semiExpress),
        ExactRun("22:18", trainType: .express),
        ExactRun("22:33", trainType: .semiExpress),
        ExactRun("22:48", trainType: .semiExpress),
        ExactRun("23:03", trainType: .semiExpress),
    ]

    private static let shinjukuDescExpressWd_org_Tanashi: [ExactRun] = [
        ExactRun("07:36", trainType: .semiExpress),
        ExactRun("18:13", trainType: .express),
        ExactRun("22:44", trainType: .semiExpress),
    ]

    private static let shinjukuDescExpressHol_org_Tanashi: [ExactRun] = [
        ExactRun("19:24", trainType: .express),
    ]

    private static let shinjukuDescExpressWd_org_ShinTokorozawa: [ExactRun] = [
        ExactRun("04:55", trainType: .semiExpress),
        ExactRun("05:40", trainType: .express),
        ExactRun("06:24", trainType: .express),
        ExactRun("07:28", trainType: .semiExpress),
        ExactRun("07:59", trainType: .semiExpress),
        ExactRun("08:22", trainType: .express),
        ExactRun("15:58", trainType: .semiExpress),
        ExactRun("16:38", trainType: .express),
        ExactRun("17:44", trainType: .semiExpress),
        ExactRun("19:25", trainType: .semiExpress),
    ]

    private static let shinjukuDescExpressHol_org_ShinTokorozawa: [ExactRun] = [
        ExactRun("04:55", trainType: .semiExpress),
        ExactRun("05:40", trainType: .express),
        ExactRun("20:27", trainType: .express),
        ExactRun("20:58", trainType: .express),
        ExactRun("22:05", trainType: .express),
        ExactRun("22:42", trainType: .express),
    ]

}
