import Foundation

extension TokyuLineData {

    // MARK: - Tokyu Den-en-toshi Line (DT)

    static let denentoshi = StaticTrainLine(
        id: "Railway:Tokyu.DenEnToshi",
        nameJa: "東急田園都市線",
        nameEn: "Tokyu Den-en-toshi Line",
        operatorId: "Operator:Tokyu",
        colorHex: "#20A288",
        stations: [
            st("Tokyu.DenEnToshi", "Shibuya", "渋谷", "Shibuya", "DT01", 35.6580, 139.7016),
            st("Tokyu.DenEnToshi", "IkejiriOhashi", "池尻大橋", "Ikejiri-ohashi", "DT02", 35.6500, 139.6870),
            st("Tokyu.DenEnToshi", "Sangenjaya", "三軒茶屋", "Sangen-jaya", "DT03", 35.6435, 139.6706),
            st("Tokyu.DenEnToshi", "KomazawaDaigaku", "駒沢大学", "Komazawa-daigaku", "DT04", 35.6270, 139.6620),
            st("Tokyu.DenEnToshi", "SakuraShimmachi", "桜新町", "Sakura-shimmachi", "DT05", 35.6280, 139.6470),
            st("Tokyu.DenEnToshi", "Yoga", "用賀", "Yoga", "DT06", 35.6260, 139.6330),
            st("Tokyu.DenEnToshi", "FutakoTamagawa", "二子玉川", "Futako-tamagawa", "DT07", 35.6120, 139.6265),
            st("Tokyu.DenEnToshi", "FutakoShinchi", "二子新地", "Futako-shinchi", "DT08", 35.6050, 139.6180),
            st("Tokyu.DenEnToshi", "Takatsu", "高津", "Takatsu", "DT09", 35.6010, 139.6150),
            st("Tokyu.DenEnToshi", "Mizonokuchi", "溝の口", "Mizonokuchi", "DT10", 35.5998, 139.6103),
            st("Tokyu.DenEnToshi", "Kajigaya", "梶が谷", "Kajigaya", "DT11", 35.5910, 139.5990),
            st("Tokyu.DenEnToshi", "Miyazakidai", "宮崎台", "Miyazakidai", "DT12", 35.5870, 139.5880),
            st("Tokyu.DenEnToshi", "Miyamaedaira", "宮前平", "Miyamaedaira", "DT13", 35.5850, 139.5780),
            st("Tokyu.DenEnToshi", "Saginuma", "鷺沼", "Saginuma", "DT14", 35.5810, 139.5680),
            st("Tokyu.DenEnToshi", "TamaPlaza", "たまプラーザ", "Tama-plaza", "DT15", 35.5720, 139.5560),
            st("Tokyu.DenEnToshi", "Azamino", "あざみ野", "Azamino", "DT16", 35.5700, 139.5430),
            st("Tokyu.DenEnToshi", "Eda", "江田", "Eda", "DT17", 35.5620, 139.5360),
            st("Tokyu.DenEnToshi", "Ichigao", "市が尾", "Ichigao", "DT18", 35.5560, 139.5270),
            st("Tokyu.DenEnToshi", "Fujigaoka", "藤が丘", "Fujigaoka", "DT19", 35.5470, 139.5180),
            st("Tokyu.DenEnToshi", "Aobadai", "青葉台", "Aobadai", "DT20", 35.5440, 139.5080),
            st("Tokyu.DenEnToshi", "Tana", "田奈", "Tana", "DT21", 35.5390, 139.4980),
            st("Tokyu.DenEnToshi", "Nagatsuta", "長津田", "Nagatsuta", "DT22", 35.5318, 139.4944),
            st("Tokyu.DenEnToshi", "Tsukushino", "つくし野", "Tsukushino", "DT23", 35.5230, 139.4830),
            st("Tokyu.DenEnToshi", "Suzukakedai", "すずかけ台", "Suzukakedai", "DT24", 35.5170, 139.4720),
            st("Tokyu.DenEnToshi", "MinamiMachida", "南町田グランベリーパーク", "Minami-machida Grandberry Park", "DT25", 35.5130, 139.4620),
            st("Tokyu.DenEnToshi", "Tsukimino", "つきみ野", "Tsukimino", "DT26", 35.5030, 139.4530),
            st("Tokyu.DenEnToshi", "ChuoRinkan", "中央林間", "Chuo-rinkan", "DT27", 35.5076, 139.4453),
        ],
        hopTimesMinutes: [
            2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        ],
        directions: [
            direction("Tokyu.DenEnToshi", "ChuoRinkan", "中央林間方面", "For Chuo-Rinkan",
                      ascending: true,
                      weekday: pattern("05:05", "23:58", [
                          ("05:05", 6), ("06:30", 3), ("09:30", 6), ("16:30", 4), ("20:00", 5), ("22:00", 7),
                      ]),
                      holiday: pattern("05:05", "23:58", [
                          ("05:05", 7), ("07:00", 6), ("10:00", 6), ("20:00", 7),
                      ]),
                      expressWeekday: denentoshiAscExpressWd,
                      expressHoliday: denentoshiAscExpressHol),
            direction("Tokyu.DenEnToshi", "Shibuya", "渋谷・大手町方面", "For Shibuya & Otemachi",
                      ascending: false,
                      weekday: pattern("05:00", "24:10", [
                          ("05:00", 6), ("06:30", 3), ("09:30", 6), ("16:30", 4), ("20:00", 5), ("22:00", 7),
                      ]),
                      holiday: pattern("05:00", "24:10", [
                          ("05:00", 7), ("07:00", 6), ("10:00", 6), ("20:00", 7),
                      ]),
                      expressWeekday: denentoshiDescExpressWd,
                      expressHoliday: denentoshiDescExpressHol),
        ],
        delayInfo: delayInfo,
        throughServices: [
            through("Tokyu.DenEnToshi.Shibuya", .descending,
                    "東京メトロ半蔵門線", "Tokyo Metro Hanzomon Line",
                    "大手町・押上方面", "for Otemachi & Oshiage",
                    to: "Railway:TokyoMetro.Hanzomon"),
        ],
        // 停車駅 from official table (absolute indices). 急行=express,
        // 準急=semiExpress (各停 Shibuya→二子玉川, then 急行 beyond 溝の口).
        // Source: https://www.tokyo-train-master.com/dt-den-en-toshi
        stopPatterns: [
            .express:     [0, 2, 6, 9, 13, 14, 15, 19, 21, 24, 26], // 急行
            .semiExpress: [0, 1, 2, 3, 4, 5, 6, 9, 13, 14, 15, 19, 21, 22, 23, 24, 25, 26], // 準急
        ]
    )

    private static let denentoshiAscExpressWd: [ExactRun] = [
        ExactRun("06:35", terminusStationId: "Station:Tokyu.DenEnToshi.Nagatsuta", trainType: .express),
        ExactRun("07:03", trainType: .express),
        ExactRun("07:22", terminusStationId: "Station:Tokyu.DenEnToshi.Nagatsuta", trainType: .semiExpress),
        ExactRun("07:33", trainType: .semiExpress),
        ExactRun("07:45", trainType: .semiExpress),
        ExactRun("07:54", trainType: .semiExpress),
        ExactRun("08:05", trainType: .semiExpress),
        ExactRun("08:18", terminusStationId: "Station:Tokyu.DenEnToshi.Nagatsuta", trainType: .semiExpress),
        ExactRun("08:29", terminusStationId: "Station:Tokyu.DenEnToshi.Nagatsuta", trainType: .semiExpress),
        ExactRun("08:38", trainType: .semiExpress),
        ExactRun("08:46", terminusStationId: "Station:Tokyu.DenEnToshi.Nagatsuta", trainType: .semiExpress),
        ExactRun("08:53", trainType: .semiExpress),
        ExactRun("08:59", terminusStationId: "Station:Tokyu.DenEnToshi.Nagatsuta", trainType: .semiExpress),
        ExactRun("09:06", trainType: .semiExpress),
        ExactRun("09:13", trainType: .express),
        ExactRun("09:22", trainType: .express),
        ExactRun("09:32", trainType: .express),
        ExactRun("09:41", trainType: .express),
        ExactRun("09:51", terminusStationId: "Station:Tokyu.DenEnToshi.Nagatsuta", trainType: .express),
        ExactRun("10:01", trainType: .express),
        ExactRun("10:13", terminusStationId: "Station:Tokyu.DenEnToshi.Nagatsuta", trainType: .express),
        ExactRun("10:23", trainType: .express),
        ExactRun("10:35", trainType: .express),
        ExactRun("10:45", trainType: .express),
        ExactRun("10:59", trainType: .express),
        ExactRun("11:15", terminusStationId: "Station:Tokyu.DenEnToshi.Nagatsuta", trainType: .express),
        ExactRun("11:31", trainType: .semiExpress),
        ExactRun("11:40", trainType: .express),
        ExactRun("11:49", trainType: .semiExpress),
        ExactRun("11:58", trainType: .express),
        ExactRun("12:08", trainType: .semiExpress),
        ExactRun("12:18", trainType: .express),
        ExactRun("12:28", trainType: .semiExpress),
        ExactRun("12:38", trainType: .express),
        ExactRun("12:48", trainType: .semiExpress),
        ExactRun("12:58", trainType: .express),
        ExactRun("13:08", trainType: .semiExpress),
        ExactRun("13:18", trainType: .express),
        ExactRun("13:28", trainType: .semiExpress),
        ExactRun("13:38", trainType: .express),
        ExactRun("13:48", trainType: .semiExpress),
        ExactRun("13:58", trainType: .express),
        ExactRun("14:08", trainType: .semiExpress),
        ExactRun("14:18", trainType: .express),
        ExactRun("14:28", trainType: .semiExpress),
        ExactRun("14:38", trainType: .express),
        ExactRun("14:48", trainType: .semiExpress),
        ExactRun("14:58", trainType: .express),
        ExactRun("15:08", trainType: .semiExpress),
        ExactRun("15:18", trainType: .express),
        ExactRun("15:28", trainType: .semiExpress),
        ExactRun("15:38", trainType: .express),
        ExactRun("15:48", trainType: .semiExpress),
        ExactRun("15:58", trainType: .express),
        ExactRun("16:08", trainType: .semiExpress),
        ExactRun("16:18", trainType: .express),
        ExactRun("16:33", trainType: .express),
        ExactRun("16:47", trainType: .express),
        ExactRun("16:59", trainType: .express),
        ExactRun("17:12", trainType: .express),
        ExactRun("17:23", trainType: .express),
        ExactRun("17:33", trainType: .express),
        ExactRun("17:44", trainType: .express),
        ExactRun("17:53", trainType: .express),
        ExactRun("18:02", trainType: .express),
        ExactRun("18:12", trainType: .express),
        ExactRun("18:18", trainType: .semiExpress),
        ExactRun("18:26", trainType: .semiExpress),
        ExactRun("18:35", trainType: .semiExpress),
        ExactRun("18:44", trainType: .semiExpress),
        ExactRun("18:53", trainType: .semiExpress),
        ExactRun("19:02", trainType: .semiExpress),
        ExactRun("19:12", trainType: .semiExpress),
        ExactRun("19:21", trainType: .semiExpress),
        ExactRun("19:34", terminusStationId: "Station:Tokyu.DenEnToshi.Nagatsuta", trainType: .express),
        ExactRun("19:44", trainType: .express),
        ExactRun("19:53", trainType: .express),
        ExactRun("20:03", trainType: .express),
        ExactRun("20:13", trainType: .express),
        ExactRun("20:23", trainType: .express),
        ExactRun("20:33", trainType: .express),
        ExactRun("20:43", trainType: .express),
        ExactRun("20:53", trainType: .express),
        ExactRun("21:03", trainType: .express),
        ExactRun("21:14", trainType: .express),
        ExactRun("21:25", trainType: .express),
        ExactRun("21:36", trainType: .express),
        ExactRun("21:47", trainType: .express),
        ExactRun("21:58", trainType: .express),
        ExactRun("22:10", trainType: .express),
        ExactRun("22:22", terminusStationId: "Station:Tokyu.DenEnToshi.Nagatsuta", trainType: .express),
        ExactRun("22:34", trainType: .express),
        ExactRun("22:46", trainType: .express),
        ExactRun("22:58", terminusStationId: "Station:Tokyu.DenEnToshi.Nagatsuta", trainType: .express),
        ExactRun("23:11", trainType: .express),
        ExactRun("23:27", trainType: .express),
        ExactRun("23:42", trainType: .semiExpress),
        ExactRun("24:04", terminusStationId: "Station:Tokyu.DenEnToshi.Nagatsuta", trainType: .semiExpress),
    ]

    private static let denentoshiAscExpressHol: [ExactRun] = [
        ExactRun("06:03", trainType: .express),
        ExactRun("06:30", trainType: .express),
        ExactRun("06:49", trainType: .express),
        ExactRun("07:08", trainType: .express),
        ExactRun("07:28", trainType: .express),
        ExactRun("07:45", trainType: .express),
        ExactRun("08:04", trainType: .express),
        ExactRun("08:19", trainType: .express),
        ExactRun("08:34", trainType: .express),
        ExactRun("08:48", trainType: .express),
        ExactRun("09:02", trainType: .express),
        ExactRun("09:15", trainType: .express),
        ExactRun("09:25", trainType: .semiExpress),
        ExactRun("09:39", trainType: .express),
        ExactRun("09:48", trainType: .semiExpress),
        ExactRun("10:01", trainType: .express),
        ExactRun("10:10", terminusStationId: "Station:Tokyu.DenEnToshi.Nagatsuta", trainType: .semiExpress),
        ExactRun("10:22", terminusStationId: "Station:Tokyu.DenEnToshi.Nagatsuta", trainType: .express),
        ExactRun("10:32", trainType: .semiExpress),
        ExactRun("10:40", trainType: .express),
        ExactRun("10:49", trainType: .semiExpress),
        ExactRun("10:58", trainType: .express),
        ExactRun("11:08", trainType: .semiExpress),
        ExactRun("11:18", trainType: .express),
        ExactRun("11:28", trainType: .semiExpress),
        ExactRun("11:38", trainType: .express),
        ExactRun("11:48", trainType: .semiExpress),
        ExactRun("11:58", trainType: .express),
        ExactRun("12:08", trainType: .semiExpress),
        ExactRun("12:18", trainType: .express),
        ExactRun("12:28", trainType: .semiExpress),
        ExactRun("12:38", trainType: .express),
        ExactRun("12:48", trainType: .semiExpress),
        ExactRun("12:58", trainType: .express),
        ExactRun("13:08", trainType: .semiExpress),
        ExactRun("13:18", trainType: .express),
        ExactRun("13:28", trainType: .semiExpress),
        ExactRun("13:38", trainType: .express),
        ExactRun("13:48", trainType: .semiExpress),
        ExactRun("13:58", trainType: .express),
        ExactRun("14:08", trainType: .semiExpress),
        ExactRun("14:18", trainType: .express),
        ExactRun("14:28", trainType: .semiExpress),
        ExactRun("14:38", trainType: .express),
        ExactRun("14:48", trainType: .semiExpress),
        ExactRun("14:58", trainType: .express),
        ExactRun("15:08", trainType: .semiExpress),
        ExactRun("15:18", trainType: .express),
        ExactRun("15:28", trainType: .semiExpress),
        ExactRun("15:38", trainType: .express),
        ExactRun("15:48", trainType: .semiExpress),
        ExactRun("15:58", trainType: .express),
        ExactRun("16:08", trainType: .semiExpress),
        ExactRun("16:18", trainType: .express),
        ExactRun("16:34", trainType: .express),
        ExactRun("16:48", trainType: .express),
        ExactRun("17:03", trainType: .express),
        ExactRun("17:13", trainType: .express),
        ExactRun("17:23", trainType: .express),
        ExactRun("17:33", trainType: .express),
        ExactRun("17:48", trainType: .express),
        ExactRun("18:03", trainType: .express),
        ExactRun("18:13", trainType: .express),
        ExactRun("18:23", trainType: .express),
        ExactRun("18:33", trainType: .express),
        ExactRun("18:48", trainType: .express),
        ExactRun("19:03", trainType: .express),
        ExactRun("19:18", trainType: .express),
        ExactRun("19:33", trainType: .express),
        ExactRun("19:48", trainType: .express),
        ExactRun("20:03", trainType: .express),
        ExactRun("20:18", terminusStationId: "Station:Tokyu.DenEnToshi.Nagatsuta", trainType: .express),
        ExactRun("20:33", trainType: .express),
        ExactRun("20:48", trainType: .express),
        ExactRun("21:03", trainType: .express),
        ExactRun("21:18", trainType: .express),
        ExactRun("21:33", trainType: .express),
        ExactRun("21:53", trainType: .express),
        ExactRun("22:11", trainType: .express),
        ExactRun("22:29", trainType: .express),
        ExactRun("22:48", trainType: .express),
        ExactRun("23:15", trainType: .semiExpress),
        ExactRun("23:41", trainType: .semiExpress),
        ExactRun("24:04", terminusStationId: "Station:Tokyu.DenEnToshi.Nagatsuta", trainType: .semiExpress),
    ]

    private static let denentoshiDescExpressWd: [ExactRun] = [
        ExactRun("05:05", trainType: .semiExpress),
        ExactRun("05:22", trainType: .semiExpress),
        ExactRun("05:37", trainType: .semiExpress),
        ExactRun("05:52", trainType: .semiExpress),
        ExactRun("06:09", trainType: .express),
        ExactRun("06:20", trainType: .express),
        ExactRun("06:30", trainType: .express),
        ExactRun("06:40", trainType: .express),
        ExactRun("06:50", trainType: .express),
        ExactRun("07:00", trainType: .express),
        ExactRun("07:04", trainType: .semiExpress),
        ExactRun("07:17", trainType: .semiExpress),
        ExactRun("07:30", trainType: .semiExpress),
        ExactRun("07:44", trainType: .semiExpress),
        ExactRun("08:00", trainType: .semiExpress),
        ExactRun("08:10", terminusStationId: "Station:Tokyu.DenEnToshi.Saginuma", trainType: .express),
        ExactRun("08:19", trainType: .express),
        ExactRun("08:33", trainType: .express),
        ExactRun("08:46", trainType: .express),
        ExactRun("09:01", trainType: .express),
        ExactRun("09:11", trainType: .express),
        ExactRun("09:22", trainType: .express),
        ExactRun("09:33", trainType: .express),
        ExactRun("09:47", trainType: .express),
        ExactRun("10:01", trainType: .express),
        ExactRun("10:05", trainType: .semiExpress),
        ExactRun("10:18", trainType: .express),
        ExactRun("10:32", trainType: .express),
        ExactRun("10:42", trainType: .express),
        ExactRun("10:47", trainType: .semiExpress),
        ExactRun("11:02", trainType: .express),
        ExactRun("11:11", trainType: .semiExpress),
        ExactRun("11:22", trainType: .express),
        ExactRun("11:32", trainType: .semiExpress),
        ExactRun("11:41", trainType: .express),
        ExactRun("11:52", trainType: .semiExpress),
        ExactRun("12:01", trainType: .express),
        ExactRun("12:08", trainType: .express),
        ExactRun("12:12", trainType: .semiExpress),
        ExactRun("12:21", trainType: .express),
        ExactRun("12:28", trainType: .express),
        ExactRun("12:32", trainType: .semiExpress),
        ExactRun("12:41", trainType: .express),
        ExactRun("12:48", trainType: .express),
        ExactRun("12:52", trainType: .semiExpress),
        ExactRun("13:01", trainType: .express),
        ExactRun("13:08", trainType: .express),
        ExactRun("13:12", trainType: .semiExpress),
        ExactRun("13:21", trainType: .express),
        ExactRun("13:28", trainType: .express),
        ExactRun("13:32", trainType: .semiExpress),
        ExactRun("13:41", trainType: .express),
        ExactRun("13:48", trainType: .express),
        ExactRun("13:52", trainType: .semiExpress),
        ExactRun("14:01", trainType: .express),
        ExactRun("14:08", trainType: .express),
        ExactRun("14:12", trainType: .semiExpress),
        ExactRun("14:21", trainType: .express),
        ExactRun("14:28", trainType: .express),
        ExactRun("14:32", trainType: .semiExpress),
        ExactRun("14:41", trainType: .express),
        ExactRun("14:48", trainType: .express),
        ExactRun("14:52", trainType: .semiExpress),
        ExactRun("15:01", trainType: .express),
        ExactRun("15:08", trainType: .express),
        ExactRun("15:12", trainType: .semiExpress),
        ExactRun("15:20", trainType: .express),
        ExactRun("15:28", trainType: .express),
        ExactRun("15:32", trainType: .semiExpress),
        ExactRun("15:41", trainType: .express),
        ExactRun("15:48", trainType: .express),
        ExactRun("15:52", trainType: .semiExpress),
        ExactRun("16:01", trainType: .express),
        ExactRun("16:12", trainType: .express),
        ExactRun("16:17", trainType: .semiExpress),
        ExactRun("16:31", trainType: .express),
        ExactRun("16:34", trainType: .semiExpress),
        ExactRun("16:49", trainType: .express),
        ExactRun("17:10", trainType: .express),
        ExactRun("17:13", trainType: .semiExpress),
        ExactRun("17:28", trainType: .express),
        ExactRun("17:32", trainType: .semiExpress),
        ExactRun("17:48", trainType: .express),
        ExactRun("17:55", trainType: .semiExpress),
        ExactRun("18:08", trainType: .express),
        ExactRun("18:15", trainType: .semiExpress),
        ExactRun("18:28", trainType: .express),
        ExactRun("18:36", trainType: .semiExpress),
        ExactRun("18:48", trainType: .express),
        ExactRun("18:55", trainType: .semiExpress),
        ExactRun("19:08", trainType: .express),
        ExactRun("19:14", trainType: .semiExpress),
        ExactRun("19:30", trainType: .express),
        ExactRun("19:37", trainType: .semiExpress),
        ExactRun("19:51", trainType: .express),
        ExactRun("20:06", trainType: .express),
        ExactRun("20:21", trainType: .express),
        ExactRun("20:37", trainType: .express),
        ExactRun("20:54", trainType: .express),
        ExactRun("21:12", trainType: .express),
        ExactRun("21:33", trainType: .express),
        ExactRun("21:52", trainType: .express),
        ExactRun("22:06", trainType: .semiExpress),
        ExactRun("22:43", trainType: .semiExpress),
    ]

    private static let denentoshiDescExpressHol: [ExactRun] = [
        ExactRun("05:05", trainType: .semiExpress),
        ExactRun("05:31", trainType: .semiExpress),
        ExactRun("06:03", trainType: .express),
        ExactRun("06:36", trainType: .express),
        ExactRun("06:50", trainType: .express),
        ExactRun("07:05", trainType: .express),
        ExactRun("07:17", trainType: .express),
        ExactRun("07:33", trainType: .express),
        ExactRun("07:46", trainType: .express),
        ExactRun("08:00", trainType: .express),
        ExactRun("08:13", trainType: .express),
        ExactRun("08:26", trainType: .express),
        ExactRun("08:38", trainType: .express),
        ExactRun("08:51", trainType: .express),
        ExactRun("09:04", trainType: .express),
        ExactRun("09:18", trainType: .express),
        ExactRun("09:32", trainType: .express),
        ExactRun("09:38", trainType: .semiExpress),
        ExactRun("09:49", trainType: .express),
        ExactRun("09:52", trainType: .semiExpress),
        ExactRun("09:58", trainType: .semiExpress),
        ExactRun("10:09", trainType: .express),
        ExactRun("10:11", trainType: .semiExpress),
        ExactRun("10:18", trainType: .semiExpress),
        ExactRun("10:28", trainType: .express),
        ExactRun("10:31", trainType: .semiExpress),
        ExactRun("10:38", trainType: .semiExpress),
        ExactRun("10:49", trainType: .express),
        ExactRun("10:52", trainType: .semiExpress),
        ExactRun("10:58", trainType: .semiExpress),
        ExactRun("11:09", trainType: .express),
        ExactRun("11:12", trainType: .semiExpress),
        ExactRun("11:18", trainType: .semiExpress),
        ExactRun("11:29", trainType: .express),
        ExactRun("11:32", trainType: .semiExpress),
        ExactRun("11:38", trainType: .semiExpress),
        ExactRun("11:48", trainType: .express),
        ExactRun("11:52", trainType: .semiExpress),
        ExactRun("11:58", trainType: .semiExpress),
        ExactRun("12:08", trainType: .express),
        ExactRun("12:12", trainType: .semiExpress),
        ExactRun("12:18", trainType: .semiExpress),
        ExactRun("12:28", trainType: .express),
        ExactRun("12:32", trainType: .semiExpress),
        ExactRun("12:38", trainType: .semiExpress),
        ExactRun("12:48", trainType: .express),
        ExactRun("12:52", trainType: .semiExpress),
        ExactRun("12:58", trainType: .semiExpress),
        ExactRun("13:08", trainType: .express),
        ExactRun("13:12", trainType: .semiExpress),
        ExactRun("13:21", trainType: .express),
        ExactRun("13:28", trainType: .express),
        ExactRun("13:32", trainType: .semiExpress),
        ExactRun("13:41", trainType: .express),
        ExactRun("13:48", trainType: .express),
        ExactRun("13:52", trainType: .semiExpress),
        ExactRun("14:01", trainType: .express),
        ExactRun("14:08", trainType: .express),
        ExactRun("14:12", trainType: .semiExpress),
        ExactRun("14:21", trainType: .express),
        ExactRun("14:28", trainType: .express),
        ExactRun("14:32", trainType: .semiExpress),
        ExactRun("14:41", trainType: .express),
        ExactRun("14:48", trainType: .express),
        ExactRun("14:52", trainType: .semiExpress),
        ExactRun("15:01", trainType: .express),
        ExactRun("15:08", trainType: .express),
        ExactRun("15:12", trainType: .semiExpress),
        ExactRun("15:21", trainType: .express),
        ExactRun("15:28", trainType: .express),
        ExactRun("15:32", trainType: .semiExpress),
        ExactRun("15:41", trainType: .express),
        ExactRun("15:48", trainType: .express),
        ExactRun("15:52", trainType: .semiExpress),
        ExactRun("16:01", trainType: .express),
        ExactRun("16:08", trainType: .express),
        ExactRun("16:12", trainType: .semiExpress),
        ExactRun("16:21", trainType: .express),
        ExactRun("16:28", trainType: .express),
        ExactRun("16:32", trainType: .semiExpress),
        ExactRun("16:46", trainType: .express),
        ExactRun("17:01", trainType: .express),
        ExactRun("17:16", trainType: .express),
        ExactRun("17:32", trainType: .express),
        ExactRun("17:45", trainType: .express),
        ExactRun("18:02", trainType: .express),
        ExactRun("18:17", trainType: .express),
        ExactRun("18:32", trainType: .express),
        ExactRun("18:47", trainType: .express),
        ExactRun("19:02", trainType: .express),
        ExactRun("19:17", trainType: .express),
        ExactRun("19:32", trainType: .express),
        ExactRun("19:47", trainType: .express),
        ExactRun("20:06", trainType: .express),
        ExactRun("20:23", trainType: .express),
        ExactRun("20:43", trainType: .express),
        ExactRun("21:00", trainType: .express),
        ExactRun("21:24", trainType: .express),
        ExactRun("21:51", trainType: .express),
        ExactRun("22:18", trainType: .express),
        ExactRun("22:47", trainType: .express),
    ]

}
