import Foundation

extension TokyuLineData {

    // MARK: - Tokyu Meguro Line (MG)

    static let meguro = StaticTrainLine(
        id: "Railway:Tokyu.Meguro",
        nameJa: "東急目黒線",
        nameEn: "Tokyu Meguro Line",
        operatorId: "Operator:Tokyu",
        colorHex: "#009CD2",
        stations: [
            st("Tokyu.Meguro", "Meguro", "目黒", "Meguro", "MG01", 35.6340, 139.7157),
            st("Tokyu.Meguro", "Fudomae", "不動前", "Fudo-mae", "MG02", 35.6260, 139.7120),
            st("Tokyu.Meguro", "MusashiKoyama", "武蔵小山", "Musashi-Koyama", "MG03", 35.6210, 139.7020),
            st("Tokyu.Meguro", "NishiKoyama", "西小山", "Nishi-Koyama", "MG04", 35.6170, 139.6960),
            st("Tokyu.Meguro", "Senzoku", "洗足", "Senzoku", "MG05", 35.6140, 139.6890),
            st("Tokyu.Meguro", "Ookayama", "大岡山", "Ookayama", "MG06", 35.6070, 139.6850),
            st("Tokyu.Meguro", "Okusawa", "奥沢", "Okusawa", "MG07", 35.6040, 139.6770),
            st("Tokyu.Meguro", "DenenChofu", "田園調布", "Den-en-chofu", "MG08", 35.5990, 139.6660),
            st("Tokyu.Meguro", "Tamagawa", "多摩川", "Tamagawa", "MG09", 35.5920, 139.6660),
            st("Tokyu.Meguro", "ShinMaruko", "新丸子", "Shin-maruko", "MG10", 35.5810, 139.6595),
            st("Tokyu.Meguro", "MusashiKosugi", "武蔵小杉", "Musashi-Kosugi", "MG11", 35.5766, 139.6597),
            st("Tokyu.Meguro", "Motosumiyoshi", "元住吉", "Motosumiyoshi", "MG12", 35.5680, 139.6510),
            st("Tokyu.Meguro", "Hiyoshi", "日吉", "Hiyoshi", "MG13", 35.5540, 139.6470),
        ],
        hopTimesMinutes: [
            2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        ],
        directions: [
            direction("Tokyu.Meguro", "Hiyoshi", "日吉・新横浜方面", "For Hiyoshi & Shin-Yokohama",
                      ascending: true,
                      weekday: pattern("05:00", "24:02", [
                          ("05:00", 8), ("06:30", 4), ("09:30", 6), ("16:30", 5), ("20:00", 6), ("22:00", 8),
                      ]),
                      holiday: pattern("05:00", "24:02", [
                          ("05:00", 8), ("07:00", 6), ("10:00", 6), ("20:00", 8),
                      ]),
                      expressWeekday: meguroAscExpressWd,
                      expressHoliday: meguroAscExpressHol),
            direction("Tokyu.Meguro", "Meguro", "目黒・大手町方面", "For Meguro & Otemachi",
                      ascending: false,
                      weekday: pattern("05:10", "24:29", [
                          ("05:10", 8), ("06:30", 4), ("09:30", 6), ("16:30", 5), ("20:00", 6), ("22:00", 8),
                      ]),
                      holiday: pattern("05:10", "24:29", [
                          ("05:10", 8), ("07:00", 6), ("10:00", 6), ("20:00", 8),
                      ]),
                      expressWeekday: meguroDescExpressWd,
                      expressHoliday: meguroDescExpressHol),
        ],
        delayInfo: delayInfo,
        throughServices: [
            through("Tokyu.Meguro.Meguro", .descending,
                    "東京メトロ南北線", "Tokyo Metro Namboku Line",
                    "四ツ谷・赤羽岩淵方面", "for Yotsuya & Akabane-Iwabuchi",
                    to: "Railway:TokyoMetro.Namboku"),
            through("Tokyu.Meguro.Meguro", .descending,
                    "都営三田線", "Toei Mita Line",
                    "大手町・西高島平方面", "for Otemachi & Nishi-Takashimadaira",
                    to: "Railway:Toei.Mita"),
            through("Tokyu.Meguro.Hiyoshi", .ascending,
                    "東急新横浜線", "Tokyu Shin-Yokohama Line",
                    "新横浜・相鉄線方面", "for Shin-Yokohama & the Sotetsu Line"),
        ],
        // 停車駅 from official table (absolute indices). 急行=express.
        // Source: https://www.tokyu.co.jp/railway/mg/
        stopPatterns: [
            .express: [0, 2, 5, 7, 8, 10, 12], // 急行
        ]
    )

    private static let meguroAscExpressWd: [ExactRun] = [
        ExactRun("05:41", trainType: .express),
        ExactRun("06:24", trainType: .express),
        ExactRun("06:55", trainType: .express),
        ExactRun("07:13", trainType: .express),
        ExactRun("07:39", trainType: .express),
        ExactRun("07:45", terminusStationId: "Station:Tokyu.Meguro.MusashiKosugi", trainType: .express),
        ExactRun("08:01", trainType: .express),
        ExactRun("08:06", terminusStationId: "Station:Tokyu.Meguro.MusashiKosugi", trainType: .express),
        ExactRun("08:12", trainType: .express),
        ExactRun("08:18", trainType: .express),
        ExactRun("08:25", trainType: .express),
        ExactRun("08:43", trainType: .express),
        ExactRun("08:51", trainType: .express),
        ExactRun("09:01", trainType: .express),
        ExactRun("09:10", trainType: .express),
        ExactRun("09:28", trainType: .express),
        ExactRun("10:00", trainType: .express),
        ExactRun("10:16", trainType: .express),
        ExactRun("10:29", trainType: .express),
        ExactRun("10:44", trainType: .express),
        ExactRun("10:59", trainType: .express),
        ExactRun("11:14", trainType: .express),
        ExactRun("11:29", trainType: .express),
        ExactRun("11:44", trainType: .express),
        ExactRun("11:59", trainType: .express),
        ExactRun("12:14", trainType: .express),
        ExactRun("12:29", trainType: .express),
        ExactRun("12:44", trainType: .express),
        ExactRun("12:59", trainType: .express),
        ExactRun("13:14", trainType: .express),
        ExactRun("13:29", trainType: .express),
        ExactRun("13:44", trainType: .express),
        ExactRun("13:59", trainType: .express),
        ExactRun("14:14", trainType: .express),
        ExactRun("14:29", trainType: .express),
        ExactRun("14:44", trainType: .express),
        ExactRun("14:59", trainType: .express),
        ExactRun("15:14", trainType: .express),
        ExactRun("15:29", trainType: .express),
        ExactRun("15:44", trainType: .express),
        ExactRun("15:59", trainType: .express),
        ExactRun("16:14", trainType: .express),
        ExactRun("16:29", trainType: .express),
        ExactRun("16:44", trainType: .express),
        ExactRun("16:59", trainType: .express),
        ExactRun("17:15", trainType: .express),
        ExactRun("17:32", trainType: .express),
        ExactRun("17:49", trainType: .express),
        ExactRun("18:06", trainType: .express),
        ExactRun("18:21", trainType: .express),
        ExactRun("18:35", trainType: .express),
        ExactRun("18:50", trainType: .express),
        ExactRun("19:05", trainType: .express),
        ExactRun("19:20", trainType: .express),
        ExactRun("19:36", trainType: .express),
        ExactRun("19:50", trainType: .express),
        ExactRun("20:05", trainType: .express),
        ExactRun("20:20", trainType: .express),
        ExactRun("20:36", trainType: .express),
        ExactRun("20:50", trainType: .express),
        ExactRun("21:06", trainType: .express),
        ExactRun("21:19", trainType: .express),
        ExactRun("21:36", trainType: .express),
        ExactRun("21:52", trainType: .express),
        ExactRun("22:08", trainType: .express),
        ExactRun("22:23", trainType: .express),
        ExactRun("23:02", trainType: .express),
        ExactRun("23:35", trainType: .express),
    ]

    private static let meguroAscExpressHol: [ExactRun] = [
        ExactRun("05:41", trainType: .express),
        ExactRun("06:24", trainType: .express),
        ExactRun("07:26", trainType: .express),
        ExactRun("07:59", trainType: .express),
        ExactRun("08:13", trainType: .express),
        ExactRun("08:28", trainType: .express),
        ExactRun("08:43", trainType: .express),
        ExactRun("08:58", trainType: .express),
        ExactRun("09:14", trainType: .express),
        ExactRun("09:29", trainType: .express),
        ExactRun("09:44", trainType: .express),
        ExactRun("09:59", trainType: .express),
        ExactRun("10:14", trainType: .express),
        ExactRun("10:30", trainType: .express),
        ExactRun("10:44", trainType: .express),
        ExactRun("10:59", trainType: .express),
        ExactRun("11:14", trainType: .express),
        ExactRun("11:29", trainType: .express),
        ExactRun("11:44", trainType: .express),
        ExactRun("11:59", trainType: .express),
        ExactRun("12:14", trainType: .express),
        ExactRun("12:29", trainType: .express),
        ExactRun("12:44", trainType: .express),
        ExactRun("12:59", trainType: .express),
        ExactRun("13:14", trainType: .express),
        ExactRun("13:29", trainType: .express),
        ExactRun("13:44", trainType: .express),
        ExactRun("13:59", trainType: .express),
        ExactRun("14:14", trainType: .express),
        ExactRun("14:29", trainType: .express),
        ExactRun("14:44", trainType: .express),
        ExactRun("14:59", trainType: .express),
        ExactRun("15:14", trainType: .express),
        ExactRun("15:29", trainType: .express),
        ExactRun("15:44", trainType: .express),
        ExactRun("15:59", trainType: .express),
        ExactRun("16:14", trainType: .express),
        ExactRun("16:29", trainType: .express),
        ExactRun("16:44", trainType: .express),
        ExactRun("16:59", trainType: .express),
        ExactRun("17:14", trainType: .express),
        ExactRun("17:29", trainType: .express),
        ExactRun("17:44", trainType: .express),
        ExactRun("17:59", trainType: .express),
        ExactRun("18:14", trainType: .express),
        ExactRun("18:29", trainType: .express),
        ExactRun("18:44", trainType: .express),
        ExactRun("18:59", trainType: .express),
        ExactRun("19:14", trainType: .express),
        ExactRun("19:29", trainType: .express),
        ExactRun("19:59", trainType: .express),
        ExactRun("20:31", trainType: .express),
        ExactRun("21:00", trainType: .express),
        ExactRun("21:24", trainType: .express),
        ExactRun("21:55", trainType: .express),
        ExactRun("22:25", trainType: .express),
        ExactRun("23:22", terminusStationId: "Station:Tokyu.Meguro.MusashiKosugi", trainType: .express),
    ]

    private static let meguroDescExpressWd: [ExactRun] = [
        ExactRun("06:02", trainType: .express),
        ExactRun("06:11", trainType: .express),
        ExactRun("06:40", trainType: .express),
        ExactRun("06:55", trainType: .express),
        ExactRun("07:01", trainType: .express),
        ExactRun("07:14", trainType: .express),
        ExactRun("07:21", trainType: .express),
        ExactRun("07:31", trainType: .express),
        ExactRun("07:36", trainType: .express),
        ExactRun("07:46", trainType: .express),
        ExactRun("07:51", trainType: .express),
        ExactRun("07:56", trainType: .express),
        ExactRun("08:01", trainType: .express),
        ExactRun("08:06", trainType: .express),
        ExactRun("08:11", trainType: .express),
        ExactRun("08:21", trainType: .express),
        ExactRun("08:26", trainType: .express),
        ExactRun("08:33", trainType: .express),
        ExactRun("08:43", trainType: .express),
        ExactRun("08:53", trainType: .express),
        ExactRun("09:06", trainType: .express),
        ExactRun("09:17", trainType: .express),
        ExactRun("09:30", trainType: .express),
        ExactRun("09:45", trainType: .express),
        ExactRun("10:04", trainType: .express),
        ExactRun("10:19", trainType: .express),
        ExactRun("10:34", trainType: .express),
        ExactRun("10:49", trainType: .express),
        ExactRun("11:04", trainType: .express),
        ExactRun("11:19", trainType: .express),
        ExactRun("11:34", trainType: .express),
        ExactRun("11:49", trainType: .express),
        ExactRun("12:04", trainType: .express),
        ExactRun("12:19", trainType: .express),
        ExactRun("12:34", trainType: .express),
        ExactRun("12:49", trainType: .express),
        ExactRun("13:04", trainType: .express),
        ExactRun("13:19", trainType: .express),
        ExactRun("13:34", trainType: .express),
        ExactRun("13:49", trainType: .express),
        ExactRun("14:04", trainType: .express),
        ExactRun("14:19", trainType: .express),
        ExactRun("14:34", trainType: .express),
        ExactRun("14:49", trainType: .express),
        ExactRun("15:04", trainType: .express),
        ExactRun("15:19", trainType: .express),
        ExactRun("15:34", trainType: .express),
        ExactRun("15:49", trainType: .express),
        ExactRun("16:04", trainType: .express),
        ExactRun("16:19", trainType: .express),
        ExactRun("16:34", trainType: .express),
        ExactRun("16:48", trainType: .express),
        ExactRun("17:02", trainType: .express),
        ExactRun("17:14", trainType: .express),
        ExactRun("17:31", trainType: .express),
        ExactRun("17:43", trainType: .express),
        ExactRun("17:54", trainType: .express),
        ExactRun("18:13", trainType: .express),
        ExactRun("18:28", trainType: .express),
        ExactRun("18:44", trainType: .express),
        ExactRun("18:58", trainType: .express),
        ExactRun("19:14", trainType: .express),
        ExactRun("19:29", trainType: .express),
        ExactRun("19:42", trainType: .express),
        ExactRun("19:57", trainType: .express),
        ExactRun("20:12", trainType: .express),
        ExactRun("20:29", trainType: .express),
        ExactRun("20:44", trainType: .express),
        ExactRun("20:59", trainType: .express),
        ExactRun("21:16", trainType: .express),
        ExactRun("21:31", trainType: .express),
        ExactRun("21:44", trainType: .express),
        ExactRun("23:19", trainType: .express),
    ]

    private static let meguroDescExpressHol: [ExactRun] = [
        ExactRun("07:24", trainType: .express),
        ExactRun("08:01", trainType: .express),
        ExactRun("08:17", trainType: .express),
        ExactRun("08:31", trainType: .express),
        ExactRun("08:48", trainType: .express),
        ExactRun("09:03", trainType: .express),
        ExactRun("09:18", trainType: .express),
        ExactRun("09:33", trainType: .express),
        ExactRun("09:48", trainType: .express),
        ExactRun("10:03", trainType: .express),
        ExactRun("10:18", trainType: .express),
        ExactRun("10:33", trainType: .express),
        ExactRun("10:49", trainType: .express),
        ExactRun("11:04", trainType: .express),
        ExactRun("11:19", trainType: .express),
        ExactRun("11:34", trainType: .express),
        ExactRun("11:49", trainType: .express),
        ExactRun("12:04", trainType: .express),
        ExactRun("12:19", trainType: .express),
        ExactRun("12:34", trainType: .express),
        ExactRun("12:49", trainType: .express),
        ExactRun("13:04", trainType: .express),
        ExactRun("13:19", trainType: .express),
        ExactRun("13:34", trainType: .express),
        ExactRun("13:49", trainType: .express),
        ExactRun("14:04", trainType: .express),
        ExactRun("14:19", trainType: .express),
        ExactRun("14:34", trainType: .express),
        ExactRun("14:49", trainType: .express),
        ExactRun("15:04", trainType: .express),
        ExactRun("15:19", trainType: .express),
        ExactRun("15:34", trainType: .express),
        ExactRun("15:49", trainType: .express),
        ExactRun("16:04", trainType: .express),
        ExactRun("16:19", trainType: .express),
        ExactRun("16:34", trainType: .express),
        ExactRun("16:49", trainType: .express),
        ExactRun("17:04", trainType: .express),
        ExactRun("17:19", trainType: .express),
        ExactRun("17:34", trainType: .express),
        ExactRun("17:49", trainType: .express),
        ExactRun("18:04", trainType: .express),
        ExactRun("18:19", trainType: .express),
        ExactRun("18:33", trainType: .express),
        ExactRun("18:49", trainType: .express),
        ExactRun("19:15", trainType: .express),
        ExactRun("19:45", trainType: .express),
        ExactRun("20:11", trainType: .express),
        ExactRun("20:47", trainType: .express),
        ExactRun("21:19", trainType: .express),
        ExactRun("21:47", trainType: .express),
        ExactRun("22:58", trainType: .express),
    ]

}
