import Foundation

extension TokyuLineData {

    // MARK: - Tokyu Toyoko Line (TY)

    static let toyoko = StaticTrainLine(
        id: "Railway:Tokyu.Toyoko",
        nameJa: "東急東横線",
        nameEn: "Tokyu Toyoko Line",
        operatorId: "Operator:Tokyu",
        colorHex: "#DA0442",
        stations: [
            st("Tokyu.Toyoko", "Shibuya", "渋谷", "Shibuya", "TY01", 35.6580, 139.7016),
            st("Tokyu.Toyoko", "Daikanyama", "代官山", "Daikanyama", "TY02", 35.6485, 139.7030),
            st("Tokyu.Toyoko", "Nakameguro", "中目黒", "Nakameguro", "TY03", 35.6440, 139.6990),
            st("Tokyu.Toyoko", "Yutenji", "祐天寺", "Yutenji", "TY04", 35.6404, 139.6934),
            st("Tokyu.Toyoko", "GakugeiDaigaku", "学芸大学", "Gakugei-daigaku", "TY05", 35.6280, 139.6855),
            st("Tokyu.Toyoko", "ToritsuDaigaku", "都立大学", "Toritsu-daigaku", "TY06", 35.6237, 139.6852),
            st("Tokyu.Toyoko", "Jiyugaoka", "自由が丘", "Jiyugaoka", "TY07", 35.6076, 139.6690),
            st("Tokyu.Toyoko", "DenenChofu", "田園調布", "Den-en-chofu", "TY08", 35.5990, 139.6660),
            st("Tokyu.Toyoko", "Tamagawa", "多摩川", "Tamagawa", "TY09", 35.5920, 139.6660),
            st("Tokyu.Toyoko", "ShinMaruko", "新丸子", "Shin-maruko", "TY10", 35.5810, 139.6595),
            st("Tokyu.Toyoko", "MusashiKosugi", "武蔵小杉", "Musashi-Kosugi", "TY11", 35.5766, 139.6597),
            st("Tokyu.Toyoko", "Motosumiyoshi", "元住吉", "Motosumiyoshi", "TY12", 35.5680, 139.6510),
            st("Tokyu.Toyoko", "Hiyoshi", "日吉", "Hiyoshi", "TY13", 35.5540, 139.6470),
            st("Tokyu.Toyoko", "Tsunashima", "綱島", "Tsunashima", "TY14", 35.5350, 139.6330),
            st("Tokyu.Toyoko", "Okurayama", "大倉山", "Okurayama", "TY15", 35.5240, 139.6300),
            st("Tokyu.Toyoko", "Kikuna", "菊名", "Kikuna", "TY16", 35.5093, 139.6303),
            st("Tokyu.Toyoko", "Myorenji", "妙蓮寺", "Myorenji", "TY17", 35.5020, 139.6260),
            st("Tokyu.Toyoko", "Hakuraku", "白楽", "Hakuraku", "TY18", 35.4930, 139.6250),
            st("Tokyu.Toyoko", "HigashiHakuraku", "東白楽", "Higashi-hakuraku", "TY19", 35.4870, 139.6250),
            st("Tokyu.Toyoko", "Tammachi", "反町", "Tammachi", "TY20", 35.4770, 139.6260),
            st("Tokyu.Toyoko", "Yokohama", "横浜", "Yokohama", "TY21", 35.4657, 139.6224),
        ],
        hopTimesMinutes: [
            2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        ],
        directions: [
            direction("Tokyu.Toyoko", "Yokohama", "横浜・元町・中華街方面", "For Yokohama & Motomachi-Chukagai",
                      ascending: true,
                      weekday: pattern("05:00", "24:21", [
                          ("05:00", 7), ("06:30", 4), ("09:30", 5), ("16:30", 4), ("20:00", 5), ("22:00", 7),
                      ]),
                      holiday: pattern("05:00", "24:21", [
                          ("05:00", 7), ("07:00", 5), ("10:00", 5), ("20:00", 7),
                      ]),
                      expressWeekday: toyokoAscExpressWd,
                      expressHoliday: toyokoAscExpressHol),
            direction("Tokyu.Toyoko", "Shibuya", "渋谷・和光市方面", "For Shibuya & Wakoshi",
                      ascending: false,
                      weekday: pattern("05:00", "24:12", [
                          ("05:00", 7), ("06:30", 4), ("09:30", 5), ("16:30", 4), ("20:00", 5), ("22:00", 7),
                      ]),
                      holiday: pattern("05:00", "24:12", [
                          ("05:00", 7), ("07:00", 5), ("10:00", 5), ("20:00", 7),
                      ]),
                      expressWeekday: toyokoDescExpressWd,
                      expressHoliday: toyokoDescExpressHol),
        ],
        delayInfo: delayInfo,
        throughServices: [
            through("Tokyu.Toyoko.Shibuya", .descending,
                    "東京メトロ副都心線", "Tokyo Metro Fukutoshin Line",
                    "池袋・和光市方面", "for Ikebukuro & Wakoshi",
                    to: "Railway:TokyoMetro.Fukutoshin"),
            through("Tokyu.Toyoko.Yokohama", .ascending,
                    "みなとみらい線", "Minatomirai Line",
                    "元町・中華街方面", "for Motomachi-Chukagai",
                    to: "Railway:Minatomirai.Minatomirai"),
        ],
        // 停車駅 from official table (absolute indices). 特急=limitedExpress
        // (+F-Liner, same 停車駅), 通勤特急=commuterLimitedExpress (特急+日吉), 急行=express.
        // Source: https://www.tokyo-train-master.com/ty-toyoko
        stopPatterns: [
            .limitedExpress:         [0, 2, 6, 10, 15, 20],       // 特急
            .commuterLimitedExpress: [0, 2, 6, 10, 12, 15, 20],   // 通勤特急
            .express:                [0, 2, 4, 6, 7, 8, 10, 12, 13, 15, 20], // 急行
        ]
    )

    // MARK: - Express run data (ODPT StationTimetable: exact times/types/termini).
    // Stops resolve from each line's absolute `stopPatterns`. See emit_tokyu.py.
    private static let toyokoAscExpressWd: [ExactRun] = [
        ExactRun("05:23", trainType: .express),
        ExactRun("05:51", trainType: .express),
        ExactRun("06:03", trainType: .express),
        ExactRun("06:26", trainType: .express),
        ExactRun("06:35", trainType: .express),
        ExactRun("06:54", trainType: .express),
        ExactRun("07:02", trainType: .express),
        ExactRun("07:08", trainType: .express),
        ExactRun("07:18", trainType: .express),
        ExactRun("07:26", trainType: .express),
        ExactRun("07:32", trainType: .express),
        ExactRun("07:41", trainType: .commuterLimitedExpress),
        ExactRun("07:47", trainType: .express),
        ExactRun("07:52", trainType: .express),
        ExactRun("07:56", trainType: .commuterLimitedExpress),
        ExactRun("08:04", trainType: .express),
        ExactRun("08:11", trainType: .commuterLimitedExpress),
        ExactRun("08:14", trainType: .express),
        ExactRun("08:19", trainType: .express),
        ExactRun("08:26", trainType: .commuterLimitedExpress),
        ExactRun("08:28", trainType: .express),
        ExactRun("08:34", trainType: .commuterLimitedExpress),
        ExactRun("08:42", trainType: .express),
        ExactRun("08:50", trainType: .commuterLimitedExpress),
        ExactRun("08:53", trainType: .express),
        ExactRun("09:00", trainType: .limitedExpress),
        ExactRun("09:06", trainType: .express),
        ExactRun("09:11", trainType: .express),
        ExactRun("09:16", trainType: .express),
        ExactRun("09:24", trainType: .limitedExpress),
        ExactRun("09:29", trainType: .express),
        ExactRun("09:33", trainType: .express),
        ExactRun("09:39", trainType: .limitedExpress),
        ExactRun("09:44", trainType: .express),
        ExactRun("09:49", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
        ExactRun("09:55", trainType: .limitedExpress),
        ExactRun("10:09", trainType: .limitedExpress),
        ExactRun("10:13", trainType: .express),
        ExactRun("10:19", trainType: .express),
        ExactRun("10:24", trainType: .limitedExpress),
        ExactRun("10:29", trainType: .express),
        ExactRun("10:32", trainType: .express),
        ExactRun("10:39", trainType: .limitedExpress),
        ExactRun("10:44", trainType: .express),
        ExactRun("10:54", trainType: .limitedExpress),
        ExactRun("10:59", trainType: .express),
        ExactRun("11:09", trainType: .limitedExpress),
        ExactRun("11:12", trainType: .express),
        ExactRun("11:17", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
        ExactRun("11:24", trainType: .limitedExpress),
        ExactRun("11:29", trainType: .express),
        ExactRun("11:39", trainType: .limitedExpress),
        ExactRun("11:42", trainType: .express),
        ExactRun("11:47", trainType: .express),
        ExactRun("11:54", trainType: .limitedExpress),
        ExactRun("11:59", trainType: .express),
        ExactRun("12:09", trainType: .limitedExpress),
        ExactRun("12:12", trainType: .express),
        ExactRun("12:17", trainType: .express),
        ExactRun("12:24", trainType: .limitedExpress),
        ExactRun("12:29", trainType: .express),
        ExactRun("12:39", trainType: .limitedExpress),
        ExactRun("12:42", trainType: .express),
        ExactRun("12:47", trainType: .express),
        ExactRun("12:54", trainType: .limitedExpress),
        ExactRun("12:59", trainType: .express),
        ExactRun("13:09", trainType: .limitedExpress),
        ExactRun("13:12", trainType: .express),
        ExactRun("13:17", trainType: .express),
        ExactRun("13:24", trainType: .limitedExpress),
        ExactRun("13:29", trainType: .express),
        ExactRun("13:39", trainType: .limitedExpress),
        ExactRun("13:42", trainType: .express),
        ExactRun("13:47", trainType: .express),
        ExactRun("13:54", trainType: .limitedExpress),
        ExactRun("13:59", trainType: .express),
        ExactRun("14:09", trainType: .limitedExpress),
        ExactRun("14:12", trainType: .express),
        ExactRun("14:17", trainType: .express),
        ExactRun("14:24", trainType: .limitedExpress),
        ExactRun("14:29", trainType: .express),
        ExactRun("14:39", trainType: .limitedExpress),
        ExactRun("14:42", trainType: .express),
        ExactRun("14:47", trainType: .express),
        ExactRun("14:54", trainType: .limitedExpress),
        ExactRun("14:59", trainType: .express),
        ExactRun("15:09", trainType: .limitedExpress),
        ExactRun("15:12", trainType: .express),
        ExactRun("15:17", trainType: .express),
        ExactRun("15:24", trainType: .limitedExpress),
        ExactRun("15:29", trainType: .express),
        ExactRun("15:39", trainType: .limitedExpress),
        ExactRun("15:42", trainType: .express),
        ExactRun("15:47", trainType: .express),
        ExactRun("15:54", trainType: .limitedExpress),
        ExactRun("15:59", trainType: .express),
        ExactRun("16:04", trainType: .express),
        ExactRun("16:07", trainType: .express),
        ExactRun("16:14", trainType: .limitedExpress),
        ExactRun("16:19", trainType: .express),
        ExactRun("16:29", trainType: .limitedExpress),
        ExactRun("16:34", trainType: .express),
        ExactRun("16:45", trainType: .limitedExpress),
        ExactRun("16:50", trainType: .express),
        ExactRun("16:53", trainType: .express),
        ExactRun("17:00", trainType: .commuterLimitedExpress),
        ExactRun("17:02", trainType: .express),
        ExactRun("17:07", trainType: .express),
        ExactRun("17:15", trainType: .commuterLimitedExpress),
        ExactRun("17:20", trainType: .express),
        ExactRun("17:24", trainType: .express),
        ExactRun("17:30", trainType: .commuterLimitedExpress),
        ExactRun("17:34", trainType: .express),
        ExactRun("17:39", trainType: .express),
        ExactRun("17:45", trainType: .commuterLimitedExpress),
        ExactRun("17:50", trainType: .express),
        ExactRun("17:55", trainType: .express),
        ExactRun("18:00", trainType: .commuterLimitedExpress),
        ExactRun("18:05", trainType: .express),
        ExactRun("18:15", trainType: .commuterLimitedExpress),
        ExactRun("18:19", trainType: .express),
        ExactRun("18:24", trainType: .express),
        ExactRun("18:30", trainType: .commuterLimitedExpress),
        ExactRun("18:35", trainType: .express),
        ExactRun("18:40", trainType: .express),
        ExactRun("18:45", trainType: .commuterLimitedExpress),
        ExactRun("18:50", trainType: .express),
        ExactRun("18:54", trainType: .express),
        ExactRun("19:00", trainType: .commuterLimitedExpress),
        ExactRun("19:05", trainType: .express),
        ExactRun("19:09", trainType: .express),
        ExactRun("19:15", trainType: .commuterLimitedExpress),
        ExactRun("19:20", trainType: .express),
        ExactRun("19:24", trainType: .express),
        ExactRun("19:30", trainType: .commuterLimitedExpress),
        ExactRun("19:35", trainType: .express),
        ExactRun("19:39", trainType: .express),
        ExactRun("19:45", trainType: .commuterLimitedExpress),
        ExactRun("19:50", trainType: .express),
        ExactRun("19:54", trainType: .express),
        ExactRun("20:00", trainType: .commuterLimitedExpress),
        ExactRun("20:05", trainType: .express),
        ExactRun("20:09", trainType: .express),
        ExactRun("20:15", trainType: .commuterLimitedExpress),
        ExactRun("20:20", trainType: .express),
        ExactRun("20:30", trainType: .commuterLimitedExpress),
        ExactRun("20:35", trainType: .express),
        ExactRun("20:45", trainType: .commuterLimitedExpress),
        ExactRun("20:50", trainType: .express),
        ExactRun("20:54", trainType: .express),
        ExactRun("21:00", trainType: .commuterLimitedExpress),
        ExactRun("21:05", trainType: .express),
        ExactRun("21:07", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
        ExactRun("21:15", trainType: .commuterLimitedExpress),
        ExactRun("21:20", trainType: .express),
        ExactRun("21:24", trainType: .express),
        ExactRun("21:30", trainType: .commuterLimitedExpress),
        ExactRun("21:35", trainType: .express),
        ExactRun("21:45", trainType: .commuterLimitedExpress),
        ExactRun("21:49", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
        ExactRun("21:52", trainType: .express),
        ExactRun("22:00", trainType: .commuterLimitedExpress),
        ExactRun("22:05", trainType: .express),
        ExactRun("22:15", trainType: .commuterLimitedExpress),
        ExactRun("22:21", trainType: .express),
        ExactRun("22:29", trainType: .commuterLimitedExpress),
        ExactRun("22:35", trainType: .express),
        ExactRun("22:38", trainType: .express),
        ExactRun("22:43", trainType: .commuterLimitedExpress),
        ExactRun("22:50", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
        ExactRun("22:53", trainType: .express),
        ExactRun("23:00", trainType: .commuterLimitedExpress),
        ExactRun("23:05", trainType: .express),
        ExactRun("23:08", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
        ExactRun("23:15", trainType: .commuterLimitedExpress),
        ExactRun("23:22", trainType: .express),
        ExactRun("23:34", trainType: .express),
        ExactRun("23:42", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
        ExactRun("23:53", trainType: .express),
        ExactRun("24:08", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
    ]

    private static let toyokoAscExpressHol: [ExactRun] = [
        ExactRun("05:23", trainType: .express),
        ExactRun("06:08", trainType: .limitedExpress),
        ExactRun("06:17", trainType: .express),
        ExactRun("06:23", trainType: .express),
        ExactRun("06:38", trainType: .limitedExpress),
        ExactRun("06:45", trainType: .express),
        ExactRun("06:53", trainType: .limitedExpress),
        ExactRun("06:58", trainType: .express),
        ExactRun("07:06", terminusStationId: "Station:Tokyu.Toyoko.Kikuna", trainType: .express),
        ExactRun("07:10", trainType: .express),
        ExactRun("07:16", trainType: .express),
        ExactRun("07:23", trainType: .limitedExpress),
        ExactRun("07:28", trainType: .express),
        ExactRun("07:38", trainType: .limitedExpress),
        ExactRun("07:45", trainType: .express),
        ExactRun("07:53", trainType: .limitedExpress),
        ExactRun("07:58", trainType: .express),
        ExactRun("08:08", trainType: .limitedExpress),
        ExactRun("08:13", trainType: .express),
        ExactRun("08:18", trainType: .express),
        ExactRun("08:23", trainType: .limitedExpress),
        ExactRun("08:28", trainType: .express),
        ExactRun("08:38", trainType: .limitedExpress),
        ExactRun("08:43", trainType: .express),
        ExactRun("08:48", trainType: .express),
        ExactRun("08:54", trainType: .limitedExpress),
        ExactRun("08:59", trainType: .express),
        ExactRun("09:09", trainType: .limitedExpress),
        ExactRun("09:14", trainType: .express),
        ExactRun("09:19", trainType: .express),
        ExactRun("09:25", trainType: .limitedExpress),
        ExactRun("09:30", trainType: .express),
        ExactRun("09:39", trainType: .limitedExpress),
        ExactRun("09:44", trainType: .express),
        ExactRun("09:49", trainType: .express),
        ExactRun("09:54", trainType: .limitedExpress),
        ExactRun("09:59", trainType: .express),
        ExactRun("10:08", trainType: .limitedExpress),
        ExactRun("10:10", trainType: .express),
        ExactRun("10:14", trainType: .express),
        ExactRun("10:24", trainType: .limitedExpress),
        ExactRun("10:29", trainType: .express),
        ExactRun("10:39", trainType: .limitedExpress),
        ExactRun("10:44", trainType: .express),
        ExactRun("10:49", trainType: .express),
        ExactRun("10:54", trainType: .limitedExpress),
        ExactRun("10:59", trainType: .express),
        ExactRun("11:09", trainType: .limitedExpress),
        ExactRun("11:12", trainType: .express),
        ExactRun("11:17", trainType: .express),
        ExactRun("11:24", trainType: .limitedExpress),
        ExactRun("11:29", trainType: .express),
        ExactRun("11:39", trainType: .limitedExpress),
        ExactRun("11:42", trainType: .express),
        ExactRun("11:47", trainType: .express),
        ExactRun("11:54", trainType: .limitedExpress),
        ExactRun("11:59", trainType: .express),
        ExactRun("12:09", trainType: .limitedExpress),
        ExactRun("12:12", trainType: .express),
        ExactRun("12:17", trainType: .express),
        ExactRun("12:24", trainType: .limitedExpress),
        ExactRun("12:29", trainType: .express),
        ExactRun("12:39", trainType: .limitedExpress),
        ExactRun("12:42", trainType: .express),
        ExactRun("12:47", trainType: .express),
        ExactRun("12:54", trainType: .limitedExpress),
        ExactRun("12:59", trainType: .express),
        ExactRun("13:09", trainType: .limitedExpress),
        ExactRun("13:12", trainType: .express),
        ExactRun("13:17", trainType: .express),
        ExactRun("13:24", trainType: .limitedExpress),
        ExactRun("13:29", trainType: .express),
        ExactRun("13:39", trainType: .limitedExpress),
        ExactRun("13:42", trainType: .express),
        ExactRun("13:47", trainType: .express),
        ExactRun("13:54", trainType: .limitedExpress),
        ExactRun("13:59", trainType: .express),
        ExactRun("14:09", trainType: .limitedExpress),
        ExactRun("14:12", trainType: .express),
        ExactRun("14:17", trainType: .express),
        ExactRun("14:24", trainType: .limitedExpress),
        ExactRun("14:29", trainType: .express),
        ExactRun("14:39", trainType: .limitedExpress),
        ExactRun("14:42", trainType: .express),
        ExactRun("14:47", trainType: .express),
        ExactRun("14:54", trainType: .limitedExpress),
        ExactRun("14:59", trainType: .express),
        ExactRun("15:09", trainType: .limitedExpress),
        ExactRun("15:12", trainType: .express),
        ExactRun("15:17", trainType: .express),
        ExactRun("15:24", trainType: .limitedExpress),
        ExactRun("15:29", trainType: .express),
        ExactRun("15:39", trainType: .limitedExpress),
        ExactRun("15:42", trainType: .express),
        ExactRun("15:47", trainType: .express),
        ExactRun("15:54", trainType: .limitedExpress),
        ExactRun("15:59", trainType: .express),
        ExactRun("16:09", trainType: .limitedExpress),
        ExactRun("16:12", trainType: .express),
        ExactRun("16:17", trainType: .express),
        ExactRun("16:24", trainType: .limitedExpress),
        ExactRun("16:29", trainType: .express),
        ExactRun("16:39", trainType: .limitedExpress),
        ExactRun("16:44", trainType: .express),
        ExactRun("16:48", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
        ExactRun("16:54", trainType: .limitedExpress),
        ExactRun("16:59", trainType: .express),
        ExactRun("17:02", trainType: .express),
        ExactRun("17:09", trainType: .limitedExpress),
        ExactRun("17:14", trainType: .express),
        ExactRun("17:24", trainType: .limitedExpress),
        ExactRun("17:29", trainType: .express),
        ExactRun("17:32", trainType: .express),
        ExactRun("17:39", trainType: .limitedExpress),
        ExactRun("17:44", trainType: .express),
        ExactRun("17:54", trainType: .limitedExpress),
        ExactRun("17:59", trainType: .express),
        ExactRun("18:02", trainType: .express),
        ExactRun("18:08", trainType: .limitedExpress),
        ExactRun("18:14", trainType: .express),
        ExactRun("18:24", trainType: .limitedExpress),
        ExactRun("18:29", trainType: .express),
        ExactRun("18:33", trainType: .express),
        ExactRun("18:39", trainType: .limitedExpress),
        ExactRun("18:44", trainType: .express),
        ExactRun("18:52", trainType: .limitedExpress),
        ExactRun("18:55", trainType: .express),
        ExactRun("19:02", trainType: .express),
        ExactRun("19:08", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
        ExactRun("19:14", trainType: .express),
        ExactRun("19:18", trainType: .express),
        ExactRun("19:24", trainType: .limitedExpress),
        ExactRun("19:34", trainType: .express),
        ExactRun("19:44", trainType: .express),
        ExactRun("19:48", trainType: .express),
        ExactRun("19:54", trainType: .limitedExpress),
        ExactRun("20:04", trainType: .express),
        ExactRun("20:10", trainType: .express),
        ExactRun("20:15", trainType: .express),
        ExactRun("20:24", trainType: .limitedExpress),
        ExactRun("20:34", trainType: .express),
        ExactRun("20:38", trainType: .express),
        ExactRun("20:44", trainType: .express),
        ExactRun("20:48", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
        ExactRun("20:54", trainType: .limitedExpress),
        ExactRun("21:05", trainType: .express),
        ExactRun("21:14", trainType: .express),
        ExactRun("21:18", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
        ExactRun("21:24", trainType: .limitedExpress),
        ExactRun("21:26", trainType: .express),
        ExactRun("21:35", trainType: .express),
        ExactRun("21:47", trainType: .express),
        ExactRun("21:54", trainType: .limitedExpress),
        ExactRun("22:09", trainType: .express),
        ExactRun("22:24", trainType: .limitedExpress),
        ExactRun("22:28", trainType: .express),
        ExactRun("22:40", trainType: .express),
        ExactRun("22:54", trainType: .limitedExpress),
        ExactRun("22:56", trainType: .express),
        ExactRun("23:01", trainType: .express),
        ExactRun("23:09", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
        ExactRun("23:24", trainType: .limitedExpress),
        ExactRun("23:32", trainType: .express),
        ExactRun("23:56", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
        ExactRun("24:07", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
    ]

    private static let toyokoDescExpressWd: [ExactRun] = [
        ExactRun("06:04", trainType: .express),
        ExactRun("06:14", trainType: .express),
        ExactRun("06:24", trainType: .limitedExpress),
        ExactRun("06:43", trainType: .commuterLimitedExpress),
        ExactRun("06:50", trainType: .express),
        ExactRun("06:56", trainType: .express),
        ExactRun("07:04", trainType: .commuterLimitedExpress),
        ExactRun("07:14", trainType: .express),
        ExactRun("07:19", trainType: .commuterLimitedExpress),
        ExactRun("07:28", trainType: .express),
        ExactRun("07:34", trainType: .commuterLimitedExpress),
        ExactRun("07:43", trainType: .express),
        ExactRun("07:49", trainType: .commuterLimitedExpress),
        ExactRun("07:58", trainType: .express),
        ExactRun("08:04", trainType: .commuterLimitedExpress),
        ExactRun("08:13", trainType: .express),
        ExactRun("08:19", trainType: .commuterLimitedExpress),
        ExactRun("08:28", trainType: .express),
        ExactRun("08:37", trainType: .commuterLimitedExpress),
        ExactRun("08:47", trainType: .express),
        ExactRun("08:54", trainType: .commuterLimitedExpress),
        ExactRun("09:00", trainType: .express),
        ExactRun("09:09", trainType: .commuterLimitedExpress),
        ExactRun("09:15", trainType: .express),
        ExactRun("09:23", trainType: .express),
        ExactRun("09:29", trainType: .limitedExpress),
        ExactRun("09:35", trainType: .express),
        ExactRun("09:42", trainType: .limitedExpress),
        ExactRun("09:48", trainType: .express),
        ExactRun("09:57", trainType: .limitedExpress),
        ExactRun("10:03", trainType: .express),
        ExactRun("10:12", trainType: .limitedExpress),
        ExactRun("10:19", trainType: .express),
        ExactRun("10:27", trainType: .limitedExpress),
        ExactRun("10:34", trainType: .express),
        ExactRun("10:42", trainType: .limitedExpress),
        ExactRun("10:49", trainType: .express),
        ExactRun("10:57", trainType: .limitedExpress),
        ExactRun("11:04", trainType: .express),
        ExactRun("11:12", trainType: .limitedExpress),
        ExactRun("11:19", trainType: .express),
        ExactRun("11:27", trainType: .limitedExpress),
        ExactRun("11:34", trainType: .express),
        ExactRun("11:42", trainType: .limitedExpress),
        ExactRun("11:49", trainType: .express),
        ExactRun("11:57", trainType: .limitedExpress),
        ExactRun("12:04", trainType: .express),
        ExactRun("12:12", trainType: .limitedExpress),
        ExactRun("12:19", trainType: .express),
        ExactRun("12:27", trainType: .limitedExpress),
        ExactRun("12:34", trainType: .express),
        ExactRun("12:42", trainType: .limitedExpress),
        ExactRun("12:49", trainType: .express),
        ExactRun("12:57", trainType: .limitedExpress),
        ExactRun("13:04", trainType: .express),
        ExactRun("13:12", trainType: .limitedExpress),
        ExactRun("13:19", trainType: .express),
        ExactRun("13:27", trainType: .limitedExpress),
        ExactRun("13:34", trainType: .express),
        ExactRun("13:42", trainType: .limitedExpress),
        ExactRun("13:49", trainType: .express),
        ExactRun("13:57", trainType: .limitedExpress),
        ExactRun("14:04", trainType: .express),
        ExactRun("14:12", trainType: .limitedExpress),
        ExactRun("14:19", trainType: .express),
        ExactRun("14:27", trainType: .limitedExpress),
        ExactRun("14:34", trainType: .express),
        ExactRun("14:42", trainType: .limitedExpress),
        ExactRun("14:49", trainType: .express),
        ExactRun("14:57", trainType: .limitedExpress),
        ExactRun("15:04", trainType: .express),
        ExactRun("15:12", trainType: .limitedExpress),
        ExactRun("15:19", trainType: .express),
        ExactRun("15:27", trainType: .limitedExpress),
        ExactRun("15:34", trainType: .express),
        ExactRun("15:42", trainType: .limitedExpress),
        ExactRun("15:49", trainType: .express),
        ExactRun("15:57", trainType: .limitedExpress),
        ExactRun("16:04", trainType: .express),
        ExactRun("16:12", trainType: .limitedExpress),
        ExactRun("16:19", trainType: .express),
        ExactRun("16:27", trainType: .limitedExpress),
        ExactRun("16:33", trainType: .express),
        ExactRun("16:42", trainType: .limitedExpress),
        ExactRun("16:51", trainType: .limitedExpress),
        ExactRun("16:59", trainType: .express),
        ExactRun("17:07", trainType: .commuterLimitedExpress),
        ExactRun("17:15", trainType: .express),
        ExactRun("17:22", trainType: .commuterLimitedExpress),
        ExactRun("17:30", trainType: .express),
        ExactRun("17:37", trainType: .commuterLimitedExpress),
        ExactRun("17:44", trainType: .express),
        ExactRun("17:52", trainType: .commuterLimitedExpress),
        ExactRun("17:59", trainType: .express),
        ExactRun("18:08", trainType: .commuterLimitedExpress),
        ExactRun("18:15", trainType: .express),
        ExactRun("18:22", trainType: .commuterLimitedExpress),
        ExactRun("18:30", trainType: .express),
        ExactRun("18:38", trainType: .commuterLimitedExpress),
        ExactRun("18:45", trainType: .express),
        ExactRun("18:53", trainType: .commuterLimitedExpress),
        ExactRun("19:00", trainType: .express),
        ExactRun("19:08", trainType: .commuterLimitedExpress),
        ExactRun("19:15", trainType: .express),
        ExactRun("19:23", trainType: .commuterLimitedExpress),
        ExactRun("19:30", trainType: .express),
        ExactRun("19:38", trainType: .commuterLimitedExpress),
        ExactRun("19:45", trainType: .express),
        ExactRun("19:53", trainType: .commuterLimitedExpress),
        ExactRun("20:00", trainType: .express),
        ExactRun("20:08", trainType: .commuterLimitedExpress),
        ExactRun("20:15", trainType: .express),
        ExactRun("20:23", trainType: .commuterLimitedExpress),
        ExactRun("20:30", trainType: .express),
        ExactRun("20:38", trainType: .commuterLimitedExpress),
        ExactRun("20:45", trainType: .express),
        ExactRun("20:53", trainType: .commuterLimitedExpress),
        ExactRun("21:00", trainType: .express),
        ExactRun("21:08", trainType: .commuterLimitedExpress),
        ExactRun("21:15", trainType: .express),
        ExactRun("21:23", trainType: .commuterLimitedExpress),
        ExactRun("21:30", trainType: .express),
        ExactRun("21:38", trainType: .commuterLimitedExpress),
        ExactRun("21:45", trainType: .express),
        ExactRun("21:52", trainType: .commuterLimitedExpress),
        ExactRun("22:00", trainType: .express),
        ExactRun("22:08", trainType: .commuterLimitedExpress),
        ExactRun("22:15", trainType: .express),
        ExactRun("22:23", trainType: .commuterLimitedExpress),
        ExactRun("22:31", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
        ExactRun("22:38", trainType: .commuterLimitedExpress),
        ExactRun("22:53", trainType: .commuterLimitedExpress),
        ExactRun("22:59", trainType: .express),
        ExactRun("23:07", trainType: .commuterLimitedExpress),
        ExactRun("23:14", trainType: .express),
        ExactRun("23:23", trainType: .commuterLimitedExpress),
        ExactRun("23:30", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
        ExactRun("23:37", trainType: .commuterLimitedExpress),
        ExactRun("23:52", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .commuterLimitedExpress),
        ExactRun("24:09", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
    ]

    private static let toyokoDescExpressHol: [ExactRun] = [
        ExactRun("06:13", trainType: .limitedExpress),
        ExactRun("06:26", trainType: .limitedExpress),
        ExactRun("06:55", trainType: .limitedExpress),
        ExactRun("07:12", trainType: .limitedExpress),
        ExactRun("07:26", trainType: .limitedExpress),
        ExactRun("07:42", trainType: .limitedExpress),
        ExactRun("07:50", trainType: .express),
        ExactRun("08:01", trainType: .express),
        ExactRun("08:12", trainType: .limitedExpress),
        ExactRun("08:18", trainType: .express),
        ExactRun("08:27", trainType: .limitedExpress),
        ExactRun("08:33", trainType: .express),
        ExactRun("08:42", trainType: .limitedExpress),
        ExactRun("08:48", trainType: .express),
        ExactRun("08:57", trainType: .limitedExpress),
        ExactRun("09:03", trainType: .express),
        ExactRun("09:12", trainType: .limitedExpress),
        ExactRun("09:18", trainType: .express),
        ExactRun("09:27", trainType: .limitedExpress),
        ExactRun("09:34", trainType: .express),
        ExactRun("09:42", trainType: .limitedExpress),
        ExactRun("09:49", trainType: .express),
        ExactRun("09:57", trainType: .limitedExpress),
        ExactRun("10:04", trainType: .express),
        ExactRun("10:12", trainType: .limitedExpress),
        ExactRun("10:19", trainType: .express),
        ExactRun("10:27", trainType: .limitedExpress),
        ExactRun("10:34", trainType: .express),
        ExactRun("10:42", trainType: .limitedExpress),
        ExactRun("10:48", trainType: .express),
        ExactRun("10:57", trainType: .limitedExpress),
        ExactRun("11:04", trainType: .express),
        ExactRun("11:12", trainType: .limitedExpress),
        ExactRun("11:19", trainType: .express),
        ExactRun("11:27", trainType: .limitedExpress),
        ExactRun("11:34", trainType: .express),
        ExactRun("11:42", trainType: .limitedExpress),
        ExactRun("11:49", trainType: .express),
        ExactRun("11:57", trainType: .limitedExpress),
        ExactRun("12:04", trainType: .express),
        ExactRun("12:12", trainType: .limitedExpress),
        ExactRun("12:19", trainType: .express),
        ExactRun("12:27", trainType: .limitedExpress),
        ExactRun("12:34", trainType: .express),
        ExactRun("12:42", trainType: .limitedExpress),
        ExactRun("12:49", trainType: .express),
        ExactRun("12:57", trainType: .limitedExpress),
        ExactRun("13:04", trainType: .express),
        ExactRun("13:12", trainType: .limitedExpress),
        ExactRun("13:19", trainType: .express),
        ExactRun("13:27", trainType: .limitedExpress),
        ExactRun("13:34", trainType: .express),
        ExactRun("13:42", trainType: .limitedExpress),
        ExactRun("13:49", trainType: .express),
        ExactRun("13:57", trainType: .limitedExpress),
        ExactRun("14:04", trainType: .express),
        ExactRun("14:12", trainType: .limitedExpress),
        ExactRun("14:19", trainType: .express),
        ExactRun("14:27", trainType: .limitedExpress),
        ExactRun("14:34", trainType: .express),
        ExactRun("14:42", trainType: .limitedExpress),
        ExactRun("14:49", trainType: .express),
        ExactRun("14:57", trainType: .limitedExpress),
        ExactRun("15:04", trainType: .express),
        ExactRun("15:12", trainType: .limitedExpress),
        ExactRun("15:19", trainType: .express),
        ExactRun("15:27", trainType: .limitedExpress),
        ExactRun("15:33", trainType: .express),
        ExactRun("15:42", trainType: .limitedExpress),
        ExactRun("15:49", trainType: .express),
        ExactRun("15:57", trainType: .limitedExpress),
        ExactRun("16:04", trainType: .express),
        ExactRun("16:12", trainType: .limitedExpress),
        ExactRun("16:19", trainType: .express),
        ExactRun("16:27", trainType: .limitedExpress),
        ExactRun("16:34", trainType: .express),
        ExactRun("16:42", trainType: .limitedExpress),
        ExactRun("16:49", trainType: .express),
        ExactRun("16:56", trainType: .limitedExpress),
        ExactRun("17:05", trainType: .express),
        ExactRun("17:12", trainType: .limitedExpress),
        ExactRun("17:19", trainType: .express),
        ExactRun("17:27", trainType: .limitedExpress),
        ExactRun("17:34", trainType: .express),
        ExactRun("17:42", trainType: .limitedExpress),
        ExactRun("17:49", trainType: .express),
        ExactRun("17:57", trainType: .limitedExpress),
        ExactRun("18:04", trainType: .express),
        ExactRun("18:12", trainType: .limitedExpress),
        ExactRun("18:20", trainType: .express),
        ExactRun("18:27", trainType: .limitedExpress),
        ExactRun("18:35", trainType: .express),
        ExactRun("18:42", trainType: .limitedExpress),
        ExactRun("18:50", trainType: .express),
        ExactRun("18:57", trainType: .limitedExpress),
        ExactRun("19:05", trainType: .express),
        ExactRun("19:12", trainType: .limitedExpress),
        ExactRun("19:20", trainType: .express),
        ExactRun("19:27", trainType: .limitedExpress),
        ExactRun("19:35", trainType: .express),
        ExactRun("19:44", trainType: .limitedExpress),
        ExactRun("19:56", trainType: .express),
        ExactRun("20:05", trainType: .express),
        ExactRun("20:14", trainType: .limitedExpress),
        ExactRun("20:26", trainType: .express),
        ExactRun("20:35", trainType: .express),
        ExactRun("20:43", trainType: .limitedExpress),
        ExactRun("20:56", trainType: .express),
        ExactRun("21:05", trainType: .express),
        ExactRun("21:14", trainType: .limitedExpress),
        ExactRun("21:26", trainType: .express),
        ExactRun("21:35", trainType: .express),
        ExactRun("21:43", trainType: .limitedExpress),
        ExactRun("21:55", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
        ExactRun("22:05", trainType: .express),
        ExactRun("22:14", trainType: .limitedExpress),
        ExactRun("22:24", trainType: .express),
        ExactRun("22:42", trainType: .express),
        ExactRun("23:02", trainType: .limitedExpress),
        ExactRun("23:16", trainType: .express),
        ExactRun("23:37", trainType: .limitedExpress),
        ExactRun("23:45", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
        ExactRun("23:57", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
        ExactRun("24:07", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
    ]

}
