import Foundation

extension KeioLineData {

    // MARK: - Keio Takao Line (KO)

    // Branches off the Keio Line at 北野; most trains through-run to/from
    // 新宿 on the Keio Line. Station numbers verified against keio.co.jp
    // (高尾山口 = KO53); coordinates from ja.wikipedia per-station infoboxes.
    // First/last from ekitan (weekday, July 2026); holiday first/last mirror
    // weekday and are approximate. Base 各駅停車 pattern; 特急/急行/快速 run
    // the same corridor but are approximated by headway bands.
    static let takao = StaticTrainLine(
        id: "Railway:Keio.Takao",
        nameJa: "京王高尾線",
        nameEn: "Keio Takao Line",
        operatorId: "Operator:Keio",
        colorHex: "#DD0077",
        stations: [
            st("Keio.Takao", "Kitano", "北野", "Kitano", "KO33", 35.6567, 139.3567),
            st("Keio.Takao", "KeioKatakura", "京王片倉", "Keio-katakura", "KO48", 35.6444, 139.3373),
            st("Keio.Takao", "Yamada", "山田", "Yamada", "KO49", 35.6444, 139.3213),
            st("Keio.Takao", "Mejirodai", "めじろ台", "Mejirodai", "KO50", 35.6433, 139.3077),
            st("Keio.Takao", "Hazama", "狭間", "Hazama", "KO51", 35.6406, 139.2933),
            st("Keio.Takao", "Takao", "高尾", "Takao", "KO52", 35.6422, 139.2819),
            st("Keio.Takao", "Takaosanguchi", "高尾山口", "Takaosanguchi", "KO53", 35.6322, 139.2699),
        ],
        hopTimesMinutes: [2, 2, 2, 2, 3, 3],
        directions: [
            direction("Keio.Takao", "Takaosanguchi", "高尾山口方面", "For Takaosanguchi",
                      ascending: true,
                      weekday: pattern("05:12", "24:14", [
                          ("05:12", 8), ("06:30", 6), ("09:30", 8), ("16:30", 6), ("20:00", 8), ("22:00", 10),
                      ]),
                      holiday: pattern("05:12", "24:14", [
                          ("05:12", 8), ("07:00", 7), ("10:00", 7), ("20:00", 9),
                      ]),
                      expressWeekday: takaoAscExpressWd,
                      expressHoliday: takaoAscExpressHol),
            direction("Keio.Takao", "Kitano", "北野・新宿方面", "For Kitano & Shinjuku",
                      ascending: false,
                      weekday: pattern("05:07", "24:13", [
                          ("05:07", 8), ("06:30", 5), ("09:30", 7), ("16:30", 6), ("20:00", 8), ("22:00", 10),
                      ]),
                      holiday: pattern("05:07", "24:13", [
                          ("05:07", 8), ("07:00", 7), ("10:00", 7), ("20:00", 9),
                      ]),
                      expressWeekday: takaoDescExpressWd,
                      expressHoliday: takaoDescExpressHol),
        ],
        delayInfo: delayInfo,
        throughServices: [
            through("Keio.Takao.Kitano", .descending,
                    "京王線", "Keio Line",
                    "明大前・新宿方面", "for Meidaimae & Shinjuku",
                    to: "Railway:Keio.Keio"),
        ]
    )

private static let takaoAscExpressHol: [ExactRun] = [
    ExactRun("06:51", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("07:49", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("08:09", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("08:52", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("10:12", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("10:52", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("11:11", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("11:52", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("12:10", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("12:31", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("12:51", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("13:11", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("13:30", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("13:51", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("14:10", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("14:31", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("14:51", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("15:11", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("15:30", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("15:50", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("16:50", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("17:09", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("17:29", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("17:50", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("18:08", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("18:28", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("18:49", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("19:08", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("19:28", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("19:48", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("20:08", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("20:27", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
]

private static let takaoAscExpressWd: [ExactRun] = [
    ExactRun("07:25", startsHere: false, trainType: .rapid, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("07:47", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("08:58", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("09:48", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("10:03", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("10:30", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("10:41", startsHere: false, trainType: .rapid, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("10:52", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("11:10", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("11:30", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("11:50", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("12:10", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("12:30", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("12:50", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("13:10", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("13:30", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("13:50", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("14:10", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("14:30", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("14:50", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("15:10", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("15:30", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("15:50", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
    ExactRun("16:10", startsHere: false, trainType: .limitedExpress, stopIndices: [0, 1, 2, 3, 4, 5, 6]),
]

private static let takaoDescExpressHol: [ExactRun] = [
    ExactRun("05:33", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("06:00", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("06:44", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("07:16", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("07:45", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("08:15", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("08:39", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("09:15", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("10:29", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("10:48", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("11:10", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("11:50", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("12:09", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("12:28", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("12:47", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("13:08", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("13:28", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("13:46", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("14:07", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("14:26", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("14:47", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("15:07", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("15:29", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("15:49", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("16:47", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("17:28", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("17:48", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("18:07", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("18:27", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("18:48", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("19:07", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("19:27", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("19:46", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("20:07", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("20:33", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("20:55", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
]

private static let takaoDescExpressWd: [ExactRun] = [
    ExactRun("05:33", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("05:57", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("06:31", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("06:55", continuesBeyond: true, trainType: .semiExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("07:22", continuesBeyond: true, trainType: .express, stopIndices: [6, 5, 3, 0]),
    ExactRun("07:50", continuesBeyond: true, trainType: .express, stopIndices: [6, 5, 3, 0]),
    ExactRun("08:06", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("09:29", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("09:45", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("10:09", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("10:27", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("10:47", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("11:08", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("11:27", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("11:47", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("12:07", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("12:27", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("12:47", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("13:07", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("13:27", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("13:47", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("14:07", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("14:27", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("14:47", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("15:07", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("15:27", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("15:47", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("16:07", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
    ExactRun("16:27", continuesBeyond: true, trainType: .limitedExpress, stopIndices: [6, 5, 4, 3, 2, 1, 0]),
]

}
