import Foundation

extension KeikyuLineData {

    // MARK: - Keikyu Main Line (KK)

    static let main = StaticTrainLine(
        id: "Railway:Keikyu.Main",
        nameJa: "京急本線",
        nameEn: "Keikyu Main Line",
        operatorId: "Operator:Keikyu",
        colorHex: "#E60012",
        stations: [
            // Sengakuji is Toei-managed (A07); leave the code empty so the
            // line symbol derives from Shinagawa's KK01
            st("Keikyu.Main", "Sengakuji", "泉岳寺", "Sengakuji", "", 35.6385, 139.7401),
            st("Keikyu.Main", "Shinagawa", "品川", "Shinagawa", "KK01", 35.6285, 139.7388),
            st("Keikyu.Main", "Kitashinagawa", "北品川", "Kita-shinagawa", "KK02", 35.6222, 139.7392),
            st("Keikyu.Main", "Shimbamba", "新馬場", "Shimbamba", "KK03", 35.6172, 139.7407),
            st("Keikyu.Main", "AomonoYokocho", "青物横丁", "Aomono-yokocho", "KK04", 35.6093, 139.7428),
            st("Keikyu.Main", "Samezu", "鮫洲", "Samezu", "KK05", 35.6050, 139.7423),
            st("Keikyu.Main", "Tachiaigawa", "立会川", "Tachiaigawa", "KK06", 35.5985, 139.7387),
            st("Keikyu.Main", "OmoriKaigan", "大森海岸", "Omorikaigan", "KK07", 35.5875, 139.7357),
            st("Keikyu.Main", "Heiwajima", "平和島", "Heiwajima", "KK08", 35.5787, 139.7347),
            st("Keikyu.Main", "Omorimachi", "大森町", "Omorimachi", "KK09", 35.5722, 139.7317),
            st("Keikyu.Main", "Umeyashiki", "梅屋敷", "Umeyashiki", "KK10", 35.5665, 139.7287),
            st("Keikyu.Main", "KeikyuKamata", "京急蒲田", "Keikyu Kamata", "KK11", 35.5607, 139.7237),
            st("Keikyu.Main", "Zoshiki", "雑色", "Zoshiki", "KK18", 35.5497, 139.7147),
            st("Keikyu.Main", "Rokugodote", "六郷土手", "Rokugodote", "KK19", 35.5397, 139.7077),
            st("Keikyu.Main", "KeikyuKawasaki", "京急川崎", "Keikyu Kawasaki", "KK20", 35.5327, 139.7007),
            st("Keikyu.Main", "Hatchonawate", "八丁畷", "Hatchonawate", "KK27", 35.5257, 139.6907),
            st("Keikyu.Main", "Tsurumiichiba", "鶴見市場", "Tsurumi-ichiba", "KK28", 35.5197, 139.6837),
            st("Keikyu.Main", "KeikyuTsurumi", "京急鶴見", "Keikyu Tsurumi", "KK29", 35.5077, 139.6787),
            st("Keikyu.Main", "KagetsuSojiji", "花月総持寺", "Kagetsu-sojiji", "KK30", 35.4997, 139.6717),
            st("Keikyu.Main", "Namamugi", "生麦", "Namamugi", "KK31", 35.4917, 139.6647),
            st("Keikyu.Main", "KeikyuShinkoyasu", "京急新子安", "Keikyu Shin-koyasu", "KK32", 35.4847, 139.6577),
            st("Keikyu.Main", "Koyasu", "子安", "Koyasu", "KK33", 35.4807, 139.6507),
            st("Keikyu.Main", "KanagawaShimmachi", "神奈川新町", "Kanagawa-shimmachi", "KK34", 35.4777, 139.6457),
            st("Keikyu.Main", "KeikyuHigashiKanagawa", "京急東神奈川", "Keikyu Higashi-kanagawa", "KK35", 35.4757, 139.6407),
            st("Keikyu.Main", "Kanagawa", "神奈川", "Kanagawa", "KK36", 35.4707, 139.6317),
            st("Keikyu.Main", "Yokohama", "横浜", "Yokohama", "KK37", 35.4657, 139.6224),
            st("Keikyu.Main", "Tobe", "戸部", "Tobe", "KK38", 35.4577, 139.6187),
            st("Keikyu.Main", "Hinodecho", "日ノ出町", "Hinodecho", "KK39", 35.4467, 139.6247),
            st("Keikyu.Main", "Koganecho", "黄金町", "Koganecho", "KK40", 35.4407, 139.6257),
            st("Keikyu.Main", "MinamiOta", "南太田", "Minami-ota", "KK41", 35.4347, 139.6207),
            st("Keikyu.Main", "Idogaya", "井土ヶ谷", "Idogaya", "KK42", 35.4287, 139.6127),
            st("Keikyu.Main", "Gumyoji", "弘明寺", "Gumyoji", "KK43", 35.4197, 139.6047),
            st("Keikyu.Main", "Kamiooka", "上大岡", "Kamiooka", "KK44", 35.4087, 139.5967),
            st("Keikyu.Main", "Byobugaura", "屏風浦", "Byobugaura", "KK45", 35.3947, 139.6027),
            st("Keikyu.Main", "Sugita", "杉田", "Sugita", "KK46", 35.3857, 139.6117),
            st("Keikyu.Main", "KeikyuTomioka", "京急富岡", "Keikyu Tomioka", "KK47", 35.3737, 139.6197),
            st("Keikyu.Main", "Nokendai", "能見台", "Nokendai", "KK48", 35.3657, 139.6237),
            st("Keikyu.Main", "KanazawaBunko", "金沢文庫", "Kanazawa-bunko", "KK49", 35.3527, 139.6217),
            st("Keikyu.Main", "KanazawaHakkei", "金沢八景", "Kanazawa-hakkei", "KK50", 35.3377, 139.6207),
            st("Keikyu.Main", "Oppama", "追浜", "Oppama", "KK54", 35.3197, 139.6247),
            st("Keikyu.Main", "KeikyuTaura", "京急田浦", "Keikyu Taura", "KK55", 35.3077, 139.6337),
            st("Keikyu.Main", "Anjinzuka", "安針塚", "Anjinzuka", "KK56", 35.2937, 139.6467),
            st("Keikyu.Main", "Hemi", "逸見", "Hemi", "KK57", 35.2867, 139.6527),
            st("Keikyu.Main", "Shioiri", "汐入", "Shioiri", "KK58", 35.2827, 139.6607),
            st("Keikyu.Main", "YokosukaChuo", "横須賀中央", "Yokosuka-chuo", "KK59", 35.2787, 139.6707),
            st("Keikyu.Main", "KenritsuDaigaku", "県立大学", "Kenritsudaigaku", "KK60", 35.2697, 139.6787),
            st("Keikyu.Main", "Horinouchi", "堀ノ内", "Horinouchi", "KK61", 35.2597, 139.6867),
            st("Keikyu.Main", "KeikyuOtsu", "京急大津", "Keikyu Otsu", "KK62", 35.2557, 139.6947),
            st("Keikyu.Main", "MaboriKaigan", "馬堀海岸", "Maborikaigan", "KK63", 35.2527, 139.7067),
            st("Keikyu.Main", "Uraga", "浦賀", "Uraga", "KK64", 35.2427, 139.7137),
        ],
        hopTimesMinutes: [
            3, 2, 1, 2, 1, 2, 2, 1, 2, 1, 2, 2, 2, 2,
            2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2,
            2, 2, 1, 1, 2, 2, 2, 3, 2, 2, 2, 2, 3,
            3, 3, 3, 2, 2, 1, 2, 2, 2, 2, 2,
        ],
        directions: [
            // First/last at Sengakuji estimated from verified Shinagawa data
            // (05:02/23:59, ekitan) minus the 2-3 min hop; Sengakuji page 404s.
            direction("Keikyu.Main", "Uraga", "横浜・浦賀方面", "For Yokohama & Uraga",
                      ascending: true,
                      weekday: pattern("05:10", "23:56", [
                          ("05:10", 8), ("06:30", 4), ("09:30", 5), ("16:30", 4), ("20:00", 6), ("22:00", 8),
                      ]),
                      holiday: pattern("05:10", "23:56", [
                          ("05:10", 8), ("07:00", 5), ("10:00", 5), ("20:00", 7),
                      ]),
                      expressWeekday: keikyuMainAscExpressWd,
                      expressHoliday: keikyuMainAscExpressHol),
            // Uraga first/last estimated (ekitan page returned 500). Northbound
            // (品川方面) skip-stop trains overwhelmingly originate off-line
            // (三崎口/久里浜 via 堀ノ内, 逗子 via 金沢八景, 羽田 via 蒲田); they
            // are modeled as a 堀ノ内 express 始発/through origin capturing the
            // 久里浜線直通 corridor (the dominant northbound express flow).
            direction("Keikyu.Main", "Sengakuji", "品川・泉岳寺方面", "For Shinagawa & Sengakuji",
                      ascending: false,
                      weekday: pattern("04:45", "23:35", [
                          ("04:45", 8), ("06:30", 4), ("09:30", 5), ("16:30", 4), ("20:00", 6), ("22:00", 8),
                      ]),
                      holiday: pattern("04:45", "23:35", [
                          ("04:45", 8), ("07:00", 5), ("10:00", 5), ("20:00", 7),
                      ]),
                      origins: [
                          // 久里浜線直通 快特/特急 join the northbound Main here.
                          originRuns("Station:Keikyu.Main.Horinouchi",
                                     keikyuMainDescExpressWd_horinouchi,
                                     keikyuMainDescExpressHol_horinouchi),
                          // 逗子線直通 エアポート急行(急行) join here bound for 羽田
                          // (Express-only, so no overlap with the 堀ノ内 快特/特急).
                          originRuns("Station:Keikyu.Main.KanazawaHakkei",
                                     keikyuMainDescExpressWd_kanazawahakkei,
                                     keikyuMainDescExpressHol_kanazawahakkei)
                      ]),
        ],
        delayInfo: delayInfo,
        throughServices: [
            through("Keikyu.Main.Sengakuji", .descending,
                    "都営浅草線", "Toei Asakusa Line",
                    "押上・成田空港方面", "for Oshiage & Narita Airport",
                    to: "Railway:Toei.Asakusa"),
            through("Keikyu.Main.KeikyuKamata", .ascending,
                    "京急空港線", "Keikyu Airport Line",
                    "羽田空港方面", "for Haneda Airport",
                    to: "Railway:Keikyu.Airport"),
            through("Keikyu.Main.KanazawaHakkei", .ascending,
                    "京急逗子線", "Keikyu Zushi Line",
                    "逗子・葉山方面", "for Zushi-Hayama",
                    to: "Railway:Keikyu.Zushi"),
            through("Keikyu.Main.Horinouchi", .ascending,
                    "京急久里浜線", "Keikyu Kurihama Line",
                    "三崎口方面", "for Misakiguchi",
                    to: "Railway:Keikyu.Kurihama"),
        ],
        // Skip-stop 停車駅 (absolute indices into `stations`), from Keikyu's
        // official 停車駅案内 (rosen-zu.net / jorudan; times & types from ODPT
        // StationTimetable). 快特: 泉岳寺・品川・京急蒲田・京急川崎・横浜・上大岡・
        // 金沢文庫・金沢八景・横須賀中央・堀ノ内. 特急: adds 青物横丁・平和島・
        // 神奈川新町・追浜・汐入・京急大津・馬堀海岸・浦賀 (特急 continues past
        // 堀ノ内 to 浦賀, all-stop on that tail). エアポート急行(急行): 品川方面 stops
        // 青物横丁・立会川・平和島; 横浜方面 stops 京急川崎・京急鶴見・神奈川新町・
        // 京急東神奈川・日ノ出町・井土ヶ谷・弘明寺・杉田・能見台 (union; segments
        // never overlap through 京急蒲田 so per-run clipping is exact).
        stopPatterns: [
            .rapidLimitedExpress: [0, 1, 11, 14, 25, 32, 37, 38, 44, 46],
            .limitedExpress: [0, 1, 4, 8, 11, 14, 22, 25, 32, 37, 38, 39, 43, 44, 46, 47, 48, 49],
            .express: [0, 1, 4, 6, 8, 11, 14, 17, 22, 23, 25, 27, 30, 31, 32, 34, 36, 37, 38],
        ]
    )

private static let keikyuMainAscExpressHol: [ExactRun] = [
    ExactRun("05:25", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("05:38", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("05:50", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("05:58", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("06:08", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("06:20", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("06:27", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("06:37", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("06:47", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("06:54", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("06:59", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("07:11", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("07:19", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("07:29", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("07:34", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("07:39", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("07:49", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("07:54", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("07:59", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("08:10", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("08:14", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("08:20", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("08:30", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("08:35", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("08:41", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("08:45", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("08:51", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("08:55", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("09:01", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("09:06", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("09:11", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("09:15", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("09:21", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("09:25", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("09:31", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("09:36", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("09:42", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("09:46", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("09:51", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("09:56", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("10:01", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("10:06", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("10:12", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("10:17", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("10:22", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("10:26", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("10:32", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("10:37", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("10:42", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("10:46", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("10:52", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("10:57", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("11:02", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("11:07", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("11:12", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("11:17", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("11:22", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("11:27", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("11:32", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("11:37", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("11:42", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("11:47", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("11:52", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("11:57", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("12:02", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("12:07", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("12:12", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("12:17", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("12:22", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("12:27", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("12:32", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("12:37", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("12:42", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("12:47", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("12:52", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("12:57", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("13:02", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("13:07", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("13:12", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("13:17", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("13:22", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("13:27", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("13:32", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("13:37", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("13:42", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("13:47", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("13:52", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("13:57", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("14:02", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("14:07", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("14:12", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("14:17", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("14:22", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("14:27", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("14:32", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("14:37", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("14:42", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("14:47", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("14:52", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("14:57", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("15:02", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("15:07", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("15:12", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("15:17", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("15:22", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("15:27", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("15:32", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("15:37", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("15:42", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("15:47", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("15:52", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("15:57", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("16:02", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("16:07", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("16:12", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("16:17", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("16:22", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("16:27", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("16:32", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("16:37", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("16:42", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("16:47", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("16:52", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("16:57", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("17:02", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("17:07", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("17:12", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("17:17", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("17:22", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("17:27", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("17:32", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("17:37", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("17:42", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("17:47", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("17:52", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("17:57", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("18:02", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("18:07", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("18:12", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("18:17", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("18:22", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("18:27", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("18:32", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("18:37", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("18:42", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("18:47", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("18:52", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("18:57", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("19:01", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("19:06", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("19:11", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("19:16", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("19:21", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("19:26", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("19:31", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("19:37", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("19:41", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("19:46", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("19:51", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("19:56", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("20:01", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("20:06", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("20:11", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("20:16", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("20:21", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("20:26", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("20:31", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("20:36", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("20:41", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("20:46", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("20:51", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("20:56", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("21:01", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("21:06", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("21:11", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("21:16", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("21:21", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("21:31", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("21:40", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("21:51", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("21:56", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("22:07", terminusStationId: "Station:Keikyu.Main.KanazawaHakkei", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("22:11", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("22:18", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("22:27", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("22:33", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("22:40", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("22:46", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("22:55", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("23:02", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("23:11", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("23:20", terminusStationId: "Station:Keikyu.Main.KanazawaHakkei", continuesBeyond: true, trainType: .express),
    ExactRun("23:30", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("23:39", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("23:57", terminusStationId: "Station:Keikyu.Main.KanazawaBunko", trainType: .limitedExpress),
]

private static let keikyuMainAscExpressWd: [ExactRun] = [
    ExactRun("05:25", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("05:38", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("05:49", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("05:58", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("06:07", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("06:16", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("06:26", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("06:34", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("06:45", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("06:47", trainType: .limitedExpress),
    ExactRun("06:52", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("07:05", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("07:11", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("07:17", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("07:26", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("07:36", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("07:38", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("07:42", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("07:49", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("07:53", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("07:59", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("08:04", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("08:09", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("08:14", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("08:20", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("08:24", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("08:30", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("08:34", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("08:39", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("08:45", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("08:49", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("08:55", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("09:00", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("09:05", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("09:10", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("09:15", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("09:22", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("09:26", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("09:31", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("09:38", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("09:41", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("09:47", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("09:52", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("09:59", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("10:03", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("10:11", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("10:14", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("10:19", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("10:24", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("10:27", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("10:33", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("10:35", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("10:42", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("10:47", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("10:50", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("10:57", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("11:02", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("11:07", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("11:12", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("11:17", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("11:22", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("11:27", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("11:32", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("11:37", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("11:42", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("11:47", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("11:52", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("11:57", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("12:02", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("12:07", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("12:12", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("12:17", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("12:22", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("12:27", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("12:32", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("12:37", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("12:42", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("12:47", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("12:52", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("12:57", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("13:02", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("13:07", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("13:12", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("13:17", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("13:22", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("13:27", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("13:32", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("13:37", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("13:42", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("13:47", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("13:52", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("13:57", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("14:02", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("14:07", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("14:12", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("14:17", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("14:22", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("14:27", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("14:32", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("14:37", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("14:42", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("14:47", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("14:52", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("14:57", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("15:02", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("15:07", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("15:12", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("15:17", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("15:22", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("15:27", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("15:32", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("15:37", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("15:42", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("15:46", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("15:51", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("15:56", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("16:01", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("16:06", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("16:12", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("16:20", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("16:25", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("16:35", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("16:41", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("16:46", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("16:55", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("17:00", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("17:05", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("17:11", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("17:16", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("17:21", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("17:26", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("17:31", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("17:36", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("17:40", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("17:46", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("17:50", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("17:56", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("18:00", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("18:06", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("18:10", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("18:16", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("18:20", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("18:26", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("18:30", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("18:36", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("18:40", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("18:46", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("18:51", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("18:56", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("19:00", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("19:06", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("19:12", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("19:16", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("19:21", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("19:26", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("19:32", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("19:41", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("19:45", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("19:52", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("19:59", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("20:06", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("20:13", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("20:19", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("20:24", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("20:31", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("20:37", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("20:45", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("20:51", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("20:59", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("21:05", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("21:11", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("21:20", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("21:26", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("21:31", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("21:40", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("21:46", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("21:53", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("22:01", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("22:06", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("22:12", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("22:20", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("22:28", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("22:34", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("22:42", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("22:47", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("22:59", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("23:05", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", continuesBeyond: true, trainType: .express),
    ExactRun("23:13", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("23:22", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("23:30", terminusStationId: "Station:Keikyu.Main.Horinouchi", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("23:41", terminusStationId: "Station:Keikyu.Main.KanazawaHakkei", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("23:50", terminusStationId: "Station:Keikyu.Main.KanagawaShimmachi", trainType: .limitedExpress),
    ExactRun("23:59", terminusStationId: "Station:Keikyu.Main.KanazawaBunko", trainType: .limitedExpress),
]

private static let keikyuMainDescExpressHol_horinouchi: [ExactRun] = [
    ExactRun("05:05", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("05:12", startsHere: false, trainType: .limitedExpress),
    ExactRun("05:22", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("05:33", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("05:44", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .limitedExpress),
    ExactRun("05:55", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("06:04", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("06:14", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .limitedExpress),
    ExactRun("06:24", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("06:34", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .limitedExpress),
    ExactRun("06:44", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("06:54", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .limitedExpress),
    ExactRun("07:04", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("07:14", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .limitedExpress),
    ExactRun("07:24", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("07:34", startsHere: false, trainType: .limitedExpress),
    ExactRun("07:44", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("07:54", startsHere: false, trainType: .limitedExpress),
    ExactRun("08:04", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("08:14", startsHere: false, trainType: .limitedExpress),
    ExactRun("08:24", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("08:34", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("08:45", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("08:55", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("09:07", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("09:18", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("09:30", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("09:39", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("09:50", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("09:59", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("10:11", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("10:19", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("10:31", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("10:39", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("10:51", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("10:59", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("11:11", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("11:19", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("11:31", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("11:39", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("11:51", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("11:59", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("12:11", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("12:19", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("12:31", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("12:39", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("12:51", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("12:59", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("13:11", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("13:19", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("13:31", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("13:39", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("13:51", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("13:59", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("14:11", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("14:19", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("14:31", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("14:39", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("14:51", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("14:59", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("15:11", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("15:19", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("15:31", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("15:39", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("15:51", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("15:59", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("16:11", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("16:19", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("16:31", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("16:39", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("16:51", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("16:59", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("17:11", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("17:19", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("17:31", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("17:39", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("17:51", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("17:59", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("18:11", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("18:19", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("18:28", startsHere: false, trainType: .limitedExpress),
    ExactRun("18:38", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("18:47", startsHere: false, trainType: .limitedExpress),
    ExactRun("18:58", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("19:07", startsHere: false, trainType: .limitedExpress),
    ExactRun("19:18", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("19:27", startsHere: false, trainType: .limitedExpress),
    ExactRun("19:38", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("19:47", startsHere: false, trainType: .limitedExpress),
    ExactRun("19:58", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("20:07", startsHere: false, trainType: .limitedExpress),
    ExactRun("20:18", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .limitedExpress),
    ExactRun("20:27", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .limitedExpress),
    ExactRun("20:38", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .limitedExpress),
    ExactRun("20:48", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("21:00", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .limitedExpress),
    ExactRun("21:14", startsHere: false, trainType: .limitedExpress),
    ExactRun("21:31", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .limitedExpress),
    ExactRun("21:51", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .limitedExpress),
    ExactRun("22:10", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("22:27", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .limitedExpress),
    ExactRun("22:45", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .limitedExpress),
    ExactRun("23:07", terminusStationId: "Station:Keikyu.Main.KanazawaBunko", startsHere: false, trainType: .limitedExpress),
]

private static let keikyuMainDescExpressWd_horinouchi: [ExactRun] = [
    ExactRun("05:05", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("05:11", startsHere: false, trainType: .limitedExpress),
    ExactRun("05:22", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("05:32", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .limitedExpress),
    ExactRun("05:43", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("05:50", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("05:55", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("06:05", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("06:13", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("06:19", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("06:31", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .limitedExpress),
    ExactRun("06:36", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("06:42", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .limitedExpress),
    ExactRun("06:46", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("06:50", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .limitedExpress),
    ExactRun("06:56", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("07:02", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .limitedExpress),
    ExactRun("07:07", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("07:12", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .limitedExpress),
    ExactRun("07:17", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("07:22", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .limitedExpress),
    ExactRun("07:24", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("07:29", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("07:35", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .limitedExpress),
    ExactRun("07:39", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("07:46", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .limitedExpress),
    ExactRun("07:51", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("07:57", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .limitedExpress),
    ExactRun("08:02", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("08:08", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .limitedExpress),
    ExactRun("08:17", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("08:30", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("08:39", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .limitedExpress),
    ExactRun("08:48", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("09:00", startsHere: false, continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("09:10", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .limitedExpress),
    ExactRun("09:20", startsHere: false, trainType: .limitedExpress),
    ExactRun("09:33", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("09:43", startsHere: false, continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("09:54", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("09:59", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("10:12", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("10:19", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("10:32", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("10:39", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("10:52", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("10:59", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("11:11", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("11:19", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("11:31", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("11:39", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("11:51", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("11:59", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("12:11", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("12:19", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("12:31", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("12:39", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("12:51", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("12:59", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("13:11", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("13:19", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("13:31", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("13:39", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("13:51", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("13:59", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("14:11", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("14:19", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("14:30", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("14:37", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("14:52", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("15:03", startsHere: false, continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("15:12", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("15:23", startsHere: false, continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("15:32", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("15:38", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("15:49", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("15:59", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("16:09", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("16:20", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("16:25", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .limitedExpress),
    ExactRun("16:32", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("16:41", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("16:44", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .limitedExpress),
    ExactRun("16:52", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("17:03", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("17:06", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .limitedExpress),
    ExactRun("17:14", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("17:24", startsHere: false, continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("17:26", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .limitedExpress),
    ExactRun("17:33", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("17:44", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("17:51", startsHere: false, trainType: .limitedExpress),
    ExactRun("18:03", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("18:13", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("18:23", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("18:33", startsHere: false, continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("18:42", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("18:53", startsHere: false, continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("19:03", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("19:12", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("19:22", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("19:32", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("19:42", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("19:53", startsHere: false, trainType: .limitedExpress),
    ExactRun("20:03", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("20:13", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("20:23", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("20:33", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("20:43", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .rapidLimitedExpress),
    ExactRun("20:54", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("21:04", startsHere: false, trainType: .limitedExpress),
    ExactRun("21:14", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .limitedExpress),
    ExactRun("21:24", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .limitedExpress),
    ExactRun("21:36", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("21:50", startsHere: false, trainType: .limitedExpress),
    ExactRun("21:59", terminusStationId: "Station:Keikyu.Main.Shinagawa", startsHere: false, trainType: .limitedExpress),
    ExactRun("22:12", startsHere: false, trainType: .limitedExpress),
    ExactRun("22:26", startsHere: false, trainType: .limitedExpress),
    ExactRun("22:47", startsHere: false, trainType: .limitedExpress),
    ExactRun("23:06", startsHere: false, continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("23:28", terminusStationId: "Station:Keikyu.Main.KanagawaShimmachi", startsHere: false, trainType: .limitedExpress),
]

private static let keikyuMainDescExpressWd_kanazawahakkei: [ExactRun] = [
    ExactRun("06:11", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("09:06", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("09:17", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("09:28", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("09:40", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("09:51", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("10:01", terminusStationId: "Station:Keikyu.Main.KanagawaShimmachi", startsHere: false, trainType: .express),
    ExactRun("10:13", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("10:34", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("10:54", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("11:14", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("11:34", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("11:54", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("12:14", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("12:34", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("12:54", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("13:14", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("13:34", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("13:54", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("14:14", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("14:34", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("14:52", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("15:08", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("15:18", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("15:28", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("15:38", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("15:58", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("16:08", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("16:17", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("16:28", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("16:40", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("16:49", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("16:59", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("17:09", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("17:21", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("17:31", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("17:41", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("17:50", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("18:01", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("18:09", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("18:18", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("18:28", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("18:39", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("18:48", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("18:58", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("19:08", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("19:27", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("19:37", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("19:47", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("19:58", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("20:07", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("20:18", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("20:28", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("20:37", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("20:48", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("20:58", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
]

private static let keikyuMainDescExpressHol_kanazawahakkei: [ExactRun] = [
    ExactRun("06:39", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("06:49", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("06:59", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("07:09", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("07:19", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("07:29", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("07:39", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("07:49", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("07:59", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("08:09", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("08:19", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("08:29", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("08:39", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("08:49", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("09:00", terminusStationId: "Station:Keikyu.Main.KanagawaShimmachi", startsHere: false, trainType: .express),
    ExactRun("09:11", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("09:33", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("09:54", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("10:14", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("10:34", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("10:54", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("11:14", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("11:34", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("11:54", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("12:14", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("12:34", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("12:54", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("13:14", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("13:34", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("13:54", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("14:14", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("14:34", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("14:54", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("15:14", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("15:34", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("15:54", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("16:14", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("16:34", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("16:54", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("17:14", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("17:34", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("17:54", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("18:14", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("18:36", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("18:55", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("19:15", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("19:35", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("19:55", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("20:15", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("20:35", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
    ExactRun("21:15", terminusStationId: "Station:Keikyu.Main.KeikyuKamata", startsHere: false, continuesBeyond: true, trainType: .express),
]

}
