import Foundation

extension KeikyuLineData {

    // MARK: - Keikyu Zushi Line (KK)

    // All express types stop at every Zushi Line station (逗子線内は各駅停車 —
    // source: ja.wikipedia 京急逗子線). Coordinates & codes from ODPT odpt:Station.
    static let zushi = StaticTrainLine(
        id: "Railway:Keikyu.Zushi",
        nameJa: "京急逗子線",
        nameEn: "Keikyu Zushi Line",
        operatorId: "Operator:Keikyu",
        colorHex: "#E60012",
        stations: [
            st("Keikyu.Zushi", "KanazawaHakkei", "金沢八景", "Kanazawa-hakkei", "KK50", 35.331210, 139.620358),
            st("Keikyu.Zushi", "Mutsuura", "六浦", "Mutsuura", "KK51", 35.322725, 139.611490),
            st("Keikyu.Zushi", "Jimmuji", "神武寺", "Jimmuji", "KK52", 35.306399, 139.593277),
            st("Keikyu.Zushi", "ZushiHayama", "逗子・葉山", "Zushi-Hayama", "KK53", 35.295851, 139.581192),
        ],
        hopTimesMinutes: [2, 3, 2],
        directions: [
            direction("Keikyu.Zushi", "ZushiHayama", "逗子・葉山方面", "For Zushi-Hayama",
                      ascending: true,
                      weekday: pattern("05:02", "24:12", [
                          ("05:02", 15), ("07:00", 10), ("09:00", 12), ("17:00", 10), ("20:00", 15),
                      ]),
                      holiday: pattern("05:02", "23:56", [
                          ("05:02", 15), ("07:00", 10), ("10:00", 12), ("20:00", 15),
                      ]),
                      expressWeekday: keikyuZushiAscExpressWd,
                      expressHoliday: keikyuZushiAscExpressHol),
            direction("Keikyu.Zushi", "KanazawaHakkei", "金沢八景・横浜・品川方面", "For Kanazawa-hakkei & Shinagawa",
                      ascending: false,
                      weekday: pattern("05:05", "24:06", [
                          ("05:05", 15), ("07:00", 10), ("09:00", 12), ("17:00", 10), ("20:00", 15),
                      ]),
                      holiday: pattern("05:05", "24:07", [
                          ("05:05", 15), ("07:00", 10), ("10:00", 12), ("20:00", 15),
                      ]),
                      expressWeekday: keikyuZushiDescExpressWd,
                      expressHoliday: keikyuZushiDescExpressHol),
        ],
        delayInfo: delayInfo,
        throughServices: [
            through("Keikyu.Zushi.KanazawaHakkei", .descending,
                    "京急本線", "Keikyu Main Line",
                    "横浜・品川・泉岳寺方面", "for Yokohama, Shinagawa & Sengakuji",
                    to: "Railway:Keikyu.Main"),
        ]
    )

private static let keikyuZushiAscExpressHol: [ExactRun] = [
    ExactRun("07:40", trainType: .express),
    ExactRun("08:10", trainType: .express),
    ExactRun("08:20", trainType: .express),
    ExactRun("08:30", trainType: .express),
    ExactRun("08:40", trainType: .express),
    ExactRun("08:50", trainType: .express),
    ExactRun("09:00", trainType: .express),
    ExactRun("09:10", trainType: .express),
    ExactRun("09:22", trainType: .express),
    ExactRun("09:32", trainType: .express),
    ExactRun("09:42", trainType: .express),
    ExactRun("09:53", trainType: .express),
    ExactRun("10:03", trainType: .express),
    ExactRun("10:13", trainType: .express),
    ExactRun("10:23", trainType: .express),
    ExactRun("10:53", trainType: .express),
    ExactRun("11:13", trainType: .express),
    ExactRun("11:33", trainType: .express),
    ExactRun("11:53", trainType: .express),
    ExactRun("12:13", trainType: .express),
    ExactRun("12:33", trainType: .express),
    ExactRun("12:53", trainType: .express),
    ExactRun("13:13", trainType: .express),
    ExactRun("13:33", trainType: .express),
    ExactRun("13:53", trainType: .express),
    ExactRun("14:13", trainType: .express),
    ExactRun("14:33", trainType: .express),
    ExactRun("14:53", trainType: .express),
    ExactRun("15:13", trainType: .express),
    ExactRun("15:33", trainType: .express),
    ExactRun("15:53", trainType: .express),
    ExactRun("16:13", trainType: .express),
    ExactRun("16:33", trainType: .express),
    ExactRun("16:53", trainType: .express),
    ExactRun("17:13", trainType: .express),
    ExactRun("17:33", trainType: .express),
    ExactRun("17:53", trainType: .express),
    ExactRun("18:13", trainType: .express),
    ExactRun("18:33", trainType: .express),
    ExactRun("18:53", trainType: .express),
    ExactRun("19:13", trainType: .express),
    ExactRun("19:33", trainType: .express),
    ExactRun("19:53", trainType: .express),
    ExactRun("20:15", trainType: .express),
    ExactRun("20:35", trainType: .express),
    ExactRun("20:55", trainType: .express),
    ExactRun("21:15", trainType: .express),
    ExactRun("21:35", trainType: .express),
    ExactRun("21:55", trainType: .express),
    ExactRun("22:15", trainType: .express),
    ExactRun("22:45", trainType: .express),
    ExactRun("22:55", trainType: .limitedExpress),
    ExactRun("24:16", trainType: .express),
]

private static let keikyuZushiAscExpressWd: [ExactRun] = [
    ExactRun("06:56", trainType: .express),
    ExactRun("07:50", trainType: .express),
    ExactRun("08:19", trainType: .express),
    ExactRun("08:55", trainType: .express),
    ExactRun("09:42", trainType: .express),
    ExactRun("09:52", trainType: .express),
    ExactRun("10:01", trainType: .express),
    ExactRun("10:12", trainType: .express),
    ExactRun("10:21", trainType: .express),
    ExactRun("10:32", trainType: .express),
    ExactRun("10:40", trainType: .express),
    ExactRun("10:50", trainType: .express),
    ExactRun("11:12", trainType: .express),
    ExactRun("11:23", trainType: .express),
    ExactRun("11:33", trainType: .express),
    ExactRun("11:54", trainType: .express),
    ExactRun("12:13", trainType: .express),
    ExactRun("12:33", trainType: .express),
    ExactRun("12:53", trainType: .express),
    ExactRun("13:33", trainType: .express),
    ExactRun("13:53", trainType: .express),
    ExactRun("14:13", trainType: .express),
    ExactRun("14:33", trainType: .express),
    ExactRun("14:53", trainType: .express),
    ExactRun("15:14", trainType: .express),
    ExactRun("15:34", trainType: .express),
    ExactRun("15:54", trainType: .express),
    ExactRun("16:15", trainType: .express),
    ExactRun("16:26", trainType: .express),
    ExactRun("16:35", trainType: .express),
    ExactRun("16:46", trainType: .express),
    ExactRun("16:58", trainType: .express),
    ExactRun("17:09", trainType: .express),
    ExactRun("17:22", trainType: .express),
    ExactRun("17:40", trainType: .express),
    ExactRun("17:49", trainType: .express),
    ExactRun("17:57", trainType: .express),
    ExactRun("18:16", trainType: .express),
    ExactRun("18:27", trainType: .express),
    ExactRun("18:37", trainType: .express),
    ExactRun("18:47", trainType: .express),
    ExactRun("18:57", trainType: .express),
    ExactRun("19:07", trainType: .express),
    ExactRun("19:16", trainType: .express),
    ExactRun("19:26", trainType: .express),
    ExactRun("19:37", trainType: .express),
    ExactRun("19:46", trainType: .express),
    ExactRun("19:57", trainType: .express),
    ExactRun("20:07", trainType: .express),
    ExactRun("20:16", trainType: .express),
    ExactRun("20:26", trainType: .express),
    ExactRun("20:36", trainType: .express),
    ExactRun("21:04", trainType: .express),
    ExactRun("21:14", trainType: .express),
    ExactRun("21:22", trainType: .express),
    ExactRun("21:32", trainType: .express),
    ExactRun("21:41", trainType: .express),
    ExactRun("21:52", trainType: .express),
    ExactRun("22:04", trainType: .express),
    ExactRun("22:12", trainType: .express),
    ExactRun("22:21", trainType: .express),
    ExactRun("22:34", trainType: .express),
    ExactRun("22:53", trainType: .express),
    ExactRun("23:00", trainType: .limitedExpress),
    ExactRun("23:53", trainType: .express),
    ExactRun("24:29", trainType: .limitedExpress),
]

private static let keikyuZushiDescExpressHol: [ExactRun] = [
    ExactRun("06:30", continuesBeyond: true, trainType: .express),
    ExactRun("06:42", continuesBeyond: true, trainType: .express),
    ExactRun("06:52", continuesBeyond: true, trainType: .express),
    ExactRun("07:02", continuesBeyond: true, trainType: .express),
    ExactRun("07:12", continuesBeyond: true, trainType: .express),
    ExactRun("07:22", continuesBeyond: true, trainType: .express),
    ExactRun("07:32", continuesBeyond: true, trainType: .express),
    ExactRun("07:42", continuesBeyond: true, trainType: .express),
    ExactRun("07:52", continuesBeyond: true, trainType: .express),
    ExactRun("08:02", continuesBeyond: true, trainType: .express),
    ExactRun("08:12", continuesBeyond: true, trainType: .express),
    ExactRun("08:22", continuesBeyond: true, trainType: .express),
    ExactRun("08:32", continuesBeyond: true, trainType: .express),
    ExactRun("08:42", continuesBeyond: true, trainType: .express),
    ExactRun("08:52", continuesBeyond: true, trainType: .express),
    ExactRun("09:03", continuesBeyond: true, trainType: .express),
    ExactRun("09:23", continuesBeyond: true, trainType: .express),
    ExactRun("09:45", continuesBeyond: true, trainType: .express),
    ExactRun("10:05", continuesBeyond: true, trainType: .express),
    ExactRun("10:25", continuesBeyond: true, trainType: .express),
    ExactRun("10:45", continuesBeyond: true, trainType: .express),
    ExactRun("11:05", continuesBeyond: true, trainType: .express),
    ExactRun("11:25", continuesBeyond: true, trainType: .express),
    ExactRun("11:45", continuesBeyond: true, trainType: .express),
    ExactRun("12:05", continuesBeyond: true, trainType: .express),
    ExactRun("12:25", continuesBeyond: true, trainType: .express),
    ExactRun("12:45", continuesBeyond: true, trainType: .express),
    ExactRun("13:05", continuesBeyond: true, trainType: .express),
    ExactRun("13:25", continuesBeyond: true, trainType: .express),
    ExactRun("13:45", continuesBeyond: true, trainType: .express),
    ExactRun("14:05", continuesBeyond: true, trainType: .express),
    ExactRun("14:25", continuesBeyond: true, trainType: .express),
    ExactRun("14:45", continuesBeyond: true, trainType: .express),
    ExactRun("15:05", continuesBeyond: true, trainType: .express),
    ExactRun("15:25", continuesBeyond: true, trainType: .express),
    ExactRun("15:45", continuesBeyond: true, trainType: .express),
    ExactRun("16:05", continuesBeyond: true, trainType: .express),
    ExactRun("16:25", continuesBeyond: true, trainType: .express),
    ExactRun("16:45", continuesBeyond: true, trainType: .express),
    ExactRun("17:05", continuesBeyond: true, trainType: .express),
    ExactRun("17:25", continuesBeyond: true, trainType: .express),
    ExactRun("17:45", continuesBeyond: true, trainType: .express),
    ExactRun("18:05", continuesBeyond: true, trainType: .express),
    ExactRun("18:26", continuesBeyond: true, trainType: .express),
    ExactRun("18:46", continuesBeyond: true, trainType: .express),
    ExactRun("19:06", continuesBeyond: true, trainType: .express),
    ExactRun("19:26", continuesBeyond: true, trainType: .express),
    ExactRun("19:46", continuesBeyond: true, trainType: .express),
    ExactRun("20:06", continuesBeyond: true, trainType: .express),
    ExactRun("20:26", continuesBeyond: true, trainType: .express),
    ExactRun("21:07", continuesBeyond: true, trainType: .express),
    ExactRun("23:10", continuesBeyond: true, trainType: .limitedExpress),
]

private static let keikyuZushiDescExpressWd: [ExactRun] = [
    ExactRun("06:04", continuesBeyond: true, trainType: .express),
    ExactRun("06:32", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("07:09", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("07:20", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("08:02", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("08:31", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("08:58", continuesBeyond: true, trainType: .express),
    ExactRun("09:09", continuesBeyond: true, trainType: .express),
    ExactRun("09:21", continuesBeyond: true, trainType: .express),
    ExactRun("09:32", continuesBeyond: true, trainType: .express),
    ExactRun("09:43", continuesBeyond: true, trainType: .express),
    ExactRun("09:54", continuesBeyond: true, trainType: .express),
    ExactRun("10:04", continuesBeyond: true, trainType: .express),
    ExactRun("10:25", continuesBeyond: true, trainType: .express),
    ExactRun("10:45", continuesBeyond: true, trainType: .express),
    ExactRun("11:05", continuesBeyond: true, trainType: .express),
    ExactRun("11:25", continuesBeyond: true, trainType: .express),
    ExactRun("11:45", continuesBeyond: true, trainType: .express),
    ExactRun("12:05", continuesBeyond: true, trainType: .express),
    ExactRun("12:25", continuesBeyond: true, trainType: .express),
    ExactRun("12:45", continuesBeyond: true, trainType: .express),
    ExactRun("13:05", continuesBeyond: true, trainType: .express),
    ExactRun("13:25", continuesBeyond: true, trainType: .express),
    ExactRun("13:45", continuesBeyond: true, trainType: .express),
    ExactRun("14:05", continuesBeyond: true, trainType: .express),
    ExactRun("14:25", continuesBeyond: true, trainType: .express),
    ExactRun("14:45", continuesBeyond: true, trainType: .express),
    ExactRun("14:56", continuesBeyond: true, trainType: .express),
    ExactRun("15:06", continuesBeyond: true, trainType: .express),
    ExactRun("15:16", continuesBeyond: true, trainType: .express),
    ExactRun("15:26", continuesBeyond: true, trainType: .express),
    ExactRun("15:46", continuesBeyond: true, trainType: .express),
    ExactRun("15:55", continuesBeyond: true, trainType: .express),
    ExactRun("16:07", continuesBeyond: true, trainType: .express),
    ExactRun("16:18", continuesBeyond: true, trainType: .express),
    ExactRun("16:28", continuesBeyond: true, trainType: .express),
    ExactRun("16:38", continuesBeyond: true, trainType: .express),
    ExactRun("16:49", continuesBeyond: true, trainType: .express),
    ExactRun("16:58", continuesBeyond: true, trainType: .express),
    ExactRun("17:11", continuesBeyond: true, trainType: .express),
    ExactRun("17:23", continuesBeyond: true, trainType: .express),
    ExactRun("17:34", continuesBeyond: true, trainType: .express),
    ExactRun("17:42", continuesBeyond: true, trainType: .express),
    ExactRun("17:52", continuesBeyond: true, trainType: .express),
    ExactRun("18:02", continuesBeyond: true, trainType: .express),
    ExactRun("18:09", continuesBeyond: true, trainType: .express),
    ExactRun("18:18", continuesBeyond: true, trainType: .express),
    ExactRun("18:30", continuesBeyond: true, trainType: .express),
    ExactRun("18:40", continuesBeyond: true, trainType: .express),
    ExactRun("18:50", continuesBeyond: true, trainType: .express),
    ExactRun("19:00", continuesBeyond: true, trainType: .express),
    ExactRun("19:19", continuesBeyond: true, trainType: .express),
    ExactRun("19:29", continuesBeyond: true, trainType: .express),
    ExactRun("19:39", continuesBeyond: true, trainType: .express),
    ExactRun("19:50", continuesBeyond: true, trainType: .express),
    ExactRun("20:00", continuesBeyond: true, trainType: .express),
    ExactRun("20:10", continuesBeyond: true, trainType: .express),
    ExactRun("20:20", continuesBeyond: true, trainType: .express),
    ExactRun("20:30", continuesBeyond: true, trainType: .express),
    ExactRun("20:41", continuesBeyond: true, trainType: .express),
    ExactRun("20:49", continuesBeyond: true, trainType: .express),
]

}
