import Foundation

extension KeikyuLineData {

    // MARK: - Keikyu Kurihama Line (KK)

    // Coordinates & codes from ODPT odpt:Station. Local band is estimated; the
    // frequent service is the 快特/特急 (all-stop within the Kurihama Line),
    // modeled as ODPT-exact express runs layered on top. All express types stop
    // at every station here (久里浜線内は各駅停車 — source: ja.wikipedia 京急久里浜線).
    static let kurihama = StaticTrainLine(
        id: "Railway:Keikyu.Kurihama",
        nameJa: "京急久里浜線",
        nameEn: "Keikyu Kurihama Line",
        operatorId: "Operator:Keikyu",
        colorHex: "#E60012",
        stations: [
            st("Keikyu.Kurihama", "Horinouchi", "堀ノ内", "Horinouchi", "KK61", 35.263653, 139.686663),
            st("Keikyu.Kurihama", "ShinOtsu", "新大津", "Shin-otsu", "KK65", 35.256904, 139.690102),
            st("Keikyu.Kurihama", "KitaKurihama", "北久里浜", "Kita-kurihama", "KK66", 35.250646, 139.686574),
            st("Keikyu.Kurihama", "KeikyuKurihama", "京急久里浜", "Keikyu Kurihama", "KK67", 35.230929, 139.702370),
            st("Keikyu.Kurihama", "YrpNobi", "YRP野比", "YRP Nobi", "KK68", 35.212021, 139.685078),
            st("Keikyu.Kurihama", "KeikyuNagasawa", "京急長沢", "Keikyu Nagasawa", "KK69", 35.205719, 139.674331),
            st("Keikyu.Kurihama", "Tsukuihama", "津久井浜", "Tsukuihama", "KK70", 35.198708, 139.665787),
            st("Keikyu.Kurihama", "MiuraKaigan", "三浦海岸", "Miura-kaigan", "KK71", 35.186584, 139.653619),
            st("Keikyu.Kurihama", "Misakiguchi", "三崎口", "Misakiguchi", "KK72", 35.177435, 139.633482),
        ],
        hopTimesMinutes: [2, 2, 2, 3, 2, 2, 2, 3],
        directions: [
            direction("Keikyu.Kurihama", "Misakiguchi", "三崎口方面", "For Misakiguchi",
                      ascending: true,
                      weekday: pattern("05:10", "24:00", [
                          ("05:10", 20), ("07:00", 12), ("09:30", 15), ("17:00", 12), ("20:00", 15), ("22:00", 20),
                      ]),
                      holiday: pattern("05:10", "24:00", [
                          ("05:10", 20), ("08:00", 15), ("10:00", 15), ("20:00", 20),
                      ]),
                      expressWeekday: keikyuKurihamaAscExpressWd,
                      expressHoliday: keikyuKurihamaAscExpressHol),
            direction("Keikyu.Kurihama", "Horinouchi", "堀ノ内・横浜・品川方面", "For Horinouchi & Shinagawa",
                      ascending: false,
                      weekday: pattern("04:50", "23:40", [
                          ("04:50", 20), ("06:30", 12), ("09:30", 15), ("17:00", 12), ("20:00", 15), ("22:00", 20),
                      ]),
                      holiday: pattern("04:50", "23:40", [
                          ("04:50", 20), ("08:00", 15), ("10:00", 15), ("20:00", 20),
                      ]),
                      expressWeekday: keikyuKurihamaDescExpressWd,
                      expressHoliday: keikyuKurihamaDescExpressHol),
        ],
        delayInfo: delayInfo,
        throughServices: [
            through("Keikyu.Kurihama.Horinouchi", .descending,
                    "京急本線", "Keikyu Main Line",
                    "横浜・品川・泉岳寺方面", "for Yokohama, Shinagawa & Sengakuji",
                    to: "Railway:Keikyu.Main"),
        ]
    )

private static let keikyuKurihamaAscExpressHol: [ExactRun] = [
    ExactRun("05:18", trainType: .limitedExpress),
    ExactRun("05:40", trainType: .limitedExpress),
    ExactRun("05:59", trainType: .limitedExpress),
    ExactRun("06:13", trainType: .limitedExpress),
    ExactRun("06:38", trainType: .limitedExpress),
    ExactRun("06:54", trainType: .limitedExpress),
    ExactRun("07:06", trainType: .limitedExpress),
    ExactRun("07:17", trainType: .limitedExpress),
    ExactRun("07:33", trainType: .limitedExpress),
    ExactRun("07:45", trainType: .limitedExpress),
    ExactRun("07:50", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("08:04", trainType: .limitedExpress),
    ExactRun("08:19", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("08:30", trainType: .limitedExpress),
    ExactRun("08:40", trainType: .limitedExpress),
    ExactRun("08:50", trainType: .limitedExpress),
    ExactRun("09:00", trainType: .limitedExpress),
    ExactRun("09:10", trainType: .limitedExpress),
    ExactRun("09:20", trainType: .limitedExpress),
    ExactRun("09:32", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("09:39", trainType: .rapidLimitedExpress),
    ExactRun("09:51", trainType: .limitedExpress),
    ExactRun("10:00", trainType: .rapidLimitedExpress),
    ExactRun("10:11", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("10:20", trainType: .rapidLimitedExpress),
    ExactRun("10:32", trainType: .limitedExpress),
    ExactRun("10:43", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("10:51", trainType: .rapidLimitedExpress),
    ExactRun("11:05", trainType: .limitedExpress),
    ExactRun("11:12", trainType: .rapidLimitedExpress),
    ExactRun("11:25", trainType: .limitedExpress),
    ExactRun("11:32", trainType: .rapidLimitedExpress),
    ExactRun("11:45", trainType: .limitedExpress),
    ExactRun("11:52", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("12:03", trainType: .limitedExpress),
    ExactRun("12:11", trainType: .rapidLimitedExpress),
    ExactRun("12:23", trainType: .limitedExpress),
    ExactRun("12:31", trainType: .rapidLimitedExpress),
    ExactRun("12:43", trainType: .limitedExpress),
    ExactRun("12:51", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("13:03", trainType: .limitedExpress),
    ExactRun("13:11", trainType: .rapidLimitedExpress),
    ExactRun("13:23", trainType: .limitedExpress),
    ExactRun("13:31", trainType: .rapidLimitedExpress),
    ExactRun("13:43", trainType: .limitedExpress),
    ExactRun("13:51", trainType: .rapidLimitedExpress),
    ExactRun("14:03", trainType: .limitedExpress),
    ExactRun("14:11", trainType: .rapidLimitedExpress),
    ExactRun("14:23", trainType: .limitedExpress),
    ExactRun("14:31", trainType: .rapidLimitedExpress),
    ExactRun("14:43", trainType: .limitedExpress),
    ExactRun("14:51", trainType: .rapidLimitedExpress),
    ExactRun("15:03", trainType: .limitedExpress),
    ExactRun("15:11", trainType: .rapidLimitedExpress),
    ExactRun("15:23", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("15:31", trainType: .rapidLimitedExpress),
    ExactRun("15:43", trainType: .limitedExpress),
    ExactRun("15:51", trainType: .rapidLimitedExpress),
    ExactRun("16:03", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("16:11", trainType: .rapidLimitedExpress),
    ExactRun("16:23", trainType: .limitedExpress),
    ExactRun("16:31", trainType: .rapidLimitedExpress),
    ExactRun("16:43", trainType: .limitedExpress),
    ExactRun("16:51", trainType: .rapidLimitedExpress),
    ExactRun("17:03", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("17:11", trainType: .rapidLimitedExpress),
    ExactRun("17:23", trainType: .limitedExpress),
    ExactRun("17:31", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("17:43", trainType: .limitedExpress),
    ExactRun("17:51", trainType: .rapidLimitedExpress),
    ExactRun("18:03", trainType: .limitedExpress),
    ExactRun("18:11", trainType: .rapidLimitedExpress),
    ExactRun("18:23", trainType: .limitedExpress),
    ExactRun("18:31", trainType: .rapidLimitedExpress),
    ExactRun("18:43", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("18:51", trainType: .rapidLimitedExpress),
    ExactRun("19:03", trainType: .limitedExpress),
    ExactRun("19:11", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("19:23", trainType: .limitedExpress),
    ExactRun("19:31", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("19:43", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("19:51", trainType: .rapidLimitedExpress),
    ExactRun("20:03", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("20:13", trainType: .limitedExpress),
    ExactRun("20:23", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("20:33", trainType: .limitedExpress),
    ExactRun("20:43", trainType: .limitedExpress),
    ExactRun("20:53", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("21:03", trainType: .limitedExpress),
    ExactRun("21:13", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("21:23", trainType: .limitedExpress),
    ExactRun("21:33", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("21:43", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("21:53", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("22:03", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("22:13", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("22:23", trainType: .limitedExpress),
    ExactRun("22:33", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("22:41", trainType: .limitedExpress),
    ExactRun("22:51", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("23:00", trainType: .limitedExpress),
    ExactRun("23:14", terminusStationId: "Station:Keikyu.Kurihama.MiuraKaigan", trainType: .limitedExpress),
    ExactRun("23:27", trainType: .limitedExpress),
    ExactRun("23:41", trainType: .limitedExpress),
    ExactRun("23:58", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("24:09", terminusStationId: "Station:Keikyu.Kurihama.MiuraKaigan", trainType: .limitedExpress),
    ExactRun("24:26", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
]

private static let keikyuKurihamaAscExpressWd: [ExactRun] = [
    ExactRun("05:16", trainType: .limitedExpress),
    ExactRun("05:35", trainType: .limitedExpress),
    ExactRun("06:12", trainType: .limitedExpress),
    ExactRun("06:38", trainType: .limitedExpress),
    ExactRun("06:54", trainType: .limitedExpress),
    ExactRun("07:06", trainType: .limitedExpress),
    ExactRun("07:13", trainType: .limitedExpress),
    ExactRun("07:31", trainType: .limitedExpress),
    ExactRun("07:40", trainType: .limitedExpress),
    ExactRun("08:00", trainType: .limitedExpress),
    ExactRun("08:15", trainType: .limitedExpress),
    ExactRun("08:23", trainType: .limitedExpress),
    ExactRun("08:33", trainType: .limitedExpress),
    ExactRun("08:43", trainType: .limitedExpress),
    ExactRun("08:55", trainType: .limitedExpress),
    ExactRun("09:04", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("09:11", trainType: .limitedExpress),
    ExactRun("09:13", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("09:22", trainType: .limitedExpress),
    ExactRun("09:29", trainType: .limitedExpress),
    ExactRun("09:33", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("09:43", trainType: .limitedExpress),
    ExactRun("09:51", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("09:59", trainType: .limitedExpress),
    ExactRun("10:10", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("10:20", trainType: .limitedExpress),
    ExactRun("10:30", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("10:38", trainType: .limitedExpress),
    ExactRun("10:48", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("10:58", trainType: .limitedExpress),
    ExactRun("11:07", trainType: .rapidLimitedExpress),
    ExactRun("11:19", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("11:28", trainType: .limitedExpress),
    ExactRun("11:31", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("11:44", trainType: .limitedExpress),
    ExactRun("11:51", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("12:04", trainType: .limitedExpress),
    ExactRun("12:11", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("12:23", trainType: .limitedExpress),
    ExactRun("12:31", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("12:43", trainType: .limitedExpress),
    ExactRun("12:51", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("13:03", trainType: .limitedExpress),
    ExactRun("13:11", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("13:23", trainType: .limitedExpress),
    ExactRun("13:31", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("13:43", trainType: .limitedExpress),
    ExactRun("13:51", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("14:03", trainType: .limitedExpress),
    ExactRun("14:11", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("14:23", trainType: .limitedExpress),
    ExactRun("14:31", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("14:43", trainType: .limitedExpress),
    ExactRun("14:51", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("15:03", trainType: .limitedExpress),
    ExactRun("15:11", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("15:23", trainType: .limitedExpress),
    ExactRun("15:31", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("15:43", trainType: .limitedExpress),
    ExactRun("15:51", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("16:03", trainType: .limitedExpress),
    ExactRun("16:11", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("16:23", trainType: .limitedExpress),
    ExactRun("16:31", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("16:43", trainType: .limitedExpress),
    ExactRun("16:51", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("17:03", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("17:12", trainType: .rapidLimitedExpress),
    ExactRun("17:22", trainType: .rapidLimitedExpress),
    ExactRun("17:33", trainType: .limitedExpress),
    ExactRun("17:41", trainType: .limitedExpress),
    ExactRun("17:48", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("17:57", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("18:07", trainType: .limitedExpress),
    ExactRun("18:14", trainType: .rapidLimitedExpress),
    ExactRun("18:23", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("18:25", trainType: .rapidLimitedExpress),
    ExactRun("18:33", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("18:35", trainType: .rapidLimitedExpress),
    ExactRun("18:44", trainType: .limitedExpress),
    ExactRun("18:46", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("18:55", trainType: .limitedExpress),
    ExactRun("18:57", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("19:05", trainType: .limitedExpress),
    ExactRun("19:07", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("19:14", trainType: .limitedExpress),
    ExactRun("19:16", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("19:24", trainType: .limitedExpress),
    ExactRun("19:26", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("19:34", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("19:36", trainType: .rapidLimitedExpress),
    ExactRun("19:44", trainType: .limitedExpress),
    ExactRun("19:54", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("19:56", trainType: .rapidLimitedExpress),
    ExactRun("20:04", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("20:14", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("20:16", trainType: .rapidLimitedExpress),
    ExactRun("20:24", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("20:34", trainType: .limitedExpress),
    ExactRun("20:36", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("20:46", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("20:53", trainType: .rapidLimitedExpress),
    ExactRun("21:04", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("21:12", trainType: .rapidLimitedExpress),
    ExactRun("21:24", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("21:32", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("21:42", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("21:52", trainType: .limitedExpress),
    ExactRun("22:02", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("22:13", trainType: .limitedExpress),
    ExactRun("22:20", trainType: .rapidLimitedExpress),
    ExactRun("22:31", trainType: .limitedExpress),
    ExactRun("22:41", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("22:44", trainType: .rapidLimitedExpress),
    ExactRun("23:01", trainType: .rapidLimitedExpress),
    ExactRun("23:23", trainType: .rapidLimitedExpress),
    ExactRun("23:34", trainType: .limitedExpress),
    ExactRun("23:48", trainType: .limitedExpress),
    ExactRun("24:00", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("24:10", terminusStationId: "Station:Keikyu.Kurihama.MiuraKaigan", trainType: .limitedExpress),
    ExactRun("24:20", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("24:28", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
]

private static let keikyuKurihamaDescExpressHol: [ExactRun] = [
    ExactRun("05:05", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("05:26", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("05:46", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("06:06", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("06:26", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("06:45", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("07:03", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("07:22", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("07:40", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("07:55", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("08:06", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("08:14", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("08:25", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("08:32", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("08:44", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("08:56", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("09:08", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("09:18", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("09:29", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("09:41", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("09:52", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("10:04", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("10:14", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("10:26", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("10:36", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("10:49", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("10:59", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("11:12", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("11:26", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("11:37", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("11:48", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("11:57", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("12:08", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("12:17", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("12:28", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("12:37", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("12:48", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("12:57", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("13:08", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("13:17", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("13:28", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("13:37", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("13:48", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("13:57", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("14:08", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("14:17", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("14:28", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("14:37", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("14:48", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("14:57", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("15:08", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("15:17", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("15:28", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("15:37", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("15:48", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("15:57", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("16:08", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("16:17", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("16:28", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("16:37", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("16:48", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("16:57", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("17:08", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("17:17", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("17:28", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("17:37", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("17:48", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("17:57", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("18:07", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("18:17", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("18:27", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("18:37", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("18:46", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("18:56", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("19:06", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("19:19", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("19:39", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("19:59", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("20:19", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("20:39", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("20:56", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("21:12", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("21:32", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("21:51", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("22:09", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("22:26", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("22:49", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("23:11", trainType: .limitedExpress),
    ExactRun("23:33", trainType: .limitedExpress),
]

private static let keikyuKurihamaDescExpressWd: [ExactRun] = [
    ExactRun("05:04", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("05:25", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("05:46", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("06:00", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("06:17", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("06:31", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("06:46", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("06:56", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("07:07", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("07:19", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("07:31", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("07:43", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("07:55", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("08:09", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("08:26", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("08:39", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("08:49", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("09:01", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("09:13", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("09:24", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("09:36", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("09:48", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("10:01", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("10:13", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("10:31", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("10:41", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("10:59", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("11:12", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("11:32", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("11:52", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("12:13", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("12:32", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("12:52", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("13:12", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("13:32", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("13:52", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("14:12", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("14:33", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("14:45", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("14:53", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("15:07", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("15:18", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("15:28", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("15:39", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("15:46", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("15:59", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("16:11", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("16:19", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("16:32", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("16:44", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("16:53", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("17:04", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("17:14", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("17:24", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("17:32", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("17:43", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("17:51", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("18:02", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("18:14", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("18:29", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("18:41", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("18:51", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("19:01", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("19:11", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("19:21", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("19:31", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("19:41", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("19:51", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("20:01", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("20:11", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .limitedExpress),
    ExactRun("20:21", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("20:31", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("20:40", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("20:50", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("21:00", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("21:11", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("21:18", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("21:30", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("21:38", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("21:49", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("22:05", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("22:15", terminusStationId: "Station:Keikyu.Kurihama.KeikyuKurihama", trainType: .rapidLimitedExpress),
    ExactRun("22:28", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("22:46", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("23:09", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("23:31", trainType: .limitedExpress),
]

}
