import Foundation

extension KeikyuLineData {

    // MARK: - Keikyu Airport Line (KK)

    static let airport = StaticTrainLine(
        id: "Railway:Keikyu.Airport",
        nameJa: "京急空港線",
        nameEn: "Keikyu Airport Line",
        operatorId: "Operator:Keikyu",
        colorHex: "#E60012",
        stations: [
            st("Keikyu.Airport", "KeikyuKamata", "京急蒲田", "Keikyu Kamata", "KK11", 35.5607, 139.7237),
            st("Keikyu.Airport", "Kojiya", "糀谷", "Kojiya", "KK12", 35.5537, 139.7317),
            st("Keikyu.Airport", "Otorii", "大鳥居", "Otorii", "KK13", 35.5487, 139.7417),
            st("Keikyu.Airport", "AnamoriInari", "穴守稲荷", "Anamori-inari", "KK14", 35.5477, 139.7517),
            st("Keikyu.Airport", "Tenkubashi", "天空橋", "Tenkubashi", "KK15", 35.5497, 139.7597),
            st("Keikyu.Airport", "HanedaAirportTerminal3", "羽田空港第3ターミナル", "Haneda Airport Terminal 3", "KK16", 35.5447, 139.7677),
            st("Keikyu.Airport", "HanedaAirportTerminal1and2", "羽田空港第1・第2ターミナル", "Haneda Airport Terminal 1 & 2", "KK17", 35.5487, 139.7847),
        ],
        hopTimesMinutes: [2, 2, 2, 2, 2, 3],
        directions: [
            // First/last estimated from Keikyu published patterns
            direction("Keikyu.Airport", "HanedaAirport", "羽田空港方面", "For Haneda Airport",
                      ascending: true,
                      weekday: pattern("05:14", "24:05", [
                          ("05:14", 8), ("06:30", 5), ("09:30", 6), ("16:30", 5), ("20:00", 6), ("22:00", 8),
                      ]),
                      holiday: pattern("05:14", "24:05", [
                          ("05:14", 8), ("07:00", 6), ("10:00", 6), ("20:00", 7),
                      ]),
                      expressWeekday: keikyuAirportAscExpressWd,
                      expressHoliday: keikyuAirportAscExpressHol),
            direction("Keikyu.Airport", "KeikyuKamata", "京急蒲田・品川方面", "For Keikyu Kamata & Shinagawa",
                      ascending: false,
                      weekday: pattern("05:26", "24:01", [
                          ("05:26", 8), ("06:30", 5), ("09:30", 6), ("16:30", 5), ("20:00", 6), ("22:00", 8),
                      ]),
                      holiday: pattern("05:26", "24:01", [
                          ("05:26", 8), ("07:00", 6), ("10:00", 6), ("20:00", 7),
                      ]),
                      expressWeekday: keikyuAirportDescExpressWd,
                      expressHoliday: keikyuAirportDescExpressHol),
        ],
        delayInfo: delayInfo,
        throughServices: [
            through("Keikyu.Airport.KeikyuKamata", .descending,
                    "京急本線", "Keikyu Main Line",
                    "品川・泉岳寺・都営浅草線方面", "for Shinagawa, Sengakuji & the Toei Asakusa Line",
                    to: "Railway:Keikyu.Main"),
        ],
        // Within the Airport Line only 快特/エアポート快特 skip stations, running
        // 京急蒲田→羽田空港第3ターミナル→羽田空港第1・第2ターミナル (passing 糀谷・
        // 大鳥居・穴守稲荷・天空橋). 特急 and エアポート急行(急行) stop at every
        // station (空港線内は各駅停車). Source: ja.wikipedia 京急空港線 停車駅.
        stopPatterns: [
            .rapidLimitedExpress: [0, 5, 6],
        ]
    )

    // MARK: - Keikyu Express Runs (ODPT StationTimetable, July 2026)
    // Skip-stop 快特/特急/エアポート急行(急行) departures at each direction origin
    // (+ a 堀ノ内 through-origin for northbound Main). Times/types/termini are
    // ODPT-exact; per-run stops resolve from each line's stopPatterns. Off-line
    // destinations terminate at the junction with continuesBeyond (蒲田→空港線,
    // 堀ノ内→久里浜線, 金沢八景→逗子線, 泉岳寺→都営浅草線直通).

private static let keikyuAirportAscExpressHol: [ExactRun] = [
    ExactRun("05:19", trainType: .limitedExpress),
    ExactRun("05:36", trainType: .rapidLimitedExpress),
    ExactRun("05:39", trainType: .express),
    ExactRun("05:48", trainType: .rapidLimitedExpress),
    ExactRun("05:53", trainType: .express),
    ExactRun("06:09", trainType: .express),
    ExactRun("06:17", trainType: .express),
    ExactRun("06:22", trainType: .express),
    ExactRun("06:30", trainType: .express),
    ExactRun("06:38", trainType: .express),
    ExactRun("06:43", trainType: .express),
    ExactRun("06:59", trainType: .express),
    ExactRun("07:04", trainType: .express),
    ExactRun("07:09", trainType: .express),
    ExactRun("07:14", trainType: .express),
    ExactRun("07:19", trainType: .express),
    ExactRun("07:24", trainType: .express),
    ExactRun("07:29", trainType: .express),
    ExactRun("07:33", trainType: .express),
    ExactRun("07:39", trainType: .express),
    ExactRun("07:43", trainType: .express),
    ExactRun("07:49", trainType: .express),
    ExactRun("07:53", trainType: .express),
    ExactRun("07:59", trainType: .express),
    ExactRun("08:03", trainType: .express),
    ExactRun("08:09", trainType: .express),
    ExactRun("08:13", trainType: .express),
    ExactRun("08:19", trainType: .express),
    ExactRun("08:23", trainType: .express),
    ExactRun("08:29", trainType: .express),
    ExactRun("08:33", trainType: .express),
    ExactRun("08:39", trainType: .express),
    ExactRun("08:44", trainType: .express),
    ExactRun("08:49", trainType: .express),
    ExactRun("08:54", trainType: .express),
    ExactRun("08:59", trainType: .express),
    ExactRun("09:05", trainType: .express),
    ExactRun("09:09", trainType: .express),
    ExactRun("09:15", trainType: .express),
    ExactRun("09:19", trainType: .express),
    ExactRun("09:24", trainType: .express),
    ExactRun("09:31", trainType: .rapidLimitedExpress),
    ExactRun("09:35", trainType: .express),
    ExactRun("09:44", trainType: .limitedExpress),
    ExactRun("09:51", trainType: .express),
    ExactRun("09:57", trainType: .limitedExpress),
    ExactRun("10:04", trainType: .limitedExpress),
    ExactRun("10:14", trainType: .express),
    ExactRun("10:25", trainType: .limitedExpress),
    ExactRun("10:32", trainType: .rapidLimitedExpress),
    ExactRun("10:34", trainType: .express),
    ExactRun("10:45", trainType: .limitedExpress),
    ExactRun("10:54", trainType: .express),
    ExactRun("11:04", trainType: .limitedExpress),
    ExactRun("11:12", trainType: .rapidLimitedExpress),
    ExactRun("11:14", trainType: .express),
    ExactRun("11:24", trainType: .limitedExpress),
    ExactRun("11:34", trainType: .express),
    ExactRun("11:44", trainType: .limitedExpress),
    ExactRun("11:52", trainType: .rapidLimitedExpress),
    ExactRun("11:54", trainType: .express),
    ExactRun("12:04", trainType: .limitedExpress),
    ExactRun("12:14", trainType: .express),
    ExactRun("12:24", trainType: .limitedExpress),
    ExactRun("12:32", trainType: .rapidLimitedExpress),
    ExactRun("12:34", trainType: .express),
    ExactRun("12:44", trainType: .limitedExpress),
    ExactRun("12:54", trainType: .express),
    ExactRun("13:04", trainType: .limitedExpress),
    ExactRun("13:12", trainType: .rapidLimitedExpress),
    ExactRun("13:14", trainType: .express),
    ExactRun("13:24", trainType: .limitedExpress),
    ExactRun("13:34", trainType: .express),
    ExactRun("13:44", trainType: .limitedExpress),
    ExactRun("13:52", trainType: .rapidLimitedExpress),
    ExactRun("13:54", trainType: .express),
    ExactRun("14:04", trainType: .limitedExpress),
    ExactRun("14:14", trainType: .express),
    ExactRun("14:24", trainType: .limitedExpress),
    ExactRun("14:32", trainType: .rapidLimitedExpress),
    ExactRun("14:34", trainType: .express),
    ExactRun("14:44", trainType: .limitedExpress),
    ExactRun("14:54", trainType: .express),
    ExactRun("15:04", trainType: .limitedExpress),
    ExactRun("15:12", trainType: .rapidLimitedExpress),
    ExactRun("15:14", trainType: .express),
    ExactRun("15:24", trainType: .limitedExpress),
    ExactRun("15:34", trainType: .express),
    ExactRun("15:44", trainType: .limitedExpress),
    ExactRun("15:52", trainType: .rapidLimitedExpress),
    ExactRun("15:54", trainType: .express),
    ExactRun("16:04", trainType: .limitedExpress),
    ExactRun("16:14", trainType: .express),
    ExactRun("16:24", trainType: .limitedExpress),
    ExactRun("16:32", trainType: .rapidLimitedExpress),
    ExactRun("16:34", trainType: .express),
    ExactRun("16:44", trainType: .limitedExpress),
    ExactRun("16:54", trainType: .express),
    ExactRun("17:04", trainType: .limitedExpress),
    ExactRun("17:12", trainType: .rapidLimitedExpress),
    ExactRun("17:14", trainType: .express),
    ExactRun("17:24", trainType: .limitedExpress),
    ExactRun("17:34", trainType: .express),
    ExactRun("17:44", trainType: .limitedExpress),
    ExactRun("17:52", trainType: .rapidLimitedExpress),
    ExactRun("17:54", trainType: .express),
    ExactRun("18:04", trainType: .limitedExpress),
    ExactRun("18:14", trainType: .express),
    ExactRun("18:24", trainType: .limitedExpress),
    ExactRun("18:32", trainType: .rapidLimitedExpress),
    ExactRun("18:34", trainType: .express),
    ExactRun("18:44", trainType: .limitedExpress),
    ExactRun("18:54", trainType: .express),
    ExactRun("19:04", trainType: .limitedExpress),
    ExactRun("19:15", trainType: .express),
    ExactRun("19:22", trainType: .rapidLimitedExpress),
    ExactRun("19:23", trainType: .express),
    ExactRun("19:35", trainType: .express),
    ExactRun("19:42", trainType: .rapidLimitedExpress),
    ExactRun("19:43", trainType: .express),
    ExactRun("19:55", trainType: .express),
    ExactRun("20:02", trainType: .rapidLimitedExpress),
    ExactRun("20:03", trainType: .express),
    ExactRun("20:15", trainType: .express),
    ExactRun("20:22", trainType: .rapidLimitedExpress),
    ExactRun("20:23", trainType: .express),
    ExactRun("20:35", trainType: .express),
    ExactRun("20:42", trainType: .rapidLimitedExpress),
    ExactRun("20:43", trainType: .express),
    ExactRun("20:55", trainType: .express),
    ExactRun("21:02", trainType: .rapidLimitedExpress),
    ExactRun("21:03", trainType: .express),
    ExactRun("21:15", trainType: .express),
    ExactRun("21:22", trainType: .rapidLimitedExpress),
    ExactRun("21:23", trainType: .express),
    ExactRun("21:35", trainType: .express),
    ExactRun("21:45", trainType: .express),
    ExactRun("21:54", trainType: .express),
    ExactRun("21:58", trainType: .express),
    ExactRun("22:09", trainType: .express),
    ExactRun("22:24", trainType: .express),
    ExactRun("22:34", trainType: .express),
    ExactRun("22:40", trainType: .express),
    ExactRun("22:47", trainType: .express),
    ExactRun("22:54", trainType: .express),
    ExactRun("23:09", trainType: .express),
    ExactRun("23:24", trainType: .express),
    ExactRun("23:40", trainType: .express),
    ExactRun("23:55", trainType: .express),
]

private static let keikyuAirportAscExpressWd: [ExactRun] = [
    ExactRun("05:19", trainType: .limitedExpress),
    ExactRun("05:36", trainType: .rapidLimitedExpress),
    ExactRun("05:38", trainType: .express),
    ExactRun("05:46", trainType: .rapidLimitedExpress),
    ExactRun("05:51", trainType: .express),
    ExactRun("06:00", trainType: .rapidLimitedExpress),
    ExactRun("06:06", trainType: .express),
    ExactRun("06:15", trainType: .express),
    ExactRun("06:21", trainType: .express),
    ExactRun("06:26", trainType: .rapidLimitedExpress),
    ExactRun("06:29", trainType: .express),
    ExactRun("06:36", trainType: .limitedExpress),
    ExactRun("06:40", trainType: .express),
    ExactRun("06:45", trainType: .express),
    ExactRun("06:52", trainType: .express),
    ExactRun("06:57", trainType: .rapidLimitedExpress),
    ExactRun("07:02", trainType: .express),
    ExactRun("07:08", trainType: .express),
    ExactRun("07:16", trainType: .express),
    ExactRun("07:20", trainType: .express),
    ExactRun("07:31", trainType: .express),
    ExactRun("07:41", trainType: .express),
    ExactRun("07:48", trainType: .rapidLimitedExpress),
    ExactRun("07:51", trainType: .express),
    ExactRun("07:58", trainType: .rapidLimitedExpress),
    ExactRun("08:02", trainType: .limitedExpress),
    ExactRun("08:05", trainType: .express),
    ExactRun("08:09", trainType: .rapidLimitedExpress),
    ExactRun("08:16", trainType: .express),
    ExactRun("08:18", trainType: .limitedExpress),
    ExactRun("08:24", trainType: .express),
    ExactRun("08:28", trainType: .limitedExpress),
    ExactRun("08:35", trainType: .express),
    ExactRun("08:47", trainType: .express),
    ExactRun("08:55", trainType: .express),
    ExactRun("09:00", trainType: .limitedExpress),
    ExactRun("09:05", trainType: .express),
    ExactRun("09:16", trainType: .express),
    ExactRun("09:25", trainType: .express),
    ExactRun("09:37", trainType: .express),
    ExactRun("09:45", trainType: .limitedExpress),
    ExactRun("09:54", trainType: .rapidLimitedExpress),
    ExactRun("09:56", trainType: .express),
    ExactRun("10:04", trainType: .express),
    ExactRun("10:05", trainType: .express),
    ExactRun("10:13", trainType: .express),
    ExactRun("10:16", trainType: .express),
    ExactRun("10:24", trainType: .express),
    ExactRun("10:28", trainType: .express),
    ExactRun("10:34", trainType: .express),
    ExactRun("10:38", trainType: .express),
    ExactRun("10:46", trainType: .express),
    ExactRun("10:56", trainType: .express),
    ExactRun("11:04", trainType: .limitedExpress),
    ExactRun("11:13", trainType: .rapidLimitedExpress),
    ExactRun("11:14", trainType: .express),
    ExactRun("11:24", trainType: .limitedExpress),
    ExactRun("11:34", trainType: .express),
    ExactRun("11:44", trainType: .limitedExpress),
    ExactRun("11:52", trainType: .rapidLimitedExpress),
    ExactRun("11:54", trainType: .express),
    ExactRun("12:04", trainType: .limitedExpress),
    ExactRun("12:14", trainType: .express),
    ExactRun("12:24", trainType: .limitedExpress),
    ExactRun("12:32", trainType: .rapidLimitedExpress),
    ExactRun("12:34", trainType: .express),
    ExactRun("12:44", trainType: .limitedExpress),
    ExactRun("12:54", trainType: .express),
    ExactRun("13:04", trainType: .limitedExpress),
    ExactRun("13:12", trainType: .rapidLimitedExpress),
    ExactRun("13:14", trainType: .express),
    ExactRun("13:24", trainType: .limitedExpress),
    ExactRun("13:34", trainType: .express),
    ExactRun("13:44", trainType: .limitedExpress),
    ExactRun("13:52", trainType: .rapidLimitedExpress),
    ExactRun("13:54", trainType: .express),
    ExactRun("14:04", trainType: .limitedExpress),
    ExactRun("14:14", trainType: .express),
    ExactRun("14:24", trainType: .limitedExpress),
    ExactRun("14:32", trainType: .rapidLimitedExpress),
    ExactRun("14:34", trainType: .express),
    ExactRun("14:44", trainType: .limitedExpress),
    ExactRun("14:54", trainType: .express),
    ExactRun("15:04", trainType: .limitedExpress),
    ExactRun("15:12", trainType: .rapidLimitedExpress),
    ExactRun("15:14", trainType: .express),
    ExactRun("15:24", trainType: .limitedExpress),
    ExactRun("15:34", trainType: .express),
    ExactRun("15:43", trainType: .rapidLimitedExpress),
    ExactRun("15:45", trainType: .express),
    ExactRun("15:52", trainType: .rapidLimitedExpress),
    ExactRun("15:54", trainType: .express),
    ExactRun("16:02", trainType: .rapidLimitedExpress),
    ExactRun("16:04", trainType: .express),
    ExactRun("16:12", trainType: .rapidLimitedExpress),
    ExactRun("16:14", trainType: .express),
    ExactRun("16:19", trainType: .limitedExpress),
    ExactRun("16:22", trainType: .express),
    ExactRun("16:28", trainType: .express),
    ExactRun("16:39", trainType: .express),
    ExactRun("16:43", trainType: .express),
    ExactRun("16:49", trainType: .express),
    ExactRun("16:54", trainType: .express),
    ExactRun("17:00", trainType: .express),
    ExactRun("17:04", trainType: .express),
    ExactRun("17:14", trainType: .express),
    ExactRun("17:17", trainType: .express),
    ExactRun("17:25", trainType: .express),
    ExactRun("17:27", trainType: .express),
    ExactRun("17:35", trainType: .express),
    ExactRun("17:37", trainType: .express),
    ExactRun("17:45", trainType: .express),
    ExactRun("17:48", trainType: .express),
    ExactRun("17:55", trainType: .express),
    ExactRun("17:57", trainType: .express),
    ExactRun("18:05", trainType: .express),
    ExactRun("18:07", trainType: .express),
    ExactRun("18:15", trainType: .express),
    ExactRun("18:17", trainType: .express),
    ExactRun("18:25", trainType: .express),
    ExactRun("18:28", trainType: .express),
    ExactRun("18:35", trainType: .express),
    ExactRun("18:37", trainType: .express),
    ExactRun("18:45", trainType: .express),
    ExactRun("18:47", trainType: .express),
    ExactRun("18:54", trainType: .express),
    ExactRun("18:57", trainType: .express),
    ExactRun("18:59", trainType: .express),
    ExactRun("19:06", trainType: .express),
    ExactRun("19:09", trainType: .express),
    ExactRun("19:15", trainType: .express),
    ExactRun("19:19", trainType: .express),
    ExactRun("19:26", trainType: .express),
    ExactRun("19:29", trainType: .express),
    ExactRun("19:35", trainType: .express),
    ExactRun("19:38", trainType: .express),
    ExactRun("19:46", trainType: .express),
    ExactRun("19:48", trainType: .express),
    ExactRun("19:55", trainType: .express),
    ExactRun("20:06", trainType: .express),
    ExactRun("20:11", trainType: .express),
    ExactRun("20:14", trainType: .express),
    ExactRun("20:21", trainType: .express),
    ExactRun("20:27", trainType: .express),
    ExactRun("20:32", trainType: .express),
    ExactRun("20:35", trainType: .express),
    ExactRun("20:42", trainType: .express),
    ExactRun("20:45", trainType: .express),
    ExactRun("20:53", trainType: .express),
    ExactRun("20:56", trainType: .express),
    ExactRun("21:03", trainType: .express),
    ExactRun("21:05", trainType: .express),
    ExactRun("21:12", trainType: .express),
    ExactRun("21:15", trainType: .express),
    ExactRun("21:23", trainType: .express),
    ExactRun("21:26", trainType: .express),
    ExactRun("21:34", trainType: .express),
    ExactRun("21:36", trainType: .express),
    ExactRun("21:43", trainType: .express),
    ExactRun("21:47", trainType: .express),
    ExactRun("21:58", trainType: .express),
    ExactRun("22:07", trainType: .express),
    ExactRun("22:16", trainType: .express),
    ExactRun("22:27", trainType: .express),
    ExactRun("22:36", trainType: .express),
    ExactRun("22:48", trainType: .express),
    ExactRun("23:02", trainType: .express),
    ExactRun("23:22", trainType: .express),
    ExactRun("23:32", trainType: .express),
    ExactRun("24:15", trainType: .express),
]

private static let keikyuAirportDescExpressHol: [ExactRun] = [
    ExactRun("05:23", continuesBeyond: true, trainType: .express),
    ExactRun("05:34", continuesBeyond: true, trainType: .express),
    ExactRun("05:40", continuesBeyond: true, trainType: .express),
    ExactRun("05:58", continuesBeyond: true, trainType: .express),
    ExactRun("06:06", continuesBeyond: true, trainType: .express),
    ExactRun("06:16", continuesBeyond: true, trainType: .express),
    ExactRun("06:23", continuesBeyond: true, trainType: .express),
    ExactRun("06:31", continuesBeyond: true, trainType: .express),
    ExactRun("06:40", continuesBeyond: true, trainType: .express),
    ExactRun("06:46", continuesBeyond: true, trainType: .express),
    ExactRun("06:53", continuesBeyond: true, trainType: .express),
    ExactRun("07:03", continuesBeyond: true, trainType: .express),
    ExactRun("07:08", continuesBeyond: true, trainType: .express),
    ExactRun("07:13", continuesBeyond: true, trainType: .express),
    ExactRun("07:22", continuesBeyond: true, trainType: .express),
    ExactRun("07:26", continuesBeyond: true, trainType: .express),
    ExactRun("07:32", continuesBeyond: true, trainType: .express),
    ExactRun("07:36", continuesBeyond: true, trainType: .express),
    ExactRun("07:42", continuesBeyond: true, trainType: .express),
    ExactRun("07:46", continuesBeyond: true, trainType: .express),
    ExactRun("07:52", continuesBeyond: true, trainType: .express),
    ExactRun("07:56", continuesBeyond: true, trainType: .express),
    ExactRun("08:02", continuesBeyond: true, trainType: .express),
    ExactRun("08:06", continuesBeyond: true, trainType: .express),
    ExactRun("08:12", continuesBeyond: true, trainType: .express),
    ExactRun("08:16", continuesBeyond: true, trainType: .express),
    ExactRun("08:22", continuesBeyond: true, trainType: .express),
    ExactRun("08:26", continuesBeyond: true, trainType: .express),
    ExactRun("08:32", continuesBeyond: true, trainType: .express),
    ExactRun("08:37", continuesBeyond: true, trainType: .express),
    ExactRun("08:42", continuesBeyond: true, trainType: .express),
    ExactRun("08:47", continuesBeyond: true, trainType: .express),
    ExactRun("08:52", continuesBeyond: true, trainType: .express),
    ExactRun("08:57", continuesBeyond: true, trainType: .express),
    ExactRun("09:02", continuesBeyond: true, trainType: .express),
    ExactRun("09:07", continuesBeyond: true, trainType: .express),
    ExactRun("09:12", continuesBeyond: true, trainType: .express),
    ExactRun("09:17", continuesBeyond: true, trainType: .express),
    ExactRun("09:20", continuesBeyond: true, trainType: .express),
    ExactRun("09:26", continuesBeyond: true, trainType: .express),
    ExactRun("09:31", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("09:36", continuesBeyond: true, trainType: .express),
    ExactRun("09:41", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("09:45", continuesBeyond: true, trainType: .express),
    ExactRun("09:57", continuesBeyond: true, trainType: .express),
    ExactRun("10:02", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("10:06", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("10:17", continuesBeyond: true, trainType: .express),
    ExactRun("10:23", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("10:26", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("10:37", continuesBeyond: true, trainType: .express),
    ExactRun("10:42", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("10:46", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("10:57", continuesBeyond: true, trainType: .express),
    ExactRun("11:03", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("11:06", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("11:17", continuesBeyond: true, trainType: .express),
    ExactRun("11:22", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("11:26", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("11:37", continuesBeyond: true, trainType: .express),
    ExactRun("11:43", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("11:46", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("11:57", continuesBeyond: true, trainType: .express),
    ExactRun("12:02", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("12:06", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("12:17", continuesBeyond: true, trainType: .express),
    ExactRun("12:23", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("12:26", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("12:37", continuesBeyond: true, trainType: .express),
    ExactRun("12:42", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("12:46", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("12:57", continuesBeyond: true, trainType: .express),
    ExactRun("13:03", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("13:06", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("13:17", continuesBeyond: true, trainType: .express),
    ExactRun("13:22", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("13:26", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("13:37", continuesBeyond: true, trainType: .express),
    ExactRun("13:43", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("13:46", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("13:57", continuesBeyond: true, trainType: .express),
    ExactRun("14:02", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("14:06", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("14:17", continuesBeyond: true, trainType: .express),
    ExactRun("14:23", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("14:26", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("14:37", continuesBeyond: true, trainType: .express),
    ExactRun("14:42", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("14:46", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("14:57", continuesBeyond: true, trainType: .express),
    ExactRun("15:03", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("15:06", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("15:17", continuesBeyond: true, trainType: .express),
    ExactRun("15:22", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("15:26", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("15:37", continuesBeyond: true, trainType: .express),
    ExactRun("15:43", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("15:46", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("15:57", continuesBeyond: true, trainType: .express),
    ExactRun("16:02", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("16:06", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("16:17", continuesBeyond: true, trainType: .express),
    ExactRun("16:23", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("16:26", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("16:37", continuesBeyond: true, trainType: .express),
    ExactRun("16:42", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("16:46", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("16:57", continuesBeyond: true, trainType: .express),
    ExactRun("17:03", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("17:06", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("17:17", continuesBeyond: true, trainType: .express),
    ExactRun("17:22", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("17:26", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("17:37", continuesBeyond: true, trainType: .express),
    ExactRun("17:43", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("17:46", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("17:57", continuesBeyond: true, trainType: .express),
    ExactRun("18:02", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("18:06", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("18:17", continuesBeyond: true, trainType: .express),
    ExactRun("18:23", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("18:26", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("18:37", continuesBeyond: true, trainType: .express),
    ExactRun("18:42", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("18:46", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("18:57", continuesBeyond: true, trainType: .express),
    ExactRun("19:02", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("19:07", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("19:18", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("19:20", continuesBeyond: true, trainType: .express),
    ExactRun("19:30", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("19:35", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("19:40", continuesBeyond: true, trainType: .express),
    ExactRun("19:50", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("19:55", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("20:00", continuesBeyond: true, trainType: .express),
    ExactRun("20:10", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("20:15", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("20:20", continuesBeyond: true, trainType: .express),
    ExactRun("20:30", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("20:35", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("20:40", continuesBeyond: true, trainType: .express),
    ExactRun("20:50", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("20:55", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("21:00", continuesBeyond: true, trainType: .express),
    ExactRun("21:10", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("21:15", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("21:20", continuesBeyond: true, trainType: .express),
    ExactRun("21:31", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("21:37", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("21:47", continuesBeyond: true, trainType: .express),
    ExactRun("21:51", continuesBeyond: true, trainType: .express),
    ExactRun("22:00", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("22:04", continuesBeyond: true, trainType: .express),
    ExactRun("22:14", continuesBeyond: true, trainType: .express),
    ExactRun("22:20", continuesBeyond: true, trainType: .express),
    ExactRun("22:27", continuesBeyond: true, trainType: .express),
    ExactRun("22:39", continuesBeyond: true, trainType: .express),
    ExactRun("22:48", continuesBeyond: true, trainType: .express),
    ExactRun("22:53", continuesBeyond: true, trainType: .express),
    ExactRun("23:01", continuesBeyond: true, trainType: .express),
    ExactRun("23:09", continuesBeyond: true, trainType: .express),
    ExactRun("23:17", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("23:21", continuesBeyond: true, trainType: .express),
    ExactRun("23:34", continuesBeyond: true, trainType: .express),
    ExactRun("23:48", continuesBeyond: true, trainType: .express),
    ExactRun("24:05", continuesBeyond: true, trainType: .rapidLimitedExpress),
]

private static let keikyuAirportDescExpressWd: [ExactRun] = [
    ExactRun("05:23", continuesBeyond: true, trainType: .express),
    ExactRun("05:34", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("05:39", continuesBeyond: true, trainType: .express),
    ExactRun("05:48", continuesBeyond: true, trainType: .express),
    ExactRun("05:56", continuesBeyond: true, trainType: .express),
    ExactRun("06:01", continuesBeyond: true, trainType: .express),
    ExactRun("06:09", continuesBeyond: true, trainType: .express),
    ExactRun("06:13", continuesBeyond: true, trainType: .express),
    ExactRun("06:29", continuesBeyond: true, trainType: .express),
    ExactRun("06:35", continuesBeyond: true, trainType: .express),
    ExactRun("06:38", continuesBeyond: true, trainType: .express),
    ExactRun("06:44", continuesBeyond: true, trainType: .express),
    ExactRun("06:52", continuesBeyond: true, trainType: .express),
    ExactRun("06:55", continuesBeyond: true, trainType: .express),
    ExactRun("07:00", continuesBeyond: true, trainType: .express),
    ExactRun("07:05", continuesBeyond: true, trainType: .express),
    ExactRun("07:13", continuesBeyond: true, trainType: .express),
    ExactRun("07:16", continuesBeyond: true, trainType: .express),
    ExactRun("07:26", continuesBeyond: true, trainType: .express),
    ExactRun("07:31", continuesBeyond: true, trainType: .express),
    ExactRun("07:36", continuesBeyond: true, trainType: .express),
    ExactRun("07:40", continuesBeyond: true, trainType: .express),
    ExactRun("07:44", continuesBeyond: true, trainType: .express),
    ExactRun("07:50", continuesBeyond: true, trainType: .express),
    ExactRun("07:57", continuesBeyond: true, trainType: .express),
    ExactRun("08:01", continuesBeyond: true, trainType: .express),
    ExactRun("08:10", continuesBeyond: true, trainType: .express),
    ExactRun("08:20", continuesBeyond: true, trainType: .express),
    ExactRun("08:26", continuesBeyond: true, trainType: .express),
    ExactRun("08:32", continuesBeyond: true, trainType: .express),
    ExactRun("08:37", continuesBeyond: true, trainType: .express),
    ExactRun("08:42", continuesBeyond: true, trainType: .express),
    ExactRun("08:47", continuesBeyond: true, trainType: .express),
    ExactRun("08:52", continuesBeyond: true, trainType: .express),
    ExactRun("08:56", continuesBeyond: true, trainType: .express),
    ExactRun("09:03", continuesBeyond: true, trainType: .express),
    ExactRun("09:08", continuesBeyond: true, trainType: .express),
    ExactRun("09:13", continuesBeyond: true, trainType: .express),
    ExactRun("09:18", continuesBeyond: true, trainType: .express),
    ExactRun("09:24", continuesBeyond: true, trainType: .express),
    ExactRun("09:30", continuesBeyond: true, trainType: .express),
    ExactRun("09:33", continuesBeyond: true, trainType: .express),
    ExactRun("09:38", continuesBeyond: true, trainType: .express),
    ExactRun("09:47", continuesBeyond: true, trainType: .express),
    ExactRun("09:51", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("09:59", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("10:06", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("10:12", continuesBeyond: true, trainType: .express),
    ExactRun("10:20", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("10:22", continuesBeyond: true, trainType: .express),
    ExactRun("10:30", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("10:32", continuesBeyond: true, trainType: .express),
    ExactRun("10:41", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("10:43", continuesBeyond: true, trainType: .express),
    ExactRun("10:51", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("10:55", continuesBeyond: true, trainType: .express),
    ExactRun("11:04", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("11:06", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("11:17", continuesBeyond: true, trainType: .express),
    ExactRun("11:22", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("11:26", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("11:37", continuesBeyond: true, trainType: .express),
    ExactRun("11:43", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("11:46", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("11:57", continuesBeyond: true, trainType: .express),
    ExactRun("12:02", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("12:06", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("12:17", continuesBeyond: true, trainType: .express),
    ExactRun("12:23", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("12:26", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("12:37", continuesBeyond: true, trainType: .express),
    ExactRun("12:42", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("12:46", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("12:57", continuesBeyond: true, trainType: .express),
    ExactRun("13:03", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("13:06", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("13:17", continuesBeyond: true, trainType: .express),
    ExactRun("13:22", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("13:26", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("13:37", continuesBeyond: true, trainType: .express),
    ExactRun("13:43", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("13:46", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("13:57", continuesBeyond: true, trainType: .express),
    ExactRun("14:02", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("14:06", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("14:17", continuesBeyond: true, trainType: .express),
    ExactRun("14:23", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("14:26", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("14:37", continuesBeyond: true, trainType: .express),
    ExactRun("14:42", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("14:46", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("14:57", continuesBeyond: true, trainType: .express),
    ExactRun("15:03", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("15:06", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("15:17", continuesBeyond: true, trainType: .express),
    ExactRun("15:22", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("15:26", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("15:36", continuesBeyond: true, trainType: .express),
    ExactRun("15:41", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("15:46", continuesBeyond: true, trainType: .express),
    ExactRun("15:50", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("15:55", continuesBeyond: true, trainType: .express),
    ExactRun("15:58", continuesBeyond: true, trainType: .express),
    ExactRun("16:06", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("16:12", continuesBeyond: true, trainType: .express),
    ExactRun("16:15", continuesBeyond: true, trainType: .express),
    ExactRun("16:21", continuesBeyond: true, trainType: .express),
    ExactRun("16:26", continuesBeyond: true, trainType: .express),
    ExactRun("16:31", continuesBeyond: true, trainType: .express),
    ExactRun("16:37", continuesBeyond: true, trainType: .express),
    ExactRun("16:42", continuesBeyond: true, trainType: .express),
    ExactRun("16:46", continuesBeyond: true, trainType: .express),
    ExactRun("16:52", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("16:56", continuesBeyond: true, trainType: .express),
    ExactRun("16:58", continuesBeyond: true, trainType: .express),
    ExactRun("17:07", continuesBeyond: true, trainType: .express),
    ExactRun("17:09", continuesBeyond: true, trainType: .express),
    ExactRun("17:18", continuesBeyond: true, trainType: .express),
    ExactRun("17:21", continuesBeyond: true, trainType: .express),
    ExactRun("17:29", continuesBeyond: true, trainType: .express),
    ExactRun("17:32", continuesBeyond: true, trainType: .express),
    ExactRun("17:40", continuesBeyond: true, trainType: .express),
    ExactRun("17:42", continuesBeyond: true, trainType: .express),
    ExactRun("17:50", continuesBeyond: true, trainType: .express),
    ExactRun("17:52", continuesBeyond: true, trainType: .express),
    ExactRun("17:58", continuesBeyond: true, trainType: .express),
    ExactRun("18:01", continuesBeyond: true, trainType: .express),
    ExactRun("18:10", continuesBeyond: true, trainType: .express),
    ExactRun("18:12", continuesBeyond: true, trainType: .express),
    ExactRun("18:20", continuesBeyond: true, trainType: .express),
    ExactRun("18:22", continuesBeyond: true, trainType: .express),
    ExactRun("18:30", continuesBeyond: true, trainType: .express),
    ExactRun("18:32", continuesBeyond: true, trainType: .express),
    ExactRun("18:39", continuesBeyond: true, trainType: .express),
    ExactRun("18:42", continuesBeyond: true, trainType: .express),
    ExactRun("18:50", continuesBeyond: true, trainType: .express),
    ExactRun("18:52", continuesBeyond: true, trainType: .express),
    ExactRun("19:00", continuesBeyond: true, trainType: .express),
    ExactRun("19:02", continuesBeyond: true, trainType: .express),
    ExactRun("19:08", continuesBeyond: true, trainType: .express),
    ExactRun("19:12", continuesBeyond: true, trainType: .express),
    ExactRun("19:17", continuesBeyond: true, trainType: .express),
    ExactRun("19:21", continuesBeyond: true, trainType: .express),
    ExactRun("19:27", continuesBeyond: true, trainType: .express),
    ExactRun("19:31", continuesBeyond: true, trainType: .express),
    ExactRun("19:38", continuesBeyond: true, trainType: .express),
    ExactRun("19:41", continuesBeyond: true, trainType: .express),
    ExactRun("19:48", continuesBeyond: true, trainType: .express),
    ExactRun("19:53", continuesBeyond: true, trainType: .express),
    ExactRun("19:58", continuesBeyond: true, trainType: .express),
    ExactRun("20:03", continuesBeyond: true, trainType: .express),
    ExactRun("20:08", continuesBeyond: true, trainType: .express),
    ExactRun("20:14", continuesBeyond: true, trainType: .express),
    ExactRun("20:20", continuesBeyond: true, trainType: .express),
    ExactRun("20:27", continuesBeyond: true, trainType: .express),
    ExactRun("20:30", continuesBeyond: true, trainType: .express),
    ExactRun("20:37", continuesBeyond: true, trainType: .express),
    ExactRun("20:40", continuesBeyond: true, trainType: .express),
    ExactRun("20:47", continuesBeyond: true, trainType: .express),
    ExactRun("20:51", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("20:58", continuesBeyond: true, trainType: .express),
    ExactRun("21:00", continuesBeyond: true, trainType: .express),
    ExactRun("21:08", continuesBeyond: true, trainType: .express),
    ExactRun("21:11", continuesBeyond: true, trainType: .express),
    ExactRun("21:19", continuesBeyond: true, trainType: .express),
    ExactRun("21:23", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("21:29", continuesBeyond: true, trainType: .express),
    ExactRun("21:32", continuesBeyond: true, trainType: .express),
    ExactRun("21:40", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("21:43", continuesBeyond: true, trainType: .rapidLimitedExpress),
    ExactRun("21:48", continuesBeyond: true, trainType: .express),
    ExactRun("21:52", continuesBeyond: true, trainType: .express),
    ExactRun("22:00", continuesBeyond: true, trainType: .express),
    ExactRun("22:08", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("22:13", continuesBeyond: true, trainType: .express),
    ExactRun("22:25", continuesBeyond: true, trainType: .express),
    ExactRun("22:35", continuesBeyond: true, trainType: .express),
    ExactRun("22:42", continuesBeyond: true, trainType: .limitedExpress),
    ExactRun("22:51", continuesBeyond: true, trainType: .express),
    ExactRun("22:56", continuesBeyond: true, trainType: .express),
    ExactRun("23:06", continuesBeyond: true, trainType: .express),
    ExactRun("23:16", continuesBeyond: true, trainType: .express),
    ExactRun("23:25", continuesBeyond: true, trainType: .express),
    ExactRun("23:34", continuesBeyond: true, trainType: .express),
    ExactRun("23:42", continuesBeyond: true, trainType: .express),
    ExactRun("23:49", continuesBeyond: true, trainType: .express),
    ExactRun("24:05", continuesBeyond: true, trainType: .rapidLimitedExpress),
]

}
