import Foundation

// MARK: - Seibu Line Data

private func st(_ path: String, _ suffix: String, _ ja: String, _ en: String,
                _ code: String, _ lat: Double, _ lon: Double) -> Station {
    Station(
        id: "Station:\(path).\(suffix)",
        name: ja, nameEn: en, stationCode: code,
        latitude: lat, longitude: lon
    )
}

private func pattern(_ first: String, _ last: String, _ bands: [(String, Double)]) -> ServicePattern {
    ServicePattern(
        first: first, last: last,
        bands: bands.map { HeadwayBand(from: $0.0, headwayMinutes: $0.1) }
    )
}

private func direction(_ path: String, _ suffix: String, _ ja: String, _ en: String,
                       ascending: Bool,
                       weekday: ServicePattern, holiday: ServicePattern,
                       origins: [IntermediateOrigin] = [],
                       expressWeekday: [ExactRun] = [],
                       expressHoliday: [ExactRun] = []) -> StaticLineDirection {
    StaticLineDirection(
        id: "static.RailDirection:\(path).\(suffix)",
        nameJa: ja, nameEn: en,
        isAscending: ascending,
        weekday: weekday, saturdayHoliday: holiday,
        intermediateOrigins: origins,
        expressWeekdayRuns: expressWeekday,
        expressSaturdayHolidayRuns: expressHoliday
    )
}

// Express 当駅始発/through origin with typed exact runs (ODPT StationTimetable),
// for skip-stop trains starting at or entering a mid-line station.
private func originRuns(_ stationId: String, _ weekday: [ExactRun], _ holiday: [ExactRun]) -> IntermediateOrigin {
    IntermediateOrigin(stationId: stationId, weekdayRuns: weekday, saturdayHolidayRuns: holiday)
}

private func through(_ junction: String, _ end: ThroughService.LineEnd,
                     _ lineJa: String, _ lineEn: String,
                     _ towardJa: String, _ towardEn: String,
                     to connectingLineId: String? = nil) -> ThroughService {
    ThroughService(
        junctionStationId: "Station:\(junction)",
        end: end,
        lineNameJa: lineJa, lineNameEn: lineEn,
        towardJa: towardJa, towardEn: towardEn,
        connectingLineId: connectingLineId
    )
}

enum SeibuLineData {

    // MARK: Delay Check

    static let delayInfo = DelayCheckInfo(
        statusPageURL: "https://www.seiburailway.jp/railways/unkou/",
        statusPageURLEn: "https://www.seiburailway.jp/global/en/",
        xAccount: nil,
        checkMethodJa: "西武鉄道「運行情報」ページまたは西武線アプリで確認できます。遅延・運転見合わせが発生した場合に掲載されます。",
        checkMethodEn: "Check the Seibu Railway operation information page or the Seibu Lines app. Delays and suspensions are posted as they occur."
    )

    static let lines: [StaticTrainLine] = [
        ikebukuro, seibuYurakucho, shinjuku,
    ]

    // MARK: - Seibu Ikebukuro Line (SI)

    static let ikebukuro = StaticTrainLine(
        id: "Railway:Seibu.Ikebukuro",
        nameJa: "西武池袋線",
        nameEn: "Seibu Ikebukuro Line",
        operatorId: "Operator:Seibu",
        colorHex: "#F08300",
        stations: [
            st("Seibu.Ikebukuro", "Ikebukuro", "池袋", "Ikebukuro", "SI01", 35.7295, 139.7109),
            st("Seibu.Ikebukuro", "Shiinamachi", "椎名町", "Shiinamachi", "SI02", 35.7237, 139.6987),
            st("Seibu.Ikebukuro", "HigashiNagasaki", "東長崎", "Higashi-nagasaki", "SI03", 35.7227, 139.6877),
            st("Seibu.Ikebukuro", "Ekoda", "江古田", "Ekoda", "SI04", 35.7367, 139.6737),
            st("Seibu.Ikebukuro", "Sakuradai", "桜台", "Sakuradai", "SI05", 35.7377, 139.6637),
            st("Seibu.Ikebukuro", "Nerima", "練馬", "Nerima", "SI06", 35.7377, 139.6537),
            st("Seibu.Ikebukuro", "Nakamurabashi", "中村橋", "Nakamurabashi", "SI07", 35.7397, 139.6387),
            st("Seibu.Ikebukuro", "Fujimidai", "富士見台", "Fujimidai", "SI08", 35.7407, 139.6287),
            st("Seibu.Ikebukuro", "NerimaTakanodai", "練馬高野台", "Nerima-takanodai", "SI09", 35.7457, 139.6187),
            st("Seibu.Ikebukuro", "ShakujiiKoen", "石神井公園", "Shakujii-koen", "SI10", 35.7437, 139.6067),
            st("Seibu.Ikebukuro", "OizumiGakuen", "大泉学園", "Oizumi-gakuen", "SI11", 35.7497, 139.5877),
            st("Seibu.Ikebukuro", "Hoya", "保谷", "Hoya", "SI12", 35.7517, 139.5687),
            st("Seibu.Ikebukuro", "Hibarigaoka", "ひばりヶ丘", "Hibarigaoka", "SI13", 35.7517, 139.5457),
            st("Seibu.Ikebukuro", "HigashiKurume", "東久留米", "Higashi-kurume", "SI14", 35.7577, 139.5297),
            st("Seibu.Ikebukuro", "Kiyose", "清瀬", "Kiyose", "SI15", 35.7697, 139.5187),
            st("Seibu.Ikebukuro", "Akitsu", "秋津", "Akitsu", "SI16", 35.7727, 139.4937),
            st("Seibu.Ikebukuro", "Tokorozawa", "所沢", "Tokorozawa", "SI17", 35.7867, 139.4733),
            st("Seibu.Ikebukuro", "NishiTokorozawa", "西所沢", "Nishi-tokorozawa", "SI18", 35.7897, 139.4487),
            st("Seibu.Ikebukuro", "Kotesashi", "小手指", "Kotesashi", "SI19", 35.7937, 139.4247),
            st("Seibu.Ikebukuro", "Sayamagaoka", "狭山ヶ丘", "Sayamagaoka", "SI20", 35.8027, 139.4087),
            st("Seibu.Ikebukuro", "MusashiFujisawa", "武蔵藤沢", "Musashi-fujisawa", "SI21", 35.8107, 139.3987),
            st("Seibu.Ikebukuro", "InariyamaKoen", "稲荷山公園", "Inariyama-koen", "SI22", 35.8317, 139.3887),
            st("Seibu.Ikebukuro", "Irumashi", "入間市", "Irumashi", "SI23", 35.8357, 139.3787),
            st("Seibu.Ikebukuro", "Bushi", "仏子", "Bushi", "SI24", 35.8407, 139.3487),
            st("Seibu.Ikebukuro", "Motokaji", "元加治", "Motokaji", "SI25", 35.8447, 139.3337),
            st("Seibu.Ikebukuro", "Hanno", "飯能", "Hanno", "SI26", 35.8557, 139.3277),
        ],
        hopTimesMinutes: [
            2, 2, 2, 2, 2, 2, 1, 2, 2, 3, 2, 3, 2, 2,
            3, 3, 2, 3, 2, 2, 3, 2, 3, 2, 3,
        ],
        directions: [
            direction("Seibu.Ikebukuro", "Hanno", "所沢・飯能方面", "For Tokorozawa & Hanno",
                      ascending: true,
                      weekday: pattern("04:58", "23:52", [
                          ("04:58", 8), ("06:30", 4), ("09:30", 6), ("16:30", 5), ("20:00", 6), ("22:00", 8),
                      ]),
                      holiday: pattern("04:58", "23:52", [
                          ("04:58", 8), ("07:00", 6), ("10:00", 6), ("20:00", 8),
                      ]),
                      origins: [
                          // 快速急行/F-Liner enter from 副都心線 at 練馬 (当駅始発 false)
                          originRuns("Station:Seibu.Ikebukuro.Nerima",
                                     ikebukuroAscExpressWd_org_Nerima, ikebukuroAscExpressHol_org_Nerima),
                      ],
                      expressWeekday: ikebukuroAscExpressWd,
                      expressHoliday: ikebukuroAscExpressHol),
            direction("Seibu.Ikebukuro", "Ikebukuro", "池袋方面", "For Ikebukuro",
                      ascending: false,
                      weekday: pattern("05:03", "23:08", [
                          ("05:03", 8), ("06:30", 4), ("09:30", 6), ("16:30", 5), ("20:00", 6), ("22:00", 8),
                      ]),
                      holiday: pattern("05:03", "23:08", [
                          ("05:03", 8), ("07:00", 6), ("10:00", 6), ("20:00", 8),
                      ]),
                      origins: [
                          originRuns("Station:Seibu.Ikebukuro.ShakujiiKoen",
                                     ikebukuroDescExpressWd_org_ShakujiiKoen, []),
                          originRuns("Station:Seibu.Ikebukuro.Kiyose",
                                     ikebukuroDescExpressWd_org_Kiyose, ikebukuroDescExpressHol_org_Kiyose),
                          originRuns("Station:Seibu.Ikebukuro.Tokorozawa",
                                     ikebukuroDescExpressWd_org_Tokorozawa, ikebukuroDescExpressHol_org_Tokorozawa),
                          originRuns("Station:Seibu.Ikebukuro.Kotesashi",
                                     ikebukuroDescExpressWd_org_Kotesashi, ikebukuroDescExpressHol_org_Kotesashi),
                      ],
                      expressWeekday: ikebukuroDescExpressWd,
                      expressHoliday: ikebukuroDescExpressHol),
        ],
        delayInfo: delayInfo,
        throughServices: [
            through("Seibu.Ikebukuro.Nerima", .descending,
                    "西武有楽町線", "Seibu Yurakucho Line",
                    "小竹向原・有楽町線・副都心線方面", "for Kotake-Mukaihara & the Yurakucho and Fukutoshin Lines",
                    to: "Railway:Seibu.SeibuYurakucho"),
            through("Seibu.Ikebukuro.Hanno", .ascending,
                    "西武池袋線・秩父線", "Seibu Ikebukuro & Chichibu Lines",
                    "西武秩父方面", "for Seibu-Chichibu"),
        ],
        // 停車駅 hand-coded from Seibu's official 停車駅案内 and cross-checked
        // against ODPT StationTimetable presence (a train appears in a
        // station's timetable only where it stops). Times/types/termini are
        // ODPT-exact; stop patterns are not ODPT-per-train verifiable.
        // Sources: https://ja.wikipedia.org/wiki/西武池袋線 (停車駅一覧),
        //          https://www.seiburailway.jp/railways/timetable/ (停車駅案内).
        // Indices are into `stations` (0=池袋 … 25=飯能).
        stopPatterns: [
            .express:             [0, 9, 12, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],                 // 急行 (runs local beyond 小手指)
            .semiExpress:         [0, 5, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25], // 準急
            .rapid:               [0, 5, 9, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],         // 快速
            .commuterExpress:     [0, 9, 10, 11, 13, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],                // 通勤急行 (千鳥停車: skips ひばりヶ丘)
            .commuterSemiExpress: [0, 5, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],    // 通勤準急 (千鳥停車: skips 石神井公園)
            .rapidExpress:        [5, 9, 12, 16, 18, 22, 25],                                                // 快速急行/F-Liner (副都心線直通)
        ]
    )

    // MARK: - Seibu Yurakucho Line (SI)

    static let seibuYurakucho = StaticTrainLine(
        id: "Railway:Seibu.SeibuYurakucho",
        nameJa: "西武有楽町線",
        nameEn: "Seibu Yurakucho Line",
        operatorId: "Operator:Seibu",
        colorHex: "#F08300",
        stations: [
            st("Seibu.SeibuYurakucho", "KotakeMukaihara", "小竹向原", "Kotake-Mukaihara", "SI37", 35.7437, 139.6787),
            st("Seibu.SeibuYurakucho", "Shinsakuradai", "新桜台", "Shin-sakuradai", "SI38", 35.7407, 139.6687),
            st("Seibu.SeibuYurakucho", "Nerima", "練馬", "Nerima", "SI06", 35.7377, 139.6537),
        ],
        hopTimesMinutes: [2, 2],
        directions: [
            // Feeder for metro through services; windows approximate the
            // through-running span
            direction("Seibu.SeibuYurakucho", "Nerima", "練馬・所沢方面", "For Nerima & Tokorozawa",
                      ascending: true,
                      weekday: pattern("05:02", "24:33", [
                          ("05:02", 10), ("06:30", 5), ("09:30", 8), ("16:30", 6), ("20:00", 8), ("22:00", 10),
                      ]),
                      holiday: pattern("05:02", "24:33", [
                          ("05:02", 10), ("07:00", 8), ("10:00", 8), ("20:00", 10),
                      ])),
            direction("Seibu.SeibuYurakucho", "KotakeMukaihara", "小竹向原方面", "For Kotake-Mukaihara",
                      ascending: false,
                      weekday: pattern("04:57", "24:16", [
                          ("04:57", 10), ("06:30", 5), ("09:30", 8), ("16:30", 6), ("20:00", 8), ("22:00", 10),
                      ]),
                      holiday: pattern("04:57", "24:16", [
                          ("04:57", 10), ("07:00", 8), ("10:00", 8), ("20:00", 10),
                      ])),
        ],
        delayInfo: delayInfo,
        throughServices: [
            through("Seibu.SeibuYurakucho.KotakeMukaihara", .descending,
                    "東京メトロ有楽町線", "Tokyo Metro Yurakucho Line",
                    "有楽町・新木場方面", "for Yurakucho & Shin-Kiba",
                    to: "Railway:TokyoMetro.Yurakucho"),
            through("Seibu.SeibuYurakucho.KotakeMukaihara", .descending,
                    "東京メトロ副都心線", "Tokyo Metro Fukutoshin Line",
                    "渋谷・横浜方面", "for Shibuya & Yokohama",
                    to: "Railway:TokyoMetro.Fukutoshin"),
            through("Seibu.SeibuYurakucho.Nerima", .ascending,
                    "西武池袋線", "Seibu Ikebukuro Line",
                    "所沢・飯能方面", "for Tokorozawa & Hanno",
                    to: "Railway:Seibu.Ikebukuro"),
        ]
    )

    // MARK: - Seibu Shinjuku Line (SS)

    // First/last: ekitan + Yahoo, July 2026 (medium confidence).
    // Coordinates: ja.wikipedia per-station infoboxes, 2026-07-08.
    static let shinjuku = StaticTrainLine(
        id: "Railway:Seibu.Shinjuku",
        nameJa: "西武新宿線",
        nameEn: "Seibu Shinjuku Line",
        operatorId: "Operator:Seibu",
        colorHex: "#00A6BF",
        stations: [
            st("Seibu.Shinjuku", "SeibuShinjuku", "西武新宿", "Seibu-Shinjuku", "SS01", 35.6963, 139.7000),
            st("Seibu.Shinjuku", "Takadanobaba", "高田馬場", "Takadanobaba", "SS02", 35.7131, 139.7041),
            st("Seibu.Shinjuku", "ShimoOchiai", "下落合", "Shimo-ochiai", "SS03", 35.7158, 139.6951),
            st("Seibu.Shinjuku", "Nakai", "中井", "Nakai", "SS04", 35.7151, 139.6872),
            st("Seibu.Shinjuku", "Araiyakushimae", "新井薬師前", "Araiyakushi-mae", "SS05", 35.7158, 139.6719),
            st("Seibu.Shinjuku", "Numabukuro", "沼袋", "Numabukuro", "SS06", 35.7194, 139.6638),
            st("Seibu.Shinjuku", "Nogata", "野方", "Nogata", "SS07", 35.7197, 139.6528),
            st("Seibu.Shinjuku", "ToritsuKasei", "都立家政", "Toritsu-kasei", "SS08", 35.7223, 139.6446),
            st("Seibu.Shinjuku", "Saginomiya", "鷺ノ宮", "Saginomiya", "SS09", 35.7226, 139.6389),
            st("Seibu.Shinjuku", "ShimoIgusa", "下井草", "Shimo-igusa", "SS10", 35.7239, 139.6243),
            st("Seibu.Shinjuku", "Iogi", "井荻", "Iogi", "SS11", 35.7245, 139.6147),
            st("Seibu.Shinjuku", "KamiIgusa", "上井草", "Kami-igusa", "SS12", 35.7251, 139.6036),
            st("Seibu.Shinjuku", "KamiShakujii", "上石神井", "Kami-shakujii", "SS13", 35.7263, 139.5921),
            st("Seibu.Shinjuku", "MusashiSeki", "武蔵関", "Musashi-seki", "SS14", 35.7276, 139.5769),
            st("Seibu.Shinjuku", "HigashiFushimi", "東伏見", "Higashi-fushimi", "SS15", 35.7287, 139.5643),
            st("Seibu.Shinjuku", "SeibuYagisawa", "西武柳沢", "Seibu-yagisawa", "SS16", 35.7286, 139.5526),
            st("Seibu.Shinjuku", "Tanashi", "田無", "Tanashi", "SS17", 35.7274, 139.5393),
            st("Seibu.Shinjuku", "HanaKoganei", "花小金井", "Hana-koganei", "SS18", 35.7261, 139.5132),
            st("Seibu.Shinjuku", "Kodaira", "小平", "Kodaira", "SS19", 35.7370, 139.4883),
            st("Seibu.Shinjuku", "Kumegawa", "久米川", "Kumegawa", "SS20", 35.7500, 139.4720),
            st("Seibu.Shinjuku", "HigashiMurayama", "東村山", "Higashi-murayama", "SS21", 35.7606, 139.4658),
            st("Seibu.Shinjuku", "Tokorozawa", "所沢", "Tokorozawa", "SS22", 35.7867, 139.4733),
            st("Seibu.Shinjuku", "KokuKoen", "航空公園", "Koku-koen", "SS23", 35.7984, 139.4657),
            st("Seibu.Shinjuku", "ShinTokorozawa", "新所沢", "Shin-tokorozawa", "SS24", 35.8067, 139.4561),
            st("Seibu.Shinjuku", "Iriso", "入曽", "Iriso", "SS25", 35.8325, 139.4272),
            st("Seibu.Shinjuku", "Sayamashi", "狭山市", "Sayamashi", "SS26", 35.8569, 139.4131),
            st("Seibu.Shinjuku", "ShinSayama", "新狭山", "Shin-sayama", "SS27", 35.8741, 139.4333),
            st("Seibu.Shinjuku", "MinamiOtsuka", "南大塚", "Minami-otsuka", "SS28", 35.8898, 139.4543),
            st("Seibu.Shinjuku", "HonKawagoe", "本川越", "Hon-kawagoe", "SS29", 35.9142, 139.4814),
        ],
        hopTimesMinutes: [
            3, 2, 1, 2, 1, 2, 1, 1, 2, 1, 2, 2, 2, 2,
            1, 2, 3, 3, 2, 2, 4, 2, 2, 4, 3, 3, 3, 4,
        ],
        directions: [
            direction("Seibu.Shinjuku", "HonKawagoe", "所沢・本川越方面", "For Tokorozawa & Hon-Kawagoe",
                      ascending: true,
                      weekday: pattern("05:01", "24:17", [
                          ("05:01", 8), ("06:30", 4), ("09:30", 5), ("16:30", 5), ("20:00", 6), ("22:00", 8),
                      ]),
                      holiday: pattern("05:01", "24:17", [
                          ("05:01", 8), ("07:00", 5), ("10:00", 5), ("20:00", 8),
                      ]),
                      // 拝島行き 急行/準急 diverge onto the 拝島線 at 小平.
                      expressWeekday: shinjukuAscExpressWd,
                      expressHoliday: shinjukuAscExpressHol),
            direction("Seibu.Shinjuku", "SeibuShinjuku", "高田馬場・西武新宿方面", "For Takadanobaba & Seibu-Shinjuku",
                      ascending: false,
                      weekday: pattern("04:54", "23:31", [
                          ("04:54", 10), ("06:30", 5), ("09:30", 8), ("16:30", 6), ("20:00", 8), ("22:00", 10),
                      ]),
                      holiday: pattern("04:54", "23:31", [
                          ("04:54", 10), ("07:00", 8), ("10:00", 8), ("20:00", 10),
                      ]),
                      origins: [
                          originRuns("Station:Seibu.Shinjuku.Tanashi",
                                     shinjukuDescExpressWd_org_Tanashi, shinjukuDescExpressHol_org_Tanashi),
                          originRuns("Station:Seibu.Shinjuku.ShinTokorozawa",
                                     shinjukuDescExpressWd_org_ShinTokorozawa, shinjukuDescExpressHol_org_ShinTokorozawa),
                      ],
                      expressWeekday: shinjukuDescExpressWd,
                      expressHoliday: shinjukuDescExpressHol),
        ],
        delayInfo: delayInfo,
        throughServices: [
            through("Seibu.Shinjuku.Kodaira", .ascending,
                    "西武拝島線", "Seibu Haijima Line",
                    "拝島方面", "for Haijima"),
        ],
        // 停車駅 hand-coded from Seibu's official 停車駅案内 and cross-checked
        // against ODPT StationTimetable presence. Times/types/termini are
        // ODPT-exact; stop patterns are not ODPT-per-train verifiable.
        // Sources: https://ja.wikipedia.org/wiki/西武新宿線 (停車駅一覧),
        //          https://www.seiburailway.jp/railways/timetable/ (停車駅案内).
        // Indices are into `stations` (0=西武新宿 … 28=本川越).
        stopPatterns: [
            .express:         [0, 1, 8, 12, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28],  // 急行
            .semiExpress:     [0, 1, 8, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28], // 準急
            .commuterExpress: [0, 1, 8, 12, 16, 20, 21, 23, 25, 28],                              // 通勤急行 (千鳥停車)
            .rapidExpress:    [0, 1, 16, 20, 21, 23, 24, 25, 26, 27, 28],                         // 快速急行
        ]
    )

    // MARK: - Seibu Ikebukuro Express Runs (ODPT StationTimetable, July-2026)

    private static let ikebukuroAscExpressWd: [ExactRun] = [
        ExactRun("05:38", trainType: .semiExpress),
        ExactRun("06:04", trainType: .semiExpress),
        ExactRun("06:19", trainType: .semiExpress),
        ExactRun("06:34", trainType: .semiExpress),
        ExactRun("06:44", trainType: .semiExpress),
        ExactRun("06:52", trainType: .semiExpress),
        ExactRun("07:00", trainType: .semiExpress),
        ExactRun("07:07", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .semiExpress),
        ExactRun("07:14", trainType: .rapid),
        ExactRun("07:20", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .semiExpress),
        ExactRun("07:23", trainType: .express),
        ExactRun("07:31", terminusStationId: "Station:Seibu.Ikebukuro.Tokorozawa", trainType: .semiExpress),
        ExactRun("07:35", trainType: .express),
        ExactRun("07:37", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .rapid),
        ExactRun("07:46", trainType: .express),
        ExactRun("07:52", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .semiExpress),
        ExactRun("07:57", trainType: .express),
        ExactRun("08:01", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .semiExpress),
        ExactRun("08:06", trainType: .express),
        ExactRun("08:11", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .rapid),
        ExactRun("08:16", trainType: .express),
        ExactRun("08:21", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .semiExpress),
        ExactRun("08:26", trainType: .express),
        ExactRun("08:32", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .semiExpress),
        ExactRun("08:37", trainType: .express),
        ExactRun("08:47", trainType: .express),
        ExactRun("08:57", trainType: .express),
        ExactRun("09:04", trainType: .rapid),
        ExactRun("09:11", trainType: .semiExpress),
        ExactRun("09:20", trainType: .express),
        ExactRun("09:27", trainType: .semiExpress),
        ExactRun("09:39", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .semiExpress),
        ExactRun("09:49", trainType: .express),
        ExactRun("09:54", terminusStationId: "Station:Seibu.Ikebukuro.Tokorozawa", trainType: .semiExpress),
        ExactRun("09:59", trainType: .express),
        ExactRun("10:10", trainType: .semiExpress),
        ExactRun("10:20", trainType: .express),
        ExactRun("10:31", trainType: .semiExpress),
        ExactRun("10:39", terminusStationId: "Station:Seibu.Ikebukuro.Tokorozawa", trainType: .semiExpress),
        ExactRun("10:50", trainType: .express),
        ExactRun("11:00", trainType: .express),
        ExactRun("11:09", trainType: .semiExpress),
        ExactRun("11:20", trainType: .express),
        ExactRun("11:31", trainType: .semiExpress),
        ExactRun("11:39", terminusStationId: "Station:Seibu.Ikebukuro.Tokorozawa", trainType: .semiExpress),
        ExactRun("11:50", trainType: .express),
        ExactRun("12:00", trainType: .express),
        ExactRun("12:09", trainType: .semiExpress),
        ExactRun("12:20", trainType: .express),
        ExactRun("12:31", trainType: .semiExpress),
        ExactRun("12:39", terminusStationId: "Station:Seibu.Ikebukuro.Tokorozawa", trainType: .semiExpress),
        ExactRun("12:50", trainType: .express),
        ExactRun("13:00", trainType: .express),
        ExactRun("13:09", trainType: .semiExpress),
        ExactRun("13:20", trainType: .express),
        ExactRun("13:31", trainType: .semiExpress),
        ExactRun("13:39", terminusStationId: "Station:Seibu.Ikebukuro.Tokorozawa", trainType: .semiExpress),
        ExactRun("13:50", trainType: .express),
        ExactRun("14:00", trainType: .express),
        ExactRun("14:09", trainType: .semiExpress),
        ExactRun("14:20", trainType: .express),
        ExactRun("14:31", trainType: .semiExpress),
        ExactRun("14:39", terminusStationId: "Station:Seibu.Ikebukuro.Tokorozawa", trainType: .semiExpress),
        ExactRun("14:50", trainType: .express),
        ExactRun("15:00", trainType: .express),
        ExactRun("15:09", trainType: .semiExpress),
        ExactRun("15:20", trainType: .express),
        ExactRun("15:31", trainType: .semiExpress),
        ExactRun("15:39", trainType: .semiExpress),
        ExactRun("15:50", trainType: .express),
        ExactRun("16:01", trainType: .semiExpress),
        ExactRun("16:09", trainType: .semiExpress),
        ExactRun("16:20", trainType: .express),
        ExactRun("16:31", trainType: .semiExpress),
        ExactRun("16:39", trainType: .semiExpress),
        ExactRun("16:50", trainType: .express),
        ExactRun("16:57", terminusStationId: "Station:Seibu.Ikebukuro.Tokorozawa", trainType: .semiExpress),
        ExactRun("17:10", trainType: .express),
        ExactRun("17:20", trainType: .express),
        ExactRun("17:25", trainType: .rapid),
        ExactRun("17:33", terminusStationId: "Station:Seibu.Ikebukuro.Tokorozawa", trainType: .semiExpress),
        ExactRun("17:40", trainType: .express),
        ExactRun("17:45", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .semiExpress),
        ExactRun("17:50", trainType: .express),
        ExactRun("17:55", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .semiExpress),
        ExactRun("18:03", terminusStationId: "Station:Seibu.Ikebukuro.Tokorozawa", trainType: .semiExpress),
        ExactRun("18:10", trainType: .express),
        ExactRun("18:15", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .semiExpress),
        ExactRun("18:20", trainType: .express),
        ExactRun("18:25", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .semiExpress),
        ExactRun("18:33", terminusStationId: "Station:Seibu.Ikebukuro.Tokorozawa", trainType: .semiExpress),
        ExactRun("18:40", trainType: .express),
        ExactRun("18:45", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .semiExpress),
        ExactRun("18:50", trainType: .express),
        ExactRun("18:55", trainType: .rapid),
        ExactRun("19:03", terminusStationId: "Station:Seibu.Ikebukuro.Tokorozawa", trainType: .semiExpress),
        ExactRun("19:10", trainType: .express),
        ExactRun("19:15", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .semiExpress),
        ExactRun("19:20", trainType: .express),
        ExactRun("19:25", terminusStationId: "Station:Seibu.Ikebukuro.Tokorozawa", trainType: .semiExpress),
        ExactRun("19:33", terminusStationId: "Station:Seibu.Ikebukuro.Tokorozawa", trainType: .semiExpress),
        ExactRun("19:40", trainType: .express),
        ExactRun("19:45", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .semiExpress),
        ExactRun("19:50", trainType: .express),
        ExactRun("19:55", trainType: .rapid),
        ExactRun("20:03", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .semiExpress),
        ExactRun("20:10", trainType: .express),
        ExactRun("20:15", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .semiExpress),
        ExactRun("20:20", trainType: .express),
        ExactRun("20:25", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .semiExpress),
        ExactRun("20:33", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .semiExpress),
        ExactRun("20:40", trainType: .express),
        ExactRun("20:50", trainType: .express),
        ExactRun("20:55", trainType: .rapid),
        ExactRun("21:03", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .semiExpress),
        ExactRun("21:10", trainType: .express),
        ExactRun("21:20", trainType: .express),
        ExactRun("21:25", trainType: .rapid),
        ExactRun("21:33", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .semiExpress),
        ExactRun("21:42", trainType: .express),
        ExactRun("21:52", trainType: .express),
        ExactRun("22:02", trainType: .express),
        ExactRun("22:12", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .rapid),
        ExactRun("22:22", trainType: .express),
        ExactRun("22:32", trainType: .rapid),
        ExactRun("22:42", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .semiExpress),
        ExactRun("22:52", trainType: .express),
        ExactRun("23:02", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .semiExpress),
        ExactRun("23:12", trainType: .express),
        ExactRun("23:22", trainType: .rapid),
        ExactRun("23:39", trainType: .semiExpress),
        ExactRun("23:52", trainType: .semiExpress),
        ExactRun("24:02", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .semiExpress),
        ExactRun("24:14", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .semiExpress),
    ]
    private static let ikebukuroAscExpressHol: [ExactRun] = [
        ExactRun("05:38", trainType: .semiExpress),
        ExactRun("05:59", trainType: .semiExpress),
        ExactRun("06:14", trainType: .rapid),
        ExactRun("06:30", trainType: .semiExpress),
        ExactRun("06:45", trainType: .semiExpress),
        ExactRun("06:56", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .semiExpress),
        ExactRun("07:02", trainType: .express),
        ExactRun("07:11", trainType: .rapid),
        ExactRun("07:20", trainType: .semiExpress),
        ExactRun("07:35", trainType: .express),
        ExactRun("07:47", trainType: .express),
        ExactRun("07:54", trainType: .rapid),
        ExactRun("08:10", trainType: .semiExpress),
        ExactRun("08:20", trainType: .rapid),
        ExactRun("08:35", trainType: .express),
        ExactRun("08:40", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .semiExpress),
        ExactRun("08:50", trainType: .express),
        ExactRun("09:03", trainType: .express),
        ExactRun("09:10", terminusStationId: "Station:Seibu.Ikebukuro.Tokorozawa", trainType: .semiExpress),
        ExactRun("09:21", trainType: .express),
        ExactRun("09:32", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .semiExpress),
        ExactRun("09:40", trainType: .express),
        ExactRun("09:50", trainType: .express),
        ExactRun("10:04", trainType: .express),
        ExactRun("10:10", terminusStationId: "Station:Seibu.Ikebukuro.Tokorozawa", trainType: .semiExpress),
        ExactRun("10:22", trainType: .express),
        ExactRun("10:32", trainType: .semiExpress),
        ExactRun("10:40", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .semiExpress),
        ExactRun("10:50", trainType: .express),
        ExactRun("10:58", trainType: .rapid),
        ExactRun("11:08", trainType: .semiExpress),
        ExactRun("11:20", trainType: .express),
        ExactRun("11:31", trainType: .semiExpress),
        ExactRun("11:39", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .semiExpress),
        ExactRun("11:50", trainType: .express),
        ExactRun("12:00", trainType: .express),
        ExactRun("12:09", trainType: .semiExpress),
        ExactRun("12:20", trainType: .express),
        ExactRun("12:31", trainType: .semiExpress),
        ExactRun("12:39", terminusStationId: "Station:Seibu.Ikebukuro.Tokorozawa", trainType: .semiExpress),
        ExactRun("12:50", trainType: .express),
        ExactRun("13:00", trainType: .express),
        ExactRun("13:09", trainType: .semiExpress),
        ExactRun("13:20", trainType: .express),
        ExactRun("13:31", trainType: .semiExpress),
        ExactRun("13:39", terminusStationId: "Station:Seibu.Ikebukuro.Tokorozawa", trainType: .semiExpress),
        ExactRun("13:50", trainType: .express),
        ExactRun("14:00", trainType: .express),
        ExactRun("14:09", trainType: .semiExpress),
        ExactRun("14:20", trainType: .express),
        ExactRun("14:31", trainType: .semiExpress),
        ExactRun("14:39", trainType: .semiExpress),
        ExactRun("14:50", trainType: .express),
        ExactRun("15:02", terminusStationId: "Station:Seibu.Ikebukuro.Tokorozawa", trainType: .semiExpress),
        ExactRun("15:09", trainType: .semiExpress),
        ExactRun("15:20", trainType: .express),
        ExactRun("15:32", terminusStationId: "Station:Seibu.Ikebukuro.Tokorozawa", trainType: .rapid),
        ExactRun("15:40", trainType: .semiExpress),
        ExactRun("15:50", trainType: .express),
        ExactRun("16:02", trainType: .semiExpress),
        ExactRun("16:10", trainType: .semiExpress),
        ExactRun("16:20", trainType: .express),
        ExactRun("16:32", trainType: .rapid),
        ExactRun("16:39", trainType: .semiExpress),
        ExactRun("16:48", trainType: .express),
        ExactRun("17:02", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .rapid),
        ExactRun("17:10", trainType: .express),
        ExactRun("17:20", trainType: .express),
        ExactRun("17:25", trainType: .rapid),
        ExactRun("17:33", terminusStationId: "Station:Seibu.Ikebukuro.NishiTokorozawa", continuesBeyond: true, trainType: .rapid),
        ExactRun("17:40", trainType: .rapid),
        ExactRun("17:50", trainType: .express),
        ExactRun("17:55", terminusStationId: "Station:Seibu.Ikebukuro.Tokorozawa", trainType: .semiExpress),
        ExactRun("18:02", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .semiExpress),
        ExactRun("18:10", trainType: .express),
        ExactRun("18:20", trainType: .express),
        ExactRun("18:24", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .semiExpress),
        ExactRun("18:34", terminusStationId: "Station:Seibu.Ikebukuro.Tokorozawa", trainType: .rapid),
        ExactRun("18:40", trainType: .express),
        ExactRun("18:50", trainType: .express),
        ExactRun("18:55", terminusStationId: "Station:Seibu.Ikebukuro.Tokorozawa", trainType: .semiExpress),
        ExactRun("19:02", terminusStationId: "Station:Seibu.Ikebukuro.Tokorozawa", trainType: .semiExpress),
        ExactRun("19:10", trainType: .express),
        ExactRun("19:19", trainType: .rapid),
        ExactRun("19:24", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .semiExpress),
        ExactRun("19:32", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .rapid),
        ExactRun("19:40", trainType: .express),
        ExactRun("19:50", trainType: .express),
        ExactRun("20:02", terminusStationId: "Station:Seibu.Ikebukuro.Tokorozawa", trainType: .rapid),
        ExactRun("20:10", trainType: .express),
        ExactRun("20:20", trainType: .express),
        ExactRun("20:35", terminusStationId: "Station:Seibu.Ikebukuro.NishiTokorozawa", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("20:41", trainType: .express),
        ExactRun("20:51", trainType: .rapid),
        ExactRun("21:05", trainType: .rapid),
        ExactRun("21:10", terminusStationId: "Station:Seibu.Ikebukuro.NishiTokorozawa", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("21:20", trainType: .express),
        ExactRun("21:35", trainType: .express),
        ExactRun("21:50", trainType: .rapid),
        ExactRun("22:05", trainType: .rapid),
        ExactRun("22:20", trainType: .express),
        ExactRun("22:35", trainType: .express),
        ExactRun("22:50", trainType: .express),
        ExactRun("23:05", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .express),
        ExactRun("23:17", trainType: .rapid),
        ExactRun("23:29", trainType: .semiExpress),
        ExactRun("23:40", trainType: .semiExpress),
        ExactRun("23:50", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .rapid),
        ExactRun("24:14", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", trainType: .semiExpress),
    ]
    private static let ikebukuroAscExpressWd_org_Nerima: [ExactRun] = [
        ExactRun("08:49", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", startsHere: false, trainType: .rapidExpress),
        ExactRun("09:18", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", startsHere: false, trainType: .rapidExpress),
        ExactRun("09:47", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", startsHere: false, trainType: .rapidExpress),
        ExactRun("10:16", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", startsHere: false, trainType: .rapidExpress),
        ExactRun("10:48", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", startsHere: false, trainType: .rapidExpress),
        ExactRun("11:18", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", startsHere: false, trainType: .rapidExpress),
        ExactRun("11:48", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", startsHere: false, trainType: .rapidExpress),
        ExactRun("12:18", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", startsHere: false, trainType: .rapidExpress),
        ExactRun("12:48", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", startsHere: false, trainType: .rapidExpress),
        ExactRun("13:18", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", startsHere: false, trainType: .rapidExpress),
        ExactRun("13:48", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", startsHere: false, trainType: .rapidExpress),
        ExactRun("14:18", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", startsHere: false, trainType: .rapidExpress),
        ExactRun("14:48", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", startsHere: false, trainType: .rapidExpress),
        ExactRun("15:18", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", startsHere: false, trainType: .rapidExpress),
        ExactRun("15:48", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", startsHere: false, trainType: .rapidExpress),
        ExactRun("16:19", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", startsHere: false, trainType: .rapidExpress),
        ExactRun("16:49", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", startsHere: false, trainType: .rapidExpress),
    ]
    private static let ikebukuroAscExpressHol_org_Nerima: [ExactRun] = [
        ExactRun("09:18", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", startsHere: false, trainType: .rapidExpress),
        ExactRun("10:17", startsHere: false, trainType: .rapidExpress),
        ExactRun("10:48", startsHere: false, trainType: .rapidExpress),
        ExactRun("11:19", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", startsHere: false, trainType: .rapidExpress),
        ExactRun("11:49", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", startsHere: false, trainType: .rapidExpress),
        ExactRun("12:18", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", startsHere: false, trainType: .rapidExpress),
        ExactRun("12:49", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", startsHere: false, trainType: .rapidExpress),
        ExactRun("13:18", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", startsHere: false, trainType: .rapidExpress),
        ExactRun("13:48", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", startsHere: false, trainType: .rapidExpress),
        ExactRun("14:18", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", startsHere: false, trainType: .rapidExpress),
        ExactRun("14:48", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", startsHere: false, trainType: .rapidExpress),
        ExactRun("15:17", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", startsHere: false, trainType: .rapidExpress),
        ExactRun("15:47", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", startsHere: false, trainType: .rapidExpress),
        ExactRun("16:47", terminusStationId: "Station:Seibu.Ikebukuro.Kotesashi", startsHere: false, trainType: .rapidExpress),
    ]
    private static let ikebukuroDescExpressWd: [ExactRun] = [
        ExactRun("05:03", trainType: .rapid),
        ExactRun("05:21", trainType: .express),
        ExactRun("05:34", trainType: .rapid),
        ExactRun("05:48", trainType: .express),
        ExactRun("05:59", trainType: .rapid),
        ExactRun("06:11", trainType: .express),
        ExactRun("06:17", trainType: .express),
        ExactRun("06:26", trainType: .express),
        ExactRun("06:35", trainType: .commuterExpress),
        ExactRun("06:43", trainType: .express),
        ExactRun("06:50", trainType: .commuterExpress),
        ExactRun("06:56", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .rapid),
        ExactRun("07:00", trainType: .commuterExpress),
        ExactRun("07:04", trainType: .rapidExpress),
        ExactRun("07:09", trainType: .express),
        ExactRun("07:15", trainType: .rapid),
        ExactRun("07:20", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("07:27", trainType: .commuterExpress),
        ExactRun("07:35", trainType: .express),
        ExactRun("07:45", trainType: .commuterExpress),
        ExactRun("07:51", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("07:55", trainType: .express),
        ExactRun("08:05", trainType: .express),
        ExactRun("08:15", trainType: .rapid),
        ExactRun("08:26", trainType: .express),
        ExactRun("08:36", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("08:46", trainType: .express),
        ExactRun("08:57", trainType: .rapid),
        ExactRun("09:07", trainType: .express),
        ExactRun("09:18", trainType: .express),
        ExactRun("09:29", trainType: .rapid),
        ExactRun("09:43", trainType: .express),
        ExactRun("09:54", trainType: .semiExpress),
        ExactRun("10:14", trainType: .express),
        ExactRun("10:24", trainType: .express),
        ExactRun("10:35", trainType: .semiExpress),
        ExactRun("10:44", trainType: .express),
        ExactRun("10:54", trainType: .semiExpress),
        ExactRun("11:14", trainType: .express),
        ExactRun("11:24", trainType: .express),
        ExactRun("11:35", trainType: .semiExpress),
        ExactRun("11:44", trainType: .express),
        ExactRun("11:54", trainType: .semiExpress),
        ExactRun("12:14", trainType: .express),
        ExactRun("12:24", trainType: .express),
        ExactRun("12:35", trainType: .semiExpress),
        ExactRun("12:44", trainType: .express),
        ExactRun("12:54", trainType: .semiExpress),
        ExactRun("13:14", trainType: .express),
        ExactRun("13:24", trainType: .express),
        ExactRun("13:35", trainType: .semiExpress),
        ExactRun("13:44", trainType: .express),
        ExactRun("13:54", trainType: .semiExpress),
        ExactRun("14:14", trainType: .express),
        ExactRun("14:24", trainType: .express),
        ExactRun("14:35", trainType: .semiExpress),
        ExactRun("14:44", trainType: .express),
        ExactRun("14:54", trainType: .semiExpress),
        ExactRun("15:14", trainType: .express),
        ExactRun("15:24", trainType: .semiExpress),
        ExactRun("15:35", trainType: .semiExpress),
        ExactRun("15:44", trainType: .express),
        ExactRun("15:54", trainType: .semiExpress),
        ExactRun("16:05", trainType: .semiExpress),
        ExactRun("16:15", trainType: .express),
        ExactRun("16:26", trainType: .semiExpress),
        ExactRun("16:37", trainType: .express),
        ExactRun("16:47", trainType: .express),
        ExactRun("16:57", trainType: .rapid),
        ExactRun("17:07", trainType: .express),
        ExactRun("17:17", trainType: .express),
        ExactRun("17:27", trainType: .rapid),
        ExactRun("17:37", trainType: .express),
        ExactRun("17:47", trainType: .express),
        ExactRun("17:57", trainType: .rapid),
        ExactRun("18:07", trainType: .express),
        ExactRun("18:17", trainType: .express),
        ExactRun("18:27", trainType: .semiExpress),
        ExactRun("18:37", trainType: .express),
        ExactRun("18:47", trainType: .express),
        ExactRun("18:56", trainType: .semiExpress),
        ExactRun("19:01", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("19:11", trainType: .express),
        ExactRun("19:26", trainType: .semiExpress),
        ExactRun("19:41", trainType: .express),
        ExactRun("19:56", trainType: .rapid),
        ExactRun("20:11", trainType: .express),
        ExactRun("20:26", trainType: .semiExpress),
        ExactRun("20:41", trainType: .express),
        ExactRun("20:56", trainType: .rapid),
        ExactRun("21:01", trainType: .rapid),
        ExactRun("21:14", trainType: .rapid),
        ExactRun("21:26", trainType: .semiExpress),
        ExactRun("21:41", trainType: .express),
        ExactRun("21:56", trainType: .semiExpress),
        ExactRun("22:10", trainType: .semiExpress),
        ExactRun("22:25", trainType: .rapid),
        ExactRun("22:48", trainType: .semiExpress),
        ExactRun("23:08", trainType: .semiExpress),
    ]
    private static let ikebukuroDescExpressHol: [ExactRun] = [
        ExactRun("05:03", trainType: .rapid),
        ExactRun("05:21", trainType: .express),
        ExactRun("05:36", trainType: .express),
        ExactRun("05:51", trainType: .express),
        ExactRun("06:06", trainType: .express),
        ExactRun("06:19", trainType: .semiExpress),
        ExactRun("06:31", trainType: .express),
        ExactRun("06:40", trainType: .rapid),
        ExactRun("06:49", trainType: .semiExpress),
        ExactRun("07:01", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .rapid),
        ExactRun("07:11", trainType: .express),
        ExactRun("07:21", trainType: .rapid),
        ExactRun("07:25", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .rapid),
        ExactRun("07:36", trainType: .semiExpress),
        ExactRun("07:42", trainType: .express),
        ExactRun("07:49", trainType: .rapid),
        ExactRun("07:58", trainType: .semiExpress),
        ExactRun("08:10", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("08:12", trainType: .express),
        ExactRun("08:21", trainType: .express),
        ExactRun("08:30", trainType: .semiExpress),
        ExactRun("08:40", trainType: .express),
        ExactRun("08:50", trainType: .rapid),
        ExactRun("09:00", trainType: .semiExpress),
        ExactRun("09:10", trainType: .express),
        ExactRun("09:21", trainType: .rapid),
        ExactRun("09:29", trainType: .semiExpress),
        ExactRun("09:43", trainType: .express),
        ExactRun("09:54", trainType: .semiExpress),
        ExactRun("10:14", trainType: .express),
        ExactRun("10:24", trainType: .express),
        ExactRun("10:34", trainType: .semiExpress),
        ExactRun("10:40", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("10:43", trainType: .express),
        ExactRun("10:54", trainType: .semiExpress),
        ExactRun("11:09", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("11:14", trainType: .express),
        ExactRun("11:34", trainType: .semiExpress),
        ExactRun("11:40", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("11:44", trainType: .express),
        ExactRun("11:54", trainType: .semiExpress),
        ExactRun("12:14", trainType: .express),
        ExactRun("12:24", trainType: .express),
        ExactRun("12:35", trainType: .semiExpress),
        ExactRun("12:44", trainType: .express),
        ExactRun("12:54", trainType: .semiExpress),
        ExactRun("13:14", trainType: .express),
        ExactRun("13:24", trainType: .express),
        ExactRun("13:35", trainType: .semiExpress),
        ExactRun("13:44", trainType: .express),
        ExactRun("13:54", trainType: .semiExpress),
        ExactRun("14:14", trainType: .express),
        ExactRun("14:24", trainType: .semiExpress),
        ExactRun("14:35", trainType: .semiExpress),
        ExactRun("14:44", trainType: .express),
        ExactRun("14:54", trainType: .semiExpress),
        ExactRun("15:14", trainType: .express),
        ExactRun("15:23", trainType: .semiExpress),
        ExactRun("15:44", trainType: .express),
        ExactRun("15:54", trainType: .semiExpress),
        ExactRun("16:14", trainType: .express),
        ExactRun("16:23", trainType: .semiExpress),
        ExactRun("16:43", trainType: .express),
        ExactRun("16:53", trainType: .semiExpress),
        ExactRun("17:01", trainType: .express),
        ExactRun("17:15", trainType: .express),
        ExactRun("17:22", trainType: .express),
        ExactRun("17:35", trainType: .semiExpress),
        ExactRun("17:42", trainType: .express),
        ExactRun("17:55", trainType: .semiExpress),
        ExactRun("18:00", trainType: .express),
        ExactRun("18:14", trainType: .express),
        ExactRun("18:28", trainType: .rapid),
        ExactRun("18:38", trainType: .semiExpress),
        ExactRun("18:45", trainType: .express),
        ExactRun("18:55", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .rapid),
        ExactRun("19:09", trainType: .express),
        ExactRun("19:26", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("19:42", trainType: .express),
        ExactRun("19:56", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("20:12", trainType: .express),
        ExactRun("20:43", trainType: .express),
        ExactRun("20:56", trainType: .semiExpress),
        ExactRun("21:11", trainType: .rapid),
        ExactRun("21:26", trainType: .rapid),
        ExactRun("21:41", trainType: .express),
        ExactRun("21:55", trainType: .semiExpress),
        ExactRun("22:10", trainType: .express),
        ExactRun("22:30", trainType: .semiExpress),
        ExactRun("22:50", trainType: .rapid),
        ExactRun("23:05", trainType: .semiExpress),
    ]
    private static let ikebukuroDescExpressWd_org_ShakujiiKoen: [ExactRun] = [
        ExactRun("21:56", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .semiExpress),
    ]
    private static let ikebukuroDescExpressWd_org_Kiyose: [ExactRun] = [
        ExactRun("09:39", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .semiExpress),
    ]
    private static let ikebukuroDescExpressHol_org_Kiyose: [ExactRun] = [
        ExactRun("19:52", trainType: .semiExpress),
        ExactRun("20:51", trainType: .semiExpress),
    ]
    private static let ikebukuroDescExpressWd_org_Tokorozawa: [ExactRun] = [
        ExactRun("10:52", trainType: .semiExpress),
        ExactRun("11:52", trainType: .semiExpress),
        ExactRun("12:52", trainType: .semiExpress),
        ExactRun("13:52", trainType: .semiExpress),
        ExactRun("14:52", trainType: .semiExpress),
        ExactRun("15:43", trainType: .semiExpress),
        ExactRun("17:58", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("18:07", trainType: .semiExpress),
        ExactRun("18:44", trainType: .semiExpress),
        ExactRun("19:14", trainType: .semiExpress),
        ExactRun("19:39", trainType: .semiExpress),
        ExactRun("20:14", trainType: .semiExpress),
        ExactRun("20:39", trainType: .semiExpress),
    ]
    private static let ikebukuroDescExpressHol_org_Tokorozawa: [ExactRun] = [
        ExactRun("06:19", trainType: .semiExpress),
        ExactRun("09:10", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("11:52", trainType: .semiExpress),
        ExactRun("13:52", trainType: .semiExpress),
        ExactRun("14:43", trainType: .semiExpress),
        ExactRun("16:14", trainType: .semiExpress),
        ExactRun("17:25", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("19:12", trainType: .semiExpress),
        ExactRun("19:40", trainType: .rapid),
        ExactRun("20:11", trainType: .rapid),
    ]
    private static let ikebukuroDescExpressWd_org_Kotesashi: [ExactRun] = [
        ExactRun("04:53", trainType: .semiExpress),
        ExactRun("06:11", trainType: .semiExpress),
        ExactRun("06:24", trainType: .semiExpress),
        ExactRun("06:28", trainType: .semiExpress),
        ExactRun("06:43", trainType: .semiExpress),
        ExactRun("06:51", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("06:58", trainType: .semiExpress),
        ExactRun("07:06", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .rapid),
        ExactRun("07:08", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("07:13", trainType: .semiExpress),
        ExactRun("07:21", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("07:26", trainType: .semiExpress),
        ExactRun("07:33", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("07:44", trainType: .commuterSemiExpress),
        ExactRun("07:50", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .rapid),
        ExactRun("07:57", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("08:01", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("08:20", trainType: .semiExpress),
        ExactRun("08:41", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("08:49", trainType: .semiExpress),
        ExactRun("09:02", trainType: .semiExpress),
        ExactRun("09:40", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("09:57", trainType: .semiExpress),
        ExactRun("10:24", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("10:54", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("11:24", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("11:54", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("12:24", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("12:54", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("13:24", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("13:54", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("14:24", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("14:54", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("15:24", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("15:54", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("16:24", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("16:37", trainType: .rapid),
        ExactRun("16:52", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("17:00", trainType: .semiExpress),
        ExactRun("17:08", trainType: .semiExpress),
        ExactRun("17:22", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("17:30", trainType: .semiExpress),
        ExactRun("17:38", trainType: .semiExpress),
        ExactRun("18:08", trainType: .semiExpress),
        ExactRun("18:20", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("18:30", trainType: .semiExpress),
        ExactRun("19:00", trainType: .semiExpress),
        ExactRun("19:39", trainType: .rapid),
        ExactRun("19:53", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("20:03", trainType: .semiExpress),
        ExactRun("20:39", trainType: .rapid),
        ExactRun("21:08", trainType: .semiExpress),
        ExactRun("22:04", trainType: .semiExpress),
        ExactRun("22:54", trainType: .semiExpress),
        ExactRun("23:15", trainType: .semiExpress),
    ]
    private static let ikebukuroDescExpressHol_org_Kotesashi: [ExactRun] = [
        ExactRun("04:53", trainType: .semiExpress),
        ExactRun("05:58", trainType: .semiExpress),
        ExactRun("06:28", trainType: .rapid),
        ExactRun("06:45", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("07:24", trainType: .semiExpress),
        ExactRun("08:52", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("09:22", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("09:54", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("09:58", trainType: .semiExpress),
        ExactRun("10:24", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("10:37", trainType: .semiExpress),
        ExactRun("11:42", trainType: .express),
        ExactRun("12:24", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("12:45", trainType: .semiExpress),
        ExactRun("12:54", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("13:24", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("13:54", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("14:24", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("14:54", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("15:24", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("15:37", trainType: .semiExpress),
        ExactRun("15:54", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("16:24", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("16:54", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("17:54", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("18:19", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("18:28", trainType: .semiExpress),
        ExactRun("18:35", trainType: .semiExpress),
        ExactRun("20:33", trainType: .rapid),
        ExactRun("20:44", terminusStationId: "Station:Seibu.Ikebukuro.Nerima", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("22:33", trainType: .semiExpress),
    ]


    // MARK: - Seibu Shinjuku Express Runs (ODPT StationTimetable, July-2026)

    private static let shinjukuAscExpressWd: [ExactRun] = [
        ExactRun("05:46", trainType: .semiExpress),
        ExactRun("06:02", trainType: .express),
        ExactRun("06:13", trainType: .express),
        ExactRun("06:24", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("06:32", trainType: .express),
        ExactRun("06:42", trainType: .express),
        ExactRun("06:51", trainType: .express),
        ExactRun("07:00", trainType: .semiExpress),
        ExactRun("07:08", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("07:15", trainType: .semiExpress),
        ExactRun("07:22", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("07:29", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .semiExpress),
        ExactRun("07:37", trainType: .semiExpress),
        ExactRun("07:45", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("07:48", trainType: .express),
        ExactRun("07:53", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("07:57", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .semiExpress),
        ExactRun("08:02", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("08:05", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("08:10", trainType: .express),
        ExactRun("08:12", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("08:17", trainType: .express),
        ExactRun("08:20", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("08:25", trainType: .express),
        ExactRun("08:27", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .semiExpress),
        ExactRun("08:32", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("08:37", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .semiExpress),
        ExactRun("08:42", terminusStationId: "Station:Seibu.Shinjuku.Tanashi", trainType: .semiExpress),
        ExactRun("08:47", trainType: .express),
        ExactRun("08:54", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("09:01", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .express),
        ExactRun("09:03", trainType: .semiExpress),
        ExactRun("09:10", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("09:16", trainType: .express),
        ExactRun("09:24", trainType: .semiExpress),
        ExactRun("09:31", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .express),
        ExactRun("09:41", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("09:46", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .express),
        ExactRun("09:51", trainType: .express),
        ExactRun("10:01", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("10:11", trainType: .express),
        ExactRun("10:21", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("10:31", trainType: .express),
        ExactRun("10:41", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("10:51", trainType: .express),
        ExactRun("11:01", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("11:11", trainType: .express),
        ExactRun("11:21", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("11:31", trainType: .express),
        ExactRun("11:41", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("11:51", trainType: .express),
        ExactRun("12:01", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("12:11", trainType: .express),
        ExactRun("12:21", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("12:31", trainType: .express),
        ExactRun("12:41", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("12:51", trainType: .express),
        ExactRun("13:01", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("13:11", trainType: .express),
        ExactRun("13:21", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("13:31", trainType: .express),
        ExactRun("13:41", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("13:51", trainType: .express),
        ExactRun("14:01", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("14:11", trainType: .express),
        ExactRun("14:21", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("14:31", trainType: .express),
        ExactRun("14:41", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("14:51", trainType: .express),
        ExactRun("15:01", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("15:11", trainType: .express),
        ExactRun("15:21", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("15:31", trainType: .express),
        ExactRun("15:41", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("15:51", trainType: .express),
        ExactRun("16:01", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("16:11", trainType: .express),
        ExactRun("16:21", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("16:31", trainType: .express),
        ExactRun("16:37", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("16:44", trainType: .express),
        ExactRun("16:51", trainType: .express),
        ExactRun("16:58", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("17:05", trainType: .express),
        ExactRun("17:12", trainType: .express),
        ExactRun("17:20", trainType: .express),
        ExactRun("17:28", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .semiExpress),
        ExactRun("17:35", trainType: .express),
        ExactRun("17:42", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("17:50", trainType: .express),
        ExactRun("17:56", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("18:03", trainType: .express),
        ExactRun("18:08", trainType: .semiExpress),
        ExactRun("18:13", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .semiExpress),
        ExactRun("18:22", trainType: .express),
        ExactRun("18:27", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("18:32", trainType: .express),
        ExactRun("18:38", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("18:44", trainType: .express),
        ExactRun("18:51", trainType: .express),
        ExactRun("18:56", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("19:04", trainType: .express),
        ExactRun("19:11", trainType: .express),
        ExactRun("19:20", trainType: .express),
        ExactRun("19:26", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("19:35", trainType: .express),
        ExactRun("19:41", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("19:49", trainType: .express),
        ExactRun("19:57", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("20:05", trainType: .express),
        ExactRun("20:11", trainType: .express),
        ExactRun("20:19", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .express),
        ExactRun("20:27", trainType: .semiExpress),
        ExactRun("20:35", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("20:41", trainType: .express),
        ExactRun("20:49", trainType: .express),
        ExactRun("20:57", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("21:04", trainType: .express),
        ExactRun("21:11", trainType: .express),
        ExactRun("21:20", trainType: .express),
        ExactRun("21:27", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("21:36", trainType: .express),
        ExactRun("21:44", trainType: .express),
        ExactRun("21:52", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("22:03", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("22:12", trainType: .express),
        ExactRun("22:24", trainType: .express),
        ExactRun("22:35", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("22:44", trainType: .express),
        ExactRun("22:54", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("23:07", trainType: .express),
        ExactRun("23:19", trainType: .semiExpress),
        ExactRun("23:32", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .semiExpress),
        ExactRun("23:42", trainType: .semiExpress),
        ExactRun("23:59", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .semiExpress),
        ExactRun("24:14", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .semiExpress),
    ]
    private static let shinjukuAscExpressHol: [ExactRun] = [
        ExactRun("05:45", trainType: .semiExpress),
        ExactRun("06:00", trainType: .express),
        ExactRun("06:16", trainType: .express),
        ExactRun("06:30", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("06:40", trainType: .express),
        ExactRun("06:50", trainType: .express),
        ExactRun("07:00", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("07:10", trainType: .express),
        ExactRun("07:20", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("07:31", trainType: .express),
        ExactRun("07:40", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("07:50", trainType: .express),
        ExactRun("07:54", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("08:01", trainType: .express),
        ExactRun("08:09", trainType: .express),
        ExactRun("08:19", trainType: .semiExpress),
        ExactRun("08:26", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("08:33", trainType: .express),
        ExactRun("08:40", trainType: .express),
        ExactRun("08:49", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .express),
        ExactRun("08:58", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("09:00", trainType: .rapidExpress),
        ExactRun("09:09", trainType: .express),
        ExactRun("09:20", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("09:27", trainType: .express),
        ExactRun("09:38", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("09:43", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .semiExpress),
        ExactRun("09:49", trainType: .express),
        ExactRun("09:56", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("10:04", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("10:10", trainType: .express),
        ExactRun("10:16", trainType: .semiExpress),
        ExactRun("10:21", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("10:31", trainType: .express),
        ExactRun("10:41", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("10:51", trainType: .express),
        ExactRun("11:01", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("11:11", trainType: .express),
        ExactRun("11:21", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("11:31", trainType: .express),
        ExactRun("11:41", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("11:51", trainType: .express),
        ExactRun("12:01", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("12:11", trainType: .express),
        ExactRun("12:21", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("12:31", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .express),
        ExactRun("12:41", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("12:51", trainType: .express),
        ExactRun("13:01", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("13:11", trainType: .express),
        ExactRun("13:21", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("13:31", trainType: .express),
        ExactRun("13:41", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("13:51", trainType: .express),
        ExactRun("14:01", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("14:11", trainType: .express),
        ExactRun("14:21", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("14:31", trainType: .express),
        ExactRun("14:41", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("14:51", trainType: .express),
        ExactRun("15:01", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("15:11", trainType: .express),
        ExactRun("15:21", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("15:31", trainType: .express),
        ExactRun("15:41", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("15:51", trainType: .express),
        ExactRun("16:01", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("16:11", trainType: .express),
        ExactRun("16:21", trainType: .express),
        ExactRun("16:31", trainType: .express),
        ExactRun("16:41", trainType: .express),
        ExactRun("16:51", trainType: .express),
        ExactRun("17:02", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("17:10", trainType: .express),
        ExactRun("17:19", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("17:25", trainType: .semiExpress),
        ExactRun("17:32", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("17:41", trainType: .express),
        ExactRun("17:49", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("17:54", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("18:02", trainType: .express),
        ExactRun("18:10", trainType: .express),
        ExactRun("18:19", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("18:24", trainType: .semiExpress),
        ExactRun("18:32", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("18:41", trainType: .express),
        ExactRun("18:49", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("18:54", trainType: .semiExpress),
        ExactRun("19:02", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("19:10", trainType: .express),
        ExactRun("19:19", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .express),
        ExactRun("19:24", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .semiExpress),
        ExactRun("19:32", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("19:40", trainType: .express),
        ExactRun("19:48", trainType: .express),
        ExactRun("19:57", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("20:02", trainType: .semiExpress),
        ExactRun("20:12", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .express),
        ExactRun("20:21", trainType: .express),
        ExactRun("20:31", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .express),
        ExactRun("20:41", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("20:51", trainType: .express),
        ExactRun("21:01", terminusStationId: "Station:Seibu.Shinjuku.Tanashi", trainType: .express),
        ExactRun("21:11", trainType: .express),
        ExactRun("21:21", trainType: .express),
        ExactRun("21:31", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .express),
        ExactRun("21:41", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("21:51", trainType: .express),
        ExactRun("22:01", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("22:11", trainType: .express),
        ExactRun("22:21", trainType: .express),
        ExactRun("22:31", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .express),
        ExactRun("22:41", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("22:51", trainType: .express),
        ExactRun("23:01", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .semiExpress),
        ExactRun("23:11", trainType: .semiExpress),
        ExactRun("23:21", terminusStationId: "Station:Seibu.Shinjuku.Kodaira", continuesBeyond: true, trainType: .express),
        ExactRun("23:31", trainType: .semiExpress),
        ExactRun("23:43", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .semiExpress),
        ExactRun("23:58", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .semiExpress),
        ExactRun("24:14", terminusStationId: "Station:Seibu.Shinjuku.ShinTokorozawa", trainType: .semiExpress),
    ]
    private static let shinjukuDescExpressWd: [ExactRun] = [
        ExactRun("04:54", trainType: .semiExpress),
        ExactRun("05:12", trainType: .express),
        ExactRun("05:31", trainType: .express),
        ExactRun("05:46", trainType: .express),
        ExactRun("06:01", trainType: .express),
        ExactRun("06:16", trainType: .express),
        ExactRun("06:24", trainType: .semiExpress),
        ExactRun("06:34", trainType: .semiExpress),
        ExactRun("06:42", trainType: .express),
        ExactRun("06:49", trainType: .express),
        ExactRun("07:04", trainType: .commuterExpress),
        ExactRun("07:06", trainType: .express),
        ExactRun("07:15", trainType: .semiExpress),
        ExactRun("07:27", trainType: .express),
        ExactRun("07:37", trainType: .semiExpress),
        ExactRun("07:48", trainType: .express),
        ExactRun("08:07", trainType: .express),
        ExactRun("08:27", trainType: .semiExpress),
        ExactRun("08:47", trainType: .express),
        ExactRun("08:57", trainType: .express),
        ExactRun("09:17", trainType: .express),
        ExactRun("09:27", trainType: .express),
        ExactRun("09:37", trainType: .express),
        ExactRun("09:57", trainType: .express),
        ExactRun("10:17", trainType: .express),
        ExactRun("10:37", trainType: .express),
        ExactRun("10:57", trainType: .express),
        ExactRun("11:17", trainType: .express),
        ExactRun("11:37", trainType: .express),
        ExactRun("11:57", trainType: .express),
        ExactRun("12:17", trainType: .express),
        ExactRun("12:37", trainType: .express),
        ExactRun("12:57", trainType: .express),
        ExactRun("13:17", trainType: .express),
        ExactRun("13:37", trainType: .express),
        ExactRun("13:57", trainType: .express),
        ExactRun("14:17", trainType: .express),
        ExactRun("14:37", trainType: .express),
        ExactRun("14:57", trainType: .express),
        ExactRun("15:17", trainType: .express),
        ExactRun("15:37", trainType: .express),
        ExactRun("15:57", trainType: .express),
        ExactRun("16:17", trainType: .express),
        ExactRun("16:38", trainType: .express),
        ExactRun("16:58", trainType: .express),
        ExactRun("17:20", trainType: .express),
        ExactRun("17:42", trainType: .express),
        ExactRun("17:53", trainType: .semiExpress),
        ExactRun("18:02", trainType: .semiExpress),
        ExactRun("18:12", trainType: .express),
        ExactRun("18:22", trainType: .express),
        ExactRun("18:32", trainType: .express),
        ExactRun("18:42", trainType: .express),
        ExactRun("19:02", trainType: .express),
        ExactRun("19:12", trainType: .express),
        ExactRun("19:22", trainType: .express),
        ExactRun("19:32", trainType: .express),
        ExactRun("19:42", trainType: .express),
        ExactRun("19:52", trainType: .semiExpress),
        ExactRun("20:02", trainType: .semiExpress),
        ExactRun("20:12", trainType: .express),
        ExactRun("20:22", trainType: .express),
        ExactRun("20:32", trainType: .semiExpress),
        ExactRun("20:42", trainType: .semiExpress),
        ExactRun("21:02", trainType: .express),
        ExactRun("21:12", trainType: .express),
        ExactRun("21:22", trainType: .express),
        ExactRun("21:42", trainType: .express),
        ExactRun("21:52", trainType: .express),
        ExactRun("22:07", trainType: .express),
        ExactRun("22:19", trainType: .semiExpress),
        ExactRun("22:32", trainType: .semiExpress),
        ExactRun("22:47", trainType: .semiExpress),
        ExactRun("23:04", trainType: .semiExpress),
    ]
    private static let shinjukuDescExpressHol: [ExactRun] = [
        ExactRun("04:54", trainType: .semiExpress),
        ExactRun("05:12", trainType: .express),
        ExactRun("05:34", trainType: .express),
        ExactRun("05:54", trainType: .express),
        ExactRun("06:07", trainType: .express),
        ExactRun("06:23", trainType: .express),
        ExactRun("06:35", trainType: .express),
        ExactRun("06:51", trainType: .express),
        ExactRun("06:59", trainType: .express),
        ExactRun("07:10", trainType: .express),
        ExactRun("07:19", trainType: .express),
        ExactRun("07:40", trainType: .express),
        ExactRun("07:49", trainType: .express),
        ExactRun("07:59", trainType: .express),
        ExactRun("08:10", trainType: .express),
        ExactRun("08:23", trainType: .express),
        ExactRun("08:39", trainType: .express),
        ExactRun("08:49", trainType: .express),
        ExactRun("09:02", trainType: .express),
        ExactRun("09:12", trainType: .express),
        ExactRun("09:20", trainType: .express),
        ExactRun("09:32", trainType: .express),
        ExactRun("09:39", trainType: .express),
        ExactRun("09:50", trainType: .express),
        ExactRun("10:09", trainType: .express),
        ExactRun("10:17", trainType: .express),
        ExactRun("10:37", trainType: .express),
        ExactRun("10:57", trainType: .express),
        ExactRun("11:17", trainType: .express),
        ExactRun("11:37", trainType: .express),
        ExactRun("11:57", trainType: .express),
        ExactRun("12:17", trainType: .express),
        ExactRun("12:37", trainType: .express),
        ExactRun("12:57", trainType: .express),
        ExactRun("13:17", trainType: .express),
        ExactRun("13:37", trainType: .express),
        ExactRun("13:57", trainType: .express),
        ExactRun("14:17", trainType: .express),
        ExactRun("14:37", trainType: .express),
        ExactRun("14:57", trainType: .express),
        ExactRun("15:17", trainType: .express),
        ExactRun("15:37", trainType: .express),
        ExactRun("15:57", trainType: .express),
        ExactRun("16:07", trainType: .express),
        ExactRun("16:17", trainType: .semiExpress),
        ExactRun("16:37", trainType: .express),
        ExactRun("16:57", trainType: .express),
        ExactRun("17:07", trainType: .express),
        ExactRun("17:17", trainType: .semiExpress),
        ExactRun("17:27", trainType: .express),
        ExactRun("17:37", trainType: .express),
        ExactRun("17:46", trainType: .semiExpress),
        ExactRun("17:56", trainType: .express),
        ExactRun("18:18", trainType: .express),
        ExactRun("18:40", trainType: .express),
        ExactRun("18:48", trainType: .semiExpress),
        ExactRun("19:02", trainType: .express),
        ExactRun("19:19", trainType: .express),
        ExactRun("19:32", trainType: .express),
        ExactRun("19:49", trainType: .express),
        ExactRun("20:02", trainType: .express),
        ExactRun("20:18", trainType: .express),
        ExactRun("20:48", trainType: .express),
        ExactRun("21:04", trainType: .semiExpress),
        ExactRun("21:18", trainType: .express),
        ExactRun("21:33", trainType: .semiExpress),
        ExactRun("22:03", trainType: .semiExpress),
        ExactRun("22:18", trainType: .express),
        ExactRun("22:33", trainType: .semiExpress),
        ExactRun("22:48", trainType: .semiExpress),
        ExactRun("23:03", trainType: .semiExpress),
    ]
    private static let shinjukuDescExpressWd_org_Tanashi: [ExactRun] = [
        ExactRun("07:36", trainType: .semiExpress),
        ExactRun("18:13", trainType: .express),
        ExactRun("22:44", trainType: .semiExpress),
    ]
    private static let shinjukuDescExpressHol_org_Tanashi: [ExactRun] = [
        ExactRun("19:24", trainType: .express),
    ]
    private static let shinjukuDescExpressWd_org_ShinTokorozawa: [ExactRun] = [
        ExactRun("04:55", trainType: .semiExpress),
        ExactRun("05:40", trainType: .express),
        ExactRun("06:24", trainType: .express),
        ExactRun("07:28", trainType: .semiExpress),
        ExactRun("07:59", trainType: .semiExpress),
        ExactRun("08:22", trainType: .express),
        ExactRun("15:58", trainType: .semiExpress),
        ExactRun("16:38", trainType: .express),
        ExactRun("17:44", trainType: .semiExpress),
        ExactRun("19:25", trainType: .semiExpress),
    ]
    private static let shinjukuDescExpressHol_org_ShinTokorozawa: [ExactRun] = [
        ExactRun("04:55", trainType: .semiExpress),
        ExactRun("05:40", trainType: .express),
        ExactRun("20:27", trainType: .express),
        ExactRun("20:58", trainType: .express),
        ExactRun("22:05", trainType: .express),
        ExactRun("22:42", trainType: .express),
    ]
}
