import Foundation

// MARK: - Tokyu Line Data

private func st(_ path: String, _ suffix: String, _ ja: String, _ en: String,
                _ code: String, _ lat: Double, _ lon: Double) -> Station {
    Station(
        id: "Station:\(path).\(suffix)",
        name: ja, nameEn: en, stationCode: code,
        latitude: lat, longitude: lon
    )
}

private func pattern(_ first: String, _ last: String, _ bands: [(String, Double)]) -> ServicePattern {
    ServicePattern(
        first: first, last: last,
        bands: bands.map { HeadwayBand(from: $0.0, headwayMinutes: $0.1) }
    )
}

private func direction(_ path: String, _ suffix: String, _ ja: String, _ en: String,
                       ascending: Bool,
                       weekday: ServicePattern, holiday: ServicePattern,
                       expressWeekday: [ExactRun] = [],
                       expressHoliday: [ExactRun] = []) -> StaticLineDirection {
    StaticLineDirection(
        id: "static.RailDirection:\(path).\(suffix)",
        nameJa: ja, nameEn: en,
        isAscending: ascending,
        weekday: weekday, saturdayHoliday: holiday,
        expressWeekdayRuns: expressWeekday,
        expressSaturdayHolidayRuns: expressHoliday
    )
}

private func through(_ junction: String, _ end: ThroughService.LineEnd,
                     _ lineJa: String, _ lineEn: String,
                     _ towardJa: String, _ towardEn: String,
                     to connectingLineId: String? = nil) -> ThroughService {
    ThroughService(
        junctionStationId: "Station:\(junction)",
        end: end,
        lineNameJa: lineJa, lineNameEn: lineEn,
        towardJa: towardJa, towardEn: towardEn,
        connectingLineId: connectingLineId
    )
}

enum TokyuLineData {

    // MARK: Delay Check

    // Delays of 15+ minutes are posted on the Tokyu Train Operation Information page
    static let delayInfo = DelayCheckInfo(
        statusPageURL: "https://www.tokyu.co.jp/unten2/unten.html",
        statusPageURLEn: "https://www.tokyu.co.jp/global/",
        xAccount: "@tokyu_official",
        checkMethodJa: "東急電鉄「運行情報」ページ、東急線アプリ、またはX（@tokyu_official）で確認できます。15分以上の遅れ・運転見合わせが発生または見込まれる場合に掲載されます。",
        checkMethodEn: "Check the Tokyu train operation information page, the Tokyu Lines app, or X (@tokyu_official). Delays or suspensions of 15 minutes or more are posted."
    )

    static let lines: [StaticTrainLine] = [
        toyoko, denentoshi, meguro,
    ]

    // MARK: - Tokyu Toyoko Line (TY)

    static let toyoko = StaticTrainLine(
        id: "Railway:Tokyu.Toyoko",
        nameJa: "東急東横線",
        nameEn: "Tokyu Toyoko Line",
        operatorId: "Operator:Tokyu",
        colorHex: "#DA0442",
        stations: [
            st("Tokyu.Toyoko", "Shibuya", "渋谷", "Shibuya", "TY01", 35.6580, 139.7016),
            st("Tokyu.Toyoko", "Daikanyama", "代官山", "Daikanyama", "TY02", 35.6485, 139.7030),
            st("Tokyu.Toyoko", "Nakameguro", "中目黒", "Nakameguro", "TY03", 35.6440, 139.6990),
            st("Tokyu.Toyoko", "Yutenji", "祐天寺", "Yutenji", "TY04", 35.6404, 139.6934),
            st("Tokyu.Toyoko", "GakugeiDaigaku", "学芸大学", "Gakugei-daigaku", "TY05", 35.6280, 139.6855),
            st("Tokyu.Toyoko", "ToritsuDaigaku", "都立大学", "Toritsu-daigaku", "TY06", 35.6237, 139.6852),
            st("Tokyu.Toyoko", "Jiyugaoka", "自由が丘", "Jiyugaoka", "TY07", 35.6076, 139.6690),
            st("Tokyu.Toyoko", "DenenChofu", "田園調布", "Den-en-chofu", "TY08", 35.5990, 139.6660),
            st("Tokyu.Toyoko", "Tamagawa", "多摩川", "Tamagawa", "TY09", 35.5920, 139.6660),
            st("Tokyu.Toyoko", "ShinMaruko", "新丸子", "Shin-maruko", "TY10", 35.5810, 139.6595),
            st("Tokyu.Toyoko", "MusashiKosugi", "武蔵小杉", "Musashi-Kosugi", "TY11", 35.5766, 139.6597),
            st("Tokyu.Toyoko", "Motosumiyoshi", "元住吉", "Motosumiyoshi", "TY12", 35.5680, 139.6510),
            st("Tokyu.Toyoko", "Hiyoshi", "日吉", "Hiyoshi", "TY13", 35.5540, 139.6470),
            st("Tokyu.Toyoko", "Tsunashima", "綱島", "Tsunashima", "TY14", 35.5350, 139.6330),
            st("Tokyu.Toyoko", "Okurayama", "大倉山", "Okurayama", "TY15", 35.5240, 139.6300),
            st("Tokyu.Toyoko", "Kikuna", "菊名", "Kikuna", "TY16", 35.5093, 139.6303),
            st("Tokyu.Toyoko", "Myorenji", "妙蓮寺", "Myorenji", "TY17", 35.5020, 139.6260),
            st("Tokyu.Toyoko", "Hakuraku", "白楽", "Hakuraku", "TY18", 35.4930, 139.6250),
            st("Tokyu.Toyoko", "HigashiHakuraku", "東白楽", "Higashi-hakuraku", "TY19", 35.4870, 139.6250),
            st("Tokyu.Toyoko", "Tammachi", "反町", "Tammachi", "TY20", 35.4770, 139.6260),
            st("Tokyu.Toyoko", "Yokohama", "横浜", "Yokohama", "TY21", 35.4657, 139.6224),
        ],
        hopTimesMinutes: [
            2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        ],
        directions: [
            direction("Tokyu.Toyoko", "Yokohama", "横浜・元町・中華街方面", "For Yokohama & Motomachi-Chukagai",
                      ascending: true,
                      weekday: pattern("05:00", "24:21", [
                          ("05:00", 7), ("06:30", 4), ("09:30", 5), ("16:30", 4), ("20:00", 5), ("22:00", 7),
                      ]),
                      holiday: pattern("05:00", "24:21", [
                          ("05:00", 7), ("07:00", 5), ("10:00", 5), ("20:00", 7),
                      ]),
                      expressWeekday: toyokoAscExpressWd,
                      expressHoliday: toyokoAscExpressHol),
            direction("Tokyu.Toyoko", "Shibuya", "渋谷・和光市方面", "For Shibuya & Wakoshi",
                      ascending: false,
                      weekday: pattern("05:00", "24:12", [
                          ("05:00", 7), ("06:30", 4), ("09:30", 5), ("16:30", 4), ("20:00", 5), ("22:00", 7),
                      ]),
                      holiday: pattern("05:00", "24:12", [
                          ("05:00", 7), ("07:00", 5), ("10:00", 5), ("20:00", 7),
                      ]),
                      expressWeekday: toyokoDescExpressWd,
                      expressHoliday: toyokoDescExpressHol),
        ],
        delayInfo: delayInfo,
        throughServices: [
            through("Tokyu.Toyoko.Shibuya", .descending,
                    "東京メトロ副都心線", "Tokyo Metro Fukutoshin Line",
                    "池袋・和光市方面", "for Ikebukuro & Wakoshi",
                    to: "Railway:TokyoMetro.Fukutoshin"),
            through("Tokyu.Toyoko.Yokohama", .ascending,
                    "みなとみらい線", "Minatomirai Line",
                    "元町・中華街方面", "for Motomachi-Chukagai",
                    to: "Railway:Minatomirai.Minatomirai"),
        ],
        // 停車駅 from official table (absolute indices). 特急=limitedExpress
        // (+F-Liner, same 停車駅), 通勤特急=commuterLimitedExpress (特急+日吉), 急行=express.
        // Source: https://www.tokyo-train-master.com/ty-toyoko
        stopPatterns: [
            .limitedExpress:         [0, 2, 6, 10, 15, 20],       // 特急
            .commuterLimitedExpress: [0, 2, 6, 10, 12, 15, 20],   // 通勤特急
            .express:                [0, 2, 4, 6, 7, 8, 10, 12, 13, 15, 20], // 急行
        ]
    )

    // MARK: - Tokyu Den-en-toshi Line (DT)

    static let denentoshi = StaticTrainLine(
        id: "Railway:Tokyu.DenEnToshi",
        nameJa: "東急田園都市線",
        nameEn: "Tokyu Den-en-toshi Line",
        operatorId: "Operator:Tokyu",
        colorHex: "#20A288",
        stations: [
            st("Tokyu.DenEnToshi", "Shibuya", "渋谷", "Shibuya", "DT01", 35.6580, 139.7016),
            st("Tokyu.DenEnToshi", "IkejiriOhashi", "池尻大橋", "Ikejiri-ohashi", "DT02", 35.6500, 139.6870),
            st("Tokyu.DenEnToshi", "Sangenjaya", "三軒茶屋", "Sangen-jaya", "DT03", 35.6435, 139.6706),
            st("Tokyu.DenEnToshi", "KomazawaDaigaku", "駒沢大学", "Komazawa-daigaku", "DT04", 35.6270, 139.6620),
            st("Tokyu.DenEnToshi", "SakuraShimmachi", "桜新町", "Sakura-shimmachi", "DT05", 35.6280, 139.6470),
            st("Tokyu.DenEnToshi", "Yoga", "用賀", "Yoga", "DT06", 35.6260, 139.6330),
            st("Tokyu.DenEnToshi", "FutakoTamagawa", "二子玉川", "Futako-tamagawa", "DT07", 35.6120, 139.6265),
            st("Tokyu.DenEnToshi", "FutakoShinchi", "二子新地", "Futako-shinchi", "DT08", 35.6050, 139.6180),
            st("Tokyu.DenEnToshi", "Takatsu", "高津", "Takatsu", "DT09", 35.6010, 139.6150),
            st("Tokyu.DenEnToshi", "Mizonokuchi", "溝の口", "Mizonokuchi", "DT10", 35.5998, 139.6103),
            st("Tokyu.DenEnToshi", "Kajigaya", "梶が谷", "Kajigaya", "DT11", 35.5910, 139.5990),
            st("Tokyu.DenEnToshi", "Miyazakidai", "宮崎台", "Miyazakidai", "DT12", 35.5870, 139.5880),
            st("Tokyu.DenEnToshi", "Miyamaedaira", "宮前平", "Miyamaedaira", "DT13", 35.5850, 139.5780),
            st("Tokyu.DenEnToshi", "Saginuma", "鷺沼", "Saginuma", "DT14", 35.5810, 139.5680),
            st("Tokyu.DenEnToshi", "TamaPlaza", "たまプラーザ", "Tama-plaza", "DT15", 35.5720, 139.5560),
            st("Tokyu.DenEnToshi", "Azamino", "あざみ野", "Azamino", "DT16", 35.5700, 139.5430),
            st("Tokyu.DenEnToshi", "Eda", "江田", "Eda", "DT17", 35.5620, 139.5360),
            st("Tokyu.DenEnToshi", "Ichigao", "市が尾", "Ichigao", "DT18", 35.5560, 139.5270),
            st("Tokyu.DenEnToshi", "Fujigaoka", "藤が丘", "Fujigaoka", "DT19", 35.5470, 139.5180),
            st("Tokyu.DenEnToshi", "Aobadai", "青葉台", "Aobadai", "DT20", 35.5440, 139.5080),
            st("Tokyu.DenEnToshi", "Tana", "田奈", "Tana", "DT21", 35.5390, 139.4980),
            st("Tokyu.DenEnToshi", "Nagatsuta", "長津田", "Nagatsuta", "DT22", 35.5318, 139.4944),
            st("Tokyu.DenEnToshi", "Tsukushino", "つくし野", "Tsukushino", "DT23", 35.5230, 139.4830),
            st("Tokyu.DenEnToshi", "Suzukakedai", "すずかけ台", "Suzukakedai", "DT24", 35.5170, 139.4720),
            st("Tokyu.DenEnToshi", "MinamiMachida", "南町田グランベリーパーク", "Minami-machida Grandberry Park", "DT25", 35.5130, 139.4620),
            st("Tokyu.DenEnToshi", "Tsukimino", "つきみ野", "Tsukimino", "DT26", 35.5030, 139.4530),
            st("Tokyu.DenEnToshi", "ChuoRinkan", "中央林間", "Chuo-rinkan", "DT27", 35.5076, 139.4453),
        ],
        hopTimesMinutes: [
            2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        ],
        directions: [
            direction("Tokyu.DenEnToshi", "ChuoRinkan", "中央林間方面", "For Chuo-Rinkan",
                      ascending: true,
                      weekday: pattern("05:05", "23:58", [
                          ("05:05", 6), ("06:30", 3), ("09:30", 6), ("16:30", 4), ("20:00", 5), ("22:00", 7),
                      ]),
                      holiday: pattern("05:05", "23:58", [
                          ("05:05", 7), ("07:00", 6), ("10:00", 6), ("20:00", 7),
                      ]),
                      expressWeekday: denentoshiAscExpressWd,
                      expressHoliday: denentoshiAscExpressHol),
            direction("Tokyu.DenEnToshi", "Shibuya", "渋谷・大手町方面", "For Shibuya & Otemachi",
                      ascending: false,
                      weekday: pattern("05:00", "24:10", [
                          ("05:00", 6), ("06:30", 3), ("09:30", 6), ("16:30", 4), ("20:00", 5), ("22:00", 7),
                      ]),
                      holiday: pattern("05:00", "24:10", [
                          ("05:00", 7), ("07:00", 6), ("10:00", 6), ("20:00", 7),
                      ]),
                      expressWeekday: denentoshiDescExpressWd,
                      expressHoliday: denentoshiDescExpressHol),
        ],
        delayInfo: delayInfo,
        throughServices: [
            through("Tokyu.DenEnToshi.Shibuya", .descending,
                    "東京メトロ半蔵門線", "Tokyo Metro Hanzomon Line",
                    "大手町・押上方面", "for Otemachi & Oshiage",
                    to: "Railway:TokyoMetro.Hanzomon"),
        ],
        // 停車駅 from official table (absolute indices). 急行=express,
        // 準急=semiExpress (各停 Shibuya→二子玉川, then 急行 beyond 溝の口).
        // Source: https://www.tokyo-train-master.com/dt-den-en-toshi
        stopPatterns: [
            .express:     [0, 2, 6, 9, 13, 14, 15, 19, 21, 24, 26], // 急行
            .semiExpress: [0, 1, 2, 3, 4, 5, 6, 9, 13, 14, 15, 19, 21, 22, 23, 24, 25, 26], // 準急
        ]
    )

    // MARK: - Tokyu Meguro Line (MG)

    static let meguro = StaticTrainLine(
        id: "Railway:Tokyu.Meguro",
        nameJa: "東急目黒線",
        nameEn: "Tokyu Meguro Line",
        operatorId: "Operator:Tokyu",
        colorHex: "#009CD2",
        stations: [
            st("Tokyu.Meguro", "Meguro", "目黒", "Meguro", "MG01", 35.6340, 139.7157),
            st("Tokyu.Meguro", "Fudomae", "不動前", "Fudo-mae", "MG02", 35.6260, 139.7120),
            st("Tokyu.Meguro", "MusashiKoyama", "武蔵小山", "Musashi-Koyama", "MG03", 35.6210, 139.7020),
            st("Tokyu.Meguro", "NishiKoyama", "西小山", "Nishi-Koyama", "MG04", 35.6170, 139.6960),
            st("Tokyu.Meguro", "Senzoku", "洗足", "Senzoku", "MG05", 35.6140, 139.6890),
            st("Tokyu.Meguro", "Ookayama", "大岡山", "Ookayama", "MG06", 35.6070, 139.6850),
            st("Tokyu.Meguro", "Okusawa", "奥沢", "Okusawa", "MG07", 35.6040, 139.6770),
            st("Tokyu.Meguro", "DenenChofu", "田園調布", "Den-en-chofu", "MG08", 35.5990, 139.6660),
            st("Tokyu.Meguro", "Tamagawa", "多摩川", "Tamagawa", "MG09", 35.5920, 139.6660),
            st("Tokyu.Meguro", "ShinMaruko", "新丸子", "Shin-maruko", "MG10", 35.5810, 139.6595),
            st("Tokyu.Meguro", "MusashiKosugi", "武蔵小杉", "Musashi-Kosugi", "MG11", 35.5766, 139.6597),
            st("Tokyu.Meguro", "Motosumiyoshi", "元住吉", "Motosumiyoshi", "MG12", 35.5680, 139.6510),
            st("Tokyu.Meguro", "Hiyoshi", "日吉", "Hiyoshi", "MG13", 35.5540, 139.6470),
        ],
        hopTimesMinutes: [
            2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        ],
        directions: [
            direction("Tokyu.Meguro", "Hiyoshi", "日吉・新横浜方面", "For Hiyoshi & Shin-Yokohama",
                      ascending: true,
                      weekday: pattern("05:00", "24:02", [
                          ("05:00", 8), ("06:30", 4), ("09:30", 6), ("16:30", 5), ("20:00", 6), ("22:00", 8),
                      ]),
                      holiday: pattern("05:00", "24:02", [
                          ("05:00", 8), ("07:00", 6), ("10:00", 6), ("20:00", 8),
                      ]),
                      expressWeekday: meguroAscExpressWd,
                      expressHoliday: meguroAscExpressHol),
            direction("Tokyu.Meguro", "Meguro", "目黒・大手町方面", "For Meguro & Otemachi",
                      ascending: false,
                      weekday: pattern("05:10", "24:29", [
                          ("05:10", 8), ("06:30", 4), ("09:30", 6), ("16:30", 5), ("20:00", 6), ("22:00", 8),
                      ]),
                      holiday: pattern("05:10", "24:29", [
                          ("05:10", 8), ("07:00", 6), ("10:00", 6), ("20:00", 8),
                      ]),
                      expressWeekday: meguroDescExpressWd,
                      expressHoliday: meguroDescExpressHol),
        ],
        delayInfo: delayInfo,
        throughServices: [
            through("Tokyu.Meguro.Meguro", .descending,
                    "東京メトロ南北線", "Tokyo Metro Namboku Line",
                    "四ツ谷・赤羽岩淵方面", "for Yotsuya & Akabane-Iwabuchi",
                    to: "Railway:TokyoMetro.Namboku"),
            through("Tokyu.Meguro.Meguro", .descending,
                    "都営三田線", "Toei Mita Line",
                    "大手町・西高島平方面", "for Otemachi & Nishi-Takashimadaira",
                    to: "Railway:Toei.Mita"),
            through("Tokyu.Meguro.Hiyoshi", .ascending,
                    "東急新横浜線", "Tokyu Shin-Yokohama Line",
                    "新横浜・相鉄線方面", "for Shin-Yokohama & the Sotetsu Line"),
        ],
        // 停車駅 from official table (absolute indices). 急行=express.
        // Source: https://www.tokyu.co.jp/railway/mg/
        stopPatterns: [
            .express: [0, 2, 5, 7, 8, 10, 12], // 急行
        ]
    )

    // MARK: - Express run data (ODPT StationTimetable: exact times/types/termini).
    // Stops resolve from each line's absolute `stopPatterns`. See emit_tokyu.py.
    private static let toyokoAscExpressWd: [ExactRun] = [
        ExactRun("05:23", trainType: .express),
        ExactRun("05:51", trainType: .express),
        ExactRun("06:03", trainType: .express),
        ExactRun("06:26", trainType: .express),
        ExactRun("06:35", trainType: .express),
        ExactRun("06:54", trainType: .express),
        ExactRun("07:02", trainType: .express),
        ExactRun("07:08", trainType: .express),
        ExactRun("07:18", trainType: .express),
        ExactRun("07:26", trainType: .express),
        ExactRun("07:32", trainType: .express),
        ExactRun("07:41", trainType: .commuterLimitedExpress),
        ExactRun("07:47", trainType: .express),
        ExactRun("07:52", trainType: .express),
        ExactRun("07:56", trainType: .commuterLimitedExpress),
        ExactRun("08:04", trainType: .express),
        ExactRun("08:11", trainType: .commuterLimitedExpress),
        ExactRun("08:14", trainType: .express),
        ExactRun("08:19", trainType: .express),
        ExactRun("08:26", trainType: .commuterLimitedExpress),
        ExactRun("08:28", trainType: .express),
        ExactRun("08:34", trainType: .commuterLimitedExpress),
        ExactRun("08:42", trainType: .express),
        ExactRun("08:50", trainType: .commuterLimitedExpress),
        ExactRun("08:53", trainType: .express),
        ExactRun("09:00", trainType: .limitedExpress),
        ExactRun("09:06", trainType: .express),
        ExactRun("09:11", trainType: .express),
        ExactRun("09:16", trainType: .express),
        ExactRun("09:24", trainType: .limitedExpress),
        ExactRun("09:29", trainType: .express),
        ExactRun("09:33", trainType: .express),
        ExactRun("09:39", trainType: .limitedExpress),
        ExactRun("09:44", trainType: .express),
        ExactRun("09:49", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
        ExactRun("09:55", trainType: .limitedExpress),
        ExactRun("10:09", trainType: .limitedExpress),
        ExactRun("10:13", trainType: .express),
        ExactRun("10:19", trainType: .express),
        ExactRun("10:24", trainType: .limitedExpress),
        ExactRun("10:29", trainType: .express),
        ExactRun("10:32", trainType: .express),
        ExactRun("10:39", trainType: .limitedExpress),
        ExactRun("10:44", trainType: .express),
        ExactRun("10:54", trainType: .limitedExpress),
        ExactRun("10:59", trainType: .express),
        ExactRun("11:09", trainType: .limitedExpress),
        ExactRun("11:12", trainType: .express),
        ExactRun("11:17", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
        ExactRun("11:24", trainType: .limitedExpress),
        ExactRun("11:29", trainType: .express),
        ExactRun("11:39", trainType: .limitedExpress),
        ExactRun("11:42", trainType: .express),
        ExactRun("11:47", trainType: .express),
        ExactRun("11:54", trainType: .limitedExpress),
        ExactRun("11:59", trainType: .express),
        ExactRun("12:09", trainType: .limitedExpress),
        ExactRun("12:12", trainType: .express),
        ExactRun("12:17", trainType: .express),
        ExactRun("12:24", trainType: .limitedExpress),
        ExactRun("12:29", trainType: .express),
        ExactRun("12:39", trainType: .limitedExpress),
        ExactRun("12:42", trainType: .express),
        ExactRun("12:47", trainType: .express),
        ExactRun("12:54", trainType: .limitedExpress),
        ExactRun("12:59", trainType: .express),
        ExactRun("13:09", trainType: .limitedExpress),
        ExactRun("13:12", trainType: .express),
        ExactRun("13:17", trainType: .express),
        ExactRun("13:24", trainType: .limitedExpress),
        ExactRun("13:29", trainType: .express),
        ExactRun("13:39", trainType: .limitedExpress),
        ExactRun("13:42", trainType: .express),
        ExactRun("13:47", trainType: .express),
        ExactRun("13:54", trainType: .limitedExpress),
        ExactRun("13:59", trainType: .express),
        ExactRun("14:09", trainType: .limitedExpress),
        ExactRun("14:12", trainType: .express),
        ExactRun("14:17", trainType: .express),
        ExactRun("14:24", trainType: .limitedExpress),
        ExactRun("14:29", trainType: .express),
        ExactRun("14:39", trainType: .limitedExpress),
        ExactRun("14:42", trainType: .express),
        ExactRun("14:47", trainType: .express),
        ExactRun("14:54", trainType: .limitedExpress),
        ExactRun("14:59", trainType: .express),
        ExactRun("15:09", trainType: .limitedExpress),
        ExactRun("15:12", trainType: .express),
        ExactRun("15:17", trainType: .express),
        ExactRun("15:24", trainType: .limitedExpress),
        ExactRun("15:29", trainType: .express),
        ExactRun("15:39", trainType: .limitedExpress),
        ExactRun("15:42", trainType: .express),
        ExactRun("15:47", trainType: .express),
        ExactRun("15:54", trainType: .limitedExpress),
        ExactRun("15:59", trainType: .express),
        ExactRun("16:04", trainType: .express),
        ExactRun("16:07", trainType: .express),
        ExactRun("16:14", trainType: .limitedExpress),
        ExactRun("16:19", trainType: .express),
        ExactRun("16:29", trainType: .limitedExpress),
        ExactRun("16:34", trainType: .express),
        ExactRun("16:45", trainType: .limitedExpress),
        ExactRun("16:50", trainType: .express),
        ExactRun("16:53", trainType: .express),
        ExactRun("17:00", trainType: .commuterLimitedExpress),
        ExactRun("17:02", trainType: .express),
        ExactRun("17:07", trainType: .express),
        ExactRun("17:15", trainType: .commuterLimitedExpress),
        ExactRun("17:20", trainType: .express),
        ExactRun("17:24", trainType: .express),
        ExactRun("17:30", trainType: .commuterLimitedExpress),
        ExactRun("17:34", trainType: .express),
        ExactRun("17:39", trainType: .express),
        ExactRun("17:45", trainType: .commuterLimitedExpress),
        ExactRun("17:50", trainType: .express),
        ExactRun("17:55", trainType: .express),
        ExactRun("18:00", trainType: .commuterLimitedExpress),
        ExactRun("18:05", trainType: .express),
        ExactRun("18:15", trainType: .commuterLimitedExpress),
        ExactRun("18:19", trainType: .express),
        ExactRun("18:24", trainType: .express),
        ExactRun("18:30", trainType: .commuterLimitedExpress),
        ExactRun("18:35", trainType: .express),
        ExactRun("18:40", trainType: .express),
        ExactRun("18:45", trainType: .commuterLimitedExpress),
        ExactRun("18:50", trainType: .express),
        ExactRun("18:54", trainType: .express),
        ExactRun("19:00", trainType: .commuterLimitedExpress),
        ExactRun("19:05", trainType: .express),
        ExactRun("19:09", trainType: .express),
        ExactRun("19:15", trainType: .commuterLimitedExpress),
        ExactRun("19:20", trainType: .express),
        ExactRun("19:24", trainType: .express),
        ExactRun("19:30", trainType: .commuterLimitedExpress),
        ExactRun("19:35", trainType: .express),
        ExactRun("19:39", trainType: .express),
        ExactRun("19:45", trainType: .commuterLimitedExpress),
        ExactRun("19:50", trainType: .express),
        ExactRun("19:54", trainType: .express),
        ExactRun("20:00", trainType: .commuterLimitedExpress),
        ExactRun("20:05", trainType: .express),
        ExactRun("20:09", trainType: .express),
        ExactRun("20:15", trainType: .commuterLimitedExpress),
        ExactRun("20:20", trainType: .express),
        ExactRun("20:30", trainType: .commuterLimitedExpress),
        ExactRun("20:35", trainType: .express),
        ExactRun("20:45", trainType: .commuterLimitedExpress),
        ExactRun("20:50", trainType: .express),
        ExactRun("20:54", trainType: .express),
        ExactRun("21:00", trainType: .commuterLimitedExpress),
        ExactRun("21:05", trainType: .express),
        ExactRun("21:07", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
        ExactRun("21:15", trainType: .commuterLimitedExpress),
        ExactRun("21:20", trainType: .express),
        ExactRun("21:24", trainType: .express),
        ExactRun("21:30", trainType: .commuterLimitedExpress),
        ExactRun("21:35", trainType: .express),
        ExactRun("21:45", trainType: .commuterLimitedExpress),
        ExactRun("21:49", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
        ExactRun("21:52", trainType: .express),
        ExactRun("22:00", trainType: .commuterLimitedExpress),
        ExactRun("22:05", trainType: .express),
        ExactRun("22:15", trainType: .commuterLimitedExpress),
        ExactRun("22:21", trainType: .express),
        ExactRun("22:29", trainType: .commuterLimitedExpress),
        ExactRun("22:35", trainType: .express),
        ExactRun("22:38", trainType: .express),
        ExactRun("22:43", trainType: .commuterLimitedExpress),
        ExactRun("22:50", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
        ExactRun("22:53", trainType: .express),
        ExactRun("23:00", trainType: .commuterLimitedExpress),
        ExactRun("23:05", trainType: .express),
        ExactRun("23:08", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
        ExactRun("23:15", trainType: .commuterLimitedExpress),
        ExactRun("23:22", trainType: .express),
        ExactRun("23:34", trainType: .express),
        ExactRun("23:42", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
        ExactRun("23:53", trainType: .express),
        ExactRun("24:08", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
    ]

    private static let toyokoAscExpressHol: [ExactRun] = [
        ExactRun("05:23", trainType: .express),
        ExactRun("06:08", trainType: .limitedExpress),
        ExactRun("06:17", trainType: .express),
        ExactRun("06:23", trainType: .express),
        ExactRun("06:38", trainType: .limitedExpress),
        ExactRun("06:45", trainType: .express),
        ExactRun("06:53", trainType: .limitedExpress),
        ExactRun("06:58", trainType: .express),
        ExactRun("07:06", terminusStationId: "Station:Tokyu.Toyoko.Kikuna", trainType: .express),
        ExactRun("07:10", trainType: .express),
        ExactRun("07:16", trainType: .express),
        ExactRun("07:23", trainType: .limitedExpress),
        ExactRun("07:28", trainType: .express),
        ExactRun("07:38", trainType: .limitedExpress),
        ExactRun("07:45", trainType: .express),
        ExactRun("07:53", trainType: .limitedExpress),
        ExactRun("07:58", trainType: .express),
        ExactRun("08:08", trainType: .limitedExpress),
        ExactRun("08:13", trainType: .express),
        ExactRun("08:18", trainType: .express),
        ExactRun("08:23", trainType: .limitedExpress),
        ExactRun("08:28", trainType: .express),
        ExactRun("08:38", trainType: .limitedExpress),
        ExactRun("08:43", trainType: .express),
        ExactRun("08:48", trainType: .express),
        ExactRun("08:54", trainType: .limitedExpress),
        ExactRun("08:59", trainType: .express),
        ExactRun("09:09", trainType: .limitedExpress),
        ExactRun("09:14", trainType: .express),
        ExactRun("09:19", trainType: .express),
        ExactRun("09:25", trainType: .limitedExpress),
        ExactRun("09:30", trainType: .express),
        ExactRun("09:39", trainType: .limitedExpress),
        ExactRun("09:44", trainType: .express),
        ExactRun("09:49", trainType: .express),
        ExactRun("09:54", trainType: .limitedExpress),
        ExactRun("09:59", trainType: .express),
        ExactRun("10:08", trainType: .limitedExpress),
        ExactRun("10:10", trainType: .express),
        ExactRun("10:14", trainType: .express),
        ExactRun("10:24", trainType: .limitedExpress),
        ExactRun("10:29", trainType: .express),
        ExactRun("10:39", trainType: .limitedExpress),
        ExactRun("10:44", trainType: .express),
        ExactRun("10:49", trainType: .express),
        ExactRun("10:54", trainType: .limitedExpress),
        ExactRun("10:59", trainType: .express),
        ExactRun("11:09", trainType: .limitedExpress),
        ExactRun("11:12", trainType: .express),
        ExactRun("11:17", trainType: .express),
        ExactRun("11:24", trainType: .limitedExpress),
        ExactRun("11:29", trainType: .express),
        ExactRun("11:39", trainType: .limitedExpress),
        ExactRun("11:42", trainType: .express),
        ExactRun("11:47", trainType: .express),
        ExactRun("11:54", trainType: .limitedExpress),
        ExactRun("11:59", trainType: .express),
        ExactRun("12:09", trainType: .limitedExpress),
        ExactRun("12:12", trainType: .express),
        ExactRun("12:17", trainType: .express),
        ExactRun("12:24", trainType: .limitedExpress),
        ExactRun("12:29", trainType: .express),
        ExactRun("12:39", trainType: .limitedExpress),
        ExactRun("12:42", trainType: .express),
        ExactRun("12:47", trainType: .express),
        ExactRun("12:54", trainType: .limitedExpress),
        ExactRun("12:59", trainType: .express),
        ExactRun("13:09", trainType: .limitedExpress),
        ExactRun("13:12", trainType: .express),
        ExactRun("13:17", trainType: .express),
        ExactRun("13:24", trainType: .limitedExpress),
        ExactRun("13:29", trainType: .express),
        ExactRun("13:39", trainType: .limitedExpress),
        ExactRun("13:42", trainType: .express),
        ExactRun("13:47", trainType: .express),
        ExactRun("13:54", trainType: .limitedExpress),
        ExactRun("13:59", trainType: .express),
        ExactRun("14:09", trainType: .limitedExpress),
        ExactRun("14:12", trainType: .express),
        ExactRun("14:17", trainType: .express),
        ExactRun("14:24", trainType: .limitedExpress),
        ExactRun("14:29", trainType: .express),
        ExactRun("14:39", trainType: .limitedExpress),
        ExactRun("14:42", trainType: .express),
        ExactRun("14:47", trainType: .express),
        ExactRun("14:54", trainType: .limitedExpress),
        ExactRun("14:59", trainType: .express),
        ExactRun("15:09", trainType: .limitedExpress),
        ExactRun("15:12", trainType: .express),
        ExactRun("15:17", trainType: .express),
        ExactRun("15:24", trainType: .limitedExpress),
        ExactRun("15:29", trainType: .express),
        ExactRun("15:39", trainType: .limitedExpress),
        ExactRun("15:42", trainType: .express),
        ExactRun("15:47", trainType: .express),
        ExactRun("15:54", trainType: .limitedExpress),
        ExactRun("15:59", trainType: .express),
        ExactRun("16:09", trainType: .limitedExpress),
        ExactRun("16:12", trainType: .express),
        ExactRun("16:17", trainType: .express),
        ExactRun("16:24", trainType: .limitedExpress),
        ExactRun("16:29", trainType: .express),
        ExactRun("16:39", trainType: .limitedExpress),
        ExactRun("16:44", trainType: .express),
        ExactRun("16:48", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
        ExactRun("16:54", trainType: .limitedExpress),
        ExactRun("16:59", trainType: .express),
        ExactRun("17:02", trainType: .express),
        ExactRun("17:09", trainType: .limitedExpress),
        ExactRun("17:14", trainType: .express),
        ExactRun("17:24", trainType: .limitedExpress),
        ExactRun("17:29", trainType: .express),
        ExactRun("17:32", trainType: .express),
        ExactRun("17:39", trainType: .limitedExpress),
        ExactRun("17:44", trainType: .express),
        ExactRun("17:54", trainType: .limitedExpress),
        ExactRun("17:59", trainType: .express),
        ExactRun("18:02", trainType: .express),
        ExactRun("18:08", trainType: .limitedExpress),
        ExactRun("18:14", trainType: .express),
        ExactRun("18:24", trainType: .limitedExpress),
        ExactRun("18:29", trainType: .express),
        ExactRun("18:33", trainType: .express),
        ExactRun("18:39", trainType: .limitedExpress),
        ExactRun("18:44", trainType: .express),
        ExactRun("18:52", trainType: .limitedExpress),
        ExactRun("18:55", trainType: .express),
        ExactRun("19:02", trainType: .express),
        ExactRun("19:08", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
        ExactRun("19:14", trainType: .express),
        ExactRun("19:18", trainType: .express),
        ExactRun("19:24", trainType: .limitedExpress),
        ExactRun("19:34", trainType: .express),
        ExactRun("19:44", trainType: .express),
        ExactRun("19:48", trainType: .express),
        ExactRun("19:54", trainType: .limitedExpress),
        ExactRun("20:04", trainType: .express),
        ExactRun("20:10", trainType: .express),
        ExactRun("20:15", trainType: .express),
        ExactRun("20:24", trainType: .limitedExpress),
        ExactRun("20:34", trainType: .express),
        ExactRun("20:38", trainType: .express),
        ExactRun("20:44", trainType: .express),
        ExactRun("20:48", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
        ExactRun("20:54", trainType: .limitedExpress),
        ExactRun("21:05", trainType: .express),
        ExactRun("21:14", trainType: .express),
        ExactRun("21:18", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
        ExactRun("21:24", trainType: .limitedExpress),
        ExactRun("21:26", trainType: .express),
        ExactRun("21:35", trainType: .express),
        ExactRun("21:47", trainType: .express),
        ExactRun("21:54", trainType: .limitedExpress),
        ExactRun("22:09", trainType: .express),
        ExactRun("22:24", trainType: .limitedExpress),
        ExactRun("22:28", trainType: .express),
        ExactRun("22:40", trainType: .express),
        ExactRun("22:54", trainType: .limitedExpress),
        ExactRun("22:56", trainType: .express),
        ExactRun("23:01", trainType: .express),
        ExactRun("23:09", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
        ExactRun("23:24", trainType: .limitedExpress),
        ExactRun("23:32", trainType: .express),
        ExactRun("23:56", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
        ExactRun("24:07", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
    ]

    private static let toyokoDescExpressWd: [ExactRun] = [
        ExactRun("06:04", trainType: .express),
        ExactRun("06:14", trainType: .express),
        ExactRun("06:24", trainType: .limitedExpress),
        ExactRun("06:43", trainType: .commuterLimitedExpress),
        ExactRun("06:50", trainType: .express),
        ExactRun("06:56", trainType: .express),
        ExactRun("07:04", trainType: .commuterLimitedExpress),
        ExactRun("07:14", trainType: .express),
        ExactRun("07:19", trainType: .commuterLimitedExpress),
        ExactRun("07:28", trainType: .express),
        ExactRun("07:34", trainType: .commuterLimitedExpress),
        ExactRun("07:43", trainType: .express),
        ExactRun("07:49", trainType: .commuterLimitedExpress),
        ExactRun("07:58", trainType: .express),
        ExactRun("08:04", trainType: .commuterLimitedExpress),
        ExactRun("08:13", trainType: .express),
        ExactRun("08:19", trainType: .commuterLimitedExpress),
        ExactRun("08:28", trainType: .express),
        ExactRun("08:37", trainType: .commuterLimitedExpress),
        ExactRun("08:47", trainType: .express),
        ExactRun("08:54", trainType: .commuterLimitedExpress),
        ExactRun("09:00", trainType: .express),
        ExactRun("09:09", trainType: .commuterLimitedExpress),
        ExactRun("09:15", trainType: .express),
        ExactRun("09:23", trainType: .express),
        ExactRun("09:29", trainType: .limitedExpress),
        ExactRun("09:35", trainType: .express),
        ExactRun("09:42", trainType: .limitedExpress),
        ExactRun("09:48", trainType: .express),
        ExactRun("09:57", trainType: .limitedExpress),
        ExactRun("10:03", trainType: .express),
        ExactRun("10:12", trainType: .limitedExpress),
        ExactRun("10:19", trainType: .express),
        ExactRun("10:27", trainType: .limitedExpress),
        ExactRun("10:34", trainType: .express),
        ExactRun("10:42", trainType: .limitedExpress),
        ExactRun("10:49", trainType: .express),
        ExactRun("10:57", trainType: .limitedExpress),
        ExactRun("11:04", trainType: .express),
        ExactRun("11:12", trainType: .limitedExpress),
        ExactRun("11:19", trainType: .express),
        ExactRun("11:27", trainType: .limitedExpress),
        ExactRun("11:34", trainType: .express),
        ExactRun("11:42", trainType: .limitedExpress),
        ExactRun("11:49", trainType: .express),
        ExactRun("11:57", trainType: .limitedExpress),
        ExactRun("12:04", trainType: .express),
        ExactRun("12:12", trainType: .limitedExpress),
        ExactRun("12:19", trainType: .express),
        ExactRun("12:27", trainType: .limitedExpress),
        ExactRun("12:34", trainType: .express),
        ExactRun("12:42", trainType: .limitedExpress),
        ExactRun("12:49", trainType: .express),
        ExactRun("12:57", trainType: .limitedExpress),
        ExactRun("13:04", trainType: .express),
        ExactRun("13:12", trainType: .limitedExpress),
        ExactRun("13:19", trainType: .express),
        ExactRun("13:27", trainType: .limitedExpress),
        ExactRun("13:34", trainType: .express),
        ExactRun("13:42", trainType: .limitedExpress),
        ExactRun("13:49", trainType: .express),
        ExactRun("13:57", trainType: .limitedExpress),
        ExactRun("14:04", trainType: .express),
        ExactRun("14:12", trainType: .limitedExpress),
        ExactRun("14:19", trainType: .express),
        ExactRun("14:27", trainType: .limitedExpress),
        ExactRun("14:34", trainType: .express),
        ExactRun("14:42", trainType: .limitedExpress),
        ExactRun("14:49", trainType: .express),
        ExactRun("14:57", trainType: .limitedExpress),
        ExactRun("15:04", trainType: .express),
        ExactRun("15:12", trainType: .limitedExpress),
        ExactRun("15:19", trainType: .express),
        ExactRun("15:27", trainType: .limitedExpress),
        ExactRun("15:34", trainType: .express),
        ExactRun("15:42", trainType: .limitedExpress),
        ExactRun("15:49", trainType: .express),
        ExactRun("15:57", trainType: .limitedExpress),
        ExactRun("16:04", trainType: .express),
        ExactRun("16:12", trainType: .limitedExpress),
        ExactRun("16:19", trainType: .express),
        ExactRun("16:27", trainType: .limitedExpress),
        ExactRun("16:33", trainType: .express),
        ExactRun("16:42", trainType: .limitedExpress),
        ExactRun("16:51", trainType: .limitedExpress),
        ExactRun("16:59", trainType: .express),
        ExactRun("17:07", trainType: .commuterLimitedExpress),
        ExactRun("17:15", trainType: .express),
        ExactRun("17:22", trainType: .commuterLimitedExpress),
        ExactRun("17:30", trainType: .express),
        ExactRun("17:37", trainType: .commuterLimitedExpress),
        ExactRun("17:44", trainType: .express),
        ExactRun("17:52", trainType: .commuterLimitedExpress),
        ExactRun("17:59", trainType: .express),
        ExactRun("18:08", trainType: .commuterLimitedExpress),
        ExactRun("18:15", trainType: .express),
        ExactRun("18:22", trainType: .commuterLimitedExpress),
        ExactRun("18:30", trainType: .express),
        ExactRun("18:38", trainType: .commuterLimitedExpress),
        ExactRun("18:45", trainType: .express),
        ExactRun("18:53", trainType: .commuterLimitedExpress),
        ExactRun("19:00", trainType: .express),
        ExactRun("19:08", trainType: .commuterLimitedExpress),
        ExactRun("19:15", trainType: .express),
        ExactRun("19:23", trainType: .commuterLimitedExpress),
        ExactRun("19:30", trainType: .express),
        ExactRun("19:38", trainType: .commuterLimitedExpress),
        ExactRun("19:45", trainType: .express),
        ExactRun("19:53", trainType: .commuterLimitedExpress),
        ExactRun("20:00", trainType: .express),
        ExactRun("20:08", trainType: .commuterLimitedExpress),
        ExactRun("20:15", trainType: .express),
        ExactRun("20:23", trainType: .commuterLimitedExpress),
        ExactRun("20:30", trainType: .express),
        ExactRun("20:38", trainType: .commuterLimitedExpress),
        ExactRun("20:45", trainType: .express),
        ExactRun("20:53", trainType: .commuterLimitedExpress),
        ExactRun("21:00", trainType: .express),
        ExactRun("21:08", trainType: .commuterLimitedExpress),
        ExactRun("21:15", trainType: .express),
        ExactRun("21:23", trainType: .commuterLimitedExpress),
        ExactRun("21:30", trainType: .express),
        ExactRun("21:38", trainType: .commuterLimitedExpress),
        ExactRun("21:45", trainType: .express),
        ExactRun("21:52", trainType: .commuterLimitedExpress),
        ExactRun("22:00", trainType: .express),
        ExactRun("22:08", trainType: .commuterLimitedExpress),
        ExactRun("22:15", trainType: .express),
        ExactRun("22:23", trainType: .commuterLimitedExpress),
        ExactRun("22:31", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
        ExactRun("22:38", trainType: .commuterLimitedExpress),
        ExactRun("22:53", trainType: .commuterLimitedExpress),
        ExactRun("22:59", trainType: .express),
        ExactRun("23:07", trainType: .commuterLimitedExpress),
        ExactRun("23:14", trainType: .express),
        ExactRun("23:23", trainType: .commuterLimitedExpress),
        ExactRun("23:30", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
        ExactRun("23:37", trainType: .commuterLimitedExpress),
        ExactRun("23:52", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .commuterLimitedExpress),
        ExactRun("24:09", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
    ]

    private static let toyokoDescExpressHol: [ExactRun] = [
        ExactRun("06:13", trainType: .limitedExpress),
        ExactRun("06:26", trainType: .limitedExpress),
        ExactRun("06:55", trainType: .limitedExpress),
        ExactRun("07:12", trainType: .limitedExpress),
        ExactRun("07:26", trainType: .limitedExpress),
        ExactRun("07:42", trainType: .limitedExpress),
        ExactRun("07:50", trainType: .express),
        ExactRun("08:01", trainType: .express),
        ExactRun("08:12", trainType: .limitedExpress),
        ExactRun("08:18", trainType: .express),
        ExactRun("08:27", trainType: .limitedExpress),
        ExactRun("08:33", trainType: .express),
        ExactRun("08:42", trainType: .limitedExpress),
        ExactRun("08:48", trainType: .express),
        ExactRun("08:57", trainType: .limitedExpress),
        ExactRun("09:03", trainType: .express),
        ExactRun("09:12", trainType: .limitedExpress),
        ExactRun("09:18", trainType: .express),
        ExactRun("09:27", trainType: .limitedExpress),
        ExactRun("09:34", trainType: .express),
        ExactRun("09:42", trainType: .limitedExpress),
        ExactRun("09:49", trainType: .express),
        ExactRun("09:57", trainType: .limitedExpress),
        ExactRun("10:04", trainType: .express),
        ExactRun("10:12", trainType: .limitedExpress),
        ExactRun("10:19", trainType: .express),
        ExactRun("10:27", trainType: .limitedExpress),
        ExactRun("10:34", trainType: .express),
        ExactRun("10:42", trainType: .limitedExpress),
        ExactRun("10:48", trainType: .express),
        ExactRun("10:57", trainType: .limitedExpress),
        ExactRun("11:04", trainType: .express),
        ExactRun("11:12", trainType: .limitedExpress),
        ExactRun("11:19", trainType: .express),
        ExactRun("11:27", trainType: .limitedExpress),
        ExactRun("11:34", trainType: .express),
        ExactRun("11:42", trainType: .limitedExpress),
        ExactRun("11:49", trainType: .express),
        ExactRun("11:57", trainType: .limitedExpress),
        ExactRun("12:04", trainType: .express),
        ExactRun("12:12", trainType: .limitedExpress),
        ExactRun("12:19", trainType: .express),
        ExactRun("12:27", trainType: .limitedExpress),
        ExactRun("12:34", trainType: .express),
        ExactRun("12:42", trainType: .limitedExpress),
        ExactRun("12:49", trainType: .express),
        ExactRun("12:57", trainType: .limitedExpress),
        ExactRun("13:04", trainType: .express),
        ExactRun("13:12", trainType: .limitedExpress),
        ExactRun("13:19", trainType: .express),
        ExactRun("13:27", trainType: .limitedExpress),
        ExactRun("13:34", trainType: .express),
        ExactRun("13:42", trainType: .limitedExpress),
        ExactRun("13:49", trainType: .express),
        ExactRun("13:57", trainType: .limitedExpress),
        ExactRun("14:04", trainType: .express),
        ExactRun("14:12", trainType: .limitedExpress),
        ExactRun("14:19", trainType: .express),
        ExactRun("14:27", trainType: .limitedExpress),
        ExactRun("14:34", trainType: .express),
        ExactRun("14:42", trainType: .limitedExpress),
        ExactRun("14:49", trainType: .express),
        ExactRun("14:57", trainType: .limitedExpress),
        ExactRun("15:04", trainType: .express),
        ExactRun("15:12", trainType: .limitedExpress),
        ExactRun("15:19", trainType: .express),
        ExactRun("15:27", trainType: .limitedExpress),
        ExactRun("15:33", trainType: .express),
        ExactRun("15:42", trainType: .limitedExpress),
        ExactRun("15:49", trainType: .express),
        ExactRun("15:57", trainType: .limitedExpress),
        ExactRun("16:04", trainType: .express),
        ExactRun("16:12", trainType: .limitedExpress),
        ExactRun("16:19", trainType: .express),
        ExactRun("16:27", trainType: .limitedExpress),
        ExactRun("16:34", trainType: .express),
        ExactRun("16:42", trainType: .limitedExpress),
        ExactRun("16:49", trainType: .express),
        ExactRun("16:56", trainType: .limitedExpress),
        ExactRun("17:05", trainType: .express),
        ExactRun("17:12", trainType: .limitedExpress),
        ExactRun("17:19", trainType: .express),
        ExactRun("17:27", trainType: .limitedExpress),
        ExactRun("17:34", trainType: .express),
        ExactRun("17:42", trainType: .limitedExpress),
        ExactRun("17:49", trainType: .express),
        ExactRun("17:57", trainType: .limitedExpress),
        ExactRun("18:04", trainType: .express),
        ExactRun("18:12", trainType: .limitedExpress),
        ExactRun("18:20", trainType: .express),
        ExactRun("18:27", trainType: .limitedExpress),
        ExactRun("18:35", trainType: .express),
        ExactRun("18:42", trainType: .limitedExpress),
        ExactRun("18:50", trainType: .express),
        ExactRun("18:57", trainType: .limitedExpress),
        ExactRun("19:05", trainType: .express),
        ExactRun("19:12", trainType: .limitedExpress),
        ExactRun("19:20", trainType: .express),
        ExactRun("19:27", trainType: .limitedExpress),
        ExactRun("19:35", trainType: .express),
        ExactRun("19:44", trainType: .limitedExpress),
        ExactRun("19:56", trainType: .express),
        ExactRun("20:05", trainType: .express),
        ExactRun("20:14", trainType: .limitedExpress),
        ExactRun("20:26", trainType: .express),
        ExactRun("20:35", trainType: .express),
        ExactRun("20:43", trainType: .limitedExpress),
        ExactRun("20:56", trainType: .express),
        ExactRun("21:05", trainType: .express),
        ExactRun("21:14", trainType: .limitedExpress),
        ExactRun("21:26", trainType: .express),
        ExactRun("21:35", trainType: .express),
        ExactRun("21:43", trainType: .limitedExpress),
        ExactRun("21:55", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
        ExactRun("22:05", trainType: .express),
        ExactRun("22:14", trainType: .limitedExpress),
        ExactRun("22:24", trainType: .express),
        ExactRun("22:42", trainType: .express),
        ExactRun("23:02", trainType: .limitedExpress),
        ExactRun("23:16", trainType: .express),
        ExactRun("23:37", trainType: .limitedExpress),
        ExactRun("23:45", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
        ExactRun("23:57", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
        ExactRun("24:07", terminusStationId: "Station:Tokyu.Toyoko.MusashiKosugi", trainType: .express),
    ]

    private static let denentoshiAscExpressWd: [ExactRun] = [
        ExactRun("06:35", terminusStationId: "Station:Tokyu.DenEnToshi.Nagatsuta", trainType: .express),
        ExactRun("07:03", trainType: .express),
        ExactRun("07:22", terminusStationId: "Station:Tokyu.DenEnToshi.Nagatsuta", trainType: .semiExpress),
        ExactRun("07:33", trainType: .semiExpress),
        ExactRun("07:45", trainType: .semiExpress),
        ExactRun("07:54", trainType: .semiExpress),
        ExactRun("08:05", trainType: .semiExpress),
        ExactRun("08:18", terminusStationId: "Station:Tokyu.DenEnToshi.Nagatsuta", trainType: .semiExpress),
        ExactRun("08:29", terminusStationId: "Station:Tokyu.DenEnToshi.Nagatsuta", trainType: .semiExpress),
        ExactRun("08:38", trainType: .semiExpress),
        ExactRun("08:46", terminusStationId: "Station:Tokyu.DenEnToshi.Nagatsuta", trainType: .semiExpress),
        ExactRun("08:53", trainType: .semiExpress),
        ExactRun("08:59", terminusStationId: "Station:Tokyu.DenEnToshi.Nagatsuta", trainType: .semiExpress),
        ExactRun("09:06", trainType: .semiExpress),
        ExactRun("09:13", trainType: .express),
        ExactRun("09:22", trainType: .express),
        ExactRun("09:32", trainType: .express),
        ExactRun("09:41", trainType: .express),
        ExactRun("09:51", terminusStationId: "Station:Tokyu.DenEnToshi.Nagatsuta", trainType: .express),
        ExactRun("10:01", trainType: .express),
        ExactRun("10:13", terminusStationId: "Station:Tokyu.DenEnToshi.Nagatsuta", trainType: .express),
        ExactRun("10:23", trainType: .express),
        ExactRun("10:35", trainType: .express),
        ExactRun("10:45", trainType: .express),
        ExactRun("10:59", trainType: .express),
        ExactRun("11:15", terminusStationId: "Station:Tokyu.DenEnToshi.Nagatsuta", trainType: .express),
        ExactRun("11:31", trainType: .semiExpress),
        ExactRun("11:40", trainType: .express),
        ExactRun("11:49", trainType: .semiExpress),
        ExactRun("11:58", trainType: .express),
        ExactRun("12:08", trainType: .semiExpress),
        ExactRun("12:18", trainType: .express),
        ExactRun("12:28", trainType: .semiExpress),
        ExactRun("12:38", trainType: .express),
        ExactRun("12:48", trainType: .semiExpress),
        ExactRun("12:58", trainType: .express),
        ExactRun("13:08", trainType: .semiExpress),
        ExactRun("13:18", trainType: .express),
        ExactRun("13:28", trainType: .semiExpress),
        ExactRun("13:38", trainType: .express),
        ExactRun("13:48", trainType: .semiExpress),
        ExactRun("13:58", trainType: .express),
        ExactRun("14:08", trainType: .semiExpress),
        ExactRun("14:18", trainType: .express),
        ExactRun("14:28", trainType: .semiExpress),
        ExactRun("14:38", trainType: .express),
        ExactRun("14:48", trainType: .semiExpress),
        ExactRun("14:58", trainType: .express),
        ExactRun("15:08", trainType: .semiExpress),
        ExactRun("15:18", trainType: .express),
        ExactRun("15:28", trainType: .semiExpress),
        ExactRun("15:38", trainType: .express),
        ExactRun("15:48", trainType: .semiExpress),
        ExactRun("15:58", trainType: .express),
        ExactRun("16:08", trainType: .semiExpress),
        ExactRun("16:18", trainType: .express),
        ExactRun("16:33", trainType: .express),
        ExactRun("16:47", trainType: .express),
        ExactRun("16:59", trainType: .express),
        ExactRun("17:12", trainType: .express),
        ExactRun("17:23", trainType: .express),
        ExactRun("17:33", trainType: .express),
        ExactRun("17:44", trainType: .express),
        ExactRun("17:53", trainType: .express),
        ExactRun("18:02", trainType: .express),
        ExactRun("18:12", trainType: .express),
        ExactRun("18:18", trainType: .semiExpress),
        ExactRun("18:26", trainType: .semiExpress),
        ExactRun("18:35", trainType: .semiExpress),
        ExactRun("18:44", trainType: .semiExpress),
        ExactRun("18:53", trainType: .semiExpress),
        ExactRun("19:02", trainType: .semiExpress),
        ExactRun("19:12", trainType: .semiExpress),
        ExactRun("19:21", trainType: .semiExpress),
        ExactRun("19:34", terminusStationId: "Station:Tokyu.DenEnToshi.Nagatsuta", trainType: .express),
        ExactRun("19:44", trainType: .express),
        ExactRun("19:53", trainType: .express),
        ExactRun("20:03", trainType: .express),
        ExactRun("20:13", trainType: .express),
        ExactRun("20:23", trainType: .express),
        ExactRun("20:33", trainType: .express),
        ExactRun("20:43", trainType: .express),
        ExactRun("20:53", trainType: .express),
        ExactRun("21:03", trainType: .express),
        ExactRun("21:14", trainType: .express),
        ExactRun("21:25", trainType: .express),
        ExactRun("21:36", trainType: .express),
        ExactRun("21:47", trainType: .express),
        ExactRun("21:58", trainType: .express),
        ExactRun("22:10", trainType: .express),
        ExactRun("22:22", terminusStationId: "Station:Tokyu.DenEnToshi.Nagatsuta", trainType: .express),
        ExactRun("22:34", trainType: .express),
        ExactRun("22:46", trainType: .express),
        ExactRun("22:58", terminusStationId: "Station:Tokyu.DenEnToshi.Nagatsuta", trainType: .express),
        ExactRun("23:11", trainType: .express),
        ExactRun("23:27", trainType: .express),
        ExactRun("23:42", trainType: .semiExpress),
        ExactRun("24:04", terminusStationId: "Station:Tokyu.DenEnToshi.Nagatsuta", trainType: .semiExpress),
    ]

    private static let denentoshiAscExpressHol: [ExactRun] = [
        ExactRun("06:03", trainType: .express),
        ExactRun("06:30", trainType: .express),
        ExactRun("06:49", trainType: .express),
        ExactRun("07:08", trainType: .express),
        ExactRun("07:28", trainType: .express),
        ExactRun("07:45", trainType: .express),
        ExactRun("08:04", trainType: .express),
        ExactRun("08:19", trainType: .express),
        ExactRun("08:34", trainType: .express),
        ExactRun("08:48", trainType: .express),
        ExactRun("09:02", trainType: .express),
        ExactRun("09:15", trainType: .express),
        ExactRun("09:25", trainType: .semiExpress),
        ExactRun("09:39", trainType: .express),
        ExactRun("09:48", trainType: .semiExpress),
        ExactRun("10:01", trainType: .express),
        ExactRun("10:10", terminusStationId: "Station:Tokyu.DenEnToshi.Nagatsuta", trainType: .semiExpress),
        ExactRun("10:22", terminusStationId: "Station:Tokyu.DenEnToshi.Nagatsuta", trainType: .express),
        ExactRun("10:32", trainType: .semiExpress),
        ExactRun("10:40", trainType: .express),
        ExactRun("10:49", trainType: .semiExpress),
        ExactRun("10:58", trainType: .express),
        ExactRun("11:08", trainType: .semiExpress),
        ExactRun("11:18", trainType: .express),
        ExactRun("11:28", trainType: .semiExpress),
        ExactRun("11:38", trainType: .express),
        ExactRun("11:48", trainType: .semiExpress),
        ExactRun("11:58", trainType: .express),
        ExactRun("12:08", trainType: .semiExpress),
        ExactRun("12:18", trainType: .express),
        ExactRun("12:28", trainType: .semiExpress),
        ExactRun("12:38", trainType: .express),
        ExactRun("12:48", trainType: .semiExpress),
        ExactRun("12:58", trainType: .express),
        ExactRun("13:08", trainType: .semiExpress),
        ExactRun("13:18", trainType: .express),
        ExactRun("13:28", trainType: .semiExpress),
        ExactRun("13:38", trainType: .express),
        ExactRun("13:48", trainType: .semiExpress),
        ExactRun("13:58", trainType: .express),
        ExactRun("14:08", trainType: .semiExpress),
        ExactRun("14:18", trainType: .express),
        ExactRun("14:28", trainType: .semiExpress),
        ExactRun("14:38", trainType: .express),
        ExactRun("14:48", trainType: .semiExpress),
        ExactRun("14:58", trainType: .express),
        ExactRun("15:08", trainType: .semiExpress),
        ExactRun("15:18", trainType: .express),
        ExactRun("15:28", trainType: .semiExpress),
        ExactRun("15:38", trainType: .express),
        ExactRun("15:48", trainType: .semiExpress),
        ExactRun("15:58", trainType: .express),
        ExactRun("16:08", trainType: .semiExpress),
        ExactRun("16:18", trainType: .express),
        ExactRun("16:34", trainType: .express),
        ExactRun("16:48", trainType: .express),
        ExactRun("17:03", trainType: .express),
        ExactRun("17:13", trainType: .express),
        ExactRun("17:23", trainType: .express),
        ExactRun("17:33", trainType: .express),
        ExactRun("17:48", trainType: .express),
        ExactRun("18:03", trainType: .express),
        ExactRun("18:13", trainType: .express),
        ExactRun("18:23", trainType: .express),
        ExactRun("18:33", trainType: .express),
        ExactRun("18:48", trainType: .express),
        ExactRun("19:03", trainType: .express),
        ExactRun("19:18", trainType: .express),
        ExactRun("19:33", trainType: .express),
        ExactRun("19:48", trainType: .express),
        ExactRun("20:03", trainType: .express),
        ExactRun("20:18", terminusStationId: "Station:Tokyu.DenEnToshi.Nagatsuta", trainType: .express),
        ExactRun("20:33", trainType: .express),
        ExactRun("20:48", trainType: .express),
        ExactRun("21:03", trainType: .express),
        ExactRun("21:18", trainType: .express),
        ExactRun("21:33", trainType: .express),
        ExactRun("21:53", trainType: .express),
        ExactRun("22:11", trainType: .express),
        ExactRun("22:29", trainType: .express),
        ExactRun("22:48", trainType: .express),
        ExactRun("23:15", trainType: .semiExpress),
        ExactRun("23:41", trainType: .semiExpress),
        ExactRun("24:04", terminusStationId: "Station:Tokyu.DenEnToshi.Nagatsuta", trainType: .semiExpress),
    ]

    private static let denentoshiDescExpressWd: [ExactRun] = [
        ExactRun("05:05", trainType: .semiExpress),
        ExactRun("05:22", trainType: .semiExpress),
        ExactRun("05:37", trainType: .semiExpress),
        ExactRun("05:52", trainType: .semiExpress),
        ExactRun("06:09", trainType: .express),
        ExactRun("06:20", trainType: .express),
        ExactRun("06:30", trainType: .express),
        ExactRun("06:40", trainType: .express),
        ExactRun("06:50", trainType: .express),
        ExactRun("07:00", trainType: .express),
        ExactRun("07:04", trainType: .semiExpress),
        ExactRun("07:17", trainType: .semiExpress),
        ExactRun("07:30", trainType: .semiExpress),
        ExactRun("07:44", trainType: .semiExpress),
        ExactRun("08:00", trainType: .semiExpress),
        ExactRun("08:10", terminusStationId: "Station:Tokyu.DenEnToshi.Saginuma", trainType: .express),
        ExactRun("08:19", trainType: .express),
        ExactRun("08:33", trainType: .express),
        ExactRun("08:46", trainType: .express),
        ExactRun("09:01", trainType: .express),
        ExactRun("09:11", trainType: .express),
        ExactRun("09:22", trainType: .express),
        ExactRun("09:33", trainType: .express),
        ExactRun("09:47", trainType: .express),
        ExactRun("10:01", trainType: .express),
        ExactRun("10:05", trainType: .semiExpress),
        ExactRun("10:18", trainType: .express),
        ExactRun("10:32", trainType: .express),
        ExactRun("10:42", trainType: .express),
        ExactRun("10:47", trainType: .semiExpress),
        ExactRun("11:02", trainType: .express),
        ExactRun("11:11", trainType: .semiExpress),
        ExactRun("11:22", trainType: .express),
        ExactRun("11:32", trainType: .semiExpress),
        ExactRun("11:41", trainType: .express),
        ExactRun("11:52", trainType: .semiExpress),
        ExactRun("12:01", trainType: .express),
        ExactRun("12:08", trainType: .express),
        ExactRun("12:12", trainType: .semiExpress),
        ExactRun("12:21", trainType: .express),
        ExactRun("12:28", trainType: .express),
        ExactRun("12:32", trainType: .semiExpress),
        ExactRun("12:41", trainType: .express),
        ExactRun("12:48", trainType: .express),
        ExactRun("12:52", trainType: .semiExpress),
        ExactRun("13:01", trainType: .express),
        ExactRun("13:08", trainType: .express),
        ExactRun("13:12", trainType: .semiExpress),
        ExactRun("13:21", trainType: .express),
        ExactRun("13:28", trainType: .express),
        ExactRun("13:32", trainType: .semiExpress),
        ExactRun("13:41", trainType: .express),
        ExactRun("13:48", trainType: .express),
        ExactRun("13:52", trainType: .semiExpress),
        ExactRun("14:01", trainType: .express),
        ExactRun("14:08", trainType: .express),
        ExactRun("14:12", trainType: .semiExpress),
        ExactRun("14:21", trainType: .express),
        ExactRun("14:28", trainType: .express),
        ExactRun("14:32", trainType: .semiExpress),
        ExactRun("14:41", trainType: .express),
        ExactRun("14:48", trainType: .express),
        ExactRun("14:52", trainType: .semiExpress),
        ExactRun("15:01", trainType: .express),
        ExactRun("15:08", trainType: .express),
        ExactRun("15:12", trainType: .semiExpress),
        ExactRun("15:20", trainType: .express),
        ExactRun("15:28", trainType: .express),
        ExactRun("15:32", trainType: .semiExpress),
        ExactRun("15:41", trainType: .express),
        ExactRun("15:48", trainType: .express),
        ExactRun("15:52", trainType: .semiExpress),
        ExactRun("16:01", trainType: .express),
        ExactRun("16:12", trainType: .express),
        ExactRun("16:17", trainType: .semiExpress),
        ExactRun("16:31", trainType: .express),
        ExactRun("16:34", trainType: .semiExpress),
        ExactRun("16:49", trainType: .express),
        ExactRun("17:10", trainType: .express),
        ExactRun("17:13", trainType: .semiExpress),
        ExactRun("17:28", trainType: .express),
        ExactRun("17:32", trainType: .semiExpress),
        ExactRun("17:48", trainType: .express),
        ExactRun("17:55", trainType: .semiExpress),
        ExactRun("18:08", trainType: .express),
        ExactRun("18:15", trainType: .semiExpress),
        ExactRun("18:28", trainType: .express),
        ExactRun("18:36", trainType: .semiExpress),
        ExactRun("18:48", trainType: .express),
        ExactRun("18:55", trainType: .semiExpress),
        ExactRun("19:08", trainType: .express),
        ExactRun("19:14", trainType: .semiExpress),
        ExactRun("19:30", trainType: .express),
        ExactRun("19:37", trainType: .semiExpress),
        ExactRun("19:51", trainType: .express),
        ExactRun("20:06", trainType: .express),
        ExactRun("20:21", trainType: .express),
        ExactRun("20:37", trainType: .express),
        ExactRun("20:54", trainType: .express),
        ExactRun("21:12", trainType: .express),
        ExactRun("21:33", trainType: .express),
        ExactRun("21:52", trainType: .express),
        ExactRun("22:06", trainType: .semiExpress),
        ExactRun("22:43", trainType: .semiExpress),
    ]

    private static let denentoshiDescExpressHol: [ExactRun] = [
        ExactRun("05:05", trainType: .semiExpress),
        ExactRun("05:31", trainType: .semiExpress),
        ExactRun("06:03", trainType: .express),
        ExactRun("06:36", trainType: .express),
        ExactRun("06:50", trainType: .express),
        ExactRun("07:05", trainType: .express),
        ExactRun("07:17", trainType: .express),
        ExactRun("07:33", trainType: .express),
        ExactRun("07:46", trainType: .express),
        ExactRun("08:00", trainType: .express),
        ExactRun("08:13", trainType: .express),
        ExactRun("08:26", trainType: .express),
        ExactRun("08:38", trainType: .express),
        ExactRun("08:51", trainType: .express),
        ExactRun("09:04", trainType: .express),
        ExactRun("09:18", trainType: .express),
        ExactRun("09:32", trainType: .express),
        ExactRun("09:38", trainType: .semiExpress),
        ExactRun("09:49", trainType: .express),
        ExactRun("09:52", trainType: .semiExpress),
        ExactRun("09:58", trainType: .semiExpress),
        ExactRun("10:09", trainType: .express),
        ExactRun("10:11", trainType: .semiExpress),
        ExactRun("10:18", trainType: .semiExpress),
        ExactRun("10:28", trainType: .express),
        ExactRun("10:31", trainType: .semiExpress),
        ExactRun("10:38", trainType: .semiExpress),
        ExactRun("10:49", trainType: .express),
        ExactRun("10:52", trainType: .semiExpress),
        ExactRun("10:58", trainType: .semiExpress),
        ExactRun("11:09", trainType: .express),
        ExactRun("11:12", trainType: .semiExpress),
        ExactRun("11:18", trainType: .semiExpress),
        ExactRun("11:29", trainType: .express),
        ExactRun("11:32", trainType: .semiExpress),
        ExactRun("11:38", trainType: .semiExpress),
        ExactRun("11:48", trainType: .express),
        ExactRun("11:52", trainType: .semiExpress),
        ExactRun("11:58", trainType: .semiExpress),
        ExactRun("12:08", trainType: .express),
        ExactRun("12:12", trainType: .semiExpress),
        ExactRun("12:18", trainType: .semiExpress),
        ExactRun("12:28", trainType: .express),
        ExactRun("12:32", trainType: .semiExpress),
        ExactRun("12:38", trainType: .semiExpress),
        ExactRun("12:48", trainType: .express),
        ExactRun("12:52", trainType: .semiExpress),
        ExactRun("12:58", trainType: .semiExpress),
        ExactRun("13:08", trainType: .express),
        ExactRun("13:12", trainType: .semiExpress),
        ExactRun("13:21", trainType: .express),
        ExactRun("13:28", trainType: .express),
        ExactRun("13:32", trainType: .semiExpress),
        ExactRun("13:41", trainType: .express),
        ExactRun("13:48", trainType: .express),
        ExactRun("13:52", trainType: .semiExpress),
        ExactRun("14:01", trainType: .express),
        ExactRun("14:08", trainType: .express),
        ExactRun("14:12", trainType: .semiExpress),
        ExactRun("14:21", trainType: .express),
        ExactRun("14:28", trainType: .express),
        ExactRun("14:32", trainType: .semiExpress),
        ExactRun("14:41", trainType: .express),
        ExactRun("14:48", trainType: .express),
        ExactRun("14:52", trainType: .semiExpress),
        ExactRun("15:01", trainType: .express),
        ExactRun("15:08", trainType: .express),
        ExactRun("15:12", trainType: .semiExpress),
        ExactRun("15:21", trainType: .express),
        ExactRun("15:28", trainType: .express),
        ExactRun("15:32", trainType: .semiExpress),
        ExactRun("15:41", trainType: .express),
        ExactRun("15:48", trainType: .express),
        ExactRun("15:52", trainType: .semiExpress),
        ExactRun("16:01", trainType: .express),
        ExactRun("16:08", trainType: .express),
        ExactRun("16:12", trainType: .semiExpress),
        ExactRun("16:21", trainType: .express),
        ExactRun("16:28", trainType: .express),
        ExactRun("16:32", trainType: .semiExpress),
        ExactRun("16:46", trainType: .express),
        ExactRun("17:01", trainType: .express),
        ExactRun("17:16", trainType: .express),
        ExactRun("17:32", trainType: .express),
        ExactRun("17:45", trainType: .express),
        ExactRun("18:02", trainType: .express),
        ExactRun("18:17", trainType: .express),
        ExactRun("18:32", trainType: .express),
        ExactRun("18:47", trainType: .express),
        ExactRun("19:02", trainType: .express),
        ExactRun("19:17", trainType: .express),
        ExactRun("19:32", trainType: .express),
        ExactRun("19:47", trainType: .express),
        ExactRun("20:06", trainType: .express),
        ExactRun("20:23", trainType: .express),
        ExactRun("20:43", trainType: .express),
        ExactRun("21:00", trainType: .express),
        ExactRun("21:24", trainType: .express),
        ExactRun("21:51", trainType: .express),
        ExactRun("22:18", trainType: .express),
        ExactRun("22:47", trainType: .express),
    ]

    private static let meguroAscExpressWd: [ExactRun] = [
        ExactRun("05:41", trainType: .express),
        ExactRun("06:24", trainType: .express),
        ExactRun("06:55", trainType: .express),
        ExactRun("07:13", trainType: .express),
        ExactRun("07:39", trainType: .express),
        ExactRun("07:45", terminusStationId: "Station:Tokyu.Meguro.MusashiKosugi", trainType: .express),
        ExactRun("08:01", trainType: .express),
        ExactRun("08:06", terminusStationId: "Station:Tokyu.Meguro.MusashiKosugi", trainType: .express),
        ExactRun("08:12", trainType: .express),
        ExactRun("08:18", trainType: .express),
        ExactRun("08:25", trainType: .express),
        ExactRun("08:43", trainType: .express),
        ExactRun("08:51", trainType: .express),
        ExactRun("09:01", trainType: .express),
        ExactRun("09:10", trainType: .express),
        ExactRun("09:28", trainType: .express),
        ExactRun("10:00", trainType: .express),
        ExactRun("10:16", trainType: .express),
        ExactRun("10:29", trainType: .express),
        ExactRun("10:44", trainType: .express),
        ExactRun("10:59", trainType: .express),
        ExactRun("11:14", trainType: .express),
        ExactRun("11:29", trainType: .express),
        ExactRun("11:44", trainType: .express),
        ExactRun("11:59", trainType: .express),
        ExactRun("12:14", trainType: .express),
        ExactRun("12:29", trainType: .express),
        ExactRun("12:44", trainType: .express),
        ExactRun("12:59", trainType: .express),
        ExactRun("13:14", trainType: .express),
        ExactRun("13:29", trainType: .express),
        ExactRun("13:44", trainType: .express),
        ExactRun("13:59", trainType: .express),
        ExactRun("14:14", trainType: .express),
        ExactRun("14:29", trainType: .express),
        ExactRun("14:44", trainType: .express),
        ExactRun("14:59", trainType: .express),
        ExactRun("15:14", trainType: .express),
        ExactRun("15:29", trainType: .express),
        ExactRun("15:44", trainType: .express),
        ExactRun("15:59", trainType: .express),
        ExactRun("16:14", trainType: .express),
        ExactRun("16:29", trainType: .express),
        ExactRun("16:44", trainType: .express),
        ExactRun("16:59", trainType: .express),
        ExactRun("17:15", trainType: .express),
        ExactRun("17:32", trainType: .express),
        ExactRun("17:49", trainType: .express),
        ExactRun("18:06", trainType: .express),
        ExactRun("18:21", trainType: .express),
        ExactRun("18:35", trainType: .express),
        ExactRun("18:50", trainType: .express),
        ExactRun("19:05", trainType: .express),
        ExactRun("19:20", trainType: .express),
        ExactRun("19:36", trainType: .express),
        ExactRun("19:50", trainType: .express),
        ExactRun("20:05", trainType: .express),
        ExactRun("20:20", trainType: .express),
        ExactRun("20:36", trainType: .express),
        ExactRun("20:50", trainType: .express),
        ExactRun("21:06", trainType: .express),
        ExactRun("21:19", trainType: .express),
        ExactRun("21:36", trainType: .express),
        ExactRun("21:52", trainType: .express),
        ExactRun("22:08", trainType: .express),
        ExactRun("22:23", trainType: .express),
        ExactRun("23:02", trainType: .express),
        ExactRun("23:35", trainType: .express),
    ]

    private static let meguroAscExpressHol: [ExactRun] = [
        ExactRun("05:41", trainType: .express),
        ExactRun("06:24", trainType: .express),
        ExactRun("07:26", trainType: .express),
        ExactRun("07:59", trainType: .express),
        ExactRun("08:13", trainType: .express),
        ExactRun("08:28", trainType: .express),
        ExactRun("08:43", trainType: .express),
        ExactRun("08:58", trainType: .express),
        ExactRun("09:14", trainType: .express),
        ExactRun("09:29", trainType: .express),
        ExactRun("09:44", trainType: .express),
        ExactRun("09:59", trainType: .express),
        ExactRun("10:14", trainType: .express),
        ExactRun("10:30", trainType: .express),
        ExactRun("10:44", trainType: .express),
        ExactRun("10:59", trainType: .express),
        ExactRun("11:14", trainType: .express),
        ExactRun("11:29", trainType: .express),
        ExactRun("11:44", trainType: .express),
        ExactRun("11:59", trainType: .express),
        ExactRun("12:14", trainType: .express),
        ExactRun("12:29", trainType: .express),
        ExactRun("12:44", trainType: .express),
        ExactRun("12:59", trainType: .express),
        ExactRun("13:14", trainType: .express),
        ExactRun("13:29", trainType: .express),
        ExactRun("13:44", trainType: .express),
        ExactRun("13:59", trainType: .express),
        ExactRun("14:14", trainType: .express),
        ExactRun("14:29", trainType: .express),
        ExactRun("14:44", trainType: .express),
        ExactRun("14:59", trainType: .express),
        ExactRun("15:14", trainType: .express),
        ExactRun("15:29", trainType: .express),
        ExactRun("15:44", trainType: .express),
        ExactRun("15:59", trainType: .express),
        ExactRun("16:14", trainType: .express),
        ExactRun("16:29", trainType: .express),
        ExactRun("16:44", trainType: .express),
        ExactRun("16:59", trainType: .express),
        ExactRun("17:14", trainType: .express),
        ExactRun("17:29", trainType: .express),
        ExactRun("17:44", trainType: .express),
        ExactRun("17:59", trainType: .express),
        ExactRun("18:14", trainType: .express),
        ExactRun("18:29", trainType: .express),
        ExactRun("18:44", trainType: .express),
        ExactRun("18:59", trainType: .express),
        ExactRun("19:14", trainType: .express),
        ExactRun("19:29", trainType: .express),
        ExactRun("19:59", trainType: .express),
        ExactRun("20:31", trainType: .express),
        ExactRun("21:00", trainType: .express),
        ExactRun("21:24", trainType: .express),
        ExactRun("21:55", trainType: .express),
        ExactRun("22:25", trainType: .express),
        ExactRun("23:22", terminusStationId: "Station:Tokyu.Meguro.MusashiKosugi", trainType: .express),
    ]

    private static let meguroDescExpressWd: [ExactRun] = [
        ExactRun("06:02", trainType: .express),
        ExactRun("06:11", trainType: .express),
        ExactRun("06:40", trainType: .express),
        ExactRun("06:55", trainType: .express),
        ExactRun("07:01", trainType: .express),
        ExactRun("07:14", trainType: .express),
        ExactRun("07:21", trainType: .express),
        ExactRun("07:31", trainType: .express),
        ExactRun("07:36", trainType: .express),
        ExactRun("07:46", trainType: .express),
        ExactRun("07:51", trainType: .express),
        ExactRun("07:56", trainType: .express),
        ExactRun("08:01", trainType: .express),
        ExactRun("08:06", trainType: .express),
        ExactRun("08:11", trainType: .express),
        ExactRun("08:21", trainType: .express),
        ExactRun("08:26", trainType: .express),
        ExactRun("08:33", trainType: .express),
        ExactRun("08:43", trainType: .express),
        ExactRun("08:53", trainType: .express),
        ExactRun("09:06", trainType: .express),
        ExactRun("09:17", trainType: .express),
        ExactRun("09:30", trainType: .express),
        ExactRun("09:45", trainType: .express),
        ExactRun("10:04", trainType: .express),
        ExactRun("10:19", trainType: .express),
        ExactRun("10:34", trainType: .express),
        ExactRun("10:49", trainType: .express),
        ExactRun("11:04", trainType: .express),
        ExactRun("11:19", trainType: .express),
        ExactRun("11:34", trainType: .express),
        ExactRun("11:49", trainType: .express),
        ExactRun("12:04", trainType: .express),
        ExactRun("12:19", trainType: .express),
        ExactRun("12:34", trainType: .express),
        ExactRun("12:49", trainType: .express),
        ExactRun("13:04", trainType: .express),
        ExactRun("13:19", trainType: .express),
        ExactRun("13:34", trainType: .express),
        ExactRun("13:49", trainType: .express),
        ExactRun("14:04", trainType: .express),
        ExactRun("14:19", trainType: .express),
        ExactRun("14:34", trainType: .express),
        ExactRun("14:49", trainType: .express),
        ExactRun("15:04", trainType: .express),
        ExactRun("15:19", trainType: .express),
        ExactRun("15:34", trainType: .express),
        ExactRun("15:49", trainType: .express),
        ExactRun("16:04", trainType: .express),
        ExactRun("16:19", trainType: .express),
        ExactRun("16:34", trainType: .express),
        ExactRun("16:48", trainType: .express),
        ExactRun("17:02", trainType: .express),
        ExactRun("17:14", trainType: .express),
        ExactRun("17:31", trainType: .express),
        ExactRun("17:43", trainType: .express),
        ExactRun("17:54", trainType: .express),
        ExactRun("18:13", trainType: .express),
        ExactRun("18:28", trainType: .express),
        ExactRun("18:44", trainType: .express),
        ExactRun("18:58", trainType: .express),
        ExactRun("19:14", trainType: .express),
        ExactRun("19:29", trainType: .express),
        ExactRun("19:42", trainType: .express),
        ExactRun("19:57", trainType: .express),
        ExactRun("20:12", trainType: .express),
        ExactRun("20:29", trainType: .express),
        ExactRun("20:44", trainType: .express),
        ExactRun("20:59", trainType: .express),
        ExactRun("21:16", trainType: .express),
        ExactRun("21:31", trainType: .express),
        ExactRun("21:44", trainType: .express),
        ExactRun("23:19", trainType: .express),
    ]

    private static let meguroDescExpressHol: [ExactRun] = [
        ExactRun("07:24", trainType: .express),
        ExactRun("08:01", trainType: .express),
        ExactRun("08:17", trainType: .express),
        ExactRun("08:31", trainType: .express),
        ExactRun("08:48", trainType: .express),
        ExactRun("09:03", trainType: .express),
        ExactRun("09:18", trainType: .express),
        ExactRun("09:33", trainType: .express),
        ExactRun("09:48", trainType: .express),
        ExactRun("10:03", trainType: .express),
        ExactRun("10:18", trainType: .express),
        ExactRun("10:33", trainType: .express),
        ExactRun("10:49", trainType: .express),
        ExactRun("11:04", trainType: .express),
        ExactRun("11:19", trainType: .express),
        ExactRun("11:34", trainType: .express),
        ExactRun("11:49", trainType: .express),
        ExactRun("12:04", trainType: .express),
        ExactRun("12:19", trainType: .express),
        ExactRun("12:34", trainType: .express),
        ExactRun("12:49", trainType: .express),
        ExactRun("13:04", trainType: .express),
        ExactRun("13:19", trainType: .express),
        ExactRun("13:34", trainType: .express),
        ExactRun("13:49", trainType: .express),
        ExactRun("14:04", trainType: .express),
        ExactRun("14:19", trainType: .express),
        ExactRun("14:34", trainType: .express),
        ExactRun("14:49", trainType: .express),
        ExactRun("15:04", trainType: .express),
        ExactRun("15:19", trainType: .express),
        ExactRun("15:34", trainType: .express),
        ExactRun("15:49", trainType: .express),
        ExactRun("16:04", trainType: .express),
        ExactRun("16:19", trainType: .express),
        ExactRun("16:34", trainType: .express),
        ExactRun("16:49", trainType: .express),
        ExactRun("17:04", trainType: .express),
        ExactRun("17:19", trainType: .express),
        ExactRun("17:34", trainType: .express),
        ExactRun("17:49", trainType: .express),
        ExactRun("18:04", trainType: .express),
        ExactRun("18:19", trainType: .express),
        ExactRun("18:33", trainType: .express),
        ExactRun("18:49", trainType: .express),
        ExactRun("19:15", trainType: .express),
        ExactRun("19:45", trainType: .express),
        ExactRun("20:11", trainType: .express),
        ExactRun("20:47", trainType: .express),
        ExactRun("21:19", trainType: .express),
        ExactRun("21:47", trainType: .express),
        ExactRun("22:58", trainType: .express),
    ]
}
