import Foundation

extension TobuLineData {

    static let nikko = StaticTrainLine(
        id: "Railway:Tobu.Nikko",
        nameJa: "東武日光線",
        nameEn: "Tobu Nikko Line",
        operatorId: "Operator:Tobu",
        colorHex: "#FFA600",
        stations: [
            st("Tobu.Nikko", "TobuDobutsuKoen", "東武動物公園", "Tobu-Dobutsu-Koen", "TS30", 36.0208, 139.7292),
            st("Tobu.Nikko", "SugitoTakanodai", "杉戸高野台", "Sugito-Takanodai", "TN01", 36.0516, 139.7146),
            st("Tobu.Nikko", "Satte", "幸手", "Satte", "TN02", 36.0748, 139.7151),
            st("Tobu.Nikko", "MinamiKurihashi", "南栗橋", "Minami-Kurihashi", "TN03", 36.1132, 139.7129),
            st("Tobu.Nikko", "Kurihashi", "栗橋", "Kurihashi", "TN04", 36.1369, 139.6942),
            st("Tobu.Nikko", "ShinKoga", "新古河", "Shin-Koga", "TN05", 36.1927, 139.6869),
            st("Tobu.Nikko", "Yagyu", "柳生", "Yagyu", "TN06", 36.2066, 139.6596),
            st("Tobu.Nikko", "ItakuraToyodaimae", "板倉東洋大前", "Itakura-Toyodaimae", "TN07", 36.2221, 139.6485),
            st("Tobu.Nikko", "Fujioka", "藤岡", "Fujioka", "TN08", 36.2556, 139.6453),
            st("Tobu.Nikko", "Shizuwa", "静和", "Shizuwa", "TN09", 36.3170, 139.6851),
            st("Tobu.Nikko", "ShinOhirashita", "新大平下", "Shin-Ohirashita", "TN10", 36.3386, 139.7015),
            st("Tobu.Nikko", "Tochigi", "栃木", "Tochigi", "TN11", 36.3717, 139.7310),
            st("Tobu.Nikko", "ShinTochigi", "新栃木", "Shin-Tochigi", "TN12", 36.3897, 139.7423),
            st("Tobu.Nikko", "Kassemba", "合戦場", "Kassemba", "TN13", 36.4080, 139.7413),
            st("Tobu.Nikko", "Ienaka", "家中", "Ienaka", "TN14", 36.4293, 139.7474),
            st("Tobu.Nikko", "TobuKanasaki", "東武金崎", "Tobu-Kanasaki", "TN15", 36.4664, 139.7494),
            st("Tobu.Nikko", "Nireki", "楡木", "Nireki", "TN16", 36.5072, 139.7454),
            st("Tobu.Nikko", "Momiyama", "樅山", "Momiyama", "TN17", 36.5332, 139.7419),
            st("Tobu.Nikko", "ShinKanuma", "新鹿沼", "Shin-Kanuma", "TN18", 36.5572, 139.7450),
            st("Tobu.Nikko", "KitaKanuma", "北鹿沼", "Kita-Kanuma", "TN19", 36.5814, 139.7374),
            st("Tobu.Nikko", "Itaga", "板荷", "Itaga", "TN20", 36.6199, 139.7078),
            st("Tobu.Nikko", "ShimoGoshiro", "下小代", "Shimo-Goshiro", "TN21", 36.6510, 139.7137),
            st("Tobu.Nikko", "Myojin", "明神", "Myojin", "TN22", 36.6763, 139.7122),
            st("Tobu.Nikko", "ShimoImaichi", "下今市", "Shimo-Imaichi", "TN23", 36.7256, 139.6922),
            st("Tobu.Nikko", "KamiImaichi", "上今市", "Kami-Imaichi", "TN24", 36.7278, 139.6816),
            st("Tobu.Nikko", "TobuNikko", "東武日光", "Tobu-Nikko", "TN25", 36.7479, 139.6195),
        ],
        hopTimesMinutes: [
            4, 3, 6, 5, 9, 4, 3, 5, 10, 4, 6, 4, 3,
            3, 5, 6, 4, 3, 4, 7, 5, 4, 8, 2, 8,
        ],
        directions: [
            direction("Tobu.Nikko", "TobuNikko", "東武日光方面", "For Tobu-Nikko", ascending: true,
                      weekday: nikkoWeekday("05:48", "22:40"), holiday: nikkoHoliday("05:48", "22:40"),
                      origins: [
                          origin("Station:Tobu.Nikko.MinamiKurihashi",
                                 ["05:34", "06:00", "06:19", "06:33", "06:48", "07:03", "07:07", "07:22", "07:38", "07:57", "08:03", "08:28", "08:48", "09:09", "09:38", "10:07", "10:46", "11:02", "11:32", "12:02", "12:32", "13:02", "13:32", "14:02", "14:32", "15:02", "15:32", "16:03", "16:24", "16:47", "17:08", "17:30", "17:48", "18:12", "18:35", "18:54", "19:13", "19:33", "19:53", "20:13", "20:32", "20:52", "21:13", "21:33", "21:53", "22:33", "23:07", "23:47"],
                                 ["05:34", "06:00", "06:19", "06:33", "06:48", "07:03", "07:07", "07:22", "07:38", "07:57", "08:03", "08:28", "08:48", "09:09", "09:38", "10:07", "10:46", "11:02", "11:32", "12:02", "12:32", "13:02", "13:32", "14:02", "14:32", "15:02", "15:32", "16:03", "16:24", "16:47", "17:08", "17:30", "17:48", "18:12", "18:35", "18:54", "19:13", "19:33", "19:53", "20:13", "20:32", "20:52", "21:13", "21:33", "21:53", "22:33", "23:07", "23:47"]),
                          origin("Station:Tobu.Nikko.Tochigi",
                                 ["05:30", "05:45", "06:43", "08:02", "15:40", "22:17", "23:17"],
                                 ["05:30", "05:45", "06:43", "08:02", "15:40", "22:17", "23:17"]),
                          origin("Station:Tobu.Nikko.ShinTochigi",
                                 ["05:07", "07:01", "11:32", "18:55"],
                                 ["05:07", "07:01", "11:32", "18:55"]),
                          origin("Station:Tobu.Nikko.ShimoImaichi",
                                 ["08:26", "09:15", "10:15", "10:49", "11:08", "14:14", "15:25", "22:07"],
                                 ["08:26", "09:15", "10:15", "10:49", "11:08", "14:14", "15:25", "22:07"])
                      ,
                          originRuns("Station:Tobu.Nikko.MinamiKurihashi",
                                     nikkoAscExpressWd_org3, nikkoAscExpressHol_org3)
                      ],
                      expressWeekday: nikkoAscExpressWd,
                      expressHoliday: nikkoAscExpressHol
            ),
            direction("Tobu.Nikko", "TobuDobutsuKoen", "東武動物公園方面", "For Tobu-Dobutsu-Koen", ascending: false,
                      weekday: nikkoWeekday("05:00", "22:30"), holiday: nikkoHoliday("05:00", "22:30"),
                      origins: [
                          origin("Station:Tobu.Nikko.MinamiKurihashi",
                                 ["04:59", "05:09", "05:23", "05:38", "05:48", "05:55", "05:59", "06:14", "06:23", "06:33", "06:39", "06:45", "06:50", "06:53", "06:58", "07:05", "07:15", "07:20", "07:28", "07:37", "07:41", "07:54", "08:08", "08:22", "08:28", "08:51", "09:17", "09:32", "09:52", "10:14", "10:39", "10:56", "11:18", "11:38", "11:56", "12:18", "12:38", "12:56", "13:18", "13:38", "13:56", "14:18", "14:36", "14:58", "15:21", "15:38", "15:55", "16:09", "16:18", "16:38", "16:49", "17:12", "17:25", "17:33", "17:53", "18:11", "18:26", "18:53", "19:01", "19:11", "19:32", "19:48", "19:53", "20:11", "20:24", "20:42", "21:05", "21:30", "21:48", "22:11", "22:23", "22:45", "22:59", "23:18"],
                                 ["04:59", "05:09", "05:23", "05:38", "05:59", "06:10", "06:23", "06:33", "06:39", "06:42", "06:53", "06:59", "07:07", "07:16", "07:27", "07:40", "07:54", "08:05", "08:21", "08:35", "08:51", "09:02", "09:12", "09:31", "09:40", "09:52", "10:15", "10:39", "10:56", "11:18", "11:38", "11:56", "12:18", "12:38", "12:56", "13:18", "13:38", "13:56", "14:18", "14:36", "14:58", "15:21", "15:38", "15:55", "16:09", "16:18", "16:38", "16:49", "17:11", "17:33", "17:53", "18:11", "18:26", "18:52", "19:11", "19:32", "19:53", "19:59", "20:11", "20:27", "20:42", "21:03", "21:10", "21:18", "21:33", "21:48", "22:07", "22:23", "22:45", "22:59", "23:18"]),
                          origin("Station:Tobu.Nikko.ShinTochigi",
                                 ["04:58", "05:19", "05:39", "05:42", "06:12", "06:32", "07:00", "07:38", "08:16", "09:10", "10:30", "10:57", "11:24", "12:30", "14:30", "15:46", "16:16", "17:25", "17:59", "18:45", "19:30", "20:00", "21:20", "22:08"],
                                 ["04:58", "05:19", "05:39", "05:42", "06:12", "06:32", "07:00", "07:38", "08:16", "09:10", "10:30", "10:57", "11:24", "12:30", "14:30", "15:46", "16:16", "17:25", "17:59", "18:45", "19:30", "20:00", "21:20", "22:08"]),
                          origin("Station:Tobu.Nikko.ShinKanuma",
                                 ["05:10", "07:28"],
                                 ["05:10", "07:28"]),
                          origin("Station:Tobu.Nikko.ShimoImaichi",
                                 ["06:25", "07:02", "09:34", "10:52", "11:35", "12:35", "14:35", "15:21", "15:50", "16:34", "17:02", "19:21", "19:53"],
                                 ["06:25", "07:02", "09:34", "10:52", "11:35", "12:35", "14:35", "15:21", "15:50", "16:34", "17:02", "19:21", "19:53"])
                      ,
                          originRuns("Station:Tobu.Nikko.MinamiKurihashi",
                                     nikkoDescExpressWd_org3, nikkoDescExpressHol_org3)
                      ]
            ),
        ],
        delayInfo: delayInfo,
        throughServices: [
            through("Tobu.Nikko.TobuDobutsuKoen", .descending,
                    "東武スカイツリーライン", "Tobu Skytree Line",
                    "北千住・浅草方面", "for Kita-Senju & Asakusa",
                    to: "Railway:Tobu.TobuSkytree"),
            through("Tobu.Nikko.ShimoImaichi", .ascending,
                    "東武鬼怒川線", "Tobu Kinugawa Line",
                    "鬼怒川温泉方面", "for Kinugawa-Onsen"),
        ]
    )

    // MARK: Tobu Nikko Line (TN)

    private static func nikkoWeekday(_ first: String, _ last: String) -> ServicePattern {
        pattern(first, last, [
            (first, 30), ("06:30", 20), ("09:30", 40), ("17:00", 30), ("20:00", 40),
        ])
    }

    private static func nikkoHoliday(_ first: String, _ last: String) -> ServicePattern {
        pattern(first, last, [
            (first, 40),
        ])
    }

    // MARK: - Tobu Nikko Express Runs (ODPT, July-2026)


private static let nikkoAscExpressHol: [ExactRun] = [
    ExactRun("05:48", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .sectionExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("06:07", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .semiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("06:36", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("06:51", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .semiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("07:24", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .sectionSemiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("07:59", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .semiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("08:14", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .sectionExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("08:33", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("08:44", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("09:01", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("09:18", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .sectionSemiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("09:24", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("09:42", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .semiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("09:54", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .sectionSemiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("10:12", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .sectionSemiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("10:24", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("10:39", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .semiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("10:45", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .sectionExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("11:01", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("11:20", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("11:42", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("12:01", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("12:20", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("12:42", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("13:01", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("13:20", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("13:42", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("14:01", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("14:20", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("14:42", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("15:01", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("15:20", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("15:51", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("16:12", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("16:31", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("16:51", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("17:13", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("17:31", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("17:54", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("18:16", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("18:32", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("18:56", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("19:16", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("19:34", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("19:56", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("20:20", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("20:33", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("20:55", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("21:16", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("21:33", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("22:13", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .semiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("22:21", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("22:47", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .semiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("23:00", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .semiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("23:10", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .semiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("23:21", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .semiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("23:35", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .semiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("23:55", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .semiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("24:06", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .semiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("24:21", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .semiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("24:38", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
]

private static let nikkoAscExpressHol_org3: [ExactRun] = [
    ExactRun("07:03", trainType: .express, stopIndices: [3, 4, 7, 10, 11, 12, 18, 23, 25]),
    ExactRun("08:03", trainType: .express, stopIndices: [3, 4, 7, 10, 11, 12, 18, 23, 25]),
]

private static let nikkoAscExpressWd: [ExactRun] = [
    ExactRun("05:48", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .sectionExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("06:07", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .semiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("06:51", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .semiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("07:24", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .sectionSemiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("07:59", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .semiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("08:14", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("08:21", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .semiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("08:36", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("08:53", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("09:01", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("09:26", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("09:31", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .sectionExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("09:52", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .semiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("10:02", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("10:12", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("10:16", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .sectionSemiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("10:24", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("10:42", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("11:01", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("11:20", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("11:43", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("12:01", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("12:20", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("12:42", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("13:01", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("13:20", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("13:42", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("14:01", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("14:20", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("14:42", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("15:01", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("15:20", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("15:51", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("16:12", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("16:31", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("16:51", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("17:09", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("17:31", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("17:54", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("17:59", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .sectionSemiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("18:16", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("18:32", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("18:51", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .sectionSemiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("18:55", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("19:16", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("19:34", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("19:46", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .sectionSemiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("19:56", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("20:13", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .sectionSemiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("20:20", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("20:33", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("20:46", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .sectionSemiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("20:56", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("21:16", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("21:33", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("21:45", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .sectionSemiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("21:59", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .semiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("22:21", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
    ExactRun("22:29", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .semiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("22:47", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .semiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("23:00", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .semiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("23:10", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .semiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("23:21", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .semiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("23:35", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .semiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("23:55", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .semiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("24:11", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .semiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("24:30", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .semiExpress, stopIndices: [0, 1, 2, 3]),
    ExactRun("24:38", terminusStationId: "Station:Tobu.Nikko.MinamiKurihashi", startsHere: false, trainType: .express, stopIndices: [0, 1, 2, 3]),
]

private static let nikkoAscExpressWd_org3: [ExactRun] = [
    ExactRun("07:03", trainType: .express, stopIndices: [3, 4, 7, 10, 11, 12, 18, 23, 25]),
    ExactRun("08:03", trainType: .express, stopIndices: [3, 4, 7, 10, 11, 12, 18, 23, 25]),
]

private static let nikkoDescExpressHol_org3: [ExactRun] = [
    ExactRun("04:59", continuesBeyond: true, trainType: .semiExpress, stopIndices: [3, 2, 1, 0]),
    ExactRun("05:09", continuesBeyond: true, trainType: .semiExpress, stopIndices: [3, 2, 1, 0]),
    ExactRun("05:23", continuesBeyond: true, trainType: .semiExpress, stopIndices: [3, 2, 1, 0]),
    ExactRun("05:38", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("05:59", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("06:10", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("06:23", continuesBeyond: true, trainType: .semiExpress, stopIndices: [3, 2, 1, 0]),
    ExactRun("06:33", continuesBeyond: true, trainType: .sectionExpress, stopIndices: [3, 2, 1, 0]),
    ExactRun("06:42", continuesBeyond: true, trainType: .semiExpress, stopIndices: [3, 2, 1, 0]),
    ExactRun("06:59", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("07:07", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("07:16", continuesBeyond: true, trainType: .semiExpress, stopIndices: [3, 2, 1, 0]),
    ExactRun("07:27", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("07:54", continuesBeyond: true, trainType: .sectionExpress, stopIndices: [3, 2, 1, 0]),
    ExactRun("08:21", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("08:35", continuesBeyond: true, trainType: .sectionExpress, stopIndices: [3, 2, 1, 0]),
    ExactRun("09:02", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("09:12", continuesBeyond: true, trainType: .semiExpress, stopIndices: [3, 2, 1, 0]),
    ExactRun("09:31", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("09:40", continuesBeyond: true, trainType: .semiExpress, stopIndices: [3, 2, 1, 0]),
    ExactRun("09:52", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("10:15", continuesBeyond: true, trainType: .semiExpress, stopIndices: [3, 2, 1, 0]),
    ExactRun("10:39", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("10:56", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("11:18", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("11:38", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("11:56", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("12:18", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("12:38", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("12:56", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("13:18", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("13:38", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("13:56", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("14:18", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("14:36", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("14:58", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("15:21", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("15:38", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("15:55", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("16:18", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("16:38", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("17:11", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("17:33", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("17:53", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("18:11", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("18:26", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("18:52", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("19:11", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("19:32", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("19:53", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("20:11", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("20:42", continuesBeyond: true, trainType: .semiExpress, stopIndices: [3, 2, 1, 0]),
    ExactRun("21:03", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("21:18", continuesBeyond: true, trainType: .semiExpress, stopIndices: [3, 2, 1, 0]),
    ExactRun("21:33", continuesBeyond: true, trainType: .sectionSemiExpress, stopIndices: [3, 2, 1, 0]),
    ExactRun("21:48", continuesBeyond: true, trainType: .semiExpress, stopIndices: [3, 2, 1, 0]),
    ExactRun("22:07", continuesBeyond: true, trainType: .semiExpress, stopIndices: [3, 2, 1, 0]),
    ExactRun("22:23", continuesBeyond: true, trainType: .semiExpress, stopIndices: [3, 2, 1, 0]),
    ExactRun("23:18", continuesBeyond: true, trainType: .sectionSemiExpress, stopIndices: [3, 2, 1, 0]),
]

private static let nikkoDescExpressWd_org3: [ExactRun] = [
    ExactRun("04:59", continuesBeyond: true, trainType: .semiExpress, stopIndices: [3, 2, 1, 0]),
    ExactRun("05:09", continuesBeyond: true, trainType: .semiExpress, stopIndices: [3, 2, 1, 0]),
    ExactRun("05:23", continuesBeyond: true, trainType: .semiExpress, stopIndices: [3, 2, 1, 0]),
    ExactRun("05:38", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("05:48", continuesBeyond: true, trainType: .semiExpress, stopIndices: [3, 2, 1, 0]),
    ExactRun("05:55", continuesBeyond: true, trainType: .semiExpress, stopIndices: [3, 2, 1, 0]),
    ExactRun("05:59", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("06:14", continuesBeyond: true, trainType: .semiExpress, stopIndices: [3, 2, 1, 0]),
    ExactRun("06:23", continuesBeyond: true, trainType: .semiExpress, stopIndices: [3, 2, 1, 0]),
    ExactRun("06:33", continuesBeyond: true, trainType: .semiExpress, stopIndices: [3, 2, 1, 0]),
    ExactRun("06:45", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("06:53", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("06:58", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("07:05", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("07:15", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("07:28", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("07:37", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("07:54", continuesBeyond: true, trainType: .sectionExpress, stopIndices: [3, 2, 1, 0]),
    ExactRun("08:22", continuesBeyond: true, trainType: .semiExpress, stopIndices: [3, 2, 1, 0]),
    ExactRun("08:28", continuesBeyond: true, trainType: .sectionExpress, stopIndices: [3, 2, 1, 0]),
    ExactRun("08:51", continuesBeyond: true, trainType: .semiExpress, stopIndices: [3, 2, 1, 0]),
    ExactRun("09:17", continuesBeyond: true, trainType: .semiExpress, stopIndices: [3, 2, 1, 0]),
    ExactRun("09:52", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("10:14", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("10:39", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("10:56", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("11:18", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("11:38", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("11:56", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("12:18", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("12:38", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("12:56", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("13:18", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("13:38", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("13:56", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("14:18", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("14:36", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("14:58", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("15:21", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("15:38", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("15:55", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("16:18", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("16:38", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("17:12", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("17:25", continuesBeyond: true, trainType: .sectionSemiExpress, stopIndices: [3, 2, 1, 0]),
    ExactRun("17:33", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("17:53", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("18:11", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("18:26", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("18:53", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("19:11", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("19:32", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("19:53", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("20:11", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("20:24", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("20:42", continuesBeyond: true, trainType: .semiExpress, stopIndices: [3, 2, 1, 0]),
    ExactRun("21:05", continuesBeyond: true, trainType: .semiExpress, stopIndices: [3, 2, 1, 0]),
    ExactRun("21:30", continuesBeyond: true, trainType: .express, stopIndices: [3, 2, 1, 0]),
    ExactRun("21:48", continuesBeyond: true, trainType: .semiExpress, stopIndices: [3, 2, 1, 0]),
    ExactRun("22:11", continuesBeyond: true, trainType: .semiExpress, stopIndices: [3, 2, 1, 0]),
    ExactRun("22:23", continuesBeyond: true, trainType: .semiExpress, stopIndices: [3, 2, 1, 0]),
    ExactRun("22:59", continuesBeyond: true, trainType: .semiExpress, stopIndices: [3, 2, 1, 0]),
    ExactRun("23:18", continuesBeyond: true, trainType: .sectionSemiExpress, stopIndices: [3, 2, 1, 0]),
]

}
