import Foundation

extension OdakyuLineData {

    static let enoshima = StaticTrainLine(
        id: "Railway:Odakyu.Enoshima",
        nameJa: "小田急江ノ島線",
        nameEn: "Odakyu Enoshima Line",
        operatorId: "Operator:Odakyu",
        colorHex: "#0085CE",
        stations: [
            st("Odakyu.Enoshima", "SagamiOno", "相模大野", "Sagami-Ono", "OH28", 35.5318, 139.4383),
            st("Odakyu.Enoshima", "HigashiRinkan", "東林間", "Higashi-Rinkan", "OE01", 35.5203, 139.4365),
            st("Odakyu.Enoshima", "ChuoRinkan", "中央林間", "Chuo-Rinkan", "OE02", 35.5079, 139.4443),
            st("Odakyu.Enoshima", "MinamiRinkan", "南林間", "Minami-Rinkan", "OE03", 35.4974, 139.4483),
            st("Odakyu.Enoshima", "Tsuruma", "鶴間", "Tsuruma", "OE04", 35.4879, 139.4514),
            st("Odakyu.Enoshima", "Yamato", "大和", "Yamato", "OE05", 35.4691, 139.4599),
            st("Odakyu.Enoshima", "Sakuragaoka", "桜ヶ丘", "Sakuragaoka", "OE06", 35.4520, 139.4635),
            st("Odakyu.Enoshima", "KozaShibuya", "高座渋谷", "Koza-Shibuya", "OE07", 35.4319, 139.4620),
            st("Odakyu.Enoshima", "Chogo", "長後", "Chogo", "OE08", 35.4177, 139.4661),
            st("Odakyu.Enoshima", "Shonandai", "湘南台", "Shonandai", "OE09", 35.3953, 139.4668),
            st("Odakyu.Enoshima", "MutsuaiNichidaimae", "六会日大前", "Mutsuai-Nichidai-mae", "OE10", 35.3820, 139.4665),
            st("Odakyu.Enoshima", "Zengyo", "善行", "Zengyo", "OE11", 35.3652, 139.4699),
            st("Odakyu.Enoshima", "FujisawaHommachi", "藤沢本町", "Fujisawa-Hommachi", "OE12", 35.3502, 139.4770),
            st("Odakyu.Enoshima", "Fujisawa", "藤沢", "Fujisawa", "OE13", 35.3387, 139.4872),
            st("Odakyu.Enoshima", "HonKugenuma", "本鵠沼", "Hon-Kugenuma", "OE14", 35.3269, 139.4816),
            st("Odakyu.Enoshima", "KugenumaKaigan", "鵠沼海岸", "Kugenuma-Kaigan", "OE15", 35.3162, 139.4788),
            st("Odakyu.Enoshima", "KataseEnoshima", "片瀬江ノ島", "Katase-Enoshima", "OE16", 35.3096, 139.4791),
        ],
        hopTimesMinutes: [3.5, 2.5, 2.5, 1.5, 3.5, 2.5, 3.5, 2.5, 3.5, 2.5, 2.5, 2.5, 3.5, 2.5, 2.5, 2.5],
        directions: [
            direction("Odakyu.Enoshima", "KataseEnoshima", "藤沢・片瀬江ノ島方面", "For Fujisawa & Katase-Enoshima", ascending: true,
                      weekday: enoshimaDownWeekday, holiday: enoshimaDownHoliday,
                      expressWeekday: enoshimaDownExpWd,
                      expressHoliday: enoshimaDownExpHol),
            direction("Odakyu.Enoshima", "SagamiOno", "相模大野方面", "For Sagami-Ono", ascending: false,
                      weekday: enoshimaUpWeekday, holiday: enoshimaUpHoliday,
                      origins: [
                          originRuns("Station:Odakyu.Enoshima.Yamato",
                                     enoshimaUpExpWd_yamato, []),
                          originRuns("Station:Odakyu.Enoshima.Fujisawa",
                                     enoshimaUpExpWd_fujisawa, enoshimaUpExpHol_fujisawa),
                      ],
                      expressWeekday: enoshimaUpExpWd,
                      expressHoliday: enoshimaUpExpHol),
        ],
        delayInfo: delayInfo,
        throughServices: [
            through("Odakyu.Enoshima.SagamiOno", .descending,
                    "小田急小田原線", "Odakyu Odawara Line",
                    "町田・新宿方面", "for Machida & Shinjuku",
                    to: "Railway:Odakyu.Odawara"),
        ],
        // 停車駅 (absolute station indices), ODPT-derived (see Odawara note).
        // 快速急行 skips 南林間/長後; 急行 adds them + 片瀬江ノ島 (藤沢 switchback).
        stopPatterns: [
            .express: [0, 2, 3, 5, 8, 9, 13, 16],
            .rapidExpress: [0, 2, 5, 9, 13],
        ]
    )

    // counts: {'rapidExpress': 2, 'express': 1}

    private static let enoshimaDownExpWd: [ExactRun] = [
        ExactRun("05:30", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", trainType: .express),
        ExactRun("05:54", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", trainType: .express),
        ExactRun("06:03", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", trainType: .express),
        ExactRun("06:20", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", trainType: .express),
        ExactRun("06:29", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", trainType: .express),
        ExactRun("06:40", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", trainType: .express),
        ExactRun("06:51", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .express),
        ExactRun("06:59", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", trainType: .express),
        ExactRun("07:07", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .express),
        ExactRun("07:26", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", trainType: .express),
        ExactRun("07:46", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .express),
        ExactRun("08:10", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .express),
        ExactRun("08:33", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .express),
        ExactRun("08:46", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("09:06", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("09:27", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("09:47", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("10:06", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("10:24", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("10:45", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("11:04", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("11:24", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("11:44", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("12:04", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("12:24", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("12:44", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("13:04", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("13:24", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("13:44", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("14:04", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("14:24", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("14:44", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("15:04", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("15:24", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("15:44", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("16:04", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("16:24", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("16:44", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("17:04", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("17:24", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("17:45", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("18:06", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("18:29", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("18:48", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("19:08", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("19:29", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("19:48", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("20:08", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("20:29", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("20:48", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("21:06", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("21:29", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("21:47", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("22:06", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("22:27", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("22:56", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("23:22", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
    ]

    // counts: {'express': 13, 'rapidExpress': 44}

    private static let enoshimaDownExpHol: [ExactRun] = [
        ExactRun("05:30", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", trainType: .express),
        ExactRun("06:06", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", trainType: .express),
        ExactRun("06:37", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .express),
        ExactRun("07:06", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", trainType: .express),
        ExactRun("07:21", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .express),
        ExactRun("07:39", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .express),
        ExactRun("07:56", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("08:25", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("08:44", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("09:05", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("09:24", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("09:45", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("10:05", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("10:25", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("10:44", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("11:06", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("11:25", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("11:49", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("12:05", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("12:24", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("12:44", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("13:04", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("13:25", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("13:44", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("14:04", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("14:24", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("14:44", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("15:04", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("15:24", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("15:44", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("16:04", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("16:24", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("16:46", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("17:06", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("17:26", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("17:46", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("18:06", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("18:26", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("18:46", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("19:06", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("19:26", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("19:45", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("20:05", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("20:24", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("20:46", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("21:05", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("21:25", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("21:46", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("22:05", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("22:24", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("22:54", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
        ExactRun("23:21", terminusStationId: "Station:Odakyu.Enoshima.Fujisawa", startsHere: false, trainType: .rapidExpress),
    ]

    // counts: {'express': 6, 'rapidExpress': 46}

    private static let enoshimaUpExpWd: [ExactRun] = [
        ExactRun("05:09", continuesBeyond: true, trainType: .express),
    ]

    // counts: {'express': 1}

    private static let enoshimaUpExpHol: [ExactRun] = [
        ExactRun("05:11", continuesBeyond: true, trainType: .express),
    ]

    // counts: {'express': 1}

    private static let enoshimaUpExpWd_yamato: [ExactRun] = [
        ExactRun("05:55", continuesBeyond: true, trainType: .express),
    ]

    // counts: {'express': 1}

    private static let enoshimaUpExpWd_fujisawa: [ExactRun] = [
        ExactRun("06:03", continuesBeyond: true, trainType: .express),
        ExactRun("06:24", continuesBeyond: true, trainType: .express),
        ExactRun("06:42", continuesBeyond: true, trainType: .express),
        ExactRun("06:52", continuesBeyond: true, trainType: .express),
        ExactRun("07:02", continuesBeyond: true, trainType: .express),
        ExactRun("07:12", continuesBeyond: true, trainType: .express),
        ExactRun("07:22", continuesBeyond: true, trainType: .express),
        ExactRun("07:32", continuesBeyond: true, trainType: .express),
        ExactRun("07:42", continuesBeyond: true, trainType: .express),
        ExactRun("08:01", continuesBeyond: true, trainType: .express),
        ExactRun("08:21", continuesBeyond: true, trainType: .express),
        ExactRun("08:38", continuesBeyond: true, trainType: .express),
        ExactRun("09:00", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("09:17", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("09:36", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("09:56", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("10:16", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("10:36", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("10:56", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("11:16", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("11:36", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("11:56", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("12:16", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("12:36", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("12:56", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("13:16", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("13:36", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("13:56", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("14:16", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("14:36", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("14:56", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("15:16", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("15:36", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("15:56", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("16:16", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("16:29", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("16:49", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("17:09", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("17:29", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("17:49", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("18:12", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("18:32", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("19:01", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("19:12", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("19:32", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("20:00", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("20:12", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("20:32", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("21:00", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("21:13", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("21:35", continuesBeyond: true, trainType: .express),
        ExactRun("22:06", continuesBeyond: true, trainType: .express),
        ExactRun("22:45", continuesBeyond: true, trainType: .express),
        ExactRun("23:07", continuesBeyond: true, trainType: .express),
    ]

    // counts: {'express': 16, 'rapidExpress': 38}

    private static let enoshimaUpExpHol_fujisawa: [ExactRun] = [
        ExactRun("06:17", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("06:52", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("07:14", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("07:35", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("07:55", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("08:11", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("08:25", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("08:57", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("09:15", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("09:35", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("09:57", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("10:16", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("10:36", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("10:57", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("11:16", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("11:37", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("11:56", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("12:16", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("12:35", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("12:56", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("13:15", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("13:36", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("13:56", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("14:16", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("14:36", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("14:56", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("15:15", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("15:36", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("15:56", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("16:13", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("16:36", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("16:56", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("17:15", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("17:36", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("17:56", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("18:15", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("18:36", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("18:56", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("19:13", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("19:36", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("19:56", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("20:15", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("20:36", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("20:52", continuesBeyond: true, trainType: .express),
        ExactRun("21:14", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("21:35", continuesBeyond: true, trainType: .express),
        ExactRun("22:05", continuesBeyond: true, trainType: .express),
        ExactRun("22:45", continuesBeyond: true, trainType: .express),
        ExactRun("23:07", continuesBeyond: true, trainType: .express),
    ]

    // MARK: Odakyu Enoshima Line (OE)

    private static let enoshimaDownWeekday = pattern("05:00", "24:30", [
        ("05:00", 8), ("06:30", 5), ("09:30", 8), ("16:30", 6), ("20:00", 8), ("22:00", 10),
    ])

    private static let enoshimaDownHoliday = pattern("05:00", "24:30", [
        ("05:00", 8), ("07:00", 7), ("10:00", 8), ("20:00", 9),
    ])

    private static let enoshimaUpWeekday = pattern("05:00", "24:18", [
        ("05:00", 10), ("09:30", 11), ("22:00", 12),
    ])

    private static let enoshimaUpHoliday = pattern("05:00", "24:18", [
        ("05:00", 10), ("10:00", 11), ("20:00", 12),
    ])

}
