import Foundation

extension OdakyuLineData {

    static let tama = StaticTrainLine(
        id: "Railway:Odakyu.Tama",
        nameJa: "小田急多摩線",
        nameEn: "Odakyu Tama Line",
        operatorId: "Operator:Odakyu",
        colorHex: "#0085CE",
        stations: [
            st("Odakyu.Tama", "ShinYurigaoka", "新百合ヶ丘", "Shin-Yurigaoka", "OH23", 35.6039, 139.5083),
            st("Odakyu.Tama", "Satsukidai", "五月台", "Satsukidai", "OT01", 35.6008, 139.4979),
            st("Odakyu.Tama", "Kurihira", "栗平", "Kurihira", "OT02", 35.5983, 139.4855),
            st("Odakyu.Tama", "Kurokawa", "黒川", "Kurokawa", "OT03", 35.5985, 139.4732),
            st("Odakyu.Tama", "Haruhino", "はるひ野", "Haruhino", "OT04", 35.5990, 139.4635),
            st("Odakyu.Tama", "OdakyuNagayama", "小田急永山", "Odakyu-Nagayama", "OT05", 35.6187, 139.4462),
            st("Odakyu.Tama", "OdakyuTamaCenter", "小田急多摩センター", "Odakyu-Tama-Center", "OT06", 35.6244, 139.4243),
            st("Odakyu.Tama", "Karakida", "唐木田", "Karakida", "OT07", 35.6146, 139.4110),
        ],
        hopTimesMinutes: [2.5, 1.5, 1.5, 1.5, 2.5, 2.5, 2.5],
        directions: [
            direction("Odakyu.Tama", "Karakida", "唐木田方面", "For Karakida", ascending: true,
                      weekday: tamaDownWeekday, holiday: tamaDownHoliday,
                      expressWeekday: tamaDownExpWd,
                      expressHoliday: tamaDownExpHol),
            direction("Odakyu.Tama", "ShinYurigaoka", "新百合ヶ丘方面", "For Shin-Yurigaoka", ascending: false,
                      weekday: tamaUpWeekday, holiday: tamaUpHoliday,
                      origins: [
                          originRuns("Station:Odakyu.Tama.OdakyuTamaCenter",
                                     tamaUpExpWd_odakyuTamaCenter, []),
                      ],
                      expressWeekday: tamaUpExpWd,
                      expressHoliday: tamaUpExpHol),
        ],
        delayInfo: delayInfo,
        throughServices: [
            through("Odakyu.Tama.ShinYurigaoka", .descending,
                    "小田急小田原線", "Odakyu Odawara Line",
                    "新宿・千代田線方面", "for Shinjuku & the Chiyoda Line",
                    to: "Railway:Odakyu.Odawara"),
        ],
        // 停車駅 (absolute station indices), ODPT-derived (see Odawara note).
        // 急行 is all-stops within the Tama Line; 快速急行/通勤急行 skip
        // 五月台/黒川/はるひ野.
        stopPatterns: [
            .express: [0, 1, 2, 3, 4, 5, 6, 7],
            .rapidExpress: [0, 2, 5, 6, 7],
            .commuterExpress: [2, 5, 6, 7],
        ]
    )

    // counts: {'rapidExpress': 44, 'express': 5}

    private static let tamaDownExpWd: [ExactRun] = [
        ExactRun("07:51", startsHere: false, trainType: .rapidExpress),
        ExactRun("08:12", startsHere: false, trainType: .rapidExpress),
        ExactRun("08:32", startsHere: false, trainType: .express),
        ExactRun("08:46", startsHere: false, trainType: .rapidExpress),
        ExactRun("09:07", startsHere: false, trainType: .rapidExpress),
        ExactRun("09:22", startsHere: false, trainType: .express),
        ExactRun("09:42", startsHere: false, trainType: .express),
        ExactRun("09:53", startsHere: false, trainType: .express),
        ExactRun("10:02", startsHere: false, trainType: .express),
        ExactRun("10:12", startsHere: false, trainType: .express),
        ExactRun("10:22", startsHere: false, trainType: .express),
        ExactRun("10:32", startsHere: false, trainType: .express),
        ExactRun("10:42", startsHere: false, trainType: .express),
        ExactRun("11:02", startsHere: false, trainType: .express),
        ExactRun("11:12", startsHere: false, trainType: .express),
        ExactRun("11:22", startsHere: false, trainType: .express),
        ExactRun("11:32", startsHere: false, trainType: .express),
        ExactRun("11:42", startsHere: false, trainType: .express),
        ExactRun("11:52", startsHere: false, trainType: .express),
        ExactRun("12:02", startsHere: false, trainType: .express),
        ExactRun("12:12", startsHere: false, trainType: .express),
        ExactRun("12:22", startsHere: false, trainType: .express),
        ExactRun("12:32", startsHere: false, trainType: .express),
        ExactRun("12:42", startsHere: false, trainType: .express),
        ExactRun("12:52", startsHere: false, trainType: .express),
        ExactRun("13:02", startsHere: false, trainType: .express),
        ExactRun("13:12", startsHere: false, trainType: .express),
        ExactRun("13:22", startsHere: false, trainType: .express),
        ExactRun("13:32", startsHere: false, trainType: .express),
        ExactRun("13:42", startsHere: false, trainType: .express),
        ExactRun("13:52", startsHere: false, trainType: .express),
        ExactRun("14:02", startsHere: false, trainType: .express),
        ExactRun("14:12", startsHere: false, trainType: .express),
        ExactRun("14:22", startsHere: false, trainType: .express),
        ExactRun("14:32", startsHere: false, trainType: .express),
        ExactRun("14:42", startsHere: false, trainType: .express),
        ExactRun("14:52", startsHere: false, trainType: .express),
        ExactRun("15:02", startsHere: false, trainType: .express),
        ExactRun("15:12", startsHere: false, trainType: .express),
        ExactRun("15:22", startsHere: false, trainType: .express),
        ExactRun("15:32", startsHere: false, trainType: .express),
        ExactRun("15:42", startsHere: false, trainType: .express),
        ExactRun("15:52", startsHere: false, trainType: .express),
        ExactRun("16:02", startsHere: false, trainType: .express),
        ExactRun("16:12", startsHere: false, trainType: .express),
        ExactRun("16:22", startsHere: false, trainType: .express),
        ExactRun("16:42", startsHere: false, trainType: .express),
        ExactRun("17:02", startsHere: false, trainType: .express),
        ExactRun("17:23", startsHere: false, trainType: .express),
        ExactRun("17:43", startsHere: false, trainType: .express),
        ExactRun("18:02", startsHere: false, trainType: .express),
        ExactRun("18:22", startsHere: false, trainType: .express),
        ExactRun("18:42", startsHere: false, trainType: .express),
        ExactRun("19:02", startsHere: false, trainType: .express),
        ExactRun("19:22", startsHere: false, trainType: .express),
        ExactRun("19:42", startsHere: false, trainType: .express),
        ExactRun("20:03", startsHere: false, trainType: .express),
        ExactRun("20:22", startsHere: false, trainType: .express),
        ExactRun("20:42", startsHere: false, trainType: .express),
        ExactRun("21:04", startsHere: false, trainType: .express),
        ExactRun("21:24", startsHere: false, trainType: .express),
        ExactRun("21:44", startsHere: false, trainType: .express),
        ExactRun("22:03", startsHere: false, trainType: .express),
        ExactRun("22:23", startsHere: false, trainType: .express),
        ExactRun("22:33", startsHere: false, trainType: .rapidExpress),
        ExactRun("22:47", startsHere: false, trainType: .express),
        ExactRun("23:01", startsHere: false, trainType: .express),
    ]

    // counts: {'rapidExpress': 5, 'express': 62}

    private static let tamaDownExpHol: [ExactRun] = [
        ExactRun("07:42", startsHere: false, trainType: .express),
        ExactRun("08:02", startsHere: false, trainType: .express),
        ExactRun("08:22", startsHere: false, trainType: .express),
        ExactRun("08:42", startsHere: false, trainType: .express),
        ExactRun("09:02", startsHere: false, trainType: .express),
        ExactRun("09:22", startsHere: false, trainType: .express),
        ExactRun("09:44", startsHere: false, trainType: .express),
        ExactRun("10:06", startsHere: false, trainType: .express),
        ExactRun("10:15", startsHere: false, trainType: .express),
        ExactRun("10:25", startsHere: false, trainType: .express),
        ExactRun("10:46", startsHere: false, trainType: .express),
        ExactRun("11:06", startsHere: false, trainType: .express),
        ExactRun("11:25", startsHere: false, trainType: .express),
        ExactRun("11:45", startsHere: false, trainType: .express),
        ExactRun("11:55", startsHere: false, trainType: .express),
        ExactRun("12:03", startsHere: false, trainType: .express),
        ExactRun("12:13", startsHere: false, trainType: .express),
        ExactRun("12:23", startsHere: false, trainType: .express),
        ExactRun("12:33", startsHere: false, trainType: .express),
        ExactRun("12:43", startsHere: false, trainType: .express),
        ExactRun("12:53", startsHere: false, trainType: .express),
        ExactRun("13:03", startsHere: false, trainType: .express),
        ExactRun("13:13", startsHere: false, trainType: .express),
        ExactRun("13:23", startsHere: false, trainType: .express),
        ExactRun("13:33", startsHere: false, trainType: .express),
        ExactRun("13:43", startsHere: false, trainType: .express),
        ExactRun("13:53", startsHere: false, trainType: .express),
        ExactRun("14:03", startsHere: false, trainType: .express),
        ExactRun("14:13", startsHere: false, trainType: .express),
        ExactRun("14:23", startsHere: false, trainType: .express),
        ExactRun("14:33", startsHere: false, trainType: .express),
        ExactRun("14:43", startsHere: false, trainType: .express),
        ExactRun("14:53", startsHere: false, trainType: .express),
        ExactRun("15:03", startsHere: false, trainType: .express),
        ExactRun("15:13", startsHere: false, trainType: .express),
        ExactRun("15:23", startsHere: false, trainType: .express),
        ExactRun("15:33", startsHere: false, trainType: .express),
        ExactRun("15:43", startsHere: false, trainType: .express),
        ExactRun("15:53", startsHere: false, trainType: .express),
        ExactRun("16:03", startsHere: false, trainType: .express),
        ExactRun("16:13", startsHere: false, trainType: .express),
        ExactRun("16:23", startsHere: false, trainType: .express),
        ExactRun("16:33", startsHere: false, trainType: .express),
        ExactRun("16:43", startsHere: false, trainType: .express),
        ExactRun("17:03", startsHere: false, trainType: .express),
        ExactRun("17:13", startsHere: false, trainType: .express),
        ExactRun("17:22", startsHere: false, trainType: .express),
        ExactRun("17:43", startsHere: false, trainType: .express),
        ExactRun("18:03", startsHere: false, trainType: .express),
        ExactRun("18:24", startsHere: false, trainType: .express),
        ExactRun("18:43", startsHere: false, trainType: .express),
        ExactRun("19:03", startsHere: false, trainType: .express),
        ExactRun("19:24", startsHere: false, trainType: .express),
        ExactRun("19:33", startsHere: false, trainType: .express),
        ExactRun("19:43", startsHere: false, trainType: .express),
        ExactRun("20:02", startsHere: false, trainType: .express),
        ExactRun("20:22", startsHere: false, trainType: .express),
        ExactRun("20:42", startsHere: false, trainType: .express),
        ExactRun("21:02", startsHere: false, trainType: .express),
        ExactRun("21:22", startsHere: false, trainType: .express),
        ExactRun("21:43", startsHere: false, trainType: .express),
        ExactRun("22:02", startsHere: false, trainType: .express),
        ExactRun("22:23", startsHere: false, trainType: .express),
        ExactRun("22:45", startsHere: false, trainType: .express),
        ExactRun("23:30", startsHere: false, trainType: .express),
    ]

    // counts: {'express': 65}

    private static let tamaUpExpWd: [ExactRun] = [
        ExactRun("05:56", continuesBeyond: true, trainType: .express),
        ExactRun("06:11", continuesBeyond: true, trainType: .express),
        ExactRun("06:34", continuesBeyond: true, trainType: .commuterExpress),
        ExactRun("07:14", continuesBeyond: true, trainType: .commuterExpress),
        ExactRun("07:44", continuesBeyond: true, trainType: .commuterExpress),
        ExactRun("08:28", continuesBeyond: true, trainType: .express),
        ExactRun("08:56", continuesBeyond: true, trainType: .express),
        ExactRun("09:18", continuesBeyond: true, trainType: .express),
        ExactRun("09:41", continuesBeyond: true, trainType: .express),
        ExactRun("10:04", continuesBeyond: true, trainType: .express),
        ExactRun("10:14", continuesBeyond: true, trainType: .express),
        ExactRun("10:24", continuesBeyond: true, trainType: .express),
        ExactRun("10:34", continuesBeyond: true, trainType: .express),
        ExactRun("10:44", continuesBeyond: true, trainType: .express),
        ExactRun("10:54", continuesBeyond: true, trainType: .express),
        ExactRun("11:04", continuesBeyond: true, trainType: .express),
        ExactRun("11:14", continuesBeyond: true, trainType: .express),
        ExactRun("11:24", continuesBeyond: true, trainType: .express),
        ExactRun("11:34", continuesBeyond: true, trainType: .express),
        ExactRun("11:44", continuesBeyond: true, trainType: .express),
        ExactRun("11:54", continuesBeyond: true, trainType: .express),
        ExactRun("12:04", continuesBeyond: true, trainType: .express),
        ExactRun("12:14", continuesBeyond: true, trainType: .express),
        ExactRun("12:24", continuesBeyond: true, trainType: .express),
        ExactRun("12:34", continuesBeyond: true, trainType: .express),
        ExactRun("12:44", continuesBeyond: true, trainType: .express),
        ExactRun("12:54", continuesBeyond: true, trainType: .express),
        ExactRun("13:04", continuesBeyond: true, trainType: .express),
        ExactRun("13:14", continuesBeyond: true, trainType: .express),
        ExactRun("13:24", continuesBeyond: true, trainType: .express),
        ExactRun("13:34", continuesBeyond: true, trainType: .express),
        ExactRun("13:44", continuesBeyond: true, trainType: .express),
        ExactRun("13:54", continuesBeyond: true, trainType: .express),
        ExactRun("14:04", continuesBeyond: true, trainType: .express),
        ExactRun("14:14", continuesBeyond: true, trainType: .express),
        ExactRun("14:24", continuesBeyond: true, trainType: .express),
        ExactRun("14:34", continuesBeyond: true, trainType: .express),
        ExactRun("14:44", continuesBeyond: true, trainType: .express),
        ExactRun("14:54", continuesBeyond: true, trainType: .express),
        ExactRun("15:04", continuesBeyond: true, trainType: .express),
        ExactRun("15:14", continuesBeyond: true, trainType: .express),
        ExactRun("15:24", continuesBeyond: true, trainType: .express),
        ExactRun("15:34", continuesBeyond: true, trainType: .express),
        ExactRun("15:43", continuesBeyond: true, trainType: .express),
        ExactRun("15:54", continuesBeyond: true, trainType: .express),
        ExactRun("16:03", continuesBeyond: true, trainType: .express),
        ExactRun("16:14", continuesBeyond: true, trainType: .express),
        ExactRun("16:23", continuesBeyond: true, trainType: .express),
        ExactRun("16:34", continuesBeyond: true, trainType: .express),
        ExactRun("17:18", continuesBeyond: true, trainType: .express),
        ExactRun("17:25", continuesBeyond: true, trainType: .express),
        ExactRun("17:39", continuesBeyond: true, trainType: .express),
        ExactRun("17:59", continuesBeyond: true, trainType: .express),
        ExactRun("18:18", continuesBeyond: true, trainType: .express),
        ExactRun("18:38", continuesBeyond: true, trainType: .express),
        ExactRun("18:58", continuesBeyond: true, trainType: .express),
        ExactRun("19:10", continuesBeyond: true, trainType: .express),
        ExactRun("19:38", continuesBeyond: true, trainType: .express),
        ExactRun("20:02", continuesBeyond: true, trainType: .express),
        ExactRun("21:47", continuesBeyond: true, trainType: .express),
    ]

    // counts: {'express': 57, 'commuterExpress': 3}

    private static let tamaUpExpHol: [ExactRun] = [
        ExactRun("06:09", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("06:29", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("06:47", continuesBeyond: true, trainType: .express),
        ExactRun("07:03", continuesBeyond: true, trainType: .express),
        ExactRun("07:24", continuesBeyond: true, trainType: .express),
        ExactRun("07:43", continuesBeyond: true, trainType: .express),
        ExactRun("08:04", continuesBeyond: true, trainType: .express),
        ExactRun("08:24", continuesBeyond: true, trainType: .express),
        ExactRun("08:43", continuesBeyond: true, trainType: .express),
        ExactRun("09:04", continuesBeyond: true, trainType: .express),
        ExactRun("09:22", continuesBeyond: true, trainType: .express),
        ExactRun("09:31", continuesBeyond: true, trainType: .express),
        ExactRun("09:48", continuesBeyond: true, trainType: .express),
        ExactRun("10:08", continuesBeyond: true, trainType: .express),
        ExactRun("10:28", continuesBeyond: true, trainType: .express),
        ExactRun("10:49", continuesBeyond: true, trainType: .express),
        ExactRun("11:08", continuesBeyond: true, trainType: .express),
        ExactRun("11:38", continuesBeyond: true, trainType: .express),
        ExactRun("11:45", continuesBeyond: true, trainType: .express),
        ExactRun("11:55", continuesBeyond: true, trainType: .express),
        ExactRun("12:04", continuesBeyond: true, trainType: .express),
        ExactRun("12:14", continuesBeyond: true, trainType: .express),
        ExactRun("12:23", continuesBeyond: true, trainType: .express),
        ExactRun("12:33", continuesBeyond: true, trainType: .express),
        ExactRun("12:43", continuesBeyond: true, trainType: .express),
        ExactRun("12:53", continuesBeyond: true, trainType: .express),
        ExactRun("13:03", continuesBeyond: true, trainType: .express),
        ExactRun("13:14", continuesBeyond: true, trainType: .express),
        ExactRun("13:23", continuesBeyond: true, trainType: .express),
        ExactRun("13:33", continuesBeyond: true, trainType: .express),
        ExactRun("13:43", continuesBeyond: true, trainType: .express),
        ExactRun("13:53", continuesBeyond: true, trainType: .express),
        ExactRun("14:03", continuesBeyond: true, trainType: .express),
        ExactRun("14:13", continuesBeyond: true, trainType: .express),
        ExactRun("14:23", continuesBeyond: true, trainType: .express),
        ExactRun("14:33", continuesBeyond: true, trainType: .express),
        ExactRun("14:43", continuesBeyond: true, trainType: .express),
        ExactRun("14:53", continuesBeyond: true, trainType: .express),
        ExactRun("15:03", continuesBeyond: true, trainType: .express),
        ExactRun("15:13", continuesBeyond: true, trainType: .express),
        ExactRun("15:23", continuesBeyond: true, trainType: .express),
        ExactRun("15:33", continuesBeyond: true, trainType: .express),
        ExactRun("15:43", continuesBeyond: true, trainType: .express),
        ExactRun("15:53", continuesBeyond: true, trainType: .express),
        ExactRun("16:04", continuesBeyond: true, trainType: .express),
        ExactRun("16:13", continuesBeyond: true, trainType: .express),
        ExactRun("16:23", continuesBeyond: true, trainType: .express),
        ExactRun("16:33", continuesBeyond: true, trainType: .express),
        ExactRun("16:43", continuesBeyond: true, trainType: .express),
        ExactRun("17:03", continuesBeyond: true, trainType: .express),
        ExactRun("17:23", continuesBeyond: true, trainType: .express),
        ExactRun("17:44", continuesBeyond: true, trainType: .express),
        ExactRun("18:03", continuesBeyond: true, trainType: .express),
        ExactRun("18:24", continuesBeyond: true, trainType: .express),
        ExactRun("18:46", continuesBeyond: true, trainType: .express),
        ExactRun("19:04", continuesBeyond: true, trainType: .express),
        ExactRun("19:14", continuesBeyond: true, trainType: .express),
        ExactRun("19:23", continuesBeyond: true, trainType: .express),
        ExactRun("19:43", continuesBeyond: true, trainType: .express),
        ExactRun("20:04", continuesBeyond: true, trainType: .express),
        ExactRun("20:23", continuesBeyond: true, trainType: .express),
        ExactRun("20:43", continuesBeyond: true, trainType: .express),
        ExactRun("21:04", continuesBeyond: true, trainType: .express),
        ExactRun("21:23", continuesBeyond: true, trainType: .express),
        ExactRun("21:43", continuesBeyond: true, trainType: .express),
        ExactRun("22:04", continuesBeyond: true, trainType: .express),
    ]

    // counts: {'rapidExpress': 2, 'express': 64}

    private static let tamaUpExpWd_odakyuTamaCenter: [ExactRun] = [
        ExactRun("06:55", continuesBeyond: true, trainType: .commuterExpress),
        ExactRun("07:07", continuesBeyond: true, trainType: .commuterExpress),
        ExactRun("07:27", continuesBeyond: true, trainType: .commuterExpress),
        ExactRun("07:36", continuesBeyond: true, trainType: .commuterExpress),
        ExactRun("07:57", continuesBeyond: true, trainType: .commuterExpress),
        ExactRun("08:10", continuesBeyond: true, trainType: .commuterExpress),
    ]

    // MARK: Odakyu Tama Line (OT)

    private static let tamaDownWeekday = pattern("05:42", "24:45", [
        ("05:42", 10), ("06:30", 7.5), ("09:30", 10), ("16:30", 8), ("20:00", 10), ("22:00", 12),
    ])

    private static let tamaDownHoliday = pattern("05:42", "24:45", [
        ("05:42", 10), ("07:00", 8), ("10:00", 10), ("20:00", 11),
    ])

    private static let tamaUpWeekday = pattern("04:55", "24:07", [
        ("04:55", 10), ("06:30", 7.5), ("09:30", 10), ("16:30", 8), ("20:00", 10), ("22:00", 12),
    ])

    private static let tamaUpHoliday = pattern("04:55", "24:07", [
        ("04:55", 10), ("07:00", 8), ("10:00", 10), ("20:00", 11),
    ])

}
