import Foundation

extension OdakyuLineData {

    // MARK: Odakyu Odawara Line (OH)

    static let odawara = StaticTrainLine(
        id: "Railway:Odakyu.Odawara",
        nameJa: "小田急小田原線",
        nameEn: "Odakyu Odawara Line",
        operatorId: "Operator:Odakyu",
        colorHex: "#0085CE",
        stations: [
            st("Odakyu.Odawara", "Shinjuku", "新宿", "Shinjuku", "OH01", 35.6905, 139.6994),
            st("Odakyu.Odawara", "MinamiShinjuku", "南新宿", "Minami-Shinjuku", "OH02", 35.6842, 139.6980),
            st("Odakyu.Odawara", "Sangubashi", "参宮橋", "Sangubashi", "OH03", 35.6784, 139.6935),
            st("Odakyu.Odawara", "YoyogiHachiman", "代々木八幡", "Yoyogi-Hachiman", "OH04", 35.6690, 139.6890),
            st("Odakyu.Odawara", "YoyogiUehara", "代々木上原", "Yoyogi-Uehara", "OH05", 35.6690, 139.6799),
            st("Odakyu.Odawara", "HigashiKitazawa", "東北沢", "Higashi-Kitazawa", "OH06", 35.6663, 139.6740),
            st("Odakyu.Odawara", "ShimoKitazawa", "下北沢", "Shimo-Kitazawa", "OH07", 35.6614, 139.6667),
            st("Odakyu.Odawara", "SetagayaDaita", "世田谷代田", "Setagaya-Daita", "OH08", 35.6591, 139.6600),
            st("Odakyu.Odawara", "Umegaoka", "梅ヶ丘", "Umegaoka", "OH09", 35.6567, 139.6533),
            st("Odakyu.Odawara", "Gotokuji", "豪徳寺", "Gotokuji", "OH10", 35.6538, 139.6469),
            st("Odakyu.Odawara", "Kyodo", "経堂", "Kyodo", "OH11", 35.6510, 139.6363),
            st("Odakyu.Odawara", "ChitoseFunabashi", "千歳船橋", "Chitose-Funabashi", "OH12", 35.6484, 139.6252),
            st("Odakyu.Odawara", "SoshigayaOkura", "祖師ヶ谷大蔵", "Soshigaya-Okura", "OH13", 35.6459, 139.6127),
            st("Odakyu.Odawara", "SeijogakuenMae", "成城学園前", "Seijogakuen-mae", "OH14", 35.6404, 139.6004),
            st("Odakyu.Odawara", "Kitami", "喜多見", "Kitami", "OH15", 35.6350, 139.5891),
            st("Odakyu.Odawara", "Komae", "狛江", "Komae", "OH16", 35.6317, 139.5786),
            st("Odakyu.Odawara", "IzumiTamagawa", "和泉多摩川", "Izumi-Tamagawa", "OH17", 35.6280, 139.5716),
            st("Odakyu.Odawara", "Noborito", "登戸", "Noborito", "OH18", 35.6205, 139.5702),
            st("Odakyu.Odawara", "MukogaokaYuen", "向ヶ丘遊園", "Mukogaoka-Yuen", "OH19", 35.6172, 139.5648),
            st("Odakyu.Odawara", "Ikuta", "生田", "Ikuta", "OH20", 35.6146, 139.5427),
            st("Odakyu.Odawara", "YomiurilandMae", "読売ランド前", "Yomiuriland-mae", "OH21", 35.6130, 139.5278),
            st("Odakyu.Odawara", "Yurigaoka", "百合ヶ丘", "Yurigaoka", "OH22", 35.6083, 139.5175),
            st("Odakyu.Odawara", "ShinYurigaoka", "新百合ヶ丘", "Shin-Yurigaoka", "OH23", 35.6039, 139.5083),
            st("Odakyu.Odawara", "Kakio", "柿生", "Kakio", "OH24", 35.5947, 139.5023),
            st("Odakyu.Odawara", "Tsurukawa", "鶴川", "Tsurukawa", "OH25", 35.5893, 139.4820),
            st("Odakyu.Odawara", "TamagawagakuenMae", "玉川学園前", "Tamagawagakuen-mae", "OH26", 35.5666, 139.4644),
            st("Odakyu.Odawara", "Machida", "町田", "Machida", "OH27", 35.5424, 139.4467),
            st("Odakyu.Odawara", "SagamiOno", "相模大野", "Sagami-Ono", "OH28", 35.5318, 139.4383),
            st("Odakyu.Odawara", "OdakyuSagamihara", "小田急相模原", "Odakyu-Sagamihara", "OH29", 35.5262, 139.4262),
            st("Odakyu.Odawara", "SobudaiMae", "相武台前", "Sobudai-mae", "OH30", 35.5165, 139.4083),
            st("Odakyu.Odawara", "Zama", "座間", "Zama", "OH31", 35.5085, 139.4009),
            st("Odakyu.Odawara", "Ebina", "海老名", "Ebina", "OH32", 35.4529, 139.3906),
            st("Odakyu.Odawara", "Atsugi", "厚木", "Atsugi", "OH33", 35.4406, 139.3719),
            st("Odakyu.Odawara", "HonAtsugi", "本厚木", "Hon-Atsugi", "OH34", 35.4394, 139.3648),
            st("Odakyu.Odawara", "AikoIshida", "愛甲石田", "Aiko-Ishida", "OH35", 35.4260, 139.3350),
            st("Odakyu.Odawara", "Isehara", "伊勢原", "Isehara", "OH36", 35.4030, 139.3149),
            st("Odakyu.Odawara", "TsurumakiOnsen", "鶴巻温泉", "Tsurumaki-Onsen", "OH37", 35.3877, 139.2760),
            st("Odakyu.Odawara", "Tokaidaigakumae", "東海大学前", "Tokaidaigaku-mae", "OH38", 35.3844, 139.2673),
            st("Odakyu.Odawara", "Hadano", "秦野", "Hadano", "OH39", 35.3714, 139.2245),
            st("Odakyu.Odawara", "Shibusawa", "渋沢", "Shibusawa", "OH40", 35.3617, 139.1830),
            st("Odakyu.Odawara", "ShinMatsuda", "新松田", "Shin-Matsuda", "OH41", 35.3437, 139.1408),
            st("Odakyu.Odawara", "Kaisei", "開成", "Kaisei", "OH42", 35.3299, 139.1332),
            st("Odakyu.Odawara", "Kayama", "栢山", "Kayama", "OH43", 35.3125, 139.1408),
            st("Odakyu.Odawara", "Tomizu", "富水", "Tomizu", "OH44", 35.3003, 139.1444),
            st("Odakyu.Odawara", "Hotaruda", "螢田", "Hotaruda", "OH45", 35.2894, 139.1477),
            st("Odakyu.Odawara", "Ashigara", "足柄", "Ashigara", "OH46", 35.2726, 139.1518),
            st("Odakyu.Odawara", "Odawara", "小田原", "Odawara", "OH47", 35.2563, 139.1552),
        ],
        hopTimesMinutes: [
            2, 1, 2, 1, 1, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 3, 2, 2, 2, 2,
            2, 3, 3, 3, 3, 2, 2, 4, 2, 2, 4.5, 6, 6, 3, 6, 6, 8, 3, 3, 3, 3, 3, 4.5,
        ],
        directions: [
            direction("Odakyu.Odawara", "Odawara", "小田原方面", "For Odawara", ascending: true,
                      weekday: odawaraDownWeekday, holiday: odawaraDownHoliday,
                      origins: [
                          originRuns("Station:Odakyu.Odawara.YoyogiUehara",
                                     odawaraDownExpWd_yoyogiUehara, odawaraDownExpHol_yoyogiUehara),
                          originRuns("Station:Odakyu.Odawara.Noborito",
                                     odawaraDownExpWd_noborito, []),
                          originRuns("Station:Odakyu.Odawara.Machida",
                                     odawaraDownExpWd_machida, odawaraDownExpHol_machida),
                          originRuns("Station:Odakyu.Odawara.SagamiOno",
                                     odawaraDownExpWd_sagamiOno, odawaraDownExpHol_sagamiOno),
                          originRuns("Station:Odakyu.Odawara.Ebina",
                                     odawaraDownExpWd_ebina, odawaraDownExpHol_ebina),
                          originRuns("Station:Odakyu.Odawara.HonAtsugi",
                                     [], odawaraDownExpHol_honAtsugi),
                          originRuns("Station:Odakyu.Odawara.Isehara",
                                     [], odawaraDownExpHol_isehara),
                      ],
                      expressWeekday: odawaraDownExpWd,
                      expressHoliday: odawaraDownExpHol),
            direction("Odakyu.Odawara", "Shinjuku", "新宿方面", "For Shinjuku", ascending: false,
                      weekday: odawaraUpWeekday, holiday: odawaraUpHoliday,
                      origins: [
                          originRuns("Station:Odakyu.Odawara.YoyogiUehara",
                                     [], odawaraUpExpHol_yoyogiUehara),
                          originRuns("Station:Odakyu.Odawara.SeijogakuenMae",
                                     odawaraUpExpWd_seijogakuenMae, odawaraUpExpHol_seijogakuenMae),
                          originRuns("Station:Odakyu.Odawara.MukogaokaYuen",
                                     odawaraUpExpWd_mukogaokaYuen, odawaraUpExpHol_mukogaokaYuen),
                          originRuns("Station:Odakyu.Odawara.ShinYurigaoka",
                                     odawaraUpExpWd_shinYurigaoka, odawaraUpExpHol_shinYurigaoka),
                          originRuns("Station:Odakyu.Odawara.Machida",
                                     [], odawaraUpExpHol_machida),
                          originRuns("Station:Odakyu.Odawara.SagamiOno",
                                     odawaraUpExpWd_sagamiOno, []),
                          originRuns("Station:Odakyu.Odawara.Ebina",
                                     odawaraUpExpWd_ebina, odawaraUpExpHol_ebina),
                          originRuns("Station:Odakyu.Odawara.HonAtsugi",
                                     odawaraUpExpWd_honAtsugi, odawaraUpExpHol_honAtsugi),
                          originRuns("Station:Odakyu.Odawara.Isehara",
                                     odawaraUpExpWd_isehara, []),
                          originRuns("Station:Odakyu.Odawara.ShinMatsuda",
                                     odawaraUpExpWd_shinMatsuda, odawaraUpExpHol_shinMatsuda),
                      ],
                      expressWeekday: odawaraUpExpWd,
                      expressHoliday: odawaraUpExpHol),
        ],
        delayInfo: delayInfo,
        throughServices: [
            through("Odakyu.Odawara.YoyogiUehara", .descending,
                    "東京メトロ千代田線", "Tokyo Metro Chiyoda Line",
                    "大手町・綾瀬方面", "for Otemachi & Ayase",
                    to: "Railway:TokyoMetro.Chiyoda"),
            through("Odakyu.Odawara.ShinYurigaoka", .ascending,
                    "小田急多摩線", "Odakyu Tama Line",
                    "唐木田方面", "for Karakida",
                    to: "Railway:Odakyu.Tama"),
            through("Odakyu.Odawara.SagamiOno", .ascending,
                    "小田急江ノ島線", "Odakyu Enoshima Line",
                    "藤沢・片瀬江ノ島方面", "for Fujisawa & Katase-Enoshima",
                    to: "Railway:Odakyu.Enoshima"),
            through("Odakyu.Odawara.Odawara", .ascending,
                    "箱根登山線", "Hakone Tozan Line",
                    "箱根湯本方面", "for Hakone-Yumoto"),
        ],
        // 停車駅 (absolute station indices). Derived from ODPT odpt:StationTimetable
        // per-station train-type presence (a type present in a station's official
        // timetable ⇔ it stops there), cross-checked vs Odakyu official station
        // timetables https://www.odakyu.jp/station/ . Patches: OH38 東海大学前 &
        // OH21 読売ランド前 have no ODPT timetable (filled from neighbours); 急行/
        // 快速急行 run local 本厚木→小田原 so include OH42–OH46.
        stopPatterns: [
            .express: [0, 4, 6, 10, 13, 17, 18, 22, 26, 27, 31, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
            .rapidExpress: [0, 4, 6, 17, 22, 26, 27, 31, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
            .semiExpress: [4, 6, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33],
            .commuterSemiExpress: [6, 10, 13, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
            .commuterExpress: [4, 6, 13, 18, 22],
        ]
    )

    // MARK: - Express runs (times/types/termini from ODPT odpt:StationTimetable;
    // stops from each line's stopPatterns). ロマンスカー特急 (paid) excluded.

    private static let odawaraDownExpWd: [ExactRun] = [
        ExactRun("05:27", trainType: .express),
        ExactRun("05:41", trainType: .express),
        ExactRun("05:52", trainType: .express),
        ExactRun("06:00", terminusStationId: "Station:Odakyu.Odawara.ShinMatsuda", trainType: .express),
        ExactRun("06:12", trainType: .express),
        ExactRun("06:20", trainType: .express),
        ExactRun("06:31", trainType: .express),
        ExactRun("06:41", trainType: .express),
        ExactRun("06:51", trainType: .express),
        ExactRun("07:02", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .express),
        ExactRun("07:11", trainType: .express),
        ExactRun("07:19", trainType: .express),
        ExactRun("07:28", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .express),
        ExactRun("07:34", trainType: .express),
        ExactRun("07:43", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("07:46", terminusStationId: "Station:Odakyu.Odawara.HonAtsugi", trainType: .express),
        ExactRun("07:53", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .express),
        ExactRun("07:57", trainType: .rapidExpress),
        ExactRun("08:03", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("08:07", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("08:13", trainType: .express),
        ExactRun("08:17", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("08:23", trainType: .express),
        ExactRun("08:26", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("08:33", trainType: .express),
        ExactRun("08:36", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("08:42", terminusStationId: "Station:Odakyu.Odawara.Isehara", trainType: .express),
        ExactRun("08:46", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("08:53", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("09:01", trainType: .rapidExpress),
        ExactRun("09:03", terminusStationId: "Station:Odakyu.Odawara.HonAtsugi", trainType: .express),
        ExactRun("09:11", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("09:13", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("09:21", trainType: .rapidExpress),
        ExactRun("09:23", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("09:30", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("09:31", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("09:37", trainType: .rapidExpress),
        ExactRun("09:41", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("09:50", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("09:53", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("10:01", trainType: .rapidExpress),
        ExactRun("10:10", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("10:12", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("10:21", trainType: .rapidExpress),
        ExactRun("10:30", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("10:31", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("10:41", trainType: .rapidExpress),
        ExactRun("10:50", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("10:51", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("11:01", trainType: .rapidExpress),
        ExactRun("11:10", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("11:11", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("11:21", trainType: .rapidExpress),
        ExactRun("11:30", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("11:31", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("11:41", trainType: .rapidExpress),
        ExactRun("11:50", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("11:51", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("12:01", trainType: .rapidExpress),
        ExactRun("12:10", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("12:11", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("12:21", trainType: .rapidExpress),
        ExactRun("12:30", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("12:31", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("12:41", trainType: .rapidExpress),
        ExactRun("12:50", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("12:51", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("13:01", trainType: .rapidExpress),
        ExactRun("13:10", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("13:11", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("13:21", trainType: .rapidExpress),
        ExactRun("13:30", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("13:31", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("13:41", trainType: .rapidExpress),
        ExactRun("13:50", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("13:51", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("14:01", trainType: .rapidExpress),
        ExactRun("14:10", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("14:11", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("14:21", trainType: .rapidExpress),
        ExactRun("14:30", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("14:31", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("14:41", trainType: .rapidExpress),
        ExactRun("14:50", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("14:51", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("15:01", trainType: .rapidExpress),
        ExactRun("15:10", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("15:11", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("15:21", trainType: .rapidExpress),
        ExactRun("15:30", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("15:31", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("15:41", terminusStationId: "Station:Odakyu.Odawara.ShinMatsuda", trainType: .rapidExpress),
        ExactRun("15:50", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("15:51", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("16:01", trainType: .rapidExpress),
        ExactRun("16:03", trainType: .express),
        ExactRun("16:10", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("16:11", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("16:21", trainType: .rapidExpress),
        ExactRun("16:23", trainType: .express),
        ExactRun("16:30", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("16:31", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("16:41", terminusStationId: "Station:Odakyu.Odawara.ShinMatsuda", trainType: .rapidExpress),
        ExactRun("16:43", trainType: .express),
        ExactRun("16:50", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("16:51", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("17:01", terminusStationId: "Station:Odakyu.Odawara.ShinMatsuda", trainType: .rapidExpress),
        ExactRun("17:03", trainType: .express),
        ExactRun("17:10", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("17:12", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("17:21", trainType: .rapidExpress),
        ExactRun("17:23", trainType: .express),
        ExactRun("17:30", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("17:33", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("17:41", terminusStationId: "Station:Odakyu.Odawara.ShinMatsuda", trainType: .rapidExpress),
        ExactRun("17:43", trainType: .express),
        ExactRun("17:50", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("17:53", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("18:01", terminusStationId: "Station:Odakyu.Odawara.ShinMatsuda", trainType: .rapidExpress),
        ExactRun("18:03", trainType: .express),
        ExactRun("18:10", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("18:13", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("18:21", trainType: .rapidExpress),
        ExactRun("18:23", trainType: .express),
        ExactRun("18:30", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("18:33", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("18:41", terminusStationId: "Station:Odakyu.Odawara.ShinMatsuda", trainType: .rapidExpress),
        ExactRun("18:43", trainType: .express),
        ExactRun("18:50", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("18:53", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("19:01", terminusStationId: "Station:Odakyu.Odawara.ShinMatsuda", trainType: .rapidExpress),
        ExactRun("19:03", trainType: .express),
        ExactRun("19:10", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("19:13", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("19:21", trainType: .rapidExpress),
        ExactRun("19:23", trainType: .express),
        ExactRun("19:30", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("19:33", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("19:41", terminusStationId: "Station:Odakyu.Odawara.ShinMatsuda", trainType: .rapidExpress),
        ExactRun("19:43", trainType: .express),
        ExactRun("19:50", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("19:53", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("20:01", terminusStationId: "Station:Odakyu.Odawara.ShinMatsuda", trainType: .rapidExpress),
        ExactRun("20:03", trainType: .express),
        ExactRun("20:10", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("20:13", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("20:21", trainType: .rapidExpress),
        ExactRun("20:23", trainType: .express),
        ExactRun("20:30", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("20:32", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("20:41", trainType: .rapidExpress),
        ExactRun("20:43", trainType: .express),
        ExactRun("20:50", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("20:52", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("21:01", trainType: .rapidExpress),
        ExactRun("21:10", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("21:12", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("21:21", trainType: .rapidExpress),
        ExactRun("21:30", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("21:31", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("21:41", trainType: .rapidExpress),
        ExactRun("21:50", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("21:51", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("22:01", trainType: .rapidExpress),
        ExactRun("22:08", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("22:14", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("22:21", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("22:31", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("22:41", trainType: .express),
        ExactRun("22:46", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("22:56", terminusStationId: "Station:Odakyu.Odawara.Isehara", trainType: .express),
        ExactRun("23:10", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", trainType: .express),
        ExactRun("23:22", trainType: .rapidExpress),
        ExactRun("23:34", terminusStationId: "Station:Odakyu.Odawara.HonAtsugi", trainType: .express),
        ExactRun("23:46", terminusStationId: "Station:Odakyu.Odawara.HonAtsugi", trainType: .express),
        ExactRun("24:00", terminusStationId: "Station:Odakyu.Odawara.Ebina", trainType: .express),
        ExactRun("24:15", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", trainType: .express),
        ExactRun("24:32", terminusStationId: "Station:Odakyu.Odawara.SeijogakuenMae", trainType: .express),
    ]

    // counts: {'express': 89, 'rapidExpress': 90}

    private static let odawaraDownExpHol: [ExactRun] = [
        ExactRun("05:27", terminusStationId: "Station:Odakyu.Odawara.ShinMatsuda", trainType: .express),
        ExactRun("05:40", trainType: .express),
        ExactRun("05:55", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .express),
        ExactRun("06:00", trainType: .express),
        ExactRun("06:11", terminusStationId: "Station:Odakyu.Odawara.ShinMatsuda", trainType: .express),
        ExactRun("06:21", trainType: .express),
        ExactRun("06:31", trainType: .express),
        ExactRun("06:41", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .express),
        ExactRun("06:51", trainType: .express),
        ExactRun("07:01", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .express),
        ExactRun("07:11", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("07:21", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("07:30", trainType: .rapidExpress),
        ExactRun("07:32", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("07:41", trainType: .rapidExpress),
        ExactRun("07:50", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("07:51", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("08:01", trainType: .rapidExpress),
        ExactRun("08:10", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("08:11", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("08:21", trainType: .rapidExpress),
        ExactRun("08:30", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("08:32", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("08:40", trainType: .rapidExpress),
        ExactRun("08:49", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("08:51", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("09:01", trainType: .rapidExpress),
        ExactRun("09:10", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("09:12", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("09:21", trainType: .rapidExpress),
        ExactRun("09:30", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("09:32", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("09:41", trainType: .rapidExpress),
        ExactRun("09:43", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("09:49", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("09:51", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("10:01", trainType: .rapidExpress),
        ExactRun("10:10", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("10:12", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("10:21", trainType: .rapidExpress),
        ExactRun("10:31", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("10:33", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("10:41", trainType: .rapidExpress),
        ExactRun("10:50", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("10:52", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("11:01", trainType: .rapidExpress),
        ExactRun("11:10", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("11:12", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("11:21", trainType: .rapidExpress),
        ExactRun("11:30", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("11:32", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("11:41", trainType: .rapidExpress),
        ExactRun("11:50", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("11:52", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("12:01", trainType: .rapidExpress),
        ExactRun("12:09", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("12:12", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("12:21", trainType: .rapidExpress),
        ExactRun("12:30", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("12:31", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("12:41", trainType: .rapidExpress),
        ExactRun("12:50", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("12:52", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("13:01", trainType: .rapidExpress),
        ExactRun("13:10", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("13:12", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("13:21", trainType: .rapidExpress),
        ExactRun("13:30", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("13:32", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("13:41", trainType: .rapidExpress),
        ExactRun("13:50", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("13:52", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("14:01", trainType: .rapidExpress),
        ExactRun("14:10", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("14:12", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("14:21", trainType: .rapidExpress),
        ExactRun("14:30", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("14:32", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("14:41", trainType: .rapidExpress),
        ExactRun("14:50", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("14:52", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("15:01", trainType: .rapidExpress),
        ExactRun("15:10", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("15:12", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("15:21", trainType: .rapidExpress),
        ExactRun("15:30", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("15:32", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("15:41", trainType: .rapidExpress),
        ExactRun("15:50", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("15:52", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("16:01", trainType: .rapidExpress),
        ExactRun("16:03", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("16:10", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("16:13", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("16:21", trainType: .rapidExpress),
        ExactRun("16:23", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", trainType: .express),
        ExactRun("16:30", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("16:33", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("16:41", trainType: .rapidExpress),
        ExactRun("16:43", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("16:50", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("16:53", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("17:01", trainType: .rapidExpress),
        ExactRun("17:03", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", trainType: .express),
        ExactRun("17:10", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("17:13", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("17:21", trainType: .rapidExpress),
        ExactRun("17:23", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", trainType: .express),
        ExactRun("17:30", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("17:33", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("17:41", trainType: .rapidExpress),
        ExactRun("17:43", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", trainType: .express),
        ExactRun("17:50", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("17:52", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("18:01", trainType: .rapidExpress),
        ExactRun("18:03", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", trainType: .express),
        ExactRun("18:10", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("18:13", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("18:21", trainType: .rapidExpress),
        ExactRun("18:23", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", trainType: .express),
        ExactRun("18:30", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("18:33", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("18:41", trainType: .rapidExpress),
        ExactRun("18:43", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", trainType: .express),
        ExactRun("18:50", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("18:52", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("19:01", trainType: .rapidExpress),
        ExactRun("19:09", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("19:11", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("19:21", trainType: .rapidExpress),
        ExactRun("19:30", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("19:31", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("19:41", trainType: .rapidExpress),
        ExactRun("19:50", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("19:51", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("20:01", trainType: .rapidExpress),
        ExactRun("20:10", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("20:12", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("20:21", trainType: .rapidExpress),
        ExactRun("20:30", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("20:31", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("20:41", terminusStationId: "Station:Odakyu.Odawara.ShinMatsuda", trainType: .rapidExpress),
        ExactRun("20:50", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("20:51", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("21:01", trainType: .rapidExpress),
        ExactRun("21:10", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("21:12", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("21:21", trainType: .rapidExpress),
        ExactRun("21:29", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("21:31", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("21:41", trainType: .rapidExpress),
        ExactRun("21:50", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("21:51", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("22:01", trainType: .rapidExpress),
        ExactRun("22:10", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", trainType: .rapidExpress),
        ExactRun("22:12", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("22:20", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("22:31", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", trainType: .express),
        ExactRun("22:41", trainType: .express),
        ExactRun("22:46", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .rapidExpress),
        ExactRun("22:54", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .express),
        ExactRun("23:10", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", trainType: .express),
        ExactRun("23:22", trainType: .rapidExpress),
        ExactRun("23:34", terminusStationId: "Station:Odakyu.Odawara.HonAtsugi", trainType: .express),
        ExactRun("23:46", terminusStationId: "Station:Odakyu.Odawara.HonAtsugi", trainType: .express),
        ExactRun("24:00", terminusStationId: "Station:Odakyu.Odawara.Ebina", trainType: .express),
        ExactRun("24:15", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", trainType: .express),
        ExactRun("24:32", terminusStationId: "Station:Odakyu.Odawara.SeijogakuenMae", trainType: .express),
    ]

    // counts: {'express': 75, 'rapidExpress': 93}

    private static let odawaraDownExpWd_yoyogiUehara: [ExactRun] = [
        ExactRun("06:38", terminusStationId: "Station:Odakyu.Odawara.MukogaokaYuen", trainType: .semiExpress),
        ExactRun("06:57", terminusStationId: "Station:Odakyu.Odawara.MukogaokaYuen", trainType: .semiExpress),
        ExactRun("07:09", terminusStationId: "Station:Odakyu.Odawara.MukogaokaYuen", trainType: .semiExpress),
        ExactRun("07:36", terminusStationId: "Station:Odakyu.Odawara.MukogaokaYuen", trainType: .semiExpress),
        ExactRun("09:39", terminusStationId: "Station:Odakyu.Odawara.MukogaokaYuen", trainType: .semiExpress),
        ExactRun("09:51", terminusStationId: "Station:Odakyu.Odawara.SeijogakuenMae", trainType: .semiExpress),
        ExactRun("10:39", terminusStationId: "Station:Odakyu.Odawara.SeijogakuenMae", trainType: .semiExpress),
        ExactRun("16:10", terminusStationId: "Station:Odakyu.Odawara.MukogaokaYuen", trainType: .semiExpress),
        ExactRun("16:27", terminusStationId: "Station:Odakyu.Odawara.SeijogakuenMae", trainType: .semiExpress),
        ExactRun("16:50", terminusStationId: "Station:Odakyu.Odawara.SeijogakuenMae", trainType: .semiExpress),
        ExactRun("17:08", terminusStationId: "Station:Odakyu.Odawara.MukogaokaYuen", trainType: .semiExpress),
        ExactRun("17:20", terminusStationId: "Station:Odakyu.Odawara.SeijogakuenMae", trainType: .semiExpress),
        ExactRun("17:30", terminusStationId: "Station:Odakyu.Odawara.MukogaokaYuen", trainType: .semiExpress),
        ExactRun("17:38", terminusStationId: "Station:Odakyu.Odawara.SeijogakuenMae", trainType: .semiExpress),
        ExactRun("17:47", terminusStationId: "Station:Odakyu.Odawara.MukogaokaYuen", trainType: .semiExpress),
        ExactRun("18:00", terminusStationId: "Station:Odakyu.Odawara.MukogaokaYuen", trainType: .semiExpress),
        ExactRun("18:20", terminusStationId: "Station:Odakyu.Odawara.MukogaokaYuen", trainType: .semiExpress),
        ExactRun("18:40", terminusStationId: "Station:Odakyu.Odawara.SeijogakuenMae", trainType: .semiExpress),
        ExactRun("18:47", terminusStationId: "Station:Odakyu.Odawara.MukogaokaYuen", trainType: .semiExpress),
        ExactRun("18:59", terminusStationId: "Station:Odakyu.Odawara.MukogaokaYuen", trainType: .semiExpress),
        ExactRun("19:20", terminusStationId: "Station:Odakyu.Odawara.MukogaokaYuen", trainType: .semiExpress),
        ExactRun("19:40", terminusStationId: "Station:Odakyu.Odawara.SeijogakuenMae", trainType: .semiExpress),
        ExactRun("19:47", terminusStationId: "Station:Odakyu.Odawara.MukogaokaYuen", trainType: .semiExpress),
        ExactRun("19:58", terminusStationId: "Station:Odakyu.Odawara.MukogaokaYuen", trainType: .semiExpress),
        ExactRun("20:20", terminusStationId: "Station:Odakyu.Odawara.SeijogakuenMae", trainType: .semiExpress),
        ExactRun("20:27", terminusStationId: "Station:Odakyu.Odawara.MukogaokaYuen", trainType: .semiExpress),
        ExactRun("20:36", terminusStationId: "Station:Odakyu.Odawara.MukogaokaYuen", trainType: .semiExpress),
        ExactRun("20:47", terminusStationId: "Station:Odakyu.Odawara.SeijogakuenMae", trainType: .semiExpress),
        ExactRun("21:00", terminusStationId: "Station:Odakyu.Odawara.HonAtsugi", trainType: .semiExpress),
        ExactRun("21:18", terminusStationId: "Station:Odakyu.Odawara.SeijogakuenMae", trainType: .semiExpress),
        ExactRun("21:40", terminusStationId: "Station:Odakyu.Odawara.MukogaokaYuen", trainType: .semiExpress),
        ExactRun("21:47", terminusStationId: "Station:Odakyu.Odawara.SeijogakuenMae", trainType: .semiExpress),
        ExactRun("23:28", terminusStationId: "Station:Odakyu.Odawara.SeijogakuenMae", trainType: .semiExpress),
    ]

    // counts: {'semiExpress': 33}

    private static let odawaraDownExpHol_yoyogiUehara: [ExactRun] = [
        ExactRun("08:47", terminusStationId: "Station:Odakyu.Odawara.SeijogakuenMae", trainType: .semiExpress),
        ExactRun("08:58", terminusStationId: "Station:Odakyu.Odawara.SeijogakuenMae", trainType: .semiExpress),
        ExactRun("09:48", terminusStationId: "Station:Odakyu.Odawara.SeijogakuenMae", trainType: .semiExpress),
        ExactRun("09:58", terminusStationId: "Station:Odakyu.Odawara.SeijogakuenMae", trainType: .semiExpress),
        ExactRun("10:28", terminusStationId: "Station:Odakyu.Odawara.SeijogakuenMae", trainType: .semiExpress),
        ExactRun("11:07", terminusStationId: "Station:Odakyu.Odawara.SeijogakuenMae", trainType: .semiExpress),
        ExactRun("16:12", terminusStationId: "Station:Odakyu.Odawara.MukogaokaYuen", trainType: .semiExpress),
        ExactRun("16:32", terminusStationId: "Station:Odakyu.Odawara.MukogaokaYuen", trainType: .semiExpress),
        ExactRun("16:52", terminusStationId: "Station:Odakyu.Odawara.MukogaokaYuen", trainType: .semiExpress),
        ExactRun("17:11", terminusStationId: "Station:Odakyu.Odawara.MukogaokaYuen", trainType: .semiExpress),
        ExactRun("17:32", terminusStationId: "Station:Odakyu.Odawara.MukogaokaYuen", trainType: .semiExpress),
        ExactRun("17:52", terminusStationId: "Station:Odakyu.Odawara.SeijogakuenMae", trainType: .semiExpress),
        ExactRun("18:12", terminusStationId: "Station:Odakyu.Odawara.MukogaokaYuen", trainType: .semiExpress),
        ExactRun("18:29", terminusStationId: "Station:Odakyu.Odawara.MukogaokaYuen", trainType: .semiExpress),
        ExactRun("18:49", terminusStationId: "Station:Odakyu.Odawara.SeijogakuenMae", trainType: .semiExpress),
        ExactRun("18:57", terminusStationId: "Station:Odakyu.Odawara.SeijogakuenMae", trainType: .semiExpress),
    ]

    // counts: {'semiExpress': 16}

    private static let odawaraDownExpWd_noborito: [ExactRun] = [
        ExactRun("07:44", terminusStationId: "Station:Odakyu.Odawara.ShinYurigaoka", continuesBeyond: true, trainType: .rapidExpress),
    ]

    // counts: {'rapidExpress': 1}

    private static let odawaraDownExpWd_machida: [ExactRun] = [
        ExactRun("06:45", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .express),
        ExactRun("07:05", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", continuesBeyond: true, trainType: .express),
        ExactRun("08:39", trainType: .express),
        ExactRun("10:05", trainType: .express),
        ExactRun("10:23", trainType: .express),
        ExactRun("10:40", trainType: .express),
        ExactRun("10:59", trainType: .express),
        ExactRun("11:19", trainType: .express),
        ExactRun("11:39", trainType: .express),
        ExactRun("11:59", trainType: .express),
        ExactRun("12:19", trainType: .express),
        ExactRun("12:39", trainType: .express),
        ExactRun("12:59", trainType: .express),
        ExactRun("13:19", trainType: .express),
        ExactRun("13:39", trainType: .express),
        ExactRun("13:59", trainType: .express),
        ExactRun("14:19", trainType: .express),
        ExactRun("14:39", trainType: .express),
        ExactRun("14:59", trainType: .express),
        ExactRun("15:19", trainType: .express),
        ExactRun("15:39", trainType: .express),
        ExactRun("15:59", trainType: .express),
    ]

    // counts: {'express': 22}

    private static let odawaraDownExpHol_machida: [ExactRun] = [
        ExactRun("07:40", trainType: .express),
        ExactRun("07:51", trainType: .express),
        ExactRun("08:23", trainType: .express),
        ExactRun("09:18", trainType: .express),
        ExactRun("09:59", trainType: .express),
        ExactRun("10:24", trainType: .express),
        ExactRun("10:40", trainType: .express),
        ExactRun("11:01", trainType: .express),
        ExactRun("11:19", trainType: .express),
        ExactRun("11:40", trainType: .express),
        ExactRun("11:59", trainType: .express),
        ExactRun("12:19", trainType: .express),
        ExactRun("12:39", trainType: .express),
        ExactRun("12:59", trainType: .express),
        ExactRun("13:19", trainType: .express),
        ExactRun("13:39", trainType: .express),
        ExactRun("13:59", trainType: .express),
        ExactRun("14:19", trainType: .express),
        ExactRun("14:39", trainType: .express),
        ExactRun("14:59", trainType: .express),
        ExactRun("15:19", trainType: .express),
        ExactRun("15:39", trainType: .express),
        ExactRun("15:59", trainType: .express),
        ExactRun("16:19", trainType: .express),
        ExactRun("16:45", trainType: .express),
        ExactRun("17:25", trainType: .express),
        ExactRun("17:45", trainType: .express),
        ExactRun("18:05", trainType: .express),
        ExactRun("18:25", trainType: .express),
        ExactRun("18:45", trainType: .express),
        ExactRun("19:05", trainType: .express),
        ExactRun("19:25", trainType: .express),
        ExactRun("19:40", trainType: .express),
        ExactRun("19:59", trainType: .express),
        ExactRun("20:59", trainType: .express),
        ExactRun("21:45", trainType: .express),
    ]

    // counts: {'express': 36}

    private static let odawaraDownExpWd_sagamiOno: [ExactRun] = [
        ExactRun("09:28", trainType: .express),
        ExactRun("09:48", trainType: .express),
        ExactRun("16:24", trainType: .express),
    ]

    // counts: {'express': 3}

    private static let odawaraDownExpHol_sagamiOno: [ExactRun] = [
        ExactRun("08:44", trainType: .express),
        ExactRun("09:05", trainType: .express),
        ExactRun("09:50", trainType: .express),
        ExactRun("17:08", trainType: .express),
        ExactRun("20:47", trainType: .express),
    ]

    // counts: {'express': 5}

    private static let odawaraDownExpWd_ebina: [ExactRun] = [
        ExactRun("05:05", trainType: .rapidExpress),
        ExactRun("05:51", trainType: .express),
    ]

    // counts: {'rapidExpress': 1, 'express': 1}

    private static let odawaraDownExpHol_ebina: [ExactRun] = [
        ExactRun("05:05", trainType: .rapidExpress),
        ExactRun("05:41", trainType: .express),
    ]

    // counts: {'rapidExpress': 1, 'express': 1}

    private static let odawaraDownExpHol_honAtsugi: [ExactRun] = [
        ExactRun("21:34", trainType: .express),
    ]

    // counts: {'express': 1}

    private static let odawaraDownExpHol_isehara: [ExactRun] = [
        ExactRun("22:26", trainType: .express),
    ]

    // counts: {'express': 1}

    private static let odawaraUpExpWd: [ExactRun] = [
        ExactRun("05:00", trainType: .rapidExpress),
        ExactRun("05:20", trainType: .rapidExpress),
        ExactRun("05:39", trainType: .rapidExpress),
        ExactRun("05:52", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", trainType: .express),
        ExactRun("06:01", trainType: .rapidExpress),
        ExactRun("06:13", trainType: .rapidExpress),
        ExactRun("06:24", trainType: .rapidExpress),
        ExactRun("06:35", trainType: .rapidExpress),
        ExactRun("06:44", trainType: .rapidExpress),
        ExactRun("06:55", trainType: .rapidExpress),
        ExactRun("07:04", trainType: .rapidExpress),
        ExactRun("07:19", trainType: .rapidExpress),
        ExactRun("07:39", trainType: .rapidExpress),
        ExactRun("07:49", trainType: .express),
        ExactRun("08:02", trainType: .rapidExpress),
        ExactRun("08:14", trainType: .express),
        ExactRun("08:28", trainType: .rapidExpress),
        ExactRun("08:37", trainType: .express),
        ExactRun("08:53", trainType: .rapidExpress),
        ExactRun("09:14", trainType: .rapidExpress),
        ExactRun("09:35", trainType: .rapidExpress),
        ExactRun("09:55", trainType: .rapidExpress),
        ExactRun("10:15", trainType: .rapidExpress),
        ExactRun("10:35", trainType: .rapidExpress),
        ExactRun("10:56", trainType: .rapidExpress),
        ExactRun("11:15", trainType: .rapidExpress),
        ExactRun("11:34", trainType: .rapidExpress),
        ExactRun("11:55", trainType: .rapidExpress),
        ExactRun("12:15", trainType: .rapidExpress),
        ExactRun("12:35", trainType: .rapidExpress),
        ExactRun("12:55", trainType: .rapidExpress),
        ExactRun("13:15", trainType: .rapidExpress),
        ExactRun("13:35", trainType: .rapidExpress),
        ExactRun("13:55", trainType: .rapidExpress),
        ExactRun("14:15", trainType: .rapidExpress),
        ExactRun("14:33", trainType: .rapidExpress),
        ExactRun("14:55", trainType: .rapidExpress),
        ExactRun("15:15", trainType: .rapidExpress),
        ExactRun("15:35", trainType: .rapidExpress),
        ExactRun("15:55", trainType: .express),
        ExactRun("16:04", trainType: .rapidExpress),
        ExactRun("16:26", trainType: .rapidExpress),
        ExactRun("16:42", trainType: .rapidExpress),
        ExactRun("17:01", trainType: .rapidExpress),
        ExactRun("17:17", trainType: .express),
        ExactRun("17:29", trainType: .rapidExpress),
        ExactRun("17:34", trainType: .express),
        ExactRun("17:49", trainType: .rapidExpress),
        ExactRun("18:07", trainType: .rapidExpress),
        ExactRun("18:17", trainType: .rapidExpress),
        ExactRun("18:34", trainType: .express),
        ExactRun("18:45", trainType: .rapidExpress),
        ExactRun("18:54", trainType: .express),
        ExactRun("19:17", trainType: .rapidExpress),
        ExactRun("19:36", trainType: .express),
        ExactRun("19:45", trainType: .rapidExpress),
        ExactRun("19:56", trainType: .express),
        ExactRun("20:18", trainType: .rapidExpress),
        ExactRun("20:35", trainType: .express),
        ExactRun("20:46", trainType: .express),
        ExactRun("21:02", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", trainType: .express),
        ExactRun("21:15", trainType: .express),
        ExactRun("21:55", trainType: .express),
        ExactRun("22:10", trainType: .express),
        ExactRun("22:31", trainType: .express),
        ExactRun("23:04", trainType: .express),
    ]

    // counts: {'rapidExpress': 47, 'express': 19}

    private static let odawaraUpExpHol: [ExactRun] = [
        ExactRun("05:00", trainType: .rapidExpress),
        ExactRun("05:27", trainType: .rapidExpress),
        ExactRun("05:43", terminusStationId: "Station:Odakyu.Odawara.HonAtsugi", trainType: .express),
        ExactRun("06:04", trainType: .rapidExpress),
        ExactRun("06:14", trainType: .rapidExpress),
        ExactRun("06:35", trainType: .rapidExpress),
        ExactRun("07:02", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", trainType: .express),
        ExactRun("07:14", trainType: .rapidExpress),
        ExactRun("07:23", terminusStationId: "Station:Odakyu.Odawara.SagamiOno", trainType: .express),
        ExactRun("07:35", trainType: .rapidExpress),
        ExactRun("08:06", trainType: .rapidExpress),
        ExactRun("08:14", trainType: .rapidExpress),
        ExactRun("08:35", trainType: .rapidExpress),
        ExactRun("08:54", trainType: .rapidExpress),
        ExactRun("09:14", trainType: .rapidExpress),
        ExactRun("09:35", trainType: .rapidExpress),
        ExactRun("09:55", trainType: .rapidExpress),
        ExactRun("10:15", trainType: .rapidExpress),
        ExactRun("10:35", trainType: .rapidExpress),
        ExactRun("10:49", trainType: .rapidExpress),
        ExactRun("11:15", trainType: .rapidExpress),
        ExactRun("11:33", trainType: .rapidExpress),
        ExactRun("11:56", trainType: .rapidExpress),
        ExactRun("12:10", trainType: .rapidExpress),
        ExactRun("12:35", trainType: .rapidExpress),
        ExactRun("12:55", trainType: .rapidExpress),
        ExactRun("13:13", trainType: .rapidExpress),
        ExactRun("13:33", trainType: .rapidExpress),
        ExactRun("13:50", trainType: .rapidExpress),
        ExactRun("14:12", trainType: .rapidExpress),
        ExactRun("14:30", trainType: .rapidExpress),
        ExactRun("14:55", trainType: .rapidExpress),
        ExactRun("15:13", trainType: .rapidExpress),
        ExactRun("15:32", trainType: .rapidExpress),
        ExactRun("15:54", trainType: .rapidExpress),
        ExactRun("16:13", trainType: .rapidExpress),
        ExactRun("16:34", trainType: .rapidExpress),
        ExactRun("16:55", trainType: .rapidExpress),
        ExactRun("17:14", trainType: .rapidExpress),
        ExactRun("17:35", trainType: .rapidExpress),
        ExactRun("17:52", trainType: .rapidExpress),
        ExactRun("18:14", trainType: .rapidExpress),
        ExactRun("18:35", trainType: .rapidExpress),
        ExactRun("18:51", trainType: .rapidExpress),
        ExactRun("19:15", trainType: .rapidExpress),
        ExactRun("19:35", trainType: .rapidExpress),
        ExactRun("19:55", trainType: .rapidExpress),
        ExactRun("20:15", trainType: .rapidExpress),
        ExactRun("20:34", trainType: .rapidExpress),
        ExactRun("21:14", trainType: .rapidExpress),
        ExactRun("21:33", terminusStationId: "Station:Odakyu.Odawara.HonAtsugi", trainType: .express),
        ExactRun("21:56", trainType: .express),
        ExactRun("22:28", trainType: .express),
        ExactRun("23:04", trainType: .express),
    ]

    // counts: {'rapidExpress': 47, 'express': 7}

    private static let odawaraUpExpHol_yoyogiUehara: [ExactRun] = [
        ExactRun("07:20", trainType: .express),
    ]

    // counts: {'express': 1}

    private static let odawaraUpExpWd_seijogakuenMae: [ExactRun] = [
        ExactRun("05:10", trainType: .express),
        ExactRun("06:01", trainType: .express),
        ExactRun("06:57", trainType: .commuterSemiExpress),
        ExactRun("07:16", trainType: .commuterSemiExpress),
        ExactRun("08:42", trainType: .semiExpress),
        ExactRun("09:01", trainType: .semiExpress),
        ExactRun("09:10", trainType: .semiExpress),
        ExactRun("09:45", trainType: .semiExpress),
        ExactRun("09:58", trainType: .semiExpress),
        ExactRun("10:08", trainType: .semiExpress),
        ExactRun("10:29", trainType: .semiExpress),
        ExactRun("18:03", trainType: .semiExpress),
        ExactRun("18:14", trainType: .semiExpress),
        ExactRun("18:33", trainType: .semiExpress),
    ]

    // counts: {'express': 2, 'commuterSemiExpress': 2, 'semiExpress': 10}

    private static let odawaraUpExpHol_seijogakuenMae: [ExactRun] = [
        ExactRun("05:10", trainType: .express),
        ExactRun("10:05", trainType: .semiExpress),
        ExactRun("10:45", trainType: .semiExpress),
        ExactRun("11:25", trainType: .semiExpress),
        ExactRun("18:41", trainType: .semiExpress),
    ]

    // counts: {'express': 1, 'semiExpress': 4}

    private static let odawaraUpExpWd_mukogaokaYuen: [ExactRun] = [
        ExactRun("08:59", trainType: .express),
        ExactRun("09:34", trainType: .express),
        ExactRun("09:59", trainType: .express),
        ExactRun("10:18", trainType: .express),
        ExactRun("16:00", trainType: .semiExpress),
        ExactRun("16:19", trainType: .semiExpress),
        ExactRun("16:40", trainType: .semiExpress),
        ExactRun("16:51", trainType: .semiExpress),
        ExactRun("18:37", trainType: .semiExpress),
        ExactRun("19:37", trainType: .semiExpress),
        ExactRun("19:56", trainType: .semiExpress),
        ExactRun("20:44", trainType: .semiExpress),
        ExactRun("21:04", trainType: .express),
        ExactRun("21:24", trainType: .express),
    ]

    // counts: {'express': 6, 'semiExpress': 8}

    private static let odawaraUpExpHol_mukogaokaYuen: [ExactRun] = [
        ExactRun("08:00", trainType: .express),
        ExactRun("08:40", trainType: .express),
        ExactRun("09:00", trainType: .express),
        ExactRun("10:16", trainType: .semiExpress),
        ExactRun("10:56", trainType: .semiExpress),
        ExactRun("11:36", trainType: .semiExpress),
        ExactRun("17:19", trainType: .express),
        ExactRun("17:39", trainType: .express),
        ExactRun("17:59", trainType: .express),
        ExactRun("18:19", trainType: .express),
        ExactRun("19:01", trainType: .semiExpress),
        ExactRun("19:19", trainType: .express),
        ExactRun("20:02", trainType: .express),
        ExactRun("20:20", trainType: .express),
        ExactRun("20:41", trainType: .semiExpress),
        ExactRun("21:00", trainType: .express),
    ]

    // counts: {'express': 11, 'semiExpress': 5}

    private static let odawaraUpExpWd_shinYurigaoka: [ExactRun] = [
        ExactRun("06:48", trainType: .commuterExpress),
        ExactRun("07:05", trainType: .commuterExpress),
        ExactRun("07:17", trainType: .commuterExpress),
        ExactRun("07:27", trainType: .commuterExpress),
        ExactRun("07:37", trainType: .commuterExpress),
        ExactRun("07:47", trainType: .commuterExpress),
        ExactRun("07:57", trainType: .commuterExpress),
        ExactRun("08:08", trainType: .commuterExpress),
        ExactRun("08:21", trainType: .commuterExpress),
        ExactRun("17:15", trainType: .express),
        ExactRun("17:24", trainType: .express),
    ]

    // counts: {'commuterExpress': 9, 'express': 2}

    private static let odawaraUpExpHol_shinYurigaoka: [ExactRun] = [
        ExactRun("08:11", trainType: .express),
    ]

    // counts: {'express': 1}

    private static let odawaraUpExpHol_machida: [ExactRun] = [
        ExactRun("07:19", trainType: .express),
        ExactRun("09:49", trainType: .express),
        ExactRun("10:09", trainType: .express),
        ExactRun("10:28", trainType: .express),
        ExactRun("10:49", trainType: .express),
        ExactRun("11:09", trainType: .express),
        ExactRun("11:28", trainType: .express),
    ]

    // counts: {'express': 7}

    private static let odawaraUpExpWd_sagamiOno: [ExactRun] = [
        ExactRun("07:00", trainType: .commuterSemiExpress),
    ]

    // counts: {'commuterSemiExpress': 1}

    private static let odawaraUpExpWd_ebina: [ExactRun] = [
        ExactRun("07:04", trainType: .commuterSemiExpress),
        ExactRun("07:24", trainType: .commuterSemiExpress),
    ]

    // counts: {'commuterSemiExpress': 2}

    private static let odawaraUpExpHol_ebina: [ExactRun] = [
        ExactRun("06:13", trainType: .express),
    ]

    // counts: {'express': 1}

    private static let odawaraUpExpWd_honAtsugi: [ExactRun] = [
        ExactRun("05:29", trainType: .express),
        ExactRun("05:52", trainType: .express),
        ExactRun("06:11", trainType: .express),
        ExactRun("06:47", trainType: .commuterSemiExpress),
        ExactRun("07:11", trainType: .commuterSemiExpress),
        ExactRun("07:31", trainType: .commuterSemiExpress),
    ]

    // counts: {'express': 3, 'commuterSemiExpress': 3}

    private static let odawaraUpExpHol_honAtsugi: [ExactRun] = [
        ExactRun("05:53", trainType: .express),
        ExactRun("06:27", trainType: .express),
        ExactRun("06:45", trainType: .express),
        ExactRun("08:43", trainType: .express),
        ExactRun("20:45", trainType: .express),
    ]

    // counts: {'express': 5}

    private static let odawaraUpExpWd_isehara: [ExactRun] = [
        ExactRun("05:55", trainType: .commuterSemiExpress),
        ExactRun("06:17", trainType: .commuterSemiExpress),
        ExactRun("07:32", trainType: .commuterSemiExpress),
    ]

    // counts: {'commuterSemiExpress': 3}

    private static let odawaraUpExpWd_shinMatsuda: [ExactRun] = [
        ExactRun("04:55", trainType: .rapidExpress),
        ExactRun("06:21", trainType: .rapidExpress),
        ExactRun("07:37", trainType: .express),
        ExactRun("17:08", trainType: .express),
        ExactRun("18:09", trainType: .express),
        ExactRun("18:40", trainType: .express),
        ExactRun("19:15", trainType: .rapidExpress),
        ExactRun("19:40", trainType: .express),
        ExactRun("20:14", trainType: .rapidExpress),
        ExactRun("20:40", trainType: .express),
        ExactRun("21:36", trainType: .express),
    ]

    // counts: {'rapidExpress': 4, 'express': 7}

    private static let odawaraUpExpHol_shinMatsuda: [ExactRun] = [
        ExactRun("04:55", trainType: .rapidExpress),
        ExactRun("07:05", trainType: .rapidExpress),
        ExactRun("22:22", trainType: .express),
    ]

    // counts: {'commuterExpress': 6}


    private static let odawaraDownWeekday = pattern("05:00", "24:43", [
        ("05:00", 7), ("06:30", 3.5), ("09:30", 5), ("16:30", 4), ("20:00", 5), ("22:00", 6),
    ])

    private static let odawaraDownHoliday = pattern("05:00", "24:43", [
        ("05:00", 7), ("07:00", 5), ("10:00", 5), ("20:00", 6),
    ])

    private static let odawaraUpWeekday = pattern("04:54", "23:49", [
        ("04:54", 8), ("06:30", 4), ("09:30", 7), ("16:30", 5), ("20:00", 7), ("22:00", 9),
    ])

    private static let odawaraUpHoliday = pattern("04:54", "23:49", [
        ("04:54", 8), ("07:00", 6), ("10:00", 7), ("20:00", 8),
    ])

}
